### ISSUE TITLE
browser-sync does not reload from command-line

### ISSUE THREAD

**Issue by zwhitchcox** [BrowserSync/browser-sync#1000]
Been wrestling for an hour, and it seems pretty simple, but I can't get browser-sync to actually reload the content when the files change. It detects a file change and outputs "File changed: index.html", but doesn't reload the page.

All I'm doing is simply:

```browser-sync start --server --files="**"```

and the page simply doesn't want to reload. I've tried this several times and usually end up making a gulpfile, but it would be nice if I could just quickly create a server that reloads.

Even when I go to the UI, and say reload all, they don't reload, nor any other commands.

**Comment by shakyShane** [comment]
Are you seeing 'connected to Browsersync' message in the top-right-hand of the browser

**Comment by shakyShane** [comment]
https://www.browsersync.io/docs/#requirements

**Comment by zwhitchcox** [comment]
It needed a body tag
