### ISSUE TITLE
Is it possible to inject js without full reload?

### ISSUE THREAD

**Issue by lifeBalance** [BrowserSync/browser-sync#1001]
Hi, I've created a small **React kit**, and when I compile Sass styles, the CSS is injected without full reloading the page (cool). Can I achieve the same with the JavaScripts?
This is [my code](https://github.com/lifeBalance/my-react-kit/tree/split-gulp-tasks) in case someone wanted to give me a hand.

Thanks.

**Comment by JodiWarren** [comment]
BrowserSync doesn't handle Javascript hot reloading, but check out this recipe: https://github.com/Browsersync/recipes/tree/master/recipes/webpack.react-hot-loader

**Comment by lifeBalance** [comment]
@JodiWarren Thanks, thing is I'm trying to do it with Broserify. I tried my hand with Webpack, but found other issues when trying to make it work with the other pieces of my build stack.

**Comment by shakyShane** [comment]
@lifeBalance @JodiWarren hot-reloading is totally possible with Browserify - we should put a recipe for it together

**Comment by lifeBalance** [comment]
@shakyShane I'm using Browserify + watchify. Take a peek to my code, maybe you can offer some advice. I've tried everything without any success.
