### ISSUE TITLE
Issue with BrowserSync instances

### ISSUE THREAD

**Issue by lifeBalance** [BrowserSync/browser-sync#1002]
Since I have my Gulp tasks split in separate files, I've created an instance of BrowserSync in the `serve.js` task, and then try to get the instance with `var bs = require("browser-sync").get('browSync);` in another file.
While this works fine for the styles task, I get the following error when trying to do the same in the scripts task:
```
throw new Error("An instance with the name `%s` was not found.".replace("%s", name));
    ^
```
[My code](https://github.com/lifeBalance/my-react-kit/blob/master/gulp/tasks/scripts.js#L10)

**Comment by lifeBalance** [comment]
Ok, I found out what the problem was, I'll leave it here for posterity. As it happens, I created the BrowserSync instance in the `serve.js` file, which contains the serve task:
```
var browserSync = require('browser-sync').create('browSync');
```

So this file must be required in the `scripts.js` file doing: 
```
var serve       = require('./serve'); // The file where I created the 'browSync' instance
var browserSync = require('browser-sync').get('browSync');
```

What is a bit confusing, is that I didn't have to require the  'browSync' instance in the  `styles.js` file, but it still works, and not sure why.

**Comment by shakyShane** [comment]
it's all about the order in which those files are interpreted by node. essentially the first file read should be the one you call `.create()` in
