### ISSUE TITLE
startPath option ignored

### ISSUE THREAD

**Issue by buecklers** [BrowserSync/browser-sync#1004]
I'm using John Papas lite-server that is using browser-sync and since version 2.x.x it passes configuration options to browser-sync. Passing the baseDir works fine but the startPath seems to be ignored. My browser just starts with localhost:300 no matter what I put into startPath.

Did I do something wrong?

Every hint is appreciated.

**Comment by shakyShane** [comment]
startPath is not a sub-property of server, it should be top level

**Comment by shakyShane** [comment]
eg:

```js

var bs = require('browser-sync').create();

bs.init({
    server: './app',
    startPath: '/about.html'
});
```

**Comment by buecklers** [comment]
Great, that works! Thank you for this lightning fast reply.

**Comment by shakyShane** [comment]
You are welcome
