### ISSUE TITLE
BrowserSync : Command not found

### ISSUE THREAD

**Issue by faheemzunjani** [BrowserSync/browser-sync#1007]
There was another issue open with the same title which has been closed but my error could not be resolved using the solutions given in that issue.

- Mac OSX El Capitan
- Node [v5.6.0]
- Npm [v3.6.0]

I installed Browser-Sync successfully using :
```bash
$ sudo npm install -g browser-sync
```
but when I check the browser-sync version by typing :
```bash
$ browser-sync --version
```
I get this error :
```bash
-bash: browser-sync: command not found
```
![screen shot 2016-02-19 at 1 15 49 pm](https://cloud.githubusercontent.com/assets/13855113/13169394/191176d6-d70b-11e5-9457-cf477b89fd70.png)

**Comment by shakyShane** [comment]
if you look, the brew command failed.

also it's `browser-sync --version`

**Comment by faheemzunjani** [comment]
Yes the brew link command failed but I had installed using the commands I mentioned above the screenshot.
```bash
$ browser-sync --version
```
is also returning Command not found error.
As I can see the installation using npm install was successful. 
Please can you help me on how to now start using browser-sync.

**Comment by fvsch** [comment]
This is not a problem with BrowserSync and should be closed. It's an issue with your environment (OSX, Homebrew, Node.js installed via Homebrew maybe, npm config).

Where does `npm` install global packages in your setup? (I think you can get that with `npm config get prefix`.) Is that folder in the `$PATH` environment variable? If not, you should add it. Be sure to add the exact folder where npm will install executables. In my case, I configured npm to install global packages to `~/Library/npm`, and I added `~/Library/npm/bin` to my `$PATH`.

**Comment by aparnagandhe** [comment]
It's worked for me. Thank you so much!!! @fvsch

**Comment by jaiminpatel008** [comment]
Check where npm installs its binaries by running `npm bin -g`, and then add that to your PATH.

`export PATH=$PATH:/usr/local/bin`

The same thing can happen at a project-level dependency if you install it on dev dependency. (`npm i -D browser-sync`)

**Comment by shrashti08** [comment]
in my desktop it show that npm command not found ..m not able to install browser sync by using the link mentioned in their website please help to resolve this
