### ISSUE TITLE
Unable to use browserSync with custom server.

### ISSUE THREAD

**Issue by paranoid-android** [BrowserSync/browser-sync#1016]
My Node.js app is using a custom server. My code looks like this:

```
./
  gulpfile.js
  release
  dev
    appServer.js
    views
    resources
```

When `gulp` is executed, the code in `dev` gets copied to `release`. Then, the following code gets executed:

```
browserSync.init({
  server: './release/appServer.js'
});
```

If I run `node ./release/appServer.js` from the command-line, everything works fine. However, when the `browserSync` line above gets executed, I see the following in my command window:

```
BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://[ipAddress]:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://[ipAddress]:3001
 --------------------------------------
[BS] Serving files from: ./release/appServer.js
```

So far, so good. Yet, when the browser opens, to http://localhost:3000, I see "Cannot GET /" in the browser window. What am I doing wrong? Isn't there a way to use a custom server via browserSync? I'm interested in using browserSync for its refresh abilities during development. However, I'm stuck. Any help is appreciated. I know this is a question. Yet, it feels like it might be a bug. For that reason, I wanted to post it here.

**Comment by shakyShane** [comment]
You need the proxy option, not the server https://www.browsersync.io/docs/options/#option-proxy

:)
