### ISSUE TITLE
proxyRes doesn't provide a callbackproxy

### ISSUE THREAD

**Issue by danieldiekmeier** [BrowserSync/browser-sync#1019]
### Issue details

Earlier, I created a pull request to include the `next` parameter in an proxyRes example.

I just quickly pushed it without trying if that did actually fix the problem, which was a mistake, because it didn't. The problem seems to be that no callback function is provided. The contents of `next` seem to be similar to the contents of `this`.

My suggestion would be to provide a callback to allow a order of execution for the proxyRes functions.

### Steps to reproduce

```js
// require the module as normal
var bs = require("browser-sync").create()

// .init starts the server
bs.init({
  open: false,
  proxy: {
    target: 'https://example.com',
    proxyRes: [
      function test(req, res, next) {
        next()
      }
    ]
  }
})
> TypeError: next is not a function
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.11.1
- Node 5.7.0
- NPM 3.6.0

### Affected platforms

- [X] OS X

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
Ahh, actually the array of functions given to proxyRes does not act as you expect (ie: it's not a middleware stack) - instead each function is simply executed in order so this is expected behaviour. We should revert the change to the docs and instead remove the `next()` call altogther

**Comment by danieldiekmeier** [comment]
How would I go about changing the Response? Use Case: I want to proxy an external site and inject a JavaScript file for testing.

**Comment by shakyShane** [comment]
https://browsersync.io/docs/options/#option-rewriteRules

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/tree/master/examples

**Comment by danieldiekmeier** [comment]
👌
