### ISSUE TITLE
CLI --files option only watches first path

### ISSUE THREAD

**Issue by ukgda** [BrowserSync/browser-sync#1024]
### Issue details

using the cli with two (or more) paths in the --files option, only the first path appears to be watched

### Steps to reproduce/test case

```shell
$ browser-sync start --files "index.html, app.css" --server
```
(only responds / watches changes to index.html)
```shell
$ browser-sync start --files "app.css, index.html" --server
```
(only responds / watches changes to app.css)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.11.1    ]
- Node        [  5.6.0  ]
- Npm         [ 3.6.0   ]

### Affected platforms

- [ x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x ] CLI

### If CLI, please paste the entire command below

{browser-sync start --files "index.html, app.css" --server}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
please use multiple files options instead.

eg: 

```shell
$ browser-sync start --files "app.css" --files "index.html" --server
```
