### ISSUE TITLE
Update socket.io dependency

### ISSUE THREAD

**Issue by MisterKamran** [BrowserSync/browser-sync#1026]
### Issue details

Currently browser-sync uses version 1.3.7 of socket.io, which ultimately has a dependency on node-XMLHttpRequest.  That dependency is being downloaded from GitHub rather than the public NPM Registry.

socket.io 1.3.7
|- socket.io-client 1.3.7
  |- engine.io-client 1.5.4
    |- node-XMLHttpRequest 1.5.0 —> Goes to https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz

### Steps to reproduce/test case

run npm install and verify the logs for any external communications to github.com

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.11.1  ]
- Node        [  5.7.1  ]
- Npm         [  3.6.0  ]

### Affected platforms

- [X] linux
- [X] windows
- [X] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [X] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by ederkley** [comment]
+1
This is preventing lite-server from working behind corporate-proxy as well

**Comment by shakyShane** [comment]
We're on the latest release now
