### ISSUE TITLE
enable bs-config.json comments

### ISSUE THREAD

**Issue by myusrn** [BrowserSync/browser-sync#1027]
### Issue details

Currently tsconfig.json, typings.json and .vscode/launch.json + settings.json + tasks.json all support use of // and /* */ comments to store details of alternative settings and notes relating to contents of those files.

I tried doing this in browsersync bs-config.json, e.g. as shown in following example, and this breaks 'npm run lite-server' startup, a package that is a wrapper around browsersync, due to browsersync bs-config.json parsing errors.
```
{ 
  "port": 3000,  // 3000 (default) and for specific port use "port": 8080 or "https": true, "port": 44300
  //"files": ["./src/**/*.{html,htm,css,js}"],
  "files": ["./**/*.{html,htm,css,js}"],
  //"server": { "baseDir": "./src" }
  "server": { "baseDir": "./" }
}
```
Is enabling similar support in browsersync bs-config.json file something that is in the plans already and if not does it sound like something that would be relevant to add?

### Steps to reproduce/test case

add // and/or /* */ comments to bs-config.json file and then retry use of browsersync, e.g. by running lite-server package provided web server, and look for failure due to bs-config.json parsing.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.1.1  ]
- Node        [  5.7.0  ]
- Npm         [ 3.6.0   ]

### Affected platforms

- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [X] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below

npm run lite [ where this is configured to execute npm lite-server package that is built on top of browsersync ]

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
Rename it to .js and use module.exports - now you have all the power of onode when generating config, along with comments :)

**Comment by myusrn** [comment]
Thanks for response.  

I'm not a node expert so wondering what using module.exports statement needs to look like for bs-config.json -> bs-config.js approach to work at which point comments would be allowed. 

searching on "node module.exports" I see lots of hits suggesting perhaps something like "module.exports = () => { <contents of existing bs-config.json here >}"  is that what you are getting at?
