### ISSUE TITLE
Updating CSS causes page reload on Angular

### ISSUE THREAD

**Issue by JonWallsten** [BrowserSync/browser-sync#1028]
### Issue details

When using BrowserSync with angular injecting CSS causes a reload, instead of just updating the stylesheet. Same code works on another site not using angular.

### Steps to reproduce/test case
Change one of the CSS files and use **plugins.browserSync.stream()** last in the pipe chain.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.11.1]
- Node        [5.6.0]
- Npm         [3.6]

### Affected platforms

- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [X] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

```
gulp.task('browser-sync', function() {
	plugins.browserSync.init({
		port: 1338,
		proxy: 'localhost:8083'
	});
});
...is
gulp.task('css', function () {
	return gulp.src(plugins.mainBowerFiles('**/*.css').concat(cssSource), {base: './'})
		.pipe(plugins.sourcemaps.init())
		.pipe(plugins.sass({outputStyle: 'compressed'}))
		.on('error', swallowError)
		.pipe(plugins.concat(bundledCSS))
		.pipe(plugins.sourcemaps.write(sourcemapsDir))
		.pipe(gulp.dest(cssDist))
		.pipe(plugins.gulpIf(ENVIRONMENT === 'DEV', plugins.browserSync.stream()));
});
...
gulp.watch(cssSource,['css']);
```

**Comment by shakyShane** [comment]
The source map files will be causing the reload. Look at this example https://www.browsersync.io/docs/gulp/#gulp-sass-maps for a fix

**Comment by JonWallsten** [comment]
But I'm suing BrowserSync with source-maps in another project without reloading. Weird.
