### ISSUE TITLE
proxy not working with webpackDevMiddleware

### ISSUE THREAD

**Issue by unbug** [BrowserSync/browser-sync#1030]
I followed this [https://github.com/BrowserSync/recipes/tree/master/recipes/webpack.babel
](https://github.com/BrowserSync/recipes/tree/master/recipes/webpack.babel
).
I use proxy instead server,and visit the proxy`http://mylab.com:3000`,the broswer does reload after js files get changed,but the js file never updated.it works fine with the `localhost:3000`
```
proxy: "http://mylab.com/myproject/",
//server: 'app'
```

`http://mylab.com` is a vhost server by apache.

**Comment by shakyShane** [comment]
This is expected - the middleware compiles/serves the bundle from memory. Run webpack separately to generate the file on disk :)

**Comment by unbug** [comment]
@shakyShane 
is there a work around to make the proxy works?
