### ISSUE TITLE
Impossible to install the last version

### ISSUE THREAD

**Issue by Ducatel** [BrowserSync/browser-sync#1033]
Hi everybody

### Issue details

It's impossible to install the last version.
Produce a lot of errors about GYP.

A *short* part of the log

````
mydirFrontEnd\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\eng
ine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\
..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(399,5): error MSB3191: Impossible de créer le répertoire "Release\obj\bu
fferutil\bufferutil.tlog\". Le chemin d'accès spécifié, le nom de fichier ou les deux sont trop longs. Le nom de fichier qualifié complet doit comprendre 
moins de 260 caractères et le nom du répertoire moins de 248 caractères. [mydirFrontEnd\node_modules\browser
-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
```


### Steps to reproduce/test case

Make `npm install` with the following `package.json`

```
`{
  "name": "YourAppName",
  "version": "0.0.1",
  "author": "YourName",
  "devDependencies": {
    "browser-sync": "^2.11.1"
  }
}
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.11.1  ]
- Node        [  4.2.4  ]
- Npm         [  2.14.12  ]

### Affected platforms

- [x] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [x] Grunt
- [x] CLI

**Comment by lukewatts** [comment]
Same...sort of. I couldn't even download with npm install

It stops on "network" and give ECONNRESET errors until I terminate.

I used 2.10.0 and it downloaded fine. Defintely a 2.11.x problem.

`npm install --save-dev browser-sync@^2.10.0`

for anyone else needing a temp solution.

**Comment by seriema** [comment]
@lukewatts the `^2.10.0` range will install the latest `v2`, but npm ignores those ranges when saving to `project.json` anyway and [uses your configured `save-prefix`](https://docs.npmjs.com/misc/config#save-prefix) instead. So you'll most likely end up with the broken `2.11.1`. You can either change your default, or (my personal choice) use the `--save-exact` flag instead:

`npm install browser-sync@2.11.0 --save-dev --save-exact`
(It's just `2.11.1` that's broken, so `2.11.0` works)

**Comment by lukewatts** [comment]
@seriema All I know is installing the latest  (^2.11.*) didn't work. Wouldn't even download from npm. Specifying ^2.10.0 worked. All I care about is refreshing the browser :)

**Comment by seriema** [comment]
@lukewatts What does your `package.json` say? Whoever runs the command you posted will get a "broken" package.json, so when they do `npm install` they'll end up installing browser-sync 2.11.1 and get a broken build. "Works on my machine" is kinda what got us here :D

**Comment by shakyShane** [comment]
socket.io is updated to latest version now which should solve this issue
