### ISSUE TITLE
[Bug] API `get`

### ISSUE THREAD

**Issue by bekos** [BrowserSync/browser-sync#1034]
### Issue details

API `get` is not working as it supposed to do.

### Steps to reproduce/test case

Following to API's documentation example I created one file test1.js
```js
var bs = require("browser-sync").create('My Server');

// Start the Browsersync server
bs.init({
    server: true
});
```
and run `node test1`... and server is running.

In another file test2.js write:
```js
var bs = require("browser-sync").get('My server');
```
and call `node test2`.... and you get an error that `An instance with the name 'My server' was not found.`.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.11.1  ]
- Node        [  4.4.0  ]
- Npm         [  2.14.2  ]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
Get only works when both files are loaded in the same process. In your example it won't work because it cannot communicate across processes.

Instead, require file 2 from file 1 and it will work :)

**Comment by bekos** [comment]
@shakyShane Thx for your response :-)

I changed files to this:
```js
// test1.js
var process = require('process');
var bs = require("browser-sync").create('My Server');

console.log('BS pid', process.pid);

bs.init({
    server: true
});
```
```js
// test2.js
var bs = require("browser-sync");
var process = require('process');
require('./test1');

console.log('MY pid', process.pid);

setTimeout(function() {
  console.log(bs.has('My server'));
}, 10000);
```

and in my console when I run `node test2`, I get this:
```bash
BS pid 6779
MY pid 6779
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://10.0.9.119:3000
 -----------------------------------
          UI: http://localhost:3002
 UI External: http://10.0.9.119:3002
 -----------------------------------
[BS] Serving files from: ./
false           <------------------------------
```

Am I doing something wrong?
