### ISSUE TITLE
Browsersync <script> tag inserted into ANY first <body> tag, including commented-out one

### ISSUE THREAD

**Issue by jkymarsh** [BrowserSync/browser-sync#1038]
### Issue details

The Browsersync `<script>` tag gets inserted into any first `<body>` tag, even if that first tag is commented out.

### Steps to reproduce/test case

Add a commented-out `<body>` tag, as such:

```html
<!-- <body class="h--nav--is-atop-hero"> -->
<body>
```

Upon reload, the Browsersync `<script>` tag will be added to this `<body>` tag, rather than an uncommented one found after it:

```html
<!-- <body class="h--nav--is-atop-hero"><script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.11.1.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
 -->
<body>
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.11.1 ]
- Node        [ 4.2.6 ]
- Npm         [ 3.6.0 ]

### Browsersync use-case

- [ x ] API
- [ x ] Gulp
- [ x ] Grunt
- [ x ] CLI

### If CLI, please paste the entire command below

Use any generic CLI command:

```
browser-sync start --server --files "css/*.css, *.html, js/*.js"
```

**Comment by shakyShane** [comment]
This is expected behaviour - the regex used is deliberately simple (as trying to catch every use-case would be impossible)

Solutions for you:

1. Provide a better regex as an option
```js
snippetOptions: {
    // Provide a custom Regex for inserting the snippet.
    rule: {
        match: /<\/body>/i,
        fn: function (snippet, match) {
            return snippet + match;
        }
    }
}
``` 

2. Just add it to the end of every document - I've tried this and it's surprisingly well-behaved on all the browsers I've tested it on

```js
snippetOptions: {
    // just append the snippet to the end of the file
    rule: {
        match: /$/i,
        fn: function (snippet, match) {
            return snippet + match;
        }
    }
}
```
