### ISSUE TITLE
Browser-sync command line not reloading *.php files.

### ISSUE THREAD

**Issue by marcinant** [BrowserSync/browser-sync#1039]
### Issue details

I use browser-sync from command line and I don't use proxy because I need to work on original port (80).

So, I inject browser-sync script directly to each php page and it's working properly with css and js files.
However adding code described in options manual has no effect. Changes in PHP files do not fire reload action.

### Steps to reproduce/test case

Just create new PHP project. Include BS snippet in code and run it on some server.
Run `browser-sync init` to generate config file.
Edit this file to add *.php files and try to use with CLI.
NO PROXY. 'browser-sync start --config bs-config.js'
Make some changes in *.php files. No reload. Watch ignores these files.

There is an example in manual for "files" option:
```
        {
            match: ["wp-content/themes/**/*.php"],
            fn:    function (event, file) {
                /** Custom event handler **/
            }
        }
```
Simple question is. Is this posible to call reload here? 
How to force reload on callback function? Is this possible in config file?

Currently I have two options: use Gulp/Grunt with additional watch task or run 'browser-sync reload' manually when I save *.php file. I really would like to avoid Gulp/Grunt. 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.11.1  ]
- Node        [  4.4.0  ]
- Npm         [  2.14.20  ]

### Affected platforms

- [ x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ x] CLI

### If CLI, please paste the entire command below

browser-sync start --config bs-config.js

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
```
files: [
        "wp-content/themes/**/*.css",
        {
            match: ["wp-content/themes/**/*.php"],
            fn:    function (event, file) {
                /** Custom event handler **/
            }
        }
    ]
```

**Comment by shakyShane** [comment]
yes, `this` inside the custom handler is bound to the public instance, so `this.reload()` will work as expected.

```js
        {
            match: ["wp-content/themes/**/*.php"],
            fn:    function (event, file) {
                /** Custom event handler **/
            }
        }
```

**Comment by ianhempsell** [comment]
I'm having similar issues with Wordpress, Webpack 4 and Browsersync.

Using the following within my webpack.config, reloads all .PHP pages in the /root/ of my theme as expected:

**new BrowserSyncWebpackPlugin({
      proxy: proxy,
      files: ['**/*.php'],
})**

But any 'included' .PHP files that are located within directories are recognized as changed within the console but do not reload the browser. An example:

**/page.php**
_loads in a template part from_
**/template-parts/part.php**

When changing the /template-parts/part.php, the console updates with
**[Browsersync] Reloading Browsers...**

But the page content does not update as expected. If you manually refresh, the change is shown.

I have tried changing my BrowserSyncWebpackPlugin to use the following, but this does not work either

{
    match: ["**/*.php"],
    fn:    function (event, file) {
        this.reload()
    }
}

Is it possible to reload the browser when a .PHP partial changes?
