### ISSUE TITLE
Feature Request: Read bs config from local package.json

### ISSUE THREAD

**Issue by fredrikekelund** [BrowserSync/browser-sync#1040]
### Issue details

I'm working with browsr-sync's CLI and was having some trouble with the file watcher on OS X. I needed to pass a setting to chokidar to get it to work correctly, and so I had to generate a config file to be able to pass a watchOptions key. This worked out nicely, but my config file turned out very short, and **it would be very nice if I could write these options in package.json instead of in a separate file to keep from cluttering my project**. Several projects let developers do this (browserify and eslint come to mind), and there's the [pkg-conf](https://www.npmjs.com/package/pkg-conf) module that maybe could ease implementation.

### Steps to reproduce/test case

Not applicable

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.11.1
- Node 5.9.0
- Npm 3.7.3

### Affected platforms

Not applicable

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

**Comment by shakyShane** [comment]
This was added in 2.12

**Comment by fredrikekelund** [comment]
Awesome - thanks! 👍
