### ISSUE TITLE
Browser command line arguments.

### ISSUE THREAD

**Issue by vsDizzy** [BrowserSync/browser-sync#1041]
## I need to run browser with specific command line:
E.g.
`chrome.exe --remote-debugging-port=9222`

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [latest]
- Node        [x]
- Npm         [x]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

```js
  bs.init({
    browser: 'chrome --remote-debugging-port=9222',
    files: 'client/**',
    ghostMode: false,
    proxy: 'http://localhost:3000'
  });
```

This just opens my default browser (Firefox).

**Comment by shakyShane** [comment]
This is out of scope for Browsersync core and can be easily added with something like this instead

```js
bs.init({
	open: false,
	files: 'client/**',
	ghostMode: false,
	proxy: 'http://localhost:3000'
}, function (err, bs) {
	require('opn')(bs.options.getIn(['urls', 'local']), {app: ['google chrome', '--incognito']});
});
```

**Comment by ReginaldoSantos** [comment]
Great hint, but for me it was given:

`[Browsersync] Watching files...
(node:25781) UnhandledPromiseRejectionWarning: Error: spawn google chrome ENOENT
    at _errnoException (util.js:1022:11)
`
Fixed using 'google-chrome' instead of 'google chrome' though ...

`require('opn')(bs.options.getIn(['urls', 'local']), {app: ['google-chrome', '--incognito']});`

**Comment by 625781186** [comment]
Now , 
We can use like this
```
function task_browserSync(done) {
  browsersync.init({

      proxy: {
        target :"http://127.0.0.1:5000/",
        // ws :true
      },

      browser: {
        app: [
          "chrome",
          '--user-data-dir=c:\\ChromeDebug',
          // "--test-type --disable-web-security"
        ]
      }
  },

    );

}

```

**Comment by halmos** [comment]
> Now , We can use like this
> 
> ```
> function task_browserSync(done) {
>   browsersync.init({
> 
> 
>       browser: {
>         app: [
>           "chrome",
>           '--user-data-dir=c:\\ChromeDebug',
>           // "--test-type --disable-web-security"
>         ]
>       }
>   },
> 
>     );
> 
> }
> ```

Can anyone verify if this works and if/where it is documented?
