### ISSUE TITLE
update socket.io

### ISSUE THREAD

**Issue by seriema** [BrowserSync/browser-sync#1043]
According to the [chat on Slack](https://browsersync.slack.com/archives/issues/p1458656436000020) I'm posting this issue, which is related to #1033 . The `socket-io` version was locked in [this commit](https://github.com/BrowserSync/browser-sync/commit/b3d008c6c45716f41813f821b6a8cc3c2114ce9e) and is related to this [breaking `socket-io` update](https://github.com/socketio/socket.io/commit/b73d9bea4efb48277eee685763026ff2df5a79ab#commitcomment-16806313).

`browser-sync` needs to be updated to include a newer version of `socket-io` which seems to solve the install issues, but the effects of the `socket-io` update needs to be investigated.

**Comment by shakyShane** [comment]
Fixed in https://github.com/BrowserSync/browser-sync/commit/953ca411b38d01023a7546ee6b66c7e9f93f251c. 

:)
