### ISSUE TITLE
Error: Cannot find module './plugins/plugins/plugins.plugin'

### ISSUE THREAD

**Issue by sclanc** [BrowserSync/browser-sync#1045]
### Issue details
This issue was originally filed with Gulp, because it occurred while trying to serve using gulp.Here is a link to the original problem: https://github.com/gulpjs/gulp/issues/1584

### Steps to reproduce/test case

Reasons for issue are still unknown. I cannot reproduce the error. I was bouncing back and forth between serving different projects when this happened.

- Browsersync [ 2.11.1   ]
- Node        [ 4.4.0   ]
- Npm         [  2.14.20  ]

- [ ubuntu gnome 15.10] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ x] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
see link

**Comment by shakyShane** [comment]
As you cannot reproduce this, it was likely a localised issue with your setup, rather than a bug within Browsersync.

:)
