### ISSUE TITLE
Adjustment of the <body> tag

### ISSUE THREAD

**Issue by firla** [BrowserSync/browser-sync#1048]
### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.11.2   ]
- Node        [ 4.4.1   ]
- Npm         [  2.14.20  ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### CLI Command

`browser-sync start --port 8887 --ui-port 8886 --no-open --logLevel debug --server ./build --files 'build/*.html, build/css/*.css, build/js/*.js'`

### Issue

Syncing doesn't work when adding a "body" comment:

    ...
    
    <body class="hold-transition fixed">
    ...

After removing the "onload" comment it works fine.

I didn't check the source code, but perhaps a weak regex when adding the `browser-sync-client.2.11.2.js` part?

**Comment by shakyShane** [comment]
This is expected behaviour - it always matches the first body tag. 

You can override the regex that is used via `snippetOptions.rule.match` as seen here https://www.browsersync.io/docs/options/#option-snippetOptions
