### ISSUE TITLE
browser-sync dont start

### ISSUE THREAD

**Issue by sersajar** [BrowserSync/browser-sync#1050]
### Issue details
I install correctly nodejs, npm and browser-sync, but when I try to start it, it does not do anything. It shows no errors, but does not open the browser, absoutely nothing happens.

_Please provide issue details here_.

### Steps to reproduce/test case

1. sudo apt-get install nodejs
2. sudo apt-get install npm
3. sudo npm install -g browser-sync
4. browser-sync start --server --directory --files "*/**"

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  last one  ]
- Node        [ installed from console with apt-get   ]
- Npm         [ installed from console with apt-get   ]

### Affected platforms

- [x ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}
browser-sync start --server --directory --files "*/**"

**Comment by shakyShane** [comment]
what does `browser-sync --version` produce?

**Comment by sersajar** [comment]
I solved it installing nodejs again, but not with apt-get.... following intructions from nodejs webstie... now my version is 2.11.2, i dont know previous version...
