### ISSUE TITLE
Is it possible to have vanity URLs? ie: remove .html extension?

### ISSUE THREAD

**Issue by mike3run** [BrowserSync/browser-sync#1055]
### Issue details

I'm just curious to know if its possible to serve .html files without the .html file extension at the end just for vanity purposes if its not possible that okay.

Thanks for making such a great tool for devs everywhere. Kudos!

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.11.2  ]
- Node        [ 5.7.1   ]
- Npm         [  3.6.0  ]

### Browsersync use-case

- [ ] API
- [X ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
sure

```js
var bs = require("./").create();

// Start the server
bs.init({
    server: {
        baseDir: "./app",
        serveStaticOptions: {
            extensions: ['html']
        }
    }
});
```

**Comment by mike3run** [comment]
![captura de pantalla 2016-06-07 a las 11 07 02 a m](https://cloud.githubusercontent.com/assets/7088511/15866321/b92a5a32-2ca3-11e6-958a-3cd3190cb0d4.png)

Holy crap that worked! Thanks maybe serveStaticOptions should be on the docs 😁

**Comment by axelboc** [comment]
I've been trying to get this to work when running browser-sync from the CLI. The [documentation](https://www.browsersync.io/docs/command-line) doesn't provide any example with the `--extensions` option. I've tried a bunch of syntaxes without success:

```
browser-sync start --server public --files public --extensions html
browser-sync start --server public --files public --extensions [ html ]
browser-sync start --server public --files public --extensions [html]
browser-sync start --server public --files public --extensions[] html
```

Also, all of the above with double quotes around the extension: `"html"`. What is the correct usage?

**Comment by jvdgroup** [comment]
Wow, that worked on my Foundation project! I had been fighting how to get pretty URLs to work on development environment (I'm more designer than developer), and this did it—thanks! :)

**Comment by arloduff** [comment]
I'm also not able to get this to work, using the latest version of Browsersync, 2.16.0

**Comment by mike3run** [comment]
share your gulp file or bs.config.js file

I've just ran it no problem with both on the latest version ;)

**Comment by arloduff** [comment]
This is my **bs-config.js**

    module.exports = {
      "port": 8000,
      "server": {
        "baseDir": "dist",
        "index": "dist/my-app/index.html",
        "serveStaticOptions": {
          "extensions": [
                "html",
          	"js"
          ]  
        }
      },
      "startPath": "/my-app"
    };

**Comment by mike3run** [comment]
i don't think ANY server would do that lol

**Comment by arloduff** [comment]
I thought that was the point of this feature. Is it only supposed to pick up html files?

**Comment by mike3run** [comment]
you should try it, but im guessing it should be limited to php and html files

**Comment by arloduff** [comment]
Seems it should have been

    extensions: "html,js"

**Comment by mike3run** [comment]
this seems to not be working anymore 😢
