### ISSUE TITLE
Having a <body> tag in a comment block will inject browser-sync-client inside the comment

### ISSUE THREAD

**Issue by tehapo** [BrowserSync/browser-sync#1056]
### Issue details

If you have a JavaScript comment block where the `<body>` tag is mentioned, the browser-sync-client gets injected inside the comment. I originally bumped into this issue while developing an Angular 2 application with Polymer components as HTML imports, but it can be reproduced with a simple HTML page as described below.

### Steps to reproduce/test case

Add the following code to the `<head>` section of an HTML file.

```html
    <script>
      /**
       * This comment contains `<body>` tag as documentation.
       */
    </script>
```

Fire up browser-sync from the command-line and the resulting page will contain the following comment section:

```html
    <script>
      /**
       * This comment contains `<body><script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.11.1.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
` tag as documentation.
       */
    </script>
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.11.1
- Node        5.9.1
- Npm         3.7.3

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below
```bash
$ browser-sync start --server --files="*.html"
```

**Comment by tehapo** [comment]
Looks like this is a duplicate of #1048 

Found a workaround to my situation by modifying the options as instructed:
https://www.browsersync.io/docs/options/#option-snippetOptions

**Comment by shakyShane** [comment]
@tehapo this is also changed in 2.12.1 script is always added to the end of the page now :)
