### ISSUE TITLE
error while installing browser sync

### ISSUE THREAD

**Issue by Shilpi1524** [BrowserSync/browser-sync#1057]
### Issue details

I'm getting below error while installing Browser Sync

C:\Users\sh261180>npm install -g browser-sync
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 23.235.43.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sh261180\npm-debug.log

**Comment by shakyShane** [comment]
> npm ERR! network connect ETIMEDOUT 23.235.43.162:443

This is an npm issue, please try again later :)

**Comment by Shilpi1524** [comment]
I tried again but again failed. Do i need to do anything??
