### ISSUE TITLE
Multiple reloads

### ISSUE THREAD

**Issue by THE-Beck** [BrowserSync/browser-sync#1059]
I'm using [generator-webapp](https://github.com/yeoman/generator-webapp) with [this](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/jade.md) jade modification (no other modification). I have lots of jade templates. If i change only one file this cause BS to reload multiple times. After reinstall still having same problem.

- Browsersync [  2.11.2  ]
- Node        [  0.12.7  ]
- Npm         [  2.11.3  ]
- windows with Cmder
- Gulp

### Command

> λ gulp serve
[15:14:29] Requiring external module babel-register
[15:14:36] Using gulpfile C:\some\folder\gulpfile.babel.js
[15:14:36] Starting 'views'...
[15:14:37] Starting 'styles'...
[15:14:37] Starting 'scripts'...
[15:14:38] Starting 'fonts'...
[15:14:41] Plumber found unhandled error:
 SyntaxError in plugin 'gulp-babel'
Message:
    C:/some/folder/app/scripts/plugins/vis.js: Binding interface in strict mode (8:8)
[15:14:44] Finished 'styles' after 7.21 s
[15:14:44] Finished 'scripts' after 6.64 s
[15:14:49] Finished 'fonts' after 12 s
[15:14:51] Finished 'views' after 15 s
[15:14:51] Starting 'serve'...
[15:14:52] Finished 'serve' after 313 ms
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:9000
    External: http://192.168.0.47:9000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.47:3001
 -------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: app
[15:15:06] Starting 'views'...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] 36 files changed (file1.html, file2.html, ...)
[15:15:18] Finished 'views' after 11 s
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...
[BS] Reloading Browsers...

**Comment by DanielJoyce** [comment]
yeah, I see this as well. Continuous spam for several tens of seconds before the web page is actually reloaded.

**Comment by THE-Beck** [comment]
Guess it's kind a complicated. BS watches the compiled `.html` files. Which means if i change something in my jade template almost every .html changes. That makes the BS reload multiple times.

Then i tried to change the watch file `.html` to `.jade` then BS reloads the browser before jade compile completes. Mostly my jade template compiles more than 10s...

Poor way to fix is adding reloadDelay i guess...

**Comment by THE-Beck** [comment]
Just found [this](https://github.com/BrowserSync/recipes/tree/master/recipes/gulp.jade) recipe. Problem was i need make seperate task to compile jade templates.

Now it's works like charm (except gulp-jade compiles templates really slow).
