### ISSUE TITLE
Add connect directory listing

### ISSUE THREAD

**Issue by jeremypeter** [BrowserSync/browser-sync#106]
It would be nice to have the [connect.directory](http://www.senchalabs.org/connect/directory.html) middleware implemented if the base directory only contains subdirectories and not an index file. 

My current setup is that my root directory contains subdirectories which contain the index file. So when browser sync opens up my browser, I get  a **Cannot GET /** error. So I currently have to spin up my own connect server using the directory middleware which lists the directories being watched by browser sync and I click into the subdirectory I want. Hope that makes sense.

**Comment by gertcuykens** [comment]
I fail to understand how to make it work?
http://www.browsersync.io/docs/options/#option-server
```js
    server: {
      baseDir: ['dist'],
      directory: true
 }
```

![image](https://cloud.githubusercontent.com/assets/863731/10713338/5c7aa900-7ab9-11e5-80e9-1bc240c3fb91.png)

How can I make de server only display a lisiting if no index.html is found?

**Comment by rkgttr** [comment]
Yeah I wonder how to do it too: list the directory if no index.html is found, serve index.html if it exists. Which would sound like a normal behaviour.

**Comment by dragosh** [comment]
why not do this? :
```
var listDirectory = true;
if (fs.existsSync('index.html')) {
  listDirectory = false
}
   
var option = {      
  directory: listDirectory
};
```

**Comment by gertcuykens** [comment]
That only works for one specific directory I think? Not when you have a mix where some directories have a index and some don't?

**Comment by eckdanny** [comment]
+1 for capturing apache-like `DirectoryIndex` behavior (e.g.; use `index.html` or whatnot if found, else show directory listing). Is there enough traction for this be a new feature request?

Haven't really dug into browserSync src yet... maybe a job for [connect-modrewrite](https://www.npmjs.com/package/connect-modrewrite)?

**Comment by nosaku** [comment]
Ran into this issue when setting up my Angular 2 learning directories into multiple directories like app1, app2 etc. It would really be nice to have the feature if serving index.html from the subdirectories if found else show the directory listing when the directory option is set to true.

**Comment by mischah** [comment]
Hej, is it correct that it’s still not possible to enable directory listing and server index files (like index.html) if they exist?

Thanks, Michael

**Comment by mischah** [comment]
> Hej, is it correct that it’s still not possible to enable directory listing and server index files (like index.html) if they exist?

After digging through the sources. Yes, it its. Since [serve-index](https://github.com/expressjs/serve-index) is used and it seems that one can’t accomplish that with passing options to `serve-index`

But isn’t it possible to check if the current directory has an index file and react to this over [here](https://github.com/browserSync/browser-sync/blob/master/lib/server/static-server.js#L29-L37)? 

Going to explore this … just in case: Would you accept a pull request for that?
