### ISSUE TITLE
Unable to watch multiple files from command line

### ISSUE THREAD

**Issue by raulramaya** [BrowserSync/browser-sync#1061]
### Issue details

Unable to watch multiple files from command line.   Same as the now closed #426 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.12.1   ]
- Node        [ 5.7.0   ]
- Npm         [ 3.6.0   ]

### Affected platforms

- [x ] windows

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x ] CLI

### If CLI, please paste the entire command below

This does not work:

```shell 
browser-sync start --server --files "**/*.htm, **/*.js, **/*.css, **/*.html"
```

But this does:
```shell 
browser-sync start --server --files "**/*.htm"
```

**Comment by shakyShane** [comment]
update to 2.12.1, then (separate strings)

```js
browser-sync start --server --files "**/*.htm" "**/*.js" "**/*.css" "**/*.html"
```
