### ISSUE TITLE
Routes Option Broke for Edge Case

### ISSUE THREAD

**Issue by trisys3** [BrowserSync/browser-sync#1063]
### Issue details

When I was using BrowserSync version 2.11.2, I was able to add a slash on the end of any route specified in the server options, but now, with version 2.12.1, this makes any files in that folder give 404 errors. This is a tiny bug and does not affect what I am doing besides causing me to make a few changes, but I figured I would report it nonetheless because it is unexpected and, technically, a breaking change.

### Steps to reproduce/test case
```js
    var bs = require('browser-sync').create('MyServer');

    bs.init({
        routes: {
            '/bower_components/': 'bower_components'
        },
        // other options
    });
```
worked on 2.11.1, but causes 404 errors for all bower component files in `my_server.com/bower_components` with 2.12.1.
```js
    var bs = require('browser-sync').create('MyServer');

    bs.init({
        routes: {
            '/bower_components': 'bower_components'
        },
        // other options
    });
```
works in both versions.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.12.1  ]
- Node        [  0.12.7  ]
- Npm         [  2.11.3  ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
thanks @trisys3 - this is indeed unexpected, I will look into the cause :)

**Comment by shakyShane** [comment]
on npm at browser-sync@2.12.7

**Comment by trisys3** [comment]
Sorry, caught up with work. It works fine.
