### ISSUE TITLE
New version cannot be updated synchronously

### ISSUE THREAD

**Issue by programmer-yang** [BrowserSync/browser-sync#1066]
2.9.3 version when I use the command:

```shell
browser-sync start --server --no-notify --files 'index.html, app/**/*.js'
```
You can monitor file update and start a server
Today I update the 2.12.3 version, found that this command does not work

**Comment by shakyShane** [comment]
fixed via 4ccdc0ab18cc56fcd1a8feda786c30425d0efb64
