### ISSUE TITLE
Typo on doc page

### ISSUE THREAD

**Issue by in-in** [BrowserSync/browser-sync#1068]
### Issue details

`brower-sync start --help` instead `browser-sync start --help`

`sh: 1: brower-sync: not found`

![selection_001](https://cloud.githubusercontent.com/assets/8797432/14582425/41862646-040d-11e6-983e-647fb00ca9f1.jpg)

### Steps to reproduce/test case

open: https://www.browsersync.io/docs/command-line/

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.11.2]
- Node        [v5.7.0]
- Npm         [3.6.0]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

`brower-sync start --help`

**Comment by shakyShane** [comment]
Fixed, thanks for reporting :)
