### ISSUE TITLE
BrowserSync remote device cannot /POST (with local expressjs dev server and NPM)

### ISSUE THREAD

**Issue by EightArmCode** [BrowserSync/browser-sync#1071]
#### Setup
I am using an ExpressJS server (localhost:9999) to develop locally with a build chain run entirely by NPM. I use nodemon to monitor and build files. I just want browser-sync to monitor the compiled files, and reload those. I am not using it to build.

#### Issue

I get browser-sync working and mirroring in my tablet, but when I try to login in the laptop, the laptop logs me in, and the tablet browser displays `cannot POST /` error. I can log into the page manually with the tablet and go to subsequent pages and the sync works. Furthermore, if I inspect the XHR using remote debugger the response status is "success." Anything you can advise me to try would be helpful. Thanks in advance for your time!

Further tinkering: If I login manually on the tablet, I can get it to sync, but it seems to keep losing the connection. For example, if I navigate to a link that is not behind the password, it is not rendering in the tablet. For some reason it keeps losing the connection.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.12.3  ]
- Node        [  5.10.1  ]
- Npm         [  3.8.3  ]

### Affected platforms
- [El Capitan 10.11.4 ] OS X

### Browsersync use-case

- [X] CLI

### If CLI, please paste the entire command below

```shell
broswer-sync start -c bs-config.js
```

### bs-config.js

```js
module.exports = {
    "ui": {
        "port": 3001,
        "weinre": {
            "port": 8080
        }
    },
    "files": [
        {
            match: [
                'build/modules/*.html', 
                'build/*.css',
                'build/*.js',
                'build/*.html',
                'js/**/*.js',
                'img/*.png',
                'img/*.gif',
                'img/theme-2/*.png',
                'css/*.css',
                'css/**/*.css',
                'css/**/**/*.css',
                'css/**/**/*.ttf',
                'css/**/**/*.eot',
                'css/**/**/*.svg',
                'css/**/**/*.woff',
                'css/**/**/*.woff2',
                'css/**/**/*.otf',
                'templates/*.html',
                'templates/**/*.html'
            ]
        }
    ],
    "watchOptions": {},
    "server": true,
    "proxy": 'localhost:9999',
    "port": 3000,
    "middleware": false,
    "serveStatic": [],
    "ghostMode": {
        "clicks": true,
        "scroll": true,
        "forms": {
            "submit": true,
            "inputs": true,
            "toggles": true
        }
    },
    "logLevel": "debug",
    "logPrefix": "BS",
    "logConnections": false,
    "logFileChanges": true,
    "logSnippet": true,
    "rewriteRules": false,
    "open": "local",
    "browser": "default",
    "xip": false,
    "hostnameSuffix": false,
    "reloadOnRestart": false,
    "notify": true,
    "scrollProportionally": true,
    "scrollThrottle": 0,
    "scrollRestoreTechnique": "window.name",
    "scrollElements": [],
    "scrollElementMapping": [],
    "reloadDelay": 0,
    "reloadDebounce": 0,
    "plugins": [],
    "injectChanges": true,
    "startPath": null,
    "host": null,
    "codeSync": true,
    "timestamps": true
};
```

### Express Server
```js

'use strict';

var express = require('express'),
	app = express(),
	pkg = require('../../package.json'),
	morgan = require('morgan');

app.use(morgan('dev')); // dev server logger

app.use(express.static('/' + __dirname + '/../../'));

app.get('/', function(req, res) {
	res.redirect('./index.html');
});

app.listen(pkg.vars.port);
```

* I have also tried adding browser sync to the ExpressJS file, but I'm getting the same error.

* I found this: http://stackoverflow.com/questions/11121501/cannot-post-post-nodejs - FYI my local server works fine and I've never had to do anything with what this post recommends, but I'm wondering if it is required for serving pages to a remote machine?

**Comment by shakyShane** [comment]
With some ajax requests, things can 'go wrong' in the land of Browsersync. You see, Browsersync needs to intercept certain requests and re-write urls to ensure all of your devices stay at the correct URL (like the ip address, or localhost etc).

This works ok for webpages, but let's say your server gives a json response that contains a hard-coded link to 'yourdevsite.com' - Browsersync does not know about this URL and therefor can end up sending a device to an incorrect place.

There are some solutions, but it requires per-app configuration, the only feasible way for me to help you with this would be if you could provide a sample project that highlighted your issue - that way I could set it up locally and find a solution.

Sorry this is not the answer you were hoping for, but the world of 'proxying' websites, especially when rewriting the URL on which they are served, is extremely difficult.
