### ISSUE TITLE
Feature Request: codeSync options for other consumers

### ISSUE THREAD

**Issue by npbenjohnson** [BrowserSync/browser-sync#1077]
Since browsersync exposes it's watcher and emitter features, it would be nice if `{codeSync: false}` told the browser script not to refresh, instead of suppressing file change messages that other consumers may use.

**Comment by shakyShane** [comment]
@npbenjohnson in this case, where you want full control over the watchers, you should use the standalone `watch` functionality

```js
bs.watch() // etc
```

Watchers registered in this manner are not affected by any internal options :)

**Comment by npbenjohnson** [comment]
Does that mean the client is aware of codeSync: false? My use case involves sending file change events that the client should ignore. I assumed that because codeSync shuts off events on the server end, the client is unaware of the codeSync setting and would just refresh regardless of the source.

**Comment by shakyShane** [comment]
Yep, the clients share the updated options
