### ISSUE TITLE
Reload HTML and JS and Inject CSS

### ISSUE THREAD

**Issue by linvi** [BrowserSync/browser-sync#1082]
### Issue details

My problem is that I would like BrowserSync to **reload** for html and js but to **refresh** the css by injection.

I have the following configuration 

``` json
{
  "port": 7000,
  "files": ["./app/**/*.{html,htm,js,css}"]
}
```

If I remove `css` nothing changes. If let it there, the entire page reloads.
How can I configure *.css to not reload the page but to be refreshed?

**Comment by shakyShane** [comment]
This works as expected for me (just tested it locally)

Could you please provide a sample project that highlights this bug and I will re-open the issue, thanks! :)
