### ISSUE TITLE
How to monitor a static site?

### ISSUE THREAD

**Issue by fghhfg** [BrowserSync/browser-sync#1085]
My website is static website.
I would like to moniter all files inside `build` directory.

All my files are in `build` directory.
And my homepage is `index.htm`.

How do I do?

```
browser-sync start --server 'build' --files 'build' --startPath index.htm
```

It don't work.

result:
<img width="273" alt="2016-05-02 16_31_53-localhost_3000_index htm" src="https://cloud.githubusercontent.com/assets/1284845/14950349/8b3aea74-1083-11e6-98ec-372341db7176.png">

the document on website:
```
# Start a server from the `app` directory, watching all files
$ browser-sync start --server 'app' --files 'app'
```
is not real useful...

my files:
```
C:.
└───build
    │   1htm.htm
    │   2htm.htm
    │   404.html
    │   index.htm
    │
    ├───css
    │       main.css
    │
    ├───img
    │   │
    │   └───thumba
    │           14416031288_f80f073c2f_b.png
    │           20151016_112148.jpg
    │           20151127_093432.jpg
    │           20151218_095304.jpg
    │
    └───js
        │   main.js
        │
        └───vendor
                modernizr-2.8.3-respond-1.4.2.min.js
```

<img width="216" alt="2016-05-02 16_34_34-build" src="https://cloud.githubusercontent.com/assets/1284845/14950391/d23a2282-1083-11e6-9a2d-4fc06a23bf87.png">

**Comment by hawz** [comment]
Hi, is this still an issue for you? I guess I'm dealing with the same problem here. Trying to start the server from the dist folder, after building it: the weird thing is everything works fine when the `directory: true` option is specified. However I need it to serve index.html.

**Comment by hawz** [comment]
Ok, it looks like browser-sync wasn't able to properly inject the snippet in the index.html file. 
Editing browserSync config like this:
```
browserSync: {
      dev: {
        bsFiles: {
          src: [
             '<%= config.distFolder %>/*.html',
             '<%= config.distFolder %>/templates/*.html',
             '<%= config.distFolder %>/templates/*.hbs',
             '<%= config.distFolder %>/templates/*.tpl',
             '<%= config.distFolder %>/js/*.js',
             '<%= config.distFolder %>/libs/*.js',
             '<%= config.distFolder %>/css/*.css'
          ]
        },
        options: {
          watchTask: true,
          server: {
            baseDir: './dist/'
          },
          snippetOptions: {
            // Provide a custom Regex for inserting the snippet.
            rule: {
              match: /<!-- browsersync -->/i,
              fn: function (snippet, match) {
                  return snippet + match;
              }
            }
          }
        }
      }
    }
```
and adding `<!-- browsersync -->` before the `</body>` closing tag does the trick.
