### ISSUE TITLE
triger scripts by changing files?

### ISSUE THREAD

**Issue by fghhfg** [BrowserSync/browser-sync#1086]
##### TL;DR

I would like to monitor `X` folder. If any files inside directory `X` changing, run `foo.bash`. Is this possible? How do I do?

---

##### Long version:

Can browser-sync trigers scripts (`foo.bash`) by changing files (`content.txt`, `bar.template`)?

```
content.txt + bar.template via foo.bash => index.htm
```

When changing files (`content.txt`, `bar.template`), browser-sync creates (`index.htm`) via `foo.bash` for me. Is this possible?
How do I do?

my working files `content.txt`, `bar.template`, `foo.bash` are in `src` directory.
my finished files are in `build` directory.

my files:
```
C:.
├───build
│   │   1htm.htm
│   │   2htm.htm
│   │   404.htm
│   │   index.htm
│   │
│   ├───css
│   │       main.css
│   │
│   ├───img
│   │   └───thumb
│   │           8174.jpg
│   │           8254.jpg
│   │
│   └───js
│           main.js
│
└───src
    │   1htm.txt
    │   2htm.txt
    │   404.txt
    │   index.txt
    │   foo.bash
    │
    ├───css
    │       main.css
    ├───template
    │       bar.template
    │
    ├───img
    │   └───thumb
    │           8174.jpg
    │           8254.jpg
    │
    └───js
            main.js

```

**Comment by shakyShane** [comment]
You could use a [child process](https://nodejs.org/api/child_process.html) to execute your script using the Browsersync watcher

```js
// Create a Browsersync instance
var bs = require("browser-sync").create();

// Call your script inside this callback
bs.watch("css/*.css", function (event, file) {
    if (event === "change") {
        //
    }
    if (event === "add") {
        //
    }
});

// Now init the Browsersync server
bs.init({
    server: "./app"
});
```

That's one way to go, or alternatively you could look at gulp/grunt setups for this type of thing :)
