### ISSUE TITLE
can not open the external URL

### ISSUE THREAD

**Issue by findvv** [BrowserSync/browser-sync#1089]
I want to open the external URL when Browsersync starts.
I set the options open to true but it's not working。
I find that in browser-sync.js line 259
```js
bs.events.emit("service:running", {
  options: bs.options,
  baseDir: bs.options.getIn(["server", "baseDir"]),
  type:    bs.options.get("mode"),
  port:    bs.options.get("port"),
  url:     bs.options.getIn(["urls", "local"]),
  urls:    bs.options.get("urls").toJS(),
  tunnel:  bs.options.getIn(["urls", "tunnel"])
});
```
The url always is bs.options.getIn(["urls", "local"]), so I only can open the local url like 'http://localhost:3071'。
Is that right?Or I make a mistake?
Thank you very much to help me!
Thank you!

**Comment by shakyShane** [comment]
Try `console.log(bs.options.getIn(["urls"]).toJS())` to see every available URL :)
