### ISSUE TITLE
HOWTO run browser-sync with a web app deployed in JBoss EAP 6.3.3 ?

### ISSUE THREAD

**Issue by jamjoum** [BrowserSync/browser-sync#1090]
### Issue details

Is there any specifc steps to run browser-sync with a web app deployed in JBoss EAP 6.3.3 ?
I installed node.js (version  4.4.3 <x64> ), i runned `npm install -g browser-sync` .
My web application (.war) is deployed in my running server JBoss EAP.
I runned `browser-sync start --proxy "http://localhost:8080/MyApp" --files "src/main/webapp/**/*"`
A new browser window is opened with URL http://localhost:3000/MyApp.
However when I changed the content of a file (xhtml,css,js), browser-sync detected it and refresh the browser but no changements appear.
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [  2.12.5  ]
- Node        [  4.4.3 <x64> ]
- Npm         [    ]
### Affected platforms
- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
### If CLI, please paste the entire command below

`browser-sync start --proxy "http://localhost:8080/MyApp" --files "src/main/webapp/**/*"
`

Thanks

**Comment by sudheerj** [comment]
I also have the same issue on JBOSS EAP 6.1+ Server.My other application runs on jetty server is working fine with Browser Sync.

**Comment by nemo97** [comment]
Did you set jboss in dev mode?
