### ISSUE TITLE
logSnippet: false prevents the UI access URL from being displayed

### ISSUE THREAD

**Issue by glen-84** [BrowserSync/browser-sync#1094]
### Issue details

I just want to hide the snippet of code, not the access URL(s).

### Steps to reproduce/test case

Set logSnippet to false.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.12.5 ]
- Node        [ 5.11.0 ]
- Npm         [ 3.8.6 ]

### Affected platforms

- [x] linux
- [x] windows
- [x] OS X
- [x] freebsd
- [x] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [x] Gulp
- [x] Grunt
- [x] CLI

### If CLI, please paste the entire command below

n/a

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

n/a

**Comment by shakyShane** [comment]
good catch! this is a bug that will be fixed asap :)

**Comment by shakyShane** [comment]
Maybe you could send a PR @glen-84 ?

here's the offending code, it would be good to have you on board as a contributor :)

https://github.com/BrowserSync/browser-sync/blob/ce6a2939fefd2b0d03c17507c7255df657ae2700/lib/logger.js#L136-L150

**Comment by glen-84** [comment]
#1095
