### ISSUE TITLE
Cannot Get

### ISSUE THREAD

**Issue by njanmelbin** [BrowserSync/browser-sync#1098]
### Issue details

Browser sync running but gives cannot get error..

### Steps to reproduce/test case

module.exports=function(grunt){
	require('load-grunt-tasks')(grunt);

	grunt.initConfig({
		browserSync: {
    			bsFiles: {
        			src : "src/*.html"
    			},
    			options: {
        			server: {
            			baseDir: "./"
  	     		 }
			 }  		 
		}

	});
	
	grunt.registerTask('default',[
           'browserSync'
		]);
}

but when I move index.html to base directory and change src : *.html ..everything works fine 
How can i run browser sync with index.html in src directory.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [    ]
- Node        [    ]
- Npm         [    ]

### Affected platforms

- [ ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
Change your config to 

```
browserSync: {
            bsFiles: {
                src : "src/*.html"
            },
            options: {
                server: {
                    baseDir: "src"
             }
         }           
    }
```
