### ISSUE TITLE
ghostMode click disabled and client logic still occurs

### ISSUE THREAD

**Issue by queimadus** [BrowserSync/browser-sync#1102]
### Issue details

Setting `ghostMode` to `false`, more specifically the `click` option stops the events from being propagated to other instances correctly but the underlying client logic is not turned off.

`browser-sync-client` adds a `click` eventListener which when emitted from a checkbox executes a  `forceChange()` function which calls `elem.blur()` and `elem.focus()` which interferes with my React application.

Is there a way to disabled this at this moment?
### Steps to reproduce/test case
- Set `ghostMode` to `false`
- Create an html with only a checkbox where: change, blur, focus events are logged
- observe that even though ghostMode.click is off, the extra `e.blur(); e.focus()` is still present
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [2.12.1]
- Node        [6.1.0]
- Npm         [3.8.6]
### Affected platforms
- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
### Browsersync use-case
- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
> Is there a way to disabled this at this moment?

Not at the moment, no :(

The reasoning is that I wanted to enable options to be toggled without requiring a page reload. But after seeing this issue I think we can fix this for you.

**Comment by ivancuric** [comment]
Was just about to submit this issue and saw this. +1.

**Comment by shakyShane** [comment]
Fixed in browser-sync@2.18.5

clicks, scroll & form input event listeners will not be registered on initial page load anymore.

**Comment by iSample** [comment]
actually，it doesn't work@2.18.5

![image](http://git.cn-hangzhou.oss.aliyun-inc.com/uploads/easygo/anywhere/7232420422007c924485bfa1c2628f02/image.png)
