### ISSUE TITLE
ngModel not updated when change input forms

### ISSUE THREAD

**Issue by rafa-as** [BrowserSync/browser-sync#1108]
### Issue details

Using browsersync with Angular SPA, when type on text input the view (not viewModel) are updated but the model not.
### Steps to reproduce/test case

Use browsersync on Angular SPA with a form and type on inputs. Print the model on the html for view if these are updated or not.
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [  2.12.8  ]
- Node        [  6.0.0  ]
- Npm         [  3.8.6  ]
### Affected platforms
- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
### Browsersync use-case
- [ ] API
- [ ] Gulp
- [x] Grunt
- [ ] CLI
### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

``` js
        browserSync: {
            dev: {
                bsFiles: {
                    src : '**/*.*'
                },
                options: {
                    watchTask: true,
                    proxy: 'localhost:8080/app',
                    plugins: [
                        {
                            module: "bs-html-injector",
                            options: {
                                files: '**/*.tpl.html'
                            }
                        }
                    ]
                }
            }
        }
```

**Comment by IvanCoronado** [comment]
I have same problem here

**Comment by imvenka** [comment]
I had the same problem. I was able to get it working for Angular 1.x by making few changes to index.min.js.  


`
/**
 * @param {BrowserSync} bs
 * @returns {Function}
 */
exports.socketEvent = function (bs) {  -- Line #1181
    return function (data) {
        if (!bs.canSync(data, OPT_PATH)) {
            return false;
        }
        var elem = bs.utils.getSingleElement(data.tagName, data.index);
        if (elem) {
            **if(angular){
                var ngElement = angular.element(elem);
                ngElement.val(data.value);
                ngElement.triggerHandler('input');
            }else{
                elem.value = data.value;    
            }**           
            return elem;
        }
        return false;
    };
};`
