### ISSUE TITLE
Changed `directory` behavior between v2.11.2 and v2.12.1

### ISSUE THREAD

**Issue by donaldpipowitch** [BrowserSync/browser-sync#1109]
We encountered a bug when upgrading from v2.11.2 to v2.12.1. Sadly the `CHANGELOG.md` is out of date and it was quite hard to find the reason for that. If I understand https://github.com/BrowserSync/browser-sync/compare/v2.11.2...v2.12.1#diff-0316241f14d1354d74d285cccc242c05R29 correctly browser-sync now only checks, if a `directory` property exists no matter what the value is. Previously we used `directory: false` here to disable directory listing. Now it is enabled, if we use `directory: false`.

It would be nice to either update the docs and changelog or to check if `directory` is falsy.

**Comment by shakyShane** [comment]
This would be a helpful PR, essentially you could change `server.has("directory")` to `server.get("directory")` (which would result in the falsey comparison you're expecting

**Comment by shakyShane** [comment]
^ I even added a failing test on branch `https://github.com/BrowserSync/browser-sync/tree/1109-directory` for this if anyone would like to make a contribution :)
