### ISSUE TITLE
Client script timeout

### ISSUE THREAD

**Issue by jamesryanbell** [BrowserSync/browser-sync#1111]
Hi

Is there a timeout that kicks for the client to disconnect after x seconds/minutes of not being used? We are finding that are leaving the client in-active for a while the script can lose connection.

If there is can this be disabled/increased?

Thanks,
James

**Comment by shakyShane** [comment]
You can increase the amount of times a reconnection will be attempted.

```js
var bs = require("./").create();

bs.init({
    server: 'app',
    socket: {
        socketIoClientConfig: {
            reconnectionAttempts: 50 // this is the default, change it to whatever you want
        }
    }
});
```

fyi, I added this restriction to avoid memory leaks (like leaving a browser open all day) - so use with caution 👍

**Comment by shakyShane** [comment]
var bs = require("./").create();

bs.init({
    server: 'app',
    socket: {
        socketIoClientConfig: {
            reconnectionAttempts: 50
        }
    }
});
