### ISSUE TITLE
Feature Request: Give option to distinguish capitalization when serving

### ISSUE THREAD

**Issue by jasonszhao** [BrowserSync/browser-sync#1113]
### Issue details

It would be nice to have an option to distinguish between upper and lowercase filenames. Github Pages does this, and often I don't catch a typo until it breaks on Github Pages.

### Steps to reproduce/test case

 1. Create `test.PNG`
 2. Start browser-sync and go to `localhost:3000/test.png`

**Expected**: 
404 error

**Actual**:
`test.PNG` served

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.9.11  ]
- Node        [  0.12.1  ]
- Npm         [  3.8.3  ]

### Affected platforms

I'm pretty sure this is applicable to all platforms and use-cases.

- [ ] linux
- [ ] windows
- [X] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below
```
browser-sync start --server
```

**Comment by shakyShane** [comment]
These types of issues are operating system/file-systems specific, so it's not something we can tackle I'm afraid :)
