### ISSUE TITLE
Unable to get font from BrowserSync server

### ISSUE THREAD

**Issue by pdmspr** [BrowserSync/browser-sync#1114]
### Issue details

When I access my application from BrowserSync's server on port 3000, the font  requests return 403s.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.12.9]
- Node        [    ]
- Npm         [    ]

### Affected platforms

- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [X] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
This sounds like you are accessing a font-service that is failing to validate the localhost address used by Browsersync

solution: Update you 'allowed domains' to include localhost
