### ISSUE TITLE
Cannot use --directory along with --index

### ISSUE THREAD

**Issue by parisk** [BrowserSync/browser-sync#1117]
### Issue details

Running Browsersync with both `--index` and `--directory` cli flags makes it always serve directory listing, when navigating to a directory's URL, even if an index file exists. I would expect it to attempt to serve the index file then and if it cannot find an index file, then serve the contents of the directory (just how Apache does it in most installations).

### Steps to reproduce/test case

1. Create a directory (e.g. `dir`)
2. Create a file called `index.html` inside `dir`
3. Start Browsersync from the command line to serve `dir` and set both the `--index` and `--directory` flags.
4. Open the Browser
5. Browsersync will serve directory listings but will not serve the `index.html` file by default, when browsing a directory's URL

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.12.8 ]
- Node        [ 0.10.45 ]
- Npm         [ 2.6.0 ]

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

```
browser-sync start --server --port 8000 --files="**" --no-ui --index index.html --directory
```

**Comment by parisk** [comment]
Are there any updates on this? Could this be fixed somehow? Is there any workaround?

**Comment by shakyShane** [comment]
We only have two choices with this.

1 - (current) - if the `--directory` flag is given, always show it - this is done so that you can still see a directory listing even if there's a index.html file in the same directory
2 - only show the directory listing if an index file is not found.

I understand *2* may be more like what you expect to happen, but the reason I chose *1* is that if you've explicitly  asked for the directory listing, you should get it.

perhaps there should be a third option, `directoryFallback` for example...

**Comment by parisk** [comment]
Choice **#2** is what I was searching for actually. Is there any straightforward programmatic workaround for this?

**Comment by shakyShane** [comment]
so the issue is that you need the directory listing middleware to be at the end of the stack, you could do

```js
var bs = require("browser-sync").create();
var serveIndex = require('serve-index');

// Start the server
bs.init({
    server: "test/fixtures"
}, function (err, bs) {
    bs.addMiddleware('', serveIndex('test/fixtures'))
});
```

**Comment by parisk** [comment]
Seems quite straightforward. Thanks a lot for this.

I will try this out and provide any new comments, if applicable.

**P.S.**: The `--directoryFallback` option sounds great as well.
