### ISSUE TITLE
Option idea: waitForDebounce (Multiple files changed = reload after the last change)

### ISSUE THREAD

**Issue by dryoma** [BrowserSync/browser-sync#1119]
### Issue details

I'd like to propose an option: in case if multiple files change simultaneoulely (or almost) don't fire page reloads until all of them are changed. Something like `waitForDebounce [Boolean]` (would work with `reloadDebounce`) or `reloadDebounceLast [Number, ms]`

Right now if `reloadDebounce` is set, a reload happens right after the first file change occures; it might be not the file currently active (html opened, etc.). so page reload doesn't reflect changes.

Setting `reloadDelay` is actually a gample; the change of the file in question might not occure in time. Or the opposite effect - waiting too long after all the changes are complete.

If the proposed option is set, the behavior would be like "Don't reload right after a file change; wait for `reloadDebounce` timeout to expire and then reload. If a change occures before that, restart the `reloadDebounce` timer" (it might be considered a `reloadDelay` that resets its timer when a change happen while the timer is running).

This (with the right value of `reloadDebounce`) will insure that reload happend only after all the file changes are complete.

### Please specify which version of Browsersync, node and npm you're running

Browsersync v2.11.1, node v4.3.1, npm v3.8.6; Windows, Grunt.

```js
var browserSyncOptions = {
  watchTask: true,
  server: {
    baseDir: "./"
  },
  reloadDelay: 3000,
  reloadDebounce: 5000,
};

module.exports = {
  p1: {
    bsFiles: {
      src : [
        'src/**/css/**/*.css',
        'src/**/js/**/*.js',
        'src/**/*.html'
      ]
    },
    options: browserSyncOptions
  }
};
```

**Comment by shakyShane** [comment]
in browser-sync@2.13.0, reloadDebounce will be all you need, with this config

```
var browserSyncOptions = {
  watchTask: true,
  server: {
    baseDir: "./"
  },
  reloadDebounce: 5000
};
```

Browsersync will wait for 5 seconds of event silence, then it will emit the last event that occured.

**Comment by dryoma** [comment]
Yeah, that's much better. But it would still run the reload twice: right after the first change and after the last one. Is there a possibility to somehow opt out of the first reload?
