### ISSUE TITLE
bs.exit() did't close server as we wish. we can still refresh page and get new html content?

### ISSUE THREAD

**Issue by hzlzh** [BrowserSync/browser-sync#1121]
I want to close the server connection by `bs.exit();` but seems not work.
Is there any other options except using child process?

- Browsersync [ 2.12.10   ]
- Node        [  5.3.0  ]
- Npm         [  2.14.21  ]

- [x] OS X
- [x] API

### If CLI, please paste the entire command below

`node test.js`

test,js
```nodejs
var bs = require("browser-sync").create();

// Start the server
bs.init({server: "./"});

// Quit the server after 5 seconds
setTimeout(function () {
    console.log('exit');
    console.log(bs);
    try{
        bs.exit();
    }catch(d){
        console.log(d);
    }
}, 3000);
```

**Comment by shakyShane** [comment]
Turns out to be a bug with socket.io https://github.com/socketio/socket.io/issues/1602#issuecomment-224270022

**Comment by littledu** [comment]
good job.
