### ISSUE TITLE
Chokidar or Anymatch for glob patterns?

### ISSUE THREAD

**Issue by zanona** [BrowserSync/browser-sync#1122]
### Issue details
[The documentation](https://browsersync.io/docs/options#option-files) states that for the `files` attribute under browsersync options, that I can use patterns following [Anymatch](https://github.com/es128/anymatch) api.

> Browsersync can watch your files as you work. Changes you make will either be injected into the page (CSS & images) or will cause all browsers to do a full-page refresh. See anymatch for more information on glob patterns.

However when using functions or anything that is not a string within `files[n].match`, I get an error:

    /Users/zanona/Developer/libs/bs-less/node_modules/chokidar/index.js:553
    throw new TypeError('Non-string provided as watch path: ' + paths);

### Steps to reproduce/test case

```js
browsersync.init({
files: [                                                                
    {
        options: { ignoreInitial: false },
        match: [
            function (p) {
                return !/bower_components|node_modules/.test(p);
            },
            serverPath + '**.html'
        ],
        fn: onHTMLChange
    }
]
});
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.12.8]
- Node        [5.7.1]
- Npm         [3.6.0]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
`match` does not accept a function like this I'm afraid.

To exclude directories though, do the following.

```js
browsersync.init({
	files: [
		{
			options: {
				ignoreInitial: false,
				ignored: [
					/bower_components|node_modules/
				]
			},
			match: [serverPath + '**.html'],
			fn: onHTMLChange
		}
	]
});
```

**Comment by zanona** [comment]
@shakyShane Thanks I figured that along the way. But then is it a bug on the documentation, because anymatch accept this kind of pattern? I got a bit confused that it mentions anymatch at all instead chokidar?

**Comment by shakyShane** [comment]
Removed from https://www.browsersync.io/docs/options
