### ISSUE TITLE
Change “Local: http://localhost:3000” to "Local: http://something.dev:3000”

### ISSUE THREAD

**Issue by ryanaltvater** [BrowserSync/browser-sync#1124]
I know this question has been asked many times already, but I'm just not following some of the proposed solutions and it's still unclear. Is it possible to change “Local: http://localhost:3000” to "Local: http://something.dev:3000” or "Local: http://local.something.com:3000"?

Right now, I have “something.dev” pointing to an IP address in /etc/hosts. I would like to launch “something.dev:3000” with BrowserSync, but I can’t seem to figure out how…even after reading other issues and questions about this request. Any idea what I'm be doing wrong, or is what I’m asking not possible? I’m looking for a custom local URL while developing, besides “localhost”, and still have all the auto-refresh glory.

**Comment by shakyShane** [comment]
Don't use any `server` or `proxy` options and you'll be given a snippet that you can paste into your website footer, like this

https://asciinema.org/a/72fejbgui07e160vlt3w0fimi

**Comment by ryanaltvater** [comment]
I already tried this and receive the same error as this issue https://github.com/BrowserSync/browser-sync/issues/791

**Comment by ryanaltvater** [comment]
![screen shot 2016-06-15 at 3 20 50 pm](https://cloud.githubusercontent.com/assets/1336787/16094140/c9121f60-330c-11e6-9f07-f4afbb6ad7e3.png)

**Comment by ryanaltvater** [comment]
@shakyShane ^

**Comment by shakyShane** [comment]
Shouldn't have your domain in it - show me your config :)

**Comment by ryanaltvater** [comment]
**HTML**
```
		<script id="__bs_script__">//<![CDATA[
			document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.13.0.js'><\/script>".replace("HOST", location.hostname));
		//]]></script>
	</body>
</html>
```

**Gulp**
```
gulp.task('webserver', function() {
	browserSync.init();
});
```

**/etc/hosts**
```
## vagrant-hostmanager-start id: 9c53f05f-6141-4f72-8b78-64ef95514498
192.168.33.10   lenovogaming.dev
## vagrant-hostmanager-end
```

**URL**
```
http://lenovogaming.dev/
```

**Network & Console**

![screen shot 2016-06-16 at 9 29 49 am](https://cloud.githubusercontent.com/assets/1336787/16118422/02710e86-33a5-11e6-8089-7541d89f4d63.png)

**Comment by shakyShane** [comment]
try 

```js
browserSync.init({
    scriptPath: function (path, port, options) {
        return options.getIn(['urls', 'local']) + path;
    }
});
```

**Comment by shakyShane** [comment]
or 

```js
browserSync.init({
    scriptPath: function (path, port, options) {
        return options.getIn(['urls', 'external']) + path;
    }
});
```

**Comment by ryanaltvater** [comment]
**HTML**
```
		<script id="__bs_script__">//<![CDATA[
			document.write("<script async src='http://10.0.1.7:3000/browser-sync/browser-sync-client.2.13.0.js'><\/script>".replace("HOST", location.hostname));
		//]]></script>
	</body>
</html>
```

**Gulp**
```
gulp.task('webserver', function() {
	browserSync.init({
	    scriptPath: function(path, port, options) {
	        return options.getIn(['urls', 'external']) + path;
	    }
	});
});
```

**/etc/hosts**
```
## vagrant-hostmanager-start id: 9c53f05f-6141-4f72-8b78-64ef95514498
192.168.33.10   lenovogaming.dev
## vagrant-hostmanager-end
```

**URL**
```
http://lenovogaming.dev/
```

**Network & Console**

![screen shot 2016-06-16 at 11 51 46 am](https://cloud.githubusercontent.com/assets/1336787/16123457/f72b18f0-33b8-11e6-84c4-3bcbea59c01d.png)

**Comment by ryanaltvater** [comment]
@shakyShane Is what I'm asking for possible, and is there specific documentation where I can find how to do this? It's seems to be a very common request, but everybody's suggestions on how to achieve it are different. I've tried those multiple ways and I'm unsuccessful. A start-to-finish guide or video snippet would be helpful for everyone wanting to know how to do this.

**Comment by ryanaltvater** [comment]
I think I may have figured it out. I'm pointing the "proxy" to Vagrant's IP address, defining the desired "host" URL, opening it, and then I also had to add an extra entry to my hosts file to point the desired "host" URL to my local IP address. My browser then opens "lenovogaming.local:3000" that points to my local IP address, and my local IP address points to the "proxy" IP address. I hope this helps someone else in need.

**Gulp**
```
gulp.task('webserver', function() {
	browserSync.init({
		host: 'lenovogaming.local',
		open: 'external',
		proxy: '192.168.33.10'
	});
});
```

**Comment by OlegFilth** [comment]
GUYS why not solve of this problem(

**Comment by asolopovas** [comment]
I also have a problem where I use browser-sync in a docker container. The problem is that withing docker environment I don't have access to domains like on Nginx. I have to proxy service name to something "https://httpd" and because of that it does not replace anchors with correct domain name like domain.test:3000, If I create `/etc/hosts/` entry with the service ip adress and domain.test than redirected urls rather than saying https://domain.test:3000 replace it with service name from which the browsersync is running in my case its https://nodejs, is there any override for that so that all links just get rewritten to specific host?
