### ISSUE TITLE
getting Cannot GET/ error

### ISSUE THREAD

**Issue by mahyarmobilab** [BrowserSync/browser-sync#1126]
Hi there,
I am working on a react and redux application. I have used browser-sync(version 2.12.5) as my development server and I have a problem with it. I need to specify a different index file for starting the server. according to what I read from documentation I can do this in following way:
I have a srcServer.js file which have this in its content:

```
browserSync({
  server: {
    baseDir: 'src/main/resources',
    index:'ui.html',
    middleware: [
      webpackDevMiddleware(bundler, {
        publicPath: config.output.publicPath,
        stats: { colors: true },
        noInfo: true
      }),
      webpackHotMiddleware(bundler),

      historyApiFallback()
    ]
  },

  files: [
    'src/main/resources/*.html'
  ]
});

```
i am using npm to run srcServer.js file. my package.json:

```
"scripts": {
    "start-message": "babel-node tools/startMessage.js",
    "prestart": "npm-run-all --parallel start-message",
    "start": "npm-run-all --parallel test:watch open:src lint:watch",
    "open:src": "babel-node tools/srcServer.js",
```
after running _npm start_ this is the output in the terminal:

```
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://172.16.3.203:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://172.16.3.203:3001
 -------------------------------------
[BS] Serving files from: src/main/resources
[BS] Watching files...

```
but I am getting cannot get / error in browser:  localhost:3000
any idea how I can solve this?

**Comment by noahjohn9259** [comment]
If anyone is experiencing this issue. Try to move historyApiFallback as the first entry in the array
