### ISSUE TITLE
CSS Injection with notify success but without any visible changes

### ISSUE THREAD

**Issue by luckyraul** [BrowserSync/browser-sync#1127]
### Issue details

When I change sass file I have Injection notify success on page. But I can't see any changes.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.13.0]
- Node        [4.2.3]
- Npm         [    ]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### Code

```
gulp.task('sass', function () {
 return gulp.src([`${sass_folder}/**/*.scss`])
     .pipe(sourcemaps.init())
     .pipe(sass().on('error', sass.logError))
     .pipe(cssnano({autoprefixer: {add: true}}))
     .pipe(sourcemaps.write('.'))
     .pipe(gulp.dest(css_folder))
     .pipe(browserSync.stream({match: '**/*.css'}))
     .pipe(notify({message: 'Styles complete', onLast: true}));
});
```
```
gulp.task('serve', ['sass'], function() {
    browserSync.init({
        proxy: 'x.example.com'
    });
    gulp.watch(`${sass_folder}/**/*.scss`, ['sass']);
    gulp.watch(`${theme_folder}/**/*.phtml`).on('change', browserSync.reload);
});

**Comment by luckyraul** [comment]
Socket event 
```
socket.io-client:socket emitting event ["file:reload",{"ext":"css","path":"/Volumes/Data/GIT/projects/xxx/src/skin/frontend/default/xxx/css/main.css","basename":"main.css","type":"inject","log":false}] +1ms
```

**Comment by shakyShane** [comment]
Please first try https://github.com/Browsersync/recipes/tree/master/recipes/gulp.sass and see if your setup can be modified to work as such.

Failing that, you will need to provide a sample application for me to help further as this is most likely an issue with configuration, but it could be on any number of modules :)

**Comment by luckyraul** [comment]
@shakyShane  

I provided you my whole gulp file!

Can you help me with investigation with communication between a bs-client and a bs-server. I found that while processing event from the bs-server inside the bs-client it compares css files on a page and inject them if they match. In my case match is found, and I can easily notice what the browser is trying to apply something(some freese and repaint). However I don't see any changes.

**Comment by shakyShane** [comment]
In that case it's probably a race condition where the event is being sent
to the client before the new file is finished writing to disk

**Comment by luckyraul** [comment]
It is not retrieving file content from the stream?!
