### ISSUE TITLE
Avoid binding to all addresses

### ISSUE THREAD

**Issue by gagern** [BrowserSync/browser-sync#1132]
Always binding to all addresses, the way the command line server currently does, can be a security problem, depending on who is on the same LAN. Even if the `offline` option is given and the only URLs printed to the user refer to localhost, the server still listens on all available addresses. It would be nice if one could pass a suitable host name or address to [the `listen` method invocation](https://github.com/BrowserSync/browser-sync/blob/b72455d50da9f3ede1fde9ac0738333726440b2c/lib/server/index.js#L36), and ideally if this were exposed to the CLI as well. At the very least, the server should be able to bind to `localhost` only. As a second step, it might make sense to allow binding to an arbitrary IP address, like e.g. the one of a virtual Docker network used for development.

This feature request is analogous to https://github.com/isaacs/st/pull/74, but since BrowserSync is far more complicated, I'm having some trouble finding all the right places to hook this up, with the CLI in particular. I'm also not sure how to name the options to integrate with the overall structure of the config.

**Comment by n9** [comment]
I have hacked the "solution" for this, see  #1431. However, it works in simple scenarios (overall tests are failing).

**Comment by onc** [comment]
This really is an issue and I would really love to see a fix for this. I'm working from a university network where all machines have global IP addresses and therefore my service would be exposed to the internet if not prevented using a firewall. I there any chance that this issue get's fixed after no response for such a long time?

**Comment by n9** [comment]
@onc You can try this: https://github.com/BrowserSync/browser-sync/pull/1431 (feel free to rebase it anywhere)

**Comment by onc** [comment]
Thank you for the suggestion and your quick response. I saw this pull request. But I think it would be great to have a cleaner solution for this. I'm using browsersync for projects of my students and would like to give them a preconfigured project but not including (patched) node modules.

**Comment by n9** [comment]
Yes, you might wait few more years, or DIY.

**Comment by shakyShane** [comment]
Fixed with the new 'listen' option


```
npm i -g browser-sync@2.25.0
browser-sync . --listen localhost
```
