### ISSUE TITLE
Able to HOST more than 1 Website possible?

### ISSUE THREAD

**Issue by bradws** [BrowserSync/browser-sync#1138]
### Question: Is it possible to HOST more-than-one site at the same time?

I'm using it with 1 website which is working fine.

My app requires 2 websites in the browser. This is for development purposes and not production. Is there a way to simply keep the default values for one instance, and just maybe provide a http port number in the configuration for the second instance (maybe something like 8080?)

Please help with the configuration options and/or point me in the right area as I can't seem to find anything on this (or even if it's possible?)

Thanks.
### My current config is simply:
```
module.exports = {
        ghostMode: false
};
```

### Please specify which version of Browsersync, node and npm you're running

- I'm using lite-server v2.2.0
- Node v5.11.1
- Npm v 3.8.6
- Using Windows 7 Ultimate

### Browsersync use-case

I am using it simply in a script in `package.json` in the [Angular 2 Quickstart](https://angular.io/docs/ts/latest/quickstart.html)

`package.json` (simplified)
```
{
  "name": "angular2-quickstart",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
     "tsc": "tsc",
    "tsc:w": "tsc -w",
   "lite": "lite-server",
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10"
  }
}
```

**Comment by shakyShane** [comment]
Unfortunately this would be out of scope for Browsersync.

You would need to call Browsersync twice with separate configurations for this to work :)
