### ISSUE TITLE
Browser-sync starts to load but crashes.

### ISSUE THREAD

**Issue by scottheron** [BrowserSync/browser-sync#1144]
### Issue details

Tried to start my project by running npm start and got the following error.

    > front-end-hackathon@ start /home/scott/code/GA-DIR/front-end-hackathon
    > node_modules/browser-sync/bin/browser-sync.js start --server . --files .

    [BS] Access URLs:
     ----------------------------------------
           Local: http://localhost:3000
        External: http://192.168.157.134:3000
     ----------------------------------------
              UI: http://localhost:3001
     UI External: http://192.168.157.134:3001
     ----------------------------------------
    [BS] Serving files from: .
    [BS] Watching files...
    events.js:160
          throw er; // Unhandled 'error' event
          ^

    Error: watch node_modules/core-js/fn/object/set-prototype-of.js ENOSPC
        at exports._errnoException (util.js:1008:11)
        at FSWatcher.start (fs.js:1429:19)
        at Object.fs.watch (fs.js:1456:11)
        at createFsWatchInstance (/home/scott/code/GA-DIR/front-end-hackathon/node_modules/chokidar/lib/nodefs-handler.js:37:15)
        at setFsWatchListener (/home/scott/code/GA-DIR/front-end-hackathon/node_modules/chokidar/lib/nodefs-handler.js:80:15)
        at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/scott/code/GA-DIR/front-end-hackathon/node_modules/chokidar/lib/nodefs-handler.js:228:14)
        at FSWatcher.NodeFsHandler._handleFile (/home/scott/code/GA-DIR/front-end-hackathon/node_modules/chokidar/lib/nodefs-handler.js:255:21)
        at FSWatcher.<anonymous> (/home/scott/code/GA-DIR/front-end-hackathon/node_modules/chokidar/lib/nodefs-handler.js:473:21)
        at FSReqWrap.oncomplete (fs.js:123:15)

    npm ERR! Linux 3.19.0-32-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
    npm ERR! node v6.3.0
    npm ERR! npm  v3.10.5
    npm ERR! code ELIFECYCLE
    npm ERR! front-end-hackathon@ start: `node_modules/browser-sync/bin/browser-sync.js start --server . --files .`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the front-end-hackathon@ start script 'node_modules/browser-sync/bin/browser-sync.js start --server . --files .'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the front-end-hackathon package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node_modules/browser-sync/bin/browser-sync.js start --server . --files .
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs front-end-hackathon
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls front-end-hackathon
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/scott/code/GA-DIR/front-end-hackathon/npm-debug.log

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.13.0 ]
- Node        [v6.3.0]
- Npm         [v3.10.5 ]

### Affected platforms

- [X] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below

`node_modules/browser-sync/bin/browser-sync.js start --server . --files .`

**Comment by bhague1281** [comment]
Possibly the issue in #224
