### ISSUE TITLE
Browsersync will add it's script tag to a <body> element within a comment

### ISSUE THREAD

**Issue by jmlee2k** [BrowserSync/browser-sync#1145]
### Issue details

In one of my HTML files, I had a commented out <body> element, and the browsersync script was injected into that element, which (of course) caused it to not work.

### Steps to reproduce/test case

Just add a commented out body tag in an HTML file, anywhere before the real body tag occurs, like so:

```
<!DOCTYPE html>
<!--<body>-->
<html>
<head>
</head>
<body>
    real content
</body>
</html>
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.13.0]
- Node        [5.1.0]
- Npm         [3.3.12]

### Affected platforms

I believe all platforms would be affected, but can't be sure.

### Browsersync use-case

N/A

**Comment by shakyShane** [comment]
Thanks for your report.

I've addressed this multiple times in the past, but basically trying to match anything in HTML with regexes is extremely error-prone, so Browsersync instead uses a deliberately simple one (just looks for the first body tag) - and in situations where you need to be more specific, you can provide a different one via https://www.browsersync.io/docs/options#option-snippetOptions

Hope this helps :)
