### ISSUE TITLE
Q: Is there a way to modify the existing DOM in proxy mode?

### ISSUE THREAD

**Issue by marvinhagemeister** [BrowserSync/browser-sync#1157]
At work we have a project where we need to put our custom css on top of an existing site. Thing is that our client has a separate repository for templates and stylesheets and we only have access to the latter.

**What we have tried so far:**

The best solution so far is to inject our custom css just before the closing body tag.

```js
const browserSync = require('browser-sync');

browserSync.init({
  proxy: 'http://example.com',
  files: ['proxy/test.css'],
  serveStatic: ['proxy'],
  snippetOptions: {
    rule: {
      match: /<\/body>/i,
      fn: function (snippet, match) {
        return '<link rel="stylesheet" type="text/css" href="/test.css"/>' + snippet + match;
      }
    }
  }
});
```

The problem is that the existing css interferes with our own. Is there any way to extend browser-sync so that it removes specific DOM nodes upon starting the server?

**Comment by marvinhagemeister** [comment]
I just found the solution after creating this issue:

The trick is to add another snippet which simply removes all `<link rel="stylesheet" ...>`-nodes via javascript.

```js
const browserSync = require('browser-sync').create();

browserSync.init({
  proxy: 'http://example.com',
  files: ['proxy/test.css'],
  serveStatic: ['proxy'],
  snippetOptions: {
    rule: {
      match: /<\/body>/i,
      fn: function (snippet, match) {
        var out = '';
        out += `<script>
          var elems = document.querySelectorAll("link[rel='stylesheet']");
          [].forEach.call(elems, function(el) {
            el.remove();
          });
        </script>`;
        out += '<link rel="stylesheet" type="text/css" href="/test.css"/>' + snippet + match;
        return out;
      }
    }
  }
});
```

**Comment by alliv8** [comment]
Is there a way to modify served css files as well from here? I was able to match css files using middleware but couldn't find a way to alter the `res`
