### ISSUE TITLE
Browsersync not injecting client script after body when in proxy mode

### ISSUE THREAD

**Issue by timkley** [BrowserSync/browser-sync#1169]
### Issue details

I have a vhost in a Vagrant Scotchbox set to web-starter-kit.test.
I'm on Mac and in my /hosts I have `web-starter-kit.test ip.of.scotchbox`. Vagrant is up and running and my project renders just fine.

I start browsersync like this:

```
## browsersync.js
var bs = require("browser-sync").create();

bs.init({
    logLevel: 'debug',
    open: false,
    proxy: 'web-starter-kit.test',
    files: ["*.html", "dist/css/**.css"]
});
```

`node browsersync.js`

In the terminal I see `Proxying: http://web-starter-kit.test` and `Local: http://localhost:3000`

If I surf to http://web-starter-kit.test the js is not injected, when I surf to localhost:3000 everthing works as expected.

### Steps to reproduce/test case

1. Setup scotchbox with a vhost
2. Link up the vhost in /etc/hosts
3. Run browser-sync

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.14.0  ]
- Node        [  5.8.0  ]
- Npm         [  3.8.2  ]

### Affected platforms

- [x] OS X

### Browsersync use-case

- [x] API

Thanks for helping me out!

**Comment by shakyShane** [comment]
This is expected - we can't modify your existing server, that's why we provide the separate URL :)
