### ISSUE TITLE
IPv6 only when using Node 6.4

### ISSUE THREAD

**Issue by martin31821** [BrowserSync/browser-sync#1174]
### Issue details

When using NodeJS 6.4 browsersync only binds to IPv6.
The exact same command works well unter NodeJS 6.3
Netstat output then:
```
> netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp6       0      0 :::4000                 :::*                    LISTEN      1000          3621239     13757/node      
tcp6       0      0 :::4001                 :::*                    LISTEN      1000          3633166     13770/node      
tcp6       0      0 :::5000                 :::*                    LISTEN      1000          3621241     13757/node      
tcp6       0      0 :::5001                 :::*                    LISTEN      1000          3633168     13770/node   
```
### Steps to reproduce/test case

* Install NodeJS 6.4
* Install NPM 3.10 
* For the above steps, you can use the node:6.4 docker container

* npm install browser-sync
* ./node-modules/.bin/browser-sync start --host 0.0.0.0
* browser-sync only binds to tcp6 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.14
- Node        6.4
- Npm         3.10

### Affected platforms

- [x] linux
- [ ] windows 
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
- only linux was tested

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

Startup command:
`${PROJECT_DIR}/node_modules/.bin/browser-sync start --host 0.0.0.0`

**Comment by shakyShane** [comment]
Tests are passing on 6.5, can you try that and if the problem persists we can re-open :)

**Comment by josephdpurcell** [comment]
For my issue, I was able to add `--listen 0.0.0.0` to resolve the issue, see https://github.com/BrowserSync/browser-sync/issues/799#issuecomment-1341755178.
