### ISSUE TITLE
Proxying a local non-HTTPS server as HTTPS

### ISSUE THREAD

**Issue by bfred-it** [BrowserSync/browser-sync#1175]
### Issue details

I'd like to use `{https: true}` when proxying a local server (Apache/PHP) that's not configured for https

### Steps to reproduce/test case

```sh
browser-sync start --proxy localhost --https
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.14.0 ]
- Node        [ v6.2.2 ]
- Npm         [ 3.10.6 ]

### Affected platforms

- [x] all

### Browsersync use-case

- [x] all

**Comment by shakyShane** [comment]
A good one for a PR 👍

**Comment by shakyShane** [comment]
browser-sync@2.15.0 👍

**Comment by bfred-it** [comment]
❤️
