### ISSUE TITLE
Browser-sync in a Docker container

### ISSUE THREAD

**Issue by nojaf** [BrowserSync/browser-sync#1177]
### Issue details

I'm trying to setup browser-sync inside a Docker container.
I'm on Windows 10 and I'm using the ```node:latest``` Docker image.

### Steps to reproduce/test case

Run ```docker run -it --rm -v "${path}:/usr/src/app" -w "/usr/src/app" -p 3000:3000 node:latest bash```
${path} is a variable with the current folder in a format that works for Docker.
```$path = "$(pwd".Replace("C:\","/c/").Replace("\","/");```

Once in the container I first try to install browser-sync and I get
```npm i browser-sync --save-dev```

```
pm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "browser-sync" "--save-dev"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! path ../express/bin/express
npm ERR! code ENOTSUP
npm ERR! errno -95
npm ERR! syscall symlink

npm ERR! nospc ENOTSUP: operation not supported on socket, symlink '../express/bin/express' -> '/usr/src/app/node_modules/.bin/express'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
```

Most liked not a bs problem here. Looks like ```.bin``` folder can't be accessed, not sure.

Next I try to run ```npm run bs```.
Package.json:
```json
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "bs":"browser-sync start --server --files index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

```
> browser-sync start --server --files index.html

sh: 1: browser-sync: not found

npm info lifecycle app@1.0.0~bs: Failed to exec bs script
npm ERR! Linux 4.4.15-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bs"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! app@1.0.0 bs: `browser-sync start --server --files index.html`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the app@1.0.0 bs script 'browser-sync start --server --files index.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browser-sync start --server --files index.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

This is probably related to the first problem.
Next I tried to install bs globally.
If I run my same command now browser-sync starts.
But if I edit my html file bs doesn't reload.
If I reload my browser manually I do see my changes.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.14.0]
- Node        [6.4.0]
- Npm         [3.10.3]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

```browser-sync start --server --files index.html```

**Comment by shakyShane** [comment]
Looks like there's an issue with available space within the container - try some of the suggestions in the following links https://www.google.co.uk/search?q=npm+nospc

Closing as I don't believe this is an issue with Browsersync, but rather the docker+your machine setup :)
