### ISSUE TITLE
BS only detects "manually saved file" changes

### ISSUE THREAD

**Issue by MtDalPizzol** [BrowserSync/browser-sync#1181]
### Issue details

I'm using SASS and I want BS to refresh the browser after my production CSS is built. I don't need it to refresh when my SASS files are changed. It needs to wait until SASS changes the output CSS file. It should refresh when this final CSS file changes. The command below doesn't detect changes made by SASS to the CSS file. If I change the glob pattern from `**/*.css` to `**/*.scss`, BS detects the changes on the SASS files as expected but refreshes the browser before the SASS compilation has ended. Seems like BS only detects changes to files that are "manually saved".

### Steps to reproduce/test case

Here is my `scripts` entry on my `package.json`:

```
"scripts": {
    "browsersync": "browser-sync start --proxy \"localhost\" --files \"**/*.php, **/*.html, **/*.css, **/*.js\" --no-ui --reload-delay 500",
    "css:build": "node-sass -o css/desktop css/desktop/main.scss --output-style compressed",
    "css:watch": "chokidar \"css/desktop/**.scss\" -c \"npm run css:build\"",
    "start": "parallelshell \"npm run css:watch\" \"npm run browsersync\""
  }
```

Run `npm start`

SCSS and CSS files are in the same directory.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.14.0]
- Node        [4.5.2]
- Npm         [2.15.9]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

browser-sync start --proxy \"jornaldacidadeonline.localhost\" --files \"**/*.php, **/*.html, **/*.css, **/*.js\" --no-ui

**Comment by shakyShane** [comment]
Probably the CSS files don't exist when you first start? either way there are some cases where file events are missed - try just watching the CSS directory instead

```diff
- **/*.css
+ path/to/css
```

try this & if there's no luck we can re-open :)
