### ISSUE TITLE
Redirect HTTP to HTTPS in proxy mode...

### ISSUE THREAD

**Issue by al-the-x** [BrowserSync/browser-sync#1183]
### Issue details

While proxying a remote with `proxy: true` or the `-p|--proxy` command-line flag, it would be great it Browser-Sync would _also_ listen for HTTP traffic and redirect to the correct HTTPS URL.

### Steps to reproduce/test case

```shell
$> cd path/to/project
$> browser-sync --ss ./ -p https://example.com &
$> open http://localhost:3000
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.14.0 ]
- Node        [ 4.4.5 ]
- Npm         [ 3.10.6 ]

### Affected platforms

- [ ] linux
- [ ] windows
- [X] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [X] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below

See above...

**Comment by shakyShane** [comment]
Hi! This is a very nice idea, but because Browsersync binds to a port (such as 3000), we can't have any other service also listening on that port.

eg: in a typical production web-server you'd redirect any `http:` requests that come in through port `80` to `https:` - but that's not something we can do with a development tools such as Browsersync. :)

**Comment by bfred-it** [comment]
Looks like this is somewhat possible and would enable BS to listen to both protocols at once, perhaps without even needing the `--https` flag

https://github.com/mscdex/httpolyglot

**Comment by al-the-x** [comment]
@shakyShane Sorry to try to resurrect an old issue, but what are your thoughts on @bfred-it's suggestion about using `httppolyglot` to handle `http` and `https` traffic simultaneously? Happy to submit a PR if you'll point me in the right direction...
