### ISSUE TITLE
How to mix webpack with browser-sync in time?

### ISSUE THREAD

**Issue by clownvary** [BrowserSync/browser-sync#1188]
### Issue details

My project using webpack and gulp,i want to add b-s in it,when files changed i want to reload browser until webpack's  task had completed   ,but the problem is the webpack task wasted time too much,did not wait for the webpack's task to complete,   then the browser reload，what should I do with it,thanks!

**Comment by xingzhipeng** [comment]
try this
gulpfile.js
`gulp.task('webpack', () => {
    gulp.src('src/index.js')
    .pipe(webpack(require('./webpack.config.js')))
    .pipe(gulp.dest('bundle'))
})
gulp.task('watch', () => {
    browserSync.reload()
})
gulp.task('default', ['webpack'], () => {
    browserSync.init({
        server: {
            baseDir: './'
        }
    })
    gulp.watch('bundle/*.js', ['watch'])
})`
webpack.config.js
`module.exports = {
  watch: true,
  entry: ['./src/index.js'],
  output: {
    filename: 'index.bundle.js'
  },
  module: {
    loaders: [
      {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
      },
    ]
  }
}`

**Comment by clownvary** [comment]
@xingzhipeng thanks,it works
