### ISSUE TITLE
browsersync.io certificate expired

### ISSUE THREAD

**Issue by gruppjo** [BrowserSync/browser-sync#1190]
### Issue details

browsersync.io https certificate expired

### Steps to reproduce/test case

visit website

![image](https://cloud.githubusercontent.com/assets/1370779/18205706/b93a146c-7123-11e6-9985-17f1226b7837.png)

**Comment by shakyShane** [comment]
Fixed, thanks :)

**Comment by gruppjo** [comment]
you're welcome :)
