### ISSUE TITLE
Problem: Browser-sync with Tomcat, nginx, etc, .jsp programs.

### ISSUE THREAD

**Issue by kanlidy** [BrowserSync/browser-sync#1194]
### Issue details
1. JAVA program with tomcat7 as container.
2. use BS proxy for http://localhost:8080
3. gulp task for sass and js.

Change js and sass files, the browser reloaded, but js and css should use F5 to reload the second time, then works.

I thought the Browser-sync do not inspect the files which in the buffer of tomcat changes, so it need the second refresh.

how to solve this problem? Thanks.
### Steps to reproduce/test case
1. IDE: jetbrains IDEA use tomcat 7
2. jeecg source code : [https://github.com/kanlidy/jeecg](https://github.com/kanlidy/jeecg)
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [ 2.14.0  ]
- Node        [  v6.3.1  ]
- Npm         [  3.10.3  ]
### Affected platforms
- [ \* ] windows 10
### Browsersync use-case
- [ \* ] Gulp
### If CLI, please paste the entire command below

`gulp server`
### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
1. Gulpfile.js:
   
   ```
       var gulp = require('gulp'),
       autoprefixer = require('gulp-autoprefixer'),
       sass = require('gulp-sass'),
       uglify = require('gulp-uglify'),
       plumber = require('gulp-plumber'),
       gutil = require('gulp-util'),
       gulpIgnore = require('gulp-ignore');
   
       var watcher = require('gulp-watch');
       var browserSync = require('browser-sync').create({
   
       });
   
       var onError = function (err) {
           gutil.beep();
           console.log(err);
       };
   
       const src = 'src/main/webapp/plug-in/admin/';
       const jsp = 'src/main/webapp/webpage/';
       const demoPage = 'src/main/webapp/webpage/com/whbt/demo/';
   
   var config = {
   
       js_path:src+'js/*.js',
       css_path:src+'css/**/*.scss',
       img_path:src+'img/*',
       watch: jsp+'**/*.jsp',
       build_js:demoPage+'',
       build_css:demoPage+'',
       build_img:demoPage+'img'
   }
   
   //Scripts Task
   //Uglifies
   gulp.task('scripts',function(){
       gulp.src(config.js_path)
           .pipe(gulpIgnore.exclude(condition))
           .pipe(plumber({
               errorHandler: onError
           })) //使用plumber
           .pipe(uglify())
           .pipe(gulp.dest(config.build_js));
   });
   
   gulp.task('scss',function(){
       gulp.src(config.css_path)
           .pipe(plumber({
               errorHandler: onError
           }))
           .pipe(sass({outputStyle: 'compressed'}))
           .pipe(autoprefixer({
               browsers: ['last 2 versions']
           }))
           .pipe(gulp.dest(config.build_css))
           .pipe(browserSync.stream({match: config.build_css}))
   });
   
   gulp.task('server',['scss','scripts'],function(){
       browserSync.init({
           //server: {
           //    baseDir: "./"
           //}
           port: 3000,
           proxy: {
               target:"localhost:8080"
           }
       });
       gulp.watch(config.css_path, ['scss']);
       watcher(config.build_css+'**/*.css',function(){
           browserSync.reload();
       });
       gulp.watch(config.js_path, ['scripts']);
       gulp.watch(config.build_js+'**/*.js').on('change', browserSync.reload);
       // gulp.watch("img/*", ['image']).on('change', browserSync.reload);
       gulp.watch(config.watch).on('change', browserSync.reload);
   });
   ```

**Comment by kanlidy** [comment]
I found a good plugin frontend-maven-plugin:  [http://stackoverflow.com/questions/25865251/how-to-organize-full-build-pipeline-with-gulp-maven-and-jenkins-all-the-way-to/25922758#25922758](http://stackoverflow.com/questions/25865251/how-to-organize-full-build-pipeline-with-gulp-maven-and-jenkins-all-the-way-to/25922758#25922758)

**Comment by ReginaldoSantos** [comment]
@kanlidy same problem here and I'm already using the maven front end plugin for building. How did you solve the refresh issue?

**Comment by ReginaldoSantos** [comment]
Just for completeness I've solved it by using the tomcat deploy location directly for publishing the changes.
