### ISSUE TITLE
Alternative way for installation

### ISSUE THREAD

**Issue by Lisa-Williams** [BrowserSync/browser-sync#1197]
### Issue details

Is there an alternative way to install Browser Sync?
I'm not willing to install Node because it litters my SSDs with folders and files.

**Comment by shakyShane** [comment]
At this time, no.

I don't see why somebody couldn't wrap it up as an electron app though 👍

**Comment by Lisa-Williams** [comment]
And Electron doesn't require the installation of Node of course.
Willing to take up the glove this morning, I discovered the following : http://electron.atom.io/docs/tutorial/quick-start/

> ## Try this Example
Clone and run the code in this tutorial by using the electron/electron-quick-start repository.
**_Note: Running this requires Git and Node.js (which includes npm) on your system._**
