### ISSUE TITLE
Uint8Array not defined when loading page on IE9

### ISSUE THREAD

**Issue by caneta** [BrowserSync/browser-sync#1198]
### Issue details

When I run a page with browserSync on IE9, I get the error "Uint8Array not defined" on file browser-sync-client.2.15.0.js. No problems with Firefox and Chrome

### Steps to reproduce/test case
Run browserSync with Gulp-3.9.1. and load the page on IE9

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.15.0]
- Node        [6.2.1]
- Npm         [3.9.5]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```js
gulp.task('serve', ['dist'], () => {

   browserSync.init({
     server: {
       baseDir: 'dist/'
     },
     open: false,
     notify: false
   });

   gulp.watch('src/scss/*.scss', ['dist:css']).on('change', browserSync.reload);
   gulp.watch('src/html/*.html', ['dist:html']).on('change', browserSync.reload);
   gulp.watch('src/js/*.js', ['dist:js']).on('change', browserSync.reload);
 });
```

**Comment by nazarsh** [comment]
+1

**Comment by jpstone** [comment]
+1

**Comment by jsosa** [comment]
+1

**Comment by draganSm** [comment]
+1

```
SCRIPT5009: 'Uint8Array' is undefined 
browser-sync-client.js?v=2.16.0, line 1 character 341
```

**Comment by endelwar** [comment]
Same error on IE8 with 2.14.3 and 2.16.0 launched in CLI

**Comment by stegano** [comment]
+1
try browser-sync<"2.13.0" version

**Comment by kellerkichel** [comment]
+1

**Comment by Hancoson** [comment]
+1

**Comment by shakyShane** [comment]
Please all try 2.17.3 where this is now resolved :)
