### ISSUE TITLE
“No 'Access-Control-Allow-Origin' header is present on the requested resource” in django

### ISSUE THREAD

**Issue by Tatenda** [BrowserSync/browser-sync#1199]
### Issue details
I am developing on top of Django. When trying to use gulp and Django together i am encountering a "No 'Access-Control-Allow-Origin'" error. I am running on localhost:3000 and have setup localhost:8000 as a porxy. 

### Steps to reproduce/test case

```js
var gulp = require('gulp'),
    browserSync = require('browser-sync');

gulp.task('browser-sync', function(){
  browserSync.init({
      notify:false,
      proxy:"localhost:8000"
  });
});
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.15.0  ]
- Node        [ 4.5.0  ]
- Npm         [  2.15.9  ]

### Affected platforms

- [x] Chrome
- [x] windows

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```js
var gulp = require('gulp'),
    browserSync = require('browser-sync');

gulp.task('browser-sync', function(){
  browserSync.init({
      notify:false,
      proxy:"localhost:8000"
  });
});

gulp.task('watch', function(){
  gulp.watch(['../*.js', 'static/js/marks_app/directives/*.js'], ['marksApp_js']);
  gulp.watch('../marks_app/**/*.html', ['marksApp_html']);
})

gulp.task('default', ['marksApp_js', 'marksApp_html', 'browser-sync', 'watch']);
```

**Comment by shakyShane** [comment]
fixed via new option

`cors: true`

https://github.com/BrowserSync/browser-sync/commit/62d83b895d032624957474b6a23da157913caabd
