### ISSUE TITLE
exclude folder from syncing 

### ISSUE THREAD

**Issue by nimo23** [BrowserSync/browser-sync#1201]
I want to exclude the folder wp-admin from browsersync. I does not work. I use gulp.

```
var files = [
			'**/*.php',
			'**/*.css',
			'**/*.js',
			'**/*.{png,jpg,gif}',
			'!/wp-admin/**',
			'!/wp-admin/',
			'**!/wp-admin/',
			'**!/wp-admin/**',
			'\!/wp-admin/**',
			'\!/wp-admin'
		    ];
```

I guess, because of the first glob patterns (**/..). Would be nice to provide a extra setting in browsersync whith a new property "exlude:".

**Comment by shakyShane** [comment]
> I guess, because of the first glob patterns

correct.

You're thinking about this the wrong way around. Instead of first matching *everything* then trying to exclude, you should just **match** specific folders instead. This will also give better performance :)

**Comment by nimo23** [comment]
Hello,

yes you right. But when I do this, then browser-sync will not scan my js-files:

```
gulp.task('browser-sync', function() {
	var files = [
                        // this does not work
			'wp-content/themes/test/**/*.js',
                        // but this would work: '/**/*.js'
		    ];

	browserSync.init(files, {
		proxy: 'http://localhost:8888/wp/',
		port: 8888,
		notify: true,
		logFileChanges: true,
		// https://github.com/BrowserSync/browser-sync/issues/10
		injectChanges: false
	});
});
```

If I change **'wp-content/themes/test/**/*.js'** to **'/**/*.js',** then it works. Browsersync scans my js-files. 

So what is wrong?
