### ISSUE TITLE
https config is overridden by flag

### ISSUE THREAD

**Issue by OliverJAsh** [BrowserSync/browser-sync#1211]
Version 2.14.0

Given a config file

```
module.exports = {
	https: {
		key: '../server/ssl/server.key',
		cert: '../server/ssl/server.crt',
	}
};
```

When I run `browser-sync start --config bs-config.js`, the options ([after merging flags](https://github.com/BrowserSync/browser-sync/blob/24dbf3ea0ee4fe350e7edc7209779a9b5c31481c/lib/cli/command.start.js#L28)) end up as:

``` js
{
    https: false,
    // …
}
```

Notice `https` is `false`.

It seems that the default `https` flag overrides my configuration.

**Comment by shakyShane** [comment]
thanks @OliverJAsh this is resolved in 2.16.1 :)
