### ISSUE TITLE
Reload intended Browser open behavior?

### ISSUE THREAD

**Issue by rgfx** [BrowserSync/browser-sync#1218]
When I first run gulp my browser automatically opens. Is the browser supposed to open up automatically after each save, or do have to manually click open? Everything works, I am not closing the browser, just going back into sublime, make change, then I need to click on chrome icon to maximize. 

Thanks.

**Comment by RichardsonWTR** [comment]
See https://www.browsersync.io/docs/options/#option-browser

**Comment by rgfx** [comment]
Yeah i saw that many times.  What am asking is if the browser opens automatically after each time i save?   Do i need to open the browser window manually after the first run,  or should it open the browser window automatically  after each save?

**Comment by RichardsonWTR** [comment]
With default options, the default browser automatically opens when you start browsersync. After this, it just reloads the page.

**Comment by rgfx** [comment]
Cool, thats all I wanted to know.
