### ISSUE TITLE
proxyReq provides no parameter

### ISSUE THREAD

**Issue by gregfr** [BrowserSync/browser-sync#1228]
### Issue details

The function listed in "proxyReq" is called with no parameter. As the parameter "proxyReq" is empty, the function "proxyReq.setHeader" (as in the example) doesn't exist and we can't accept the request.

### Steps to reproduce/test case

    "proxy": {
        target: "localhost",
        proxyReq: [
            function (proxyReq) {
                // proxyReq.setHeader('X-Special-Proxy-Header', 'foobar');
                console.log(proxyReq.headers);
            }
        ]

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.17.0  ]
- Node        [  4.2.6  ]
- Npm         [  3.5.2  ]

### Affected platforms

- [ X ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
`proxyReq` is there, but headers at this point are not complete so you cannot access `.headers` - please see https://github.com/nodejitsu/node-http-proxy#setup-a-stand-alone-proxy-server-with-proxy-request-header-re-writing for examples of how to use this option :)

**Comment by shakyShane** [comment]
Also note: This is only on 'outgoing' requests, so you'll only see that header in your target app

**Comment by gregfr** [comment]
OK my goal is simply that the proxied request carries on the headers (esp. the Host header) so the final server knows which site is requested. Is it the correct way to do that?

**Comment by benjie** [comment]
Same issue here; browser-sync seems to change the configuration required to pass-through the Host header quite frequently.

From some source-diving I've figured out this solves it (`changeOrigin: false`):

```js
proxy: {
  target: "http://localhost:" + port,
  proxyOptions: {
    changeOrigin: false
  }
}
```

**Comment by benjie** [comment]
@gregfr ^

**Comment by wibjorn** [comment]
For anyone who finds themselves here, it seems changeOrigin is no longer a valid option.
