### ISSUE TITLE
browsersync module on npm

### ISSUE THREAD

**Issue by thisconnect** [BrowserSync/browser-sync#1231]
Please consider taking over https://www.npmjs.com/package/browsersync

> browsersync 
This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.
Security holding package
You may adopt this package by contacting support@npmjs.com and requesting the name.

**Comment by shakyShane** [comment]
We've taken over this package name now. Thanks for bringing to our attention :)

**Comment by thisconnect** [comment]
thank you
