### ISSUE TITLE
Failed to parse SourceMap for Browser-Sync socket.io

### ISSUE THREAD

**Issue by christiansakai** [BrowserSync/browser-sync#1233]
![screen shot 2016-10-18 at 4 42 02 pm](https://cloud.githubusercontent.com/assets/7025139/19496023/a95458a6-9553-11e6-863a-28242711b9a6.png)

### Issue details

I am using Browserify, seems that it cannot find Source Maps for Browser-Sync socket.io minified file.

I did look into `node_modules/lib/public` and there was no `socket.io.min.1.5.0.js.map` file there

**Comment by shakyShane** [comment]
fixed in browser-sync@2.17.4 :)
