### ISSUE TITLE
"browsersync reload" does not work with self-signed certificate

### ISSUE THREAD

**Issue by vbraun** [BrowserSync/browser-sync#1235]
### Issue details

The "browser-sync reload" cli command does not work when setting up browser-sync with a self-signed certificate.
### Steps to reproduce/test case

Run browsersync with 

```
https:  {key: .., cert: ...} 
```
### Please specify which version of Browsersync, node and npm you're running
- Browsersync [ 2.17.0 ]
- Node        [ v5.0.0 ]
- Npm         [  3.3.6 ]
### Affected platforms
- [X] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_
### Browsersync use-case
- [ ] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI
### If CLI, please paste the entire command below

Not the topic here, but would be nice if just "reload" were to do the right thing: 

```
$ browser-sync reload
socket hang up
```

After a while I figured out that I need to provide the https:// scheme by hand:

```
$ browser-sync reload --url https://localhost:3000
self signed certificate
```

but that chokes on the self-signed certificate (imho a common use case) and does not reload either.

Workaround:

```
$ wget -O - --no-check-certificate https://localhost:3000/__browser_sync__?method=reload 2>> /dev/null
Called public API method `.reload()`
```

**Comment by jakeNiemiec** [comment]
Similar (unresolved) issue I had from months ago #1216 😞

**Comment by shakyShane** [comment]
@vbraun this will allow the reload command to work over https, but you'll still need to supply the `--url` flag as above in your example as there's no other way for `reload` to know the address of the running instance
