### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by rklak** [BrowserSync/browser-sync#124]
When on my website I login to my profile and the browser gets a session coookie - the browser-sync dont get it ... so I'm not login.

Maybe there is a way to transfer cookies from my website when I use a config file with proxy mode in browser-sync?

**Comment by gsklee** [comment]
@shakyShane I'm using 1.9.1 and still have problems with cookies.

We have a staging site at `http://our.internal.staging:4000` where we login and get cookies. Now I'm developing a new project on `http://our.internal.staging:5000` using BrowserSync and the requests aren't sending out with the cookies attached and I failed to log.
