### ISSUE TITLE
basedir doesn't like relative paths up the tree?

### ISSUE THREAD

**Issue by kevinSuttle** [BrowserSync/browser-sync#125]
For example, when I use `./app` as my `baseDir`:

```
gulp.task('browser-sync', function() {
    browserSync.init(["app/*.css", "app/js/*.js"], {
        server: {
            baseDir: "./app"
        },
    });
});
```

I can't reference directories up the tree, resulting in a 404. Is there a workaround?
`<script src="../bower_components/angular-route/angular-route.min.js"></script>` 

I mean, I get that it's not a natural server behavior to up the tree, so maybe I should just move the `bower_components` into the `/app` directory and shut up. :)

**Comment by palbcn** [comment]
I can't get routes to accept an absolute path, is there something I am missing?

**Comment by RichardsonWilliam** [comment]
I know this post is old, but I made it with this configuration:
```node
gulp.task('browserSync',function(){
	browserSync.init({
		startPath:'./app',
		server:{
			baseDir: './'
		}
	})
});
```
`baseDir` has my `node_modules` folder and `app` folder has my `index.html` file.

In my `index.html` file the `script` tag looks like this:
`<script src='../node_modules/<path_to_file>'></script>`
