### ISSUE TITLE
I disabled mirror click in browser-sync settings but still working

### ISSUE THREAD

**Issue by nasserghiasi** [BrowserSync/browser-sync#1257]
### Issue details
mirror clicks is working after disabling it. 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.15  ]
- Node        [  7  ]
- Npm         [  4  ]

### Affected platforms

OS X

### Browsersync use-case

Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
```
  gulp.watch(path.join(conf.paths.src, '/app/**/*.html'), function(event) {
    browserSync.reload(event.path);
  });
```

**Comment by shakyShane** [comment]
You need to reload each browser after disabling this option.

If this doesn't fix your problem, please reply with more details about your setup and instructions on how to reproduce this problem :)

**Comment by nasserghiasi** [comment]
Ok. I will send wore detail. But I still have this problem
