### ISSUE TITLE
BrowserSync does not detect filechanges in root if `baseDir` is absolute path

### ISSUE THREAD

**Issue by kvz** [BrowserSync/browser-sync#1259]
### Issue details

I'd like to use an absolute path for `baseDir` but then changes in `./index.html` go unnoticed

### Steps to reproduce/test case

Use ~this BrowserSync config

```
browsersync = {
  server: {
    baseDir: '/Users/kvz/code/frey-website/_site'
  },
  files: '.'
}
```

BrowserSync notices changes in subdirs (e.g. `/Users/kvz/code/frey-website/_site/assets`) but not in the root (e.g. `/Users/kvz/code/frey-website/index.html`).

When I switch to the correct cwd (e.g. `/Users/kvz/code/frey-website`) and then change the config to this:

```
browsersync = {
  server: {
    baseDir: '_site'
  },
  files: '.'
}
```

Things work as expected.

Any chance we can also get absolute paths to work?

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.2]
- Node        [7]
- Npm         [3]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

When I use the cli for configuration, it works as expected: `cd / && browser-sync start --server /Users/kvz/code/frey-website/_site --files '.'`

It's just when I move this to a `--config` file that it does not, it seems.

**Comment by kvz** [comment]
Ignore me, I suck! :D

For those stumbling upon here: I had to use the same absolute path in both the `baseDir` as in `files`

**Comment by Khaledneo** [comment]
I'm facing same issue, But I didn't understand what is exactly the issue. Can you Re-explain please. Thanks anyway.
