### ISSUE TITLE
page running on browsersync looks different

### ISSUE THREAD

**Issue by binarytrance** [BrowserSync/browser-sync#1262]
The same page with the same code looks different when i run it locally on browsersync vs when I simply double click on the file and run it on the browser. I also checked it on [Browsestack](https://www.browserstack.com/start) and it shows the version of the page which displayed when i double clicked it.  Visual represetation:
This is how it looks on browsersync: http://imgur.com/qiYODZH
This is how it looks everywhere else: http://imgur.com/HRSAatP
As you can see everything (margin, padding, border width, font size etc.) looks a tad bit smaller on browsersync.
I checked the console for any untoward default html but everything seems fine.
### Following are the versions of Browsersync, node and npm I am running

- Browsersync [ 2.18.2   ]
- Node        [ 6.9.1   ]
- Npm         [ 3.10.8   ]

### I have only tested it on:
- windows

### This happens both on:

-  Gulp
-  CLI

### In CLI, 
I installed browsersync globally and watched the files by doing this:
- `npm install -g browser-sync`
- `browser-sync start --server --files "*.html, css/*.css"`

### Gulp didn't recognize the global installation therefore i installed it in the project folder with the following command:
- `npm install browser-sync --save-dev`
and inside the `gulpfile.js`:
```
var browserSync = require('browser-sync').create();
gulp.task('sass', function() {
  return gulp.src('page/stylesheets/main.scss') // Gets all files ending with .scss in app/scss
    .pipe(sass())
    .pipe(gulp.dest('page/stylesheets'))
    .pipe(browserSync.reload({
      stream: true
    }))
});
```

**Comment by shakyShane** [comment]
In those  two screenshots, one has browser zoom applied (notice how the magnifying class is present in one, but absent in the other)

That's all you need, remove the zoom :)
