### ISSUE TITLE
is there a way in rewriteRule to replace content based on data from  GET params?

### ISSUE THREAD

**Issue by safareli** [BrowserSync/browser-sync#1266]
I want to define `rewriteRules` in which I could replace match based on GET params or basically have access to `req` as in `middleware`.

**Comment by shakyShane** [comment]
Sure, just provide a function and you'll have access to both req and res object (note, this is not an express app however, so you'll need to parse the url etc manually :)

```js
const bs = require('./').create();

bs.init({
    server: './app',
    rewriteRules: [
        {
            match: '<head>',
            replace: function(req, res, match) {
                console.log(req.url);
                return `<HEAD>`;
            }
        }
    ]
});
```
