### ISSUE TITLE
CSS not getting injected!

### ISSUE THREAD

**Issue by techsin** [BrowserSync/browser-sync#1269]
### Issue details

So it worked once but hasn't since, cleared cache, restarted computer, ran terminal with administrator rights, and so on. No matter what I do css won't get updated, even though in terminal it says 1 File changed finished in 8ms etc. At reloading page manually does show new css. I had code for reloading on html changes, that worked too. i see async script tag by BS in body as well. 

### Steps to reproduce/test case
write simple express app. Put style.css in public/stylesheets/style.css, and run include it in layout.jade and then run gulp with the code below. 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.2]
- Node        [v6.7.0]
- Npm         [3.10.3]

### Affected platforms
- [ x ] windows

### Browsersync use-case
- [ x ] Gulp

{Browsersync init code here}

```js
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();

gulp.task('serve', function() {
    browserSync.init({proxy: "localhost:3000"});
    gulp.watch("public/stylesheets/**/*", ['css']);
});

gulp.task('css', function() {
     return gulp.src("public/stylesheets/**/*").pipe(browserSync.stream());
});

gulp.task('default', ['serve']);

```

**Comment by shakyShane** [comment]
Have you checked https://browsersync.io/docs#requirements?

**Comment by techsin** [comment]
just to add some more info : 

when i do npm install -g browser-sync in end i get i get this warnning

`npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15`

i've body tag, visual studio code, and installing visual studio. I'll get back if it doesn't fix it.

**Comment by techsin** [comment]
ok installed Visual studio. And it doesn't work. Won't inject, does everything else but won't inject.

**Comment by techsin** [comment]
i checked chrome socket messages on what's happening when i make changes, as in what gets received over websocket from terminal.. this is the message

`42/browser-sync,["file:reload",{"ext":"css","path":"C:\\Users\\userName\\Desktop\\Projects\\v2ube\\app\\public\\stylesheets\\style.css","basename":"style.css","type":"inject","log":false}]`

shouldn't path be relative to web and not direct path to filesystem.

**Comment by techsin** [comment]
sorry nvm, this was all big waste of time. Prefixfreejs was taking all linked stylesheets and embedding them as style tags so ofcourse updated files couldn't be injected back.
