### ISSUE TITLE
.view-details instead of .view-tiles for #files

### ISSUE THREAD

**Issue by kenilam** [BrowserSync/browser-sync#1271]
I have been using browser-sync for quite sometimes now, and it is one of flavorite tools - **Can't live with out it.!**

Recently I came across an application I was building that require to show the modified date per folder, per file. I inspected the UI and it is actually possible and simple as swapping the class from `.view-tiles` to `.view-details` like:

`<ul id='files' class='view-titles>` to `<ul id='files' class='view-details>` 

So I read into the codes and the documentations for `browser-sync`, `browser-syn-ui` yet I wasn't about find any way to implement that.

Would you be about to point to me to the right direction?

Thanks in advance

**Comment by shakyShane** [comment]
I'm not sure I understand your question. Do you mean you'd like to modify a part of the Browsersync UI to include file stats?

**Comment by kenilam** [comment]
Thanks for responses, and yes that is exactly what I meant. And all it need is swap the 'view-tiles' to 'view-details'
