### ISSUE TITLE
Keep getting "Privacy Error" when trying to proxy a local https

### ISSUE THREAD

**Issue by corysimmons** [BrowserSync/browser-sync#1272]
Latest BrowserSync/Node/npm/etc.

I have `https://foo.dev` working -- no privacy error.

When I run `browser-sync start --proxy https://foo.dev` it goes to https://localhost:3000 but Chrome throws a privacy error.

I've tried throwing a lot of combinations of options at it with no success.

Can someone tell me how to do this without getting the privacy error?

**Comment by shakyShane** [comment]
Browsersync is using self-signed cert to provide the proxy feature, you can click through the error and everything will work as expected.

If you really want to get rid of the error you can add the Browsersync certs to your keychain (on a mac) - not sure how to do it on windows/linux though I'm afraid :)

**Comment by corysimmons** [comment]
Cool, I'll add them to my keychain, thanks Shane. =)

**Comment by corysimmons** [comment]
For posterity's sake:

![image](https://cloud.githubusercontent.com/assets/224636/21201277/58be34a6-c218-11e6-915f-9daa68a5b1ee.png)

- Double click `server.crt`
- Double click the `localhost` cert in the list of Keychain certs
- Dropdown "Trust"
- "When Using this Cert" -> "Always Trust"
- Save, close Keychain
- Restart BrowserSync `browser-sync start --proxy https://foo.dev`

**Comment by aznnomness** [comment]
I know this is very old at this point but I have stumbled across this in my searching.
I experienced the same thing (using 2.23.6) and found that the following resolves it:

Get a hold of the site's
- key/cer files.
- If you don't have those (I have not tested this yet) just the pem.
- If you don't have the pem file, if you can get the pfx file and use the following openssl command to extract the pem file (found here https://myonlineusb.wordpress.com/2011/06/19/what-are-the-differences-between-pem-der-p7bpkcs7-pfxpkcs12-certificates/)
```
Convert PFX to PEM
——————————————————————————————–
$ openssl pkcs12 -in certificate.pfx -out certificate.cer -nodes
——————————————————————————————–

NOTE: While converting PFX to PEM format, openssl will put all the Certificates and Private Key into a single file. You will need to open the file in Text editor and copy each Certificate & Private key(including the BEGIN/END statements) to its own individual text file and save them as certificate.cer, CAcert.cer, privateKey.key respectively.
```
You can then set the config to the following:

```"proxy": "https://yourdomain.com",
"host": "yourdomain.com",
"https": {
  "key": "./path/to/your/key/file.key",
  "cert": "./path/to/your/cert/file.cer"
}
```
If anyone sees any flaws in this please let me know, it has been working for me so far.
