### ISSUE TITLE
deprecated node-uuid@1.4.7: use uuid module instead

### ISSUE THREAD

**Issue by nathanfielding1990** [BrowserSync/browser-sync#1277]
### Issue details

PS C:\windows\system32> npm --version
3.10.9
PS C:\windows\system32> node --version
v6.9.2
PS C:\windows\system32> npm install -g browser-sync
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
C:\Users\sahin_000\AppData\Roaming\npm\browser-sync -> C:\Users\sahin_000\AppData\Roaming\npm\node_modules\browser-sync\
bin\browser-sync.js
C:\Users\sahin_000\AppData\Roaming\npm
`-- browser-sync@2.18.5
  `-- localtunnel@1.8.2
    `-- request@2.78.0
      `-- http-signature@1.1.1
        `-- sshpk@1.10.1
          +-- bcrypt-pbkdf@1.0.0
          +-- ecc-jsbn@0.1.1
          +-- jodid25519@1.0.2
          +-- jsbn@0.1.0
          `-- tweetnacl@0.14.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\browser-sync\node_modules\chokidar\node_mo
dules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})

PS C:\windows\system32> browser-sync --version
browser-sync : The term 'browser-sync' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ browser-sync --version
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (browser-sync:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Steps to reproduce/test case
I installed node through msi. Checked the version and it works.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  Cannot install  ]
- Node        [  6.9.2  ]
- Npm         [  3.10.9  ]

### Affected platforms

- [ ] linux
- [X ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by nathanfielding1990** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'test' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\coursera\package.json'
4 verbose stack     at Error (native)
5 verbose cwd C:\coursera\coursera-test
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
8 error node v6.9.2
9 error npm  v3.10.9
10 error path C:\coursera\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\coursera\package.json'
15 error enoent ENOENT: no such file or directory, open 'C:\coursera\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

This is what i got after testing npm

**Comment by aymanbahr** [comment]
i get the same on Mac air 
any help ?

**Comment by akupac** [comment]
Same on Kubuntu 16.04

Got this two error messages at browser-sync install:

> npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17

NODEJS version: 4.2.6
NPM version: 3.5.2

**Comment by exarus** [comment]
having the same issue on:
OS: Windows
Node: **7.3.0**
Yarn: **0.19.1**

**Comment by MDShahrouq** [comment]
Can Any one tell what command should to use to fix this issue.
I am currently using Ubuntu 14.04 LTS

**Comment by MohsinGhani** [comment]
`npm uninstall --save node-uuid`
`npm install --save uuid`

The old node-uuid module is deprecated and won't be maintained moving forward. The module is still published in NPM for backward compatibility (with the deprecation notice). If you need the source, clone this repo then git checkout v1.4.7.

**Comment by Bersam** [comment]
this is still happening, seems it is because of localtunnel, here's on going issue on localtunnel.
https://github.com/localtunnel/localtunnel/issues/162

**Comment by DanielRuf** [comment]
The localtunnel dependenc is on 1.8.2, the fix is in localtunnel 1.8.3 as localtunnel as request as dependency. So this issue is still not fixed.
