### ISSUE TITLE
Reload browser when a new file is added in a watched directory

### ISSUE THREAD

**Issue by thejohnfreeman** [BrowserSync/browser-sync#1291]
### Issue details

BrowserSync will not reload the browser when a new file is added in a source directory, but it will reload on subsequent changes to that new file. I suspect BrowserSync is watching only the 'change' event from chokidar, and not the 'add' event, but I have not investigated at all.

### Steps to reproduce/test case

```sh
$ mkdir source
$ npm start & # start browser-sync
$ touch source/index.js # nothing happens
$ touch source/index.js # browser reloads
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.18.6
- Node 6.9.4
- Npm 3.10.10

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

`browser-sync start --config browser-sync.config.js`

```js
// browser-sync.config.js
module.exports = {
  "server": true,
  "serveStatic": ["source"],
  "files": ["source"],
  // I have also tried source/**
}
```

Related: #93

**Comment by shakyShane** [comment]
@thejohnfreeman  Adding `watchEvents` in the next release, so the following will work

```js
module.exports = {
  "server": true,
  "serveStatic": ["source"],
  "files": ["source"],
  "watchEvents": ["add", "change"]
}

```
