### ISSUE TITLE
Unit tests need to be updated to reflect 'Jade' rename to 'Pug'

### ISSUE THREAD

**Issue by mcqj** [BrowserSync/browser-sync#1292]
### Steps to reproduce/test case

Simply run the unit tests and watch for failure

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.6  ]
- Node        [ 6.9.4   ]

file affected:-   /test/specs/commands/recipes.js
search for occurrences of jade

**Comment by shakyShane** [comment]
Thanks!
