### ISSUE TITLE
Other Tunnel Options?

### ISSUE THREAD

**Issue by entozoon** [BrowserSync/browser-sync#1294]
Are there alternative tunnel options, other than localtunnel?
I only ask because it's rather flakey (and has been for a long time). Crashing within 30 seconds nowadays, re issue:
https://github.com/localtunnel/localtunnel/issues/156

**Comment by shakyShane** [comment]
@entozoon we will not be adding alternatives unfortunately.

I did add ngrok at one point, but it turned out to be equally unreliable.

If you have a specific requirement, you can just use the API to wire it up yourself

```js
const bs = require('browser-sync').create();

bs.init({
    server: './app'
}, function(err, bs) {
    // point your tunnel at this address
    console.log(bs.options.getIn(['urls', 'local']))
});
```
