### ISSUE TITLE
How to use browser-sync nice with service worker ??

### ISSUE THREAD

**Issue by leung85** [BrowserSync/browser-sync#1295]
### Issue details
browser-sync is not reloaded anymore after the 1st reload, no WebSocket connected
It is because of the service worker cache. and it only occurs using localhost.
It works perfectly with IP or press F5 to clear cache because the service worker is not registered
It should only find in chrome/firefox as another browser not support service worker yet.
How to use browser-sync nice with service worker using localhost??

### Steps to reproduce/test case
1. use localhost in URL 
2. use service worker
3. change some code for 1st reload
4. Not reload anymore 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.18.6  ]
- Node        [ 7.4.0   ]
- Npm         [  4.0.5  ]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}
```
gulp.task('serve', function(){
    browserSync.init({
        server: {
            baseDir: DIST_DIR
        },
         files: [
            DIST_DIR + "/service-worker.js"
        ],
    });
});
```

**Comment by Pouja** [comment]
I have the same issue, with the same node/npm version and grunt as use case. Except on Linux.
