### ISSUE TITLE
command line arguments in single quotes don't seem to work

### ISSUE THREAD

**Issue by moloko** [BrowserSync/browser-sync#1302]
### Issue details
The [documentation page for the command line](https://www.browsersync.io/docs/command-line/) shows examples of parameters like `--files` being used with values in single-quotes, but these don't seem to work (on Windows 10 anyway)

### Steps to reproduce/test case

On Windows 10, start browser-sync on the command line with a command like:
```
browser-sync start --server --files 'index.html'
```
Although BS starts with the message `[BS] Watching files...`, you should find that it doesn't actually work in that changes to that file trigger nothing in the console - and so no reload in the browser.

Change the command to use double-quotes:
```
browser-sync start --server --files "index.html"
```
And it should work fine in that changes to index.html trigger both a `[BS] File changed: index.html` message in the console and a page reload.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.6 ]
- Node        [ 4.3.1 ]
- Npm         [ 2.14.12 ]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

`browser-sync start --server --files 'index.html'`

**Comment by moloko** [comment]
I've tried using both the Windows native command line and via cmder (just in case it was cmder, which is what I normally use, being weird)

**Comment by unstoo** [comment]
Thank you. I've been bashing my head over this for the last 30 minutes.

**Comment by shakyShane** [comment]
@moloko this is due to how args are parsed in windows, it's not a bug in Browsersync.

I can & will update the docs to use double quotes however 👍
