### ISSUE TITLE
No script injection if <body> tag is not present

### ISSUE THREAD

**Issue by Lajule** [BrowserSync/browser-sync#1303]
### Issue details

_The script that browser-sync uses to reload browsers is not injected if the document don't contains the `<body>` tag_.

### Steps to reproduce/test case

_Try to serve the following document :_
```
<!doctype html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <title>Test</title>
  <h1>Hello</h1>
</html>
```

_Try to reload the browser using :_
```
browser-sync reload
```

**The browser is not reloaded because no script is injected in document**.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.7   ]
- Node        [  7.1.0  ]
- Npm         [ 4.0.2  ]

### Affected platforms

- [x] linux
- [x] windows
- [x] OS X
- [x] freebsd
- [x] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [x] Gulp
- [x] Grunt
- [x] CLI

**Comment by oduska** [comment]
https://browsersync.io/docs#requirements

> Browsersync works by injecting an asynchronous script tag (<script async>...</script>) right after the <body> tag during initial request. In order for this to work properly the <body> tag must be present.

> Alternatively you can provide a custom rule for the snippet using [snippetOptions](https://browsersync.io/docs/options/#option-snippetOptions)

**Comment by shakyShane** [comment]
Thanks @oduska

**Comment by Lajule** [comment]
thanks @oduska,
"snippetOptions" do the job ;-)
