### ISSUE TITLE
disable browser-sync

### ISSUE THREAD

**Issue by arnava17** [BrowserSync/browser-sync#1304]
I am using angular 2 seed project downloaded from angular official website. It uses browser-sync. I need to disable browser-sync in my seed project. How can I do it?

**Comment by jaegz** [comment]
I dont see browser-sync anywhere in the repo...
https://github.com/angular/angular2-seed

**Comment by shakyShane** [comment]
@arnava17 it shouldn't be there now as @jaegz mentioned
