### ISSUE TITLE
Gulp Browser-sync Throwing Error module.js:471 cannot find ./lib/public/resume.js Windows 7

### ISSUE THREAD

**Issue by jaegz** [BrowserSync/browser-sync#1306]
### Issue details

Trying to run gulp task and browser-sync is throwing an error - halting the process. Tried npm cache clean, reverting back to previous versions of npm with no luck...

```
> gulp
module.js:471
    throw err;
    ^
Error: Cannot find module './lib/public/resume'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Function.create (C:\test\node_modules\browser-sync\index.js:307:20)
    at Object.<anonymous> (C:\test\gulpfile.js:23:44)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

resume.js is present in node_modules/browser-sync/lib/public

The same set up is on my colleague's computer, but it works! I've been at this for several hours and not sure where else to look so I'm opening this issue.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.7 ]
- Node        [ 6.9.4 ]
- Npm         [ 4.1.2 ]
- Git Bash win32 x64
- prefix = "C:\\Users\\{myusername}\\AppData\\Roaming\\npm
- node bin location C:\Program Files\nodejs\node.exe
- HOME = C:\Users\{myusername}
- which npm = /c/Program Files/nodejs/npm
- which node = /c/Program Files/nodejs/node
- $echo NODE_PATH = n/a command not found

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### gulpfile.js

```
var gulp = require('gulp');
var browserSync = require('browser-sync').create();
var reload = browserSync.reload;

gulp.task( 'browser-sync', function() {
	browserSync.init({
		server: './',
		notify: {
    		     styles: {
        		top: 'auto',
        		bottom: '0'
    		     }
		},
		injectChanges: true
	});
});

gulp.task( 'default', ['styles', 'js', 'browser-sync'], function() {
	gulp.watch(html, reload);
	gulp.watch(assets.scss, ['styles']);
	gulp.watch(assets.js, ['js', reload]);
});
```

**Comment by jaegz** [comment]
Update: I'm beginning to believe this issue is stemming from some kind of system settings, permissions, or symantec antivirus/firewall restrictions. Upon further testing. Browser-sync **was** able to be installed and run with the above gulp task in Safe Mode with Networking, but when running in Windows normal mode, that resume.js error is triggered. Please keep this issue open for now as I feel I am getting closer to the culprit. Will report back with what we find.

**Comment by Pradhyo** [comment]
Does the file exist?
I have a related issue because I am not able to create the file 'resume.js' anywhere on my machine.

**Comment by jaegz** [comment]
@Pradhyo Interesting... I am experiencing something similar... 

![image](https://cloud.githubusercontent.com/assets/7094801/23185994/669dd010-f853-11e6-9eaf-a27fd103f148.png)

**Comment by jaegz** [comment]
I just confirmed with our support team that it is in fact Symantec Endpoint Protection (antivirus/firewall software) that is preventing `resume.js` from being altered. Not exactly sure why yet, but I'll post the exact details of the rule/exception once I get additional info.

**Comment by jaegz** [comment]
@shakyShane Good news - this issue has been resolved! For some reason our work environment has a Symantec Endpoint Protection restriction on creating/editing/deleting a file with the name of `resume.js`. I worked with our support team today to get an exception for our development team and everything is running smooth.

**Comment by gregmelson** [comment]
If it helps anyone, I had the same issue. I ended up deleting the project and running PowerShell as an Administrator then recreating the project and it worked first time. Hope that also helps (I didn't have Symantec Endpoint Protection restrictions)
