### ISSUE TITLE
images won't show up in any browsers

### ISSUE THREAD

**Issue by TheCowDealer** [BrowserSync/browser-sync#1307]
Images won't show up in any browsers. Not with a static nor dynamic website, however it does work if I just open them directly from my text editor. I am currently running version 2.18.7. on windows 10, I have also tried downgrading to version 2.17.5, but with no luck. Everything elese seems to work fine except the images. I am not very experienced with this and honestly have no clue what to do. 
 Thanks in advance.

**Comment by shakyShane** [comment]
Browsersync does not alter your images in any way, so I cannot suggest a fix. 

Feel free to provide a small sample project (or screencast) that show this bug and I will re-open :)
