### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by nmaxcom** [BrowserSync/browser-sync#1308]
I've been using BrowserSync for quite a while now. It's been some time since I had to use it and that's when I noticed that it didn't work. At all.

I used to use a huge gulpfile.js but going nuts with this I've being stripping it down to its bare bones.

I'm using this gulpfile.js:

```javascript
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();

// Static Server + watching scss/html files
gulp.task('serve', function() {
    browserSync.init({
        server: "./dst"
    });

    gulp.watch("dst/*.html").on('change', browserSync.reload);
});

gulp.task('default', ['serve']);
```

It's a copy&paste from its website slimmed down to just see if it can pick up just html changes.

In all my tests it seems the file watch goes through properly: "[BS] Reloading Browsers..." but nothing happens. I've reinstalled node_modules, ~/.npm, I've tried all forms shown in its website, github and everywhere I've looked. It's always the same, changes detected, apparently there's a reload or inject (I've also tried setting inject to false), but nothing happens at all. If I manually refresh the browser, the changes appear.

According to its website, **a script tag should be injected after the body tag**, but I haven't been able to see it in the DOM, maybe there lays the problem.

I'm using Chrome (although Firefox responds the same).

- Browsersync [  2.18.6  ]
- Node        [  v7.4.0  ]
- Npm         [  4.1.2  ]

gulp -v
[21:40:04] CLI version 3.9.1
[21:40:04] Local version 3.9.1

OSX El Capitan 10.11.5

**Comment by vedranjaic** [comment]
I have the same problem

**Comment by shakyShane** [comment]
@nmaxcom does your page have a `<body>` tag? Do you see 'Browsersync connected' in the top right-hand-side of the browser when you reload the page?

**Comment by nmaxcom** [comment]
Damn it. I didn't even have html or head tags. I must have messed up with htmlmin and didn't notice.

It seems to work fine now, thank you.
