### ISSUE TITLE
I uninstalled browser-sync: cant run php built-in server +  [404]: /browser-sync/browser-sync-client.js

### ISSUE THREAD

**Issue by guillecro** [BrowserSync/browser-sync#1310]
Guys, please. I need your help. 
So I was trying gulp and browser-sync and installed them through npm.

I usually use the php built-in server to run my apps
`
$ php -S 0.0.0.0:8000`

So I have this Wordpress app that I am trying to make run. I am running out of time so I wont be using gulp and browser-sync, so I tried to uninstall them...

But now, I cannot run my project.
When I go to localhost:8000 **it takes me to the Apache2 Ubuntu Default Page...** But I am running my project on my php built-in server..

Also php always shows me a 404 of a browser-sync file...
```
[Mon Feb  6 21:53:20 2017] 127.0.0.1:50080 [404]: /browser-sync/browser-sync-client.js?v=2.18.7 - No such file or directory
```
Like.. What just happened? I uninstalled browser-sync, even removed the node-modules of gulp + browser-sync. Why I am getting this? Why its injecting this <script> of this browser-sync client? Why apache is working over my php server when I am using the port?

How do I properly purge browser-sync from my system? 
I feel that it changed some proxy config or something like that..
Please any help is very welcome.

**Comment by shakyShane** [comment]
Browsersync does not alter your system in any way - so no worries there :)

The most likely cause of this would be your browser having some cached HTML that includes a reference to the Browsersync file - either that or you've left it lingering around in one of your templates?

**Comment by guillecro** [comment]
I cleaned all my cache and even reinstalled all my browsers. Checked Apache, PHP, Node.. but not sure where to find what was causing this.

Nevermind. Just reinstalled Ubuntu, so its ok now.
