### ISSUE TITLE
Very Very Slow Watch SASS

### ISSUE THREAD

**Issue by pablocampina** [BrowserSync/browser-sync#1312]
### Issue details

Very very very slow watch and inject sass

### Steps to reproduce/test case

Default configuration sage 8.5 by (roots.io)
https://github.com/roots/sage/blob/sage-8/gulpfile.js

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.18.7  ]
- Node        [  7.5.0  ]
- Npm         [  4.1.2  ]

### Affected platforms

- [x] OS X (Sierra)

### Browsersync use-case

- [x] Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

gulp.task('watch', function() {
  browserSync.init({
    files: ['{lib,templates}/**/*.php', '*.php'],
    proxy: config.devUrl,
    snippetOptions: {
      whitelist: ['/wp-admin/admin-ajax.php'],
      blacklist: ['/wp-admin/**']
    }
  });
  gulp.watch([path.source + 'styles/**/*'], ['styles']);
  gulp.watch([path.source + 'scripts/**/*'], ['jshint', 'scripts']);
  gulp.watch([path.source + 'fonts/**/*'], ['fonts']);
  gulp.watch([path.source + 'images/**/*'], ['images']);
  gulp.watch(['bower.json', 'assets/manifest.json'], ['build']);
});

**Comment by wonderment** [comment]
@pabloworks Were you able to resolve this? Most seem to have issues related to .local instances and it's an easy fix, but that's not what we're experiencing.

**Comment by pablocampina** [comment]
Hi, sorry for my delay
I solve that

.pipe(cssNano, {
```
      safe: true,
      mergeRules: false <- adding that line
    })
```
