### ISSUE TITLE
Disable auto open  site in browser when browser sync start

### ISSUE THREAD

**Issue by Inst4nt-Fisherm4n** [BrowserSync/browser-sync#1316]
Browser-sync has browser option when browser-sync start. In this option BS can set browsers to launch. But BS have no option to don't start any browser. To complete this i set:
	// Dont srart browser
	browser: "dontstart"
May be better make special option to disable autostart browser.

**Comment by shakyShane** [comment]
`open: false` will do this for you :)

**Comment by mindrones** [comment]
After struggling with it a bit I've just found that to avoid opening a browser from the command line I had to use `--open ''` as a way to set `open` to `false`.

I'm not sure if this is obvious for the many but it would be very handy stating this in the doc at https://browsersync.io/docs/command-line#start :)
