### ISSUE TITLE
How to use BrowserSync with Azure website

### ISSUE THREAD

**Issue by naveenkumargc** [BrowserSync/browser-sync#1326]
I would like to how to use BrowserSync with website / web app hosted in Azure. I would like to use code-sync feature of this in the Azure

**Comment by shakyShane** [comment]
Browsersync is a tool for local development, where you have access to the source files.

If you just want to proxy an existing site to use some other features (such as network throttle on devices etc) then you can just use

```
browser-sync start --proxy http://example.com
```

If i've misunderstood your question, please let me know :)
