### ISSUE TITLE
Error watching file for changes: EPERM

### ISSUE THREAD

**Issue by ScorpioCoding** [BrowserSync/browser-sync#1328]
**What were you expecting to happen?**
I was expecting to get an event trigger : deleted

**What do you whish to achieve**
IS when the user manualy deletes a file or folder or both within the **src** folder.
That it is automatically also done in the **dist** folder.
With a minimal condition that they match naming

**What actually happened?**
```
Error: Error watching file for changes: EPERM
at exports._errnoException (util.js:1029:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1375:11)
```
**Npm dependencies**
`gup and browser-sync`
_Aha you might say there's your problem it's the other dependency.
You could be right, but to test my issue gulp has to be running continuously  and thus browser-sync.
And that's when we see the issue_

**Sample code**
```
var gulp = require('gulp');
var browserSync   = require('browser-sync');

gulp.task('browserSync', function () {
  browserSync({
    server: {
      baseDir: './dist',
    },
  });
});

gulp.task('html', function () {
  return gulp.src('./dist/**/*.html')
    .pipe(browserSync.reload({ stream: true }));
});

gulp.task('watch', function () {
  gulp.watch('dist/**/*.html', ['html']);
  gulp.watch('src/pug/**/*.pug', ['pug']);

  console.log('here');
  var watcher = gulp.watch('src/**/*');
  watcher.on('change', function(event){
    console.log('trigger fired : ' + event.type);
    if (event.type === 'deleted') {
      console.log('delete trigger fired');
    }
  });
});

gulp.task('default', ['watch', 'browserSync']);

```

**Testing**
```
Files - add,paste,delete,move, - work fine
Folders - add,paste - work fine
Folders - move, delete - ERROR
```
**What version of browser-sync are you using?**
`browser-sync -v 2.18.8`
**What version of gulp are you using?**
```
CLI version 3.9.1
Local version 3.9.1
Local version 3.8.11
```

**What versions of npm and node are you using?**
```
node v7.7.1
npm 4.1.2
```

**What OS are you using?**
```
Microsoft Windows 10 Pro x64
Version	10.0.14393 Build 14393
```

**Testing in different Editors and using windows explore**
```
.Atom -v1.14.4 x64
.VScode -v1.10.1
```
**Testing- Directory Structure**
![filestructure](https://cloud.githubusercontent.com/assets/20724826/23582287/944b350c-0127-11e7-8a08-ab07440159c1.PNG)

**Comment by shakyShane** [comment]
I'm not sure why you think this is a Browsersync issue? 

If you believe it is, you could provide a miminal, Browsersync-only code example and I will happily help. :)

**Comment by ScorpioCoding** [comment]
@shakyShane 
I posted the issue also @gulp and got a response today.
[gulp issue #1921](https://github.com/gulpjs/gulp/issues/1921)

And there answer is to use "gulp-watch" or "chokidar" which is I will be trying out next.
Thank you anyway for looking at the issue
