### ISSUE TITLE
Configure proxy like it's 100% invisible

### ISSUE THREAD

**Issue by mikehaas763** [BrowserSync/browser-sync#1334]
I'm somewhat making an assumption. I'm trying to set up a local browsersync proxy to a corporate QA environment. However I've tried a thousand combinations of settings and can't get it to work. I usually end up getting a timeout. I suspect it may be because the request doesn't look quite right to the servers. Anyone have an example for how to configure the proxy so the request goes out looking exactly like it would as if it were coming directly from my browser?

**Comment by marvinhagemeister** [comment]
We need more information about your setup, before we can help you. Did you run browser-sync via the CLI, gulp or something else?
