### ISSUE TITLE
BS not reload page after changes in css

### ISSUE THREAD

**Issue by Seasle** [BrowserSync/browser-sync#1335]
![Screenshot](http://i.imgur.com/tJ6zZUV.png)

**Comment by marvinhagemeister** [comment]
Thanks for submitting a bug report. We need more information about your setup before we can actually help you. Locally, on my macbook browser-sync reloads correctly upon changing any css file matching `css/*.css`.

Can you share your folder structure and what version of browser-sync you are using?

**Comment by Seasle** [comment]
![Screenshot](http://i.imgur.com/obCDiH5.png)
* Browser-sync version: `2.18.8`
* Node version: `v7.7.4`
