### ISSUE TITLE
How to enable Remote Debugger (weinre) by bs.init(options)?

### ISSUE THREAD

**Issue by Shaman05** [BrowserSync/browser-sync#1341]
### Issue details

Is there any way to automatically open the **Remote Debugger (weinre)**?

I just try: 
![image](https://cloud.githubusercontent.com/assets/951756/24181009/4df98e30-0ef3-11e7-966a-75f3b7921efb.png)

But it doesn't work automatically

**Comment by ckken** [comment]
??? how can fixed it
