### ISSUE TITLE
Option To Make BrowserSync Work Offline

### ISSUE THREAD

**Issue by sahtlil** [BrowserSync/browser-sync#1345]
I've read some of the solution out there to make browserSync Grunt work offline, like make the option online to false but I serach in the nud-modules everywhere and couldn't find it.
so can anyone tell me where I can find it ?

**Comment by marvinhagemeister** [comment]
Seems like a quick search would've been enough: See https://github.com/BrowserSync/browser-sync/issues/876

**Comment by sahtlil** [comment]
The dude said
"try setting online: false - that should help" 
but I don't know where to find tha option?
I've already seen it but as I said where is the option ?

**Comment by sahtlil** [comment]
up guys

**Comment by shakyShane** [comment]
https://browsersync.io/docs/options#option-online
