### ISSUE TITLE
Client doesn't react to SYNC/RESET ALL buttons unless ghostMode.location = true

### ISSUE THREAD

**Issue by episode17** [BrowserSync/browser-sync#1363]
### Issue details

Using the RESET ALL & SYNC ALL buttons in the ui don't do anything unless
```js
ghostMode: { location: true }
```
is set. (this option does not seem documented)

### Steps to reproduce/test case

1) Start browser-sync using API
2) Navigate around in new window
3) Click RESET ALL in ui
4) Nothing happens (although the socket receives the event)
5) add `location: true` to `ghostMode` config
6) Repeat 1 to 3
7) It works!

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.8]
- Node        [7.8.0]
- Npm         [4.2.0]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

```js
const browserSync = require('browser-sync').create();

browserSync.init({
    proxy: {
        target: 'localhost:9091',
        ws: true
    },
    ghostMode: {
        location: true // Fix
    }
});

```

**Comment by shakyShane** [comment]
@episode17 great catch! fix incoming
