### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by xf-** [BrowserSync/browser-sync#1371]
### Issue details

https://www.browsersync.io/ certificate is expired

### Steps to reproduce/test case

Open https://www.browsersync.io/

**Comment by shakyShane** [comment]
All sorted, thanks :)

**Comment by xf-** [comment]
@shakyShane maybe use renew and a hook to reload nginx with new certificate.
https://certbot.eff.org/docs/using.html#renewing-certificates
