### ISSUE TITLE
Feature Request: Change default logPrefix to "Browsersync"

### ISSUE THREAD

**Issue by joemaller** [BrowserSync/browser-sync#1377]
### Proposal

Browsersync should change its default `logPrefix` from "BS" to "Browsersync". There are several reasons why:

1. For pre-fab build systems, the "BS" prefix may be a mystery. Remind users that Browsersync is the tool making the magic happen. 
2. Most (all?) English speaking countries use "BS" as shorthand for 🐮💩 
3. Browsersync is one of my favorite tools, I want more people to know about it. 
4. The name's not CamelCase.

The default string is here: [lib/default-config.js:L184](https://github.com/BrowserSync/browser-sync/blob/c990ea223b5792e6d9b9c8fea34efb7f634a84c9/lib/default-config.js#L176-L184)

Branding!
![image](https://cloud.githubusercontent.com/assets/8320/26117259/f0978c9e-3a33-11e7-8337-fe461005d91f.png)

This should be a tiny, cosmetic change, but if anyone was upset about it, the string can be easily changed back:

```js
browserSync.init({
    logPrefix: "BS"
});
```

**Comment by shakyShane** [comment]
Not going to argue with that!

send a PR :)
