### ISSUE TITLE
Using ~ as home directory fail to open file or directory.

### ISSUE THREAD

**Issue by ruchern** [BrowserSync/browser-sync#1394]
### Issue details

Using `~` as home directory to link `https` cert files does not work.

`Error: ENOENT: no such file or directory, open '~/.localhost-ssl/key.pem'`

### Steps to reproduce/test case

Using the following code to specify cert files will reproduce the error.

```javascript
mix.browserSync({
    proxy: 'https://app.dev',
    https: {
        cert: '~/.localhost-ssl/cert.pem',
        key: '~/.localhost-ssl/key.pem'
    }
})
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.12]
- Node        [8.0.0]
- Npm         [5.0.2]

### Affected platforms

- linux
- OS X

### Browsersync use-case

- CLI

### If CLI, please paste the entire command below

`npm run watch` based off `Laravel-Mix`

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```javascript
mix.browserSync({
    proxy: 'https://app.dev',
    https: {
        cert: '~/.localhost-ssl/cert.pem',
        key: '~/.localhost-ssl/key.pem'
    }
})
```

**Comment by ruchern** [comment]
Trying to circumvent issue #1381 while using `~` as home directory.

**Comment by swashcap** [comment]
Looks like [`key` and `cert` extraction happens via `fs.readFileSync`](https://github.com/BrowserSync/browser-sync/blob/d3d871d5415219068f84b1dad16ab58a1cca2a94/lib/server/utils.js#L39-L45):

```js
function getKey(options) {
    return fs.readFileSync(options.getIn(["https", "key"])  || join(__dirname, "certs", "server.key"));
}

function getCert(options) {
    return fs.readFileSync(options.getIn(["https", "cert"]) || join(__dirname, "certs", "server.crt"));
}
```

[`fs.readFileSync`](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options) expects its first param, `path`, to be a “filename or file descriptor.” Not exactly sure what that means, but I know that Node.js doesn’t expand `~` like shells do. You’ll need to use Node.js’s built-ins to do this manually:

```js
const os = require('os')
const path = require('path')
// ...
mix.browserSync({
    proxy: 'https://app.dev',
    https: {
        cert: path.join(os.homedir(), '/.localhost-ssl/cert.pem'),
        key: path.join(os.homedir(), '/.localhost-ssl/key.pem')
    }
})
```

**Comment by ruchern** [comment]
@swashcap Ah, thanks. Why did I not thought of using absolute path.
