### ISSUE TITLE
Bump localtunnel to 1.8.3

### ISSUE THREAD

**Issue by alexandernanberg** [BrowserSync/browser-sync#1405]
### Issue details

npm and yarn throws this warning when installing browser-sync

`browser-sync > localtunnel > request > node-uuid@1.4.8: Use uuid module instead`

`localtunnel` have updated their dependency of the `request` package with the latest 1.8.3 release. So browser-sync is last in line to update. 

Would be nice to be able to install without getting a warning 😄 

### Steps to reproduce/test case

Run `npm install`

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.12   ]
- Node        [ 8.1.2  ]
- Npm         [  5.0.3  ]

**Comment by swashcap** [comment]
Took care of this in #1403. Just waiting for a patch'd publish!

**Comment by shakyShane** [comment]
All done, browser-sync@2.18.13

Thanks :)
