### ISSUE TITLE
Bad redirects with Wordpress and Docker

### ISSUE THREAD

**Issue by jakehamilton** [BrowserSync/browser-sync#1407]
### Issue details

Links seem to be redirected to the service's name that is proxied. Navigating to
`localhost` is fine, but clicking a link that is set to `localhost/abc` redirects to
`otherService/abc`.

### Steps to reproduce/test case

Using the following Dockerfile and docker-compose you should be able to reproduce this:

##### Dockerfile

```dockerfile
FROM node:8.1-alpine

RUN npm i -g browser-sync && mkdir -p /opt/app

WORKDIR /opt/app
```

##### docker-compose.yml

```docker-compose
version: '3.1'

services:
    wordpress:
        image: wordpress
        environment:
            WORDPRESS_DB_PASSWORD: test
        volumes:
            - ./data:/var/www/html
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: test
    browsersync:
        command: browser-sync start --port 80 --proxy 'wordpress:80' --files "./**/*" --no-open
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/opt/app
        ports:
            - 80:80
            - 3001:3001
```

Run `docker-compose up --build` and navigate to [`localhost`](http://localhost). Links redirect from `localhost/abc` to `wordpress/abc`. Setting the `host` option does not fix this.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.12]
- Node        [8.1]
- Npm         [5.x]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

browser-sync start --port 80 --proxy 'wordpress:80' --files "./**/*" --no-open

**Comment by titaniumbones** [comment]
@jakehamilton did you ever respolve this? I'm having a similar issue on Linux.

**Comment by jakehamilton** [comment]
@titaniumbones, unfortunately I never managed to solve this problem. As far as I could tell, it had to do with Wordpress using its configured host name for in any links. If you are dealing with wordpress, you could try setting the host name to `localhost` or some local proxied domain.

**Comment by jakehamilton** [comment]
I'd actually forgotten that this issue exists and seeing as how I don't think this is related to browser-sync, I'll close the issue.
