### ISSUE TITLE
Notify Element needs CSS love.

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#141]
The notify element that informs the user of connections + file changes needs some serious attention.

This is a great opportunity for a designer/developer to contribute to this Open Source project - I'm basically just looking for a CSS wizz to create an awesome growl-like notification that can be used by BrowserSync.

This is what we currently have - not much to beat right?

![current](http://cl.ly/image/0G3g2g3J2e3O/Screen%20Shot%202014-04-17%20at%2018.28.37.png)

Here's the 'BrowserSync' word mark in outlines as seen on http://browsersync.io if you want to use that.

https://www.sugarsync.com/pf/D7377973_73548509_925643

Reply here, or via [@BrowserSync](https://twitter.com/browsersync) with any links to codepens/jsbins/jsfiddles - really looking forward to seeing any contributions :)

**Comment by matthewmcvickar** [comment]
@shakyShane Can you include this in the documentation on the BrowserSync site? I was looking for this option and only found this GitHub issue by Googling.

**Comment by davidhund** [comment]
:+1:

**Comment by doginthehat** [comment]
:+1: 

Also worth mentioning in the documentation, passing an array _overwrites_ the styles, passing an object _merges_ the styles.

I find the latter simpler: `styles: {'top':'auto','bottom':'0','borderBottomLeftRadius': "0",'fontSize': "12px"}` keeps it anchored to the edges but moves it to the bottom and makes the font size consistent on any site.
