### ISSUE TITLE
express 2.x series is deprecated && connect 1.x series is deprecated warnings

### ISSUE THREAD

**Issue by matt3224** [BrowserSync/browser-sync#1413]
warning browser-sync > browser-sync-ui > weinre > express@2.5.11: express 2.x series is deprecated
warning browser-sync > browser-sync-ui > weinre > express > connect@1.9.2: connect 1.x series is deprecated

Just FYI

**Comment by EvtK** [comment]
+1

browsing for the same thing, ended up here :). 

Please update, thanks.

**Comment by marcelogarbin** [comment]
+1

**Comment by gleip** [comment]
+1

**Comment by engemasa** [comment]
+1

**Comment by duxy2002** [comment]
+1

**Comment by RomkaLTU** [comment]
+1

**Comment by raphaelokon** [comment]
**This is also breaking Node v4** 
`browser-sync` depends on `browser-sync-ui "0.6.3"` which in turn depends on 
`weinre`  which in turn depends on 
the deprecated `express` listed above which in turn depends on 
the deprecated `connect` listed above
which includes `mime ">= 0.0.1"` 
**which in turn breaks for all Node < v6 as it resolves to `mime@2.0.2`** 
which dropped support for Node <v4 https://github.com/broofa/node-mime#version-2-notes
/cc @bmuenzenmeyer

**Comment by harshitkumar31** [comment]
+1

**Comment by Hatko** [comment]
+1

**Comment by spencerbeggs** [comment]
+1

**Comment by Sinequanonh** [comment]
+1

**Comment by EugeneAndrievsky** [comment]
+1

**Comment by mehfuzh** [comment]
+1

**Comment by ben-coates** [comment]
+1

**Comment by katerberg** [comment]
Is there an update on when this will be fixed?

**Comment by shakyShane** [comment]
Hi all!

The 'fix' here is to remove weinre altogether - it's old & probably no-one uses it anyway!

That would make it a new major version, which is not an issue, but any code related to the UI that contains weinre refs needs updating too, meaning it's a good few hours work.

**Comment by matt3224** [comment]
@shakyShane eta?

**Comment by phamdt** [comment]
does someone want to volunteer a PR?

**Comment by shakyShane** [comment]
@matt3224 @phamdt within the next 2 days :)

**Comment by shakyShane** [comment]
released as browser-sync@2.19.0

There was no API related to weinre, so I'm releasing as a minor update - it removes functionality, but cannot 'break' anyones tools/projects/builds that rely on 2.x

**Comment by simonua** [comment]
You, sir, are awesome! I am updating this dependency of mine right now to start testing it. Thank you very much, @shakyShane!

**Comment by simonua** [comment]
Tested great. Released our internal, consuming package last night. Thanks again, @shakyShane! Happy holidays!

**Comment by ckken** [comment]
why kill my weinre?

**Comment by luwes** [comment]
does anyone know another way than Weinre to debug Google Chrome on iOS?

**Comment by quisse** [comment]
Using weinre standalone in combination with ngrok can do a great things.
https://www.undefinednull.com/2015/03/17/remote-debugging-localhost-with-weinre/

**Comment by JodiWarren** [comment]
> does anyone know another way than Weinre to debug Google Chrome on iOS?

@luwes If it's any help, you shouldn't be getting rendering differences between Chrome and Safari on iOS. Due to Apple's restrictions, Chrome is using exactly the same rendering engine as Safari.

Safari on iOS can be debugged with Safari desktop, so that might suffice for your needs.

If you do need to debug it on an actual device, Browserstack offers Chrome iOS as a platform.

I know it's not a 1:1 replacement, but hopefully some of that can help.

**Comment by kilgarenone** [comment]
How do you guys do remote debugging now that 'weinre' is gone?

**Comment by surunzi** [comment]
I wrote a replacement for weinre, using the lastest chrome devtools frontend.  Check it out: https://github.com/liriliri/chii

**Comment by Mr-Chilly** [comment]
@surunzi thanks a trillion, it's better, faster, and the easiest option for remote debugging awkward devices!
