### ISSUE TITLE
Browsersync doesn't save scroll position in Firefox.

### ISSUE THREAD

**Issue by testgit-1** [BrowserSync/browser-sync#1418]
### Issue details
Page scrolls up after file changes (include changes in css).
After css changes I got notification "Injected: style.css". But page scrolls up too.
It's break our work process.

### Steps to reproduce/test case
The problem occurs in Firefox after changes css for long html page.

 ## Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.18.13   ]
- Node        [  7.7.1  ]
- Npm         [ 5.3.0   ]

### Affected platforms
- windows

### Browsersync use-case

- Gulp v.3.9.1

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```
const gulp         = require('gulp');
const browserSync  = require('browser-sync').create();

gulp.task('server', function() {
  browserSync.init({
    server: {
      baseDir: 'build/',
    },
    open: false,
    online: false,

    files:[  
        'build/*.html',
        'build/css',
        'build/js',
        'build/fonts/',
        'build/img',
    ],

    ghostMode: {
        scroll: true
    },

    logLevel: 'info', // 'debug', 'info', 'silent', 'warn'
    logConnections: false,
    logPrefix: "Browser-Sync",
    port: 8080,
    notify: true
  });
});
```

**Comment by shakyShane** [comment]
fixed in browser-sync@2.24.7 :)
