### ISSUE TITLE
Multiple access-control-allow-origins headers 

### ISSUE THREAD

**Issue by dmitrynovik** [BrowserSync/browser-sync#1427]
### Issue details

XMLHttpRequest cannot load http://localhost/api/admin/programs/billers?registeredBillerKey=c8ac14ed-622b-47d0-8cd3-c627934281f8. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, *', but only one is allowed. Origin 'http://localhost:3000' is therefore not allowed access.

The Chrome console shows the following network traffic:

### Request
Request URL:http://localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=LwOWI3r
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:3000
Referrer Policy:no-referrer-when-downgrade
### Response Headers
view source
**Access-Control-Allow-Origin:***
Connection:keep-alive
Content-Length:100
Content-Type:application/octet-stream
Date:Tue, 19 Sep 2017 04:59:13 GMT
Set-Cookie:io=9ouBSATBEwWoPxwQAAAC; Path=/; HttpOnly
Request Headers
view source

### Request
Request URL:http://localhost:3000/browser-sync/socket.io/?EIO=3&transport=polling&t=LwOWI4C&sid=9ouBSATBEwWoPxwQAAAC
Request Method:POST
Status Code:200 OK
Remote Address:[::1]:3000
Referrer Policy:no-referrer-when-downgrade
### Response Headers
Access-Control-Allow-Credentials:true
**Access-Control-Allow-Origin:http://localhost:3000**
Connection:keep-alive
Content-Length:2
Content-Type:text/html
Date:Tue, 19 Sep 2017 04:59:13 GMT
Set-Cookie:io=9ouBSATBEwWoPxwQAAAC; Path=/; HttpOnly

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.18.8    ]
- Node        [   6.11.2  ]
- Npm         [ 3.10.10   ]

### Affected platforms

- [x ] linux
- [  x ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ x ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by dmitrynovik** [comment]
Sorry, found the culprit and it's not browser-sync

**Comment by rickysullivan** [comment]
Having similar issue. What was the fix?

**Comment by dmitrynovik** [comment]
@rickysullivan your server-side code supplies the header access-control-allow-origins more than once. Where and why - it depends on code and technology, there is no generic answer

**Comment by rickysullivan** [comment]
Cheers. Will look at my server side code.
