### ISSUE TITLE
Mac High Sierra localhost:3000 timeouts but virtual hosts work

### ISSUE THREAD

**Issue by seanlanglands** [BrowserSync/browser-sync#1434]
### Issue details

Just upgraded to Max OS High Sierra and my virtual hosts still work fine out side of browsersync, for example: mysite.localhost, but now my proxy URLs don't resolve and eventually timeout. localhost:3001 works but not localhost:3000.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.13]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by smasty** [comment]
I have a similar issue with Firefox 57.0b3 on Debian Jessie.
Running Browsersync 2.18.13 from the CLI, I cannot access browsersync on `localhost:3000` from Firefox 57, but in Chrome everything works fine. Only way to access it from Firefox is to use `127.0.0.1:3000`. The same applies for the UI on port 3001.

**Comment by aworkz** [comment]
I just had the same problem and was reading this, eventually re-checked my hosts file and tabs instead of spaces in these lines:
````
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost```
Fixed it, and it's now working fine.

**Comment by DesignICU** [comment]
Sean, did you ever resolve this? Having the same problem now…

(Another) Sean

**Comment by adam-lynch** [comment]
I had the same with `.localhost` on OS X Sierra. It used to work until we changed our dev environment from `.dev` to `.localhost`. Turns out I had `.dev` related stuff in my `/etc/hosts` (didn't update it) and Chrome was the only browser it worked in because they must do some magic.

**Comment by DesignICU** [comment]
Yes, I resolved mine over the weekend, too. Made sure to use .dev rather than .local (I'm now using Local by Flywheel) and corrected my devUrl in manifest.json to match Local’s xxxx.dev URL (rather than localhost:3000).
