### ISSUE TITLE
Error: Cannot find module 'etag'

### ISSUE THREAD

**Issue by DanStach** [BrowserSync/browser-sync#1471]
### Issue details
Issue browser-sync 2.20.0 causes issue with build process. however  browser-sync 2.19.0 works correctly

Error seen:
error	21-Dec-2017 16:14:55	module.js:327
error	21-Dec-2017 16:14:55	    throw err;
error	21-Dec-2017 16:14:55	    ^
error	21-Dec-2017 16:14:55	
error	21-Dec-2017 16:14:55	Error: Cannot find module 'etag'
error	21-Dec-2017 16:14:55	    at Function.Module._resolveFilename (module.js:325:15)
error	21-Dec-2017 16:14:55	    at Function.Module._load (module.js:276:25)
error	21-Dec-2017 16:14:55	    at Module.require (module.js:353:17)

_Please provide issue details here_.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.20.0  ]
- Node        [  4.4.5  ]
- Npm         [  2.15.11  ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
Thanks, this is fixed in a patch release browser-sync@2.20.1
