### ISSUE TITLE
Grunt plugin issue

### ISSUE THREAD

**Issue by ArmorDarks** [BrowserSync/browser-sync#1472]
Hello guys!

It seems that Grunt plugin repository has been abandoned and nobody merges even PRs...

Can someone take a look, please? https://github.com/BrowserSync/grunt-browser-sync/pull/147

Maybe you need a help?

**Comment by ArmorDarks** [comment]
Hm, now I see why it is abandoned...

Anyone? ping @shakyShane

**Comment by ArmorDarks** [comment]
ping @shakyShane

**Comment by shakyShane** [comment]
@ArmorDarks I attend to the PR in the original repo :)
