### ISSUE TITLE
No changelog since 2.18.11

### ISSUE THREAD

**Issue by vincentmorneau** [BrowserSync/browser-sync#1474]
There's been a few releases since 2.18.11. Could you add a few lines to the latest release so we are aware of any breaking changes?

**Comment by shakyShane** [comment]
I'm in the process of creating a grouped release doc, will be done by this evening (it will cover everything up to `2.22.0`

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/releases
