### ISSUE TITLE
Update dependency for license

### ISSUE THREAD

**Issue by ThiagoMVF** [BrowserSync/browser-sync#1478]
### Issue details

One of the project's dependencies (`immutable`) has had its license updated to better fit the OSS environment.

The current browser-sync release doesn't point to an `immutable` version that has the new license. Any browser-sync users end up with the old `immutable` license in their dependency tree - and that is an issue for some corporations. Updating the required version to `3.8.2` ( https://github.com/facebook/immutable-js/releases/tag/v3.8.2 ) would address it.

### Steps to reproduce/test case

Installed browser-sync as a dependency.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.23.2 ]
- Node        [ v6.2.0 ]
- Npm         [ 3.8.9 ]

### Affected platforms

- [ ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by shakyShane** [comment]
fixed in browser-sync@2.23.4 :)
