### ISSUE TITLE
Regression: image changes are not injected

### ISSUE THREAD

**Issue by cristianl** [BrowserSync/browser-sync#1489]
### Issue details

After 2.22.0, changes to images always trigger hard reloads, instead of cachebusting URLs. This regression was introduced recently. I believe it's related to the changes made to the client, using code from Live Reload. 

2.21.0 works.

### Steps to reproduce/test case

All ways of notifying image changes (via `stream()`, letting BS watch files, or notifying via the HTTP protocol) cause reloads.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.23.2  ]
- Node        [  5.6.0  ]
- Npm         [  9.3.0  ]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### Init code
I use BS with webpack middleware and bs-html-injector. I thought it was caused by bs-html-injector, but after testing with a simpler setup and using minimal settings, I can confirm it's not specific to my use case.

```js
const browserSync = require('browser-sync').create()

function launchBrowserSync(callback) {
  browserSync.init({ server: outputDirs.publicRoot }, callback)
}
```

**Comment by shakyShane** [comment]
thanks @cristianl - this will be resolved in the next release
