### ISSUE TITLE
browser-sync  Single Page Applications (SPA)  refresh is fail ,when vue-router use history

### ISSUE THREAD

**Issue by antiantian** [BrowserSync/browser-sync#1492]
### code
```bash
 const router = {
    mode: 'history',
    base: __dirname ,
    routes: ConfigRoute,
    scrollBehavior(to,from,savedPosition){
        if(savedPosition){
            return savedPosition;
        }else{
            return {x: 0,y: 0}
        }
    }
}    
let routes = [
    {
      path: '/',
      redirect:'/home'
    },
    {
      path: '/home',
      name: 'Home',
      component: Home
    },

    {
      path: '/act',
      name: 'Act',
      component: Act
    },
    {
       path: '/firestart/newDetails',
        component:NewDetails
    },
    {
       path: '/firestart/newDetails/:id',
        component: NewDetails
    },
    { 
      path: '*', 
      component: NotFoundComponent }
  ]
```

  ### Issue details
```bash
when vue-router use history  refresh is fail  
http://localhost:8002/act is right!
```
![image](https://user-images.githubusercontent.com/23133017/34821347-5d9141c8-f6fe-11e7-89ef-04a2ee62958d.png)
```bash
http://localhost:8002//firestart/newDetails   is fail!
```

![image](https://user-images.githubusercontent.com/23133017/34821374-7421322c-f6fe-11e7-85fe-86b292ab8426.png)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [    ]
- Node        [    ]
- Npm         [    ]

### Affected platforms

- [x] windows

### Browsersync use-case

- [x] Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}
![image](https://user-images.githubusercontent.com/23133017/34821185-dfb98274-f6fd-11e7-9ba8-1abcc10cff27.png)

**Comment by shakyShane** [comment]
@antiantian for me to address this possible issue, you would need to create a sample project/repo that clearly shows the issue.

you can use the following as a template https://github.com/BrowserSync/recipes/tree/master/recipes/server

**Comment by antiantian** [comment]
there is project website ： https://github.com/antiantian/browser-sync-Single-Page-Applications
