### ISSUE TITLE
Browser-sync erroneously redirects when missing trailing slash

### ISSUE THREAD

**Issue by verticelo** [BrowserSync/browser-sync#1494]
Hi there!

### Issue details

Running Apache 2.4 with: 
/var/www/html/index.php
/var/www/html/test/index.php

In the browser when going to:
http://localhost:3000/test/    - it works
http://localhost:3000/test    - it does not work, browser-sync redirects to http://localhost:80/test

Going to:
http://localhost:80/test/   - it works
http://localhost:80/test   - it works

Expected:
Browser-sync should not issue a redirect but rather proxy Apache.

I have verified that the redirect is not from Apache. It comes from browser-sync directly.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.23.5]
- Node        [8.9.4]
- Npm         [5.6.0]

### Affected platforms

- [x] linux ubuntu 16.04

### Browsersync use-case

- [ ] API
- [X] Gulp v3.9.1
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```js
gulp.task('browser-sync', function () {
    return browserSync.init({
        proxy: "localhost:80",
        open: false
    });
});
```

**Comment by shakyShane** [comment]
@verticelo There's no logic in Browsersync to perform a redirect based on the presence or absence of a trailing slash.

You can prove this with the Browsersync.io website

```bash
browser-sync https://browsersync.io
```

Request `/docs` without slash - gives a 200
```
$ curl https://localhost:3000/docs -kI

HTTP/1.1 200 OK
...
```

Now repeat the same request *with* the slash, still gives a 200.
```
$ curl https://localhost:3000/docs/ -kI

HTTP/1.1 200 OK
...
```

To prove the redirect comes from the server configuration, you can use `https://wearejh.com`. If we check without Browsersync first, we can see a 301 returned

```bash
curl https://wearejh.com/case-studies -I

HTTP/1.1 301 Moved Permanently
Location: https://wearejh.com/case-studies/
...
```

If you believe this is bug in Browsersync however, please produce either a sample project/repo or provide a URL I can proxy in which to verify. Thanks
