### ISSUE TITLE
Wrong mime type and the css is not included on the page

### ISSUE THREAD

**Issue by nickimola** [BrowserSync/browser-sync#1495]
When i use gulp to compile my less files together into one single css (nothing custom yet, only bootstrap + fontawesome) and then the browser reloads, css files are not imported properly, as chrome complains that the mime type if my css files is text/html instead of text/css

- Browsersync [   2.14.3 ]
- Node        [  6.9.2  ]
- Npm         [  3.10.9  ]

on 

- [x] OS X

### Browsersync use-case

- [x] Gulp

Browsersync options:

    browsersync: {
        files: [build + '/**', '!' + build + '/**.map'], 
        notify: true,
        open: false, 
        server: {
            baseDir: build
        },
        watchOptions: {
            debounceDelay: 2000 
        }
    }

The error i get is:

Refused to apply style from 'http://localhost:3000/assets/styles/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by jhume** [comment]
@nickimola did you resolve this issue?  I am seeing something similar...

**Comment by nickimola** [comment]
@jhume Hi,
Yes i did. The problem in my case was a library imported with the comments.
Removing the library also solved the issues.
This is probably just something related to my particular case i think, and i don't know how useful it can be
