### ISSUE TITLE
Cannot change style of notify !!! I try options.notify.styles ???

### ISSUE THREAD

**Issue by KytoSai** [BrowserSync/browser-sync#1496]
### Issue details

I can't change style of notify. I try options.notify.styles to change but it can't !!!!

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.18.13  ]
- Node        [  9.2  ]
- Npm         [ 5.5.1   ]

### Affected platforms

- windows

### Browsersync use-case

- Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```
return browserSync.init({
    reloadDelay: 300, // Fix htmlprocess watch not change
    open: false, // Stop auto open browser
    notify: {
      styles: [
        'display: none; ',
        'padding: 6px 15px 3px;',
        'position: fixed;',
        'font-size: 40px;',
        'z-index: 9999;',
        'left: 0px;',
        'bottom: 0px;',
        'color: rgb(74, 74, 74);',
        'background-color: rgb(17, 17, 17);',
        'color: rgb(229, 229, 229);'
      ]
    },
    cors: false,
    server: {
      baseDir: APP.dist.path,
      index  : 'index.html',
    }
  });
```

**Comment by shakyShane** [comment]
I just tried your example, and I see the following

![screen shot 2018-01-16 at 09 50 55 3](https://user-images.githubusercontent.com/1643522/34982728-2d3ed97e-faa3-11e7-90cb-7cd6f434d05e.png)

If i've mis-understood your issue, please let me know :)
