### ISSUE TITLE
How to stop logging change in browser console?

### ISSUE THREAD

**Issue by GoodGuyNick** [BrowserSync/browser-sync#1497]
### Issue details
After editing style.css I get this in browser console:
```
19:57:26 ✨ Browsersync reloading stylesheet: http://localhost:3000/style.css
```
I've searched documentation and internet but can't find a way to disable this.
### Steps to reproduce/test case

cd to folder and run browser-sync start --server --files '*.*' and then edit some CSS

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.23.5  ]
- Node        [  8.9.4  ]
- Npm         [  5.6.0  ]

### Affected platforms

- [X] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [X] CLI
- [ ] API
- [ ] Gulp
- [ ] Grunt

### If CLI, please paste the entire command below

{browser-sync start --server --files '*.*'}

**Comment by shakyShane** [comment]
@GoodGuyNick This is coming in the next release. All console logging will be disabled by default

**Comment by GoodGuyNick** [comment]
Thank you
