### ISSUE TITLE
Index should handle no static files

### ISSUE THREAD

**Issue by sebastiannm** [BrowserSync/browser-sync#150]
As it's common that JS frameworks (ex. angular, spine) uses always the index file and then takes cares of the request, should it not be an option to redirect any no static file to the index file (index.html as default otherwise use the one in the config file)?

I have been looking into "connect-modrewrite" but it was not possible to make it work yet.

Any suggestion?

**Comment by chrisdhanaraj** [comment]
For anyone potentially confused about this in the future, this requires connect-modrewrite (npm install connect-modrewrite), and the actually rewrite should be wrapped in parens, i.e.

```
middleware: [
  modRewrite(['!\.html|\.js|\.css|\.png$ /index.html [L]'])
]
```

**Comment by voor** [comment]
And anyone still confused, will probably need this:

```
var modRewrite = require('connect-modrewrite');
```
At the top of the browser-sync task.
