### ISSUE TITLE
IE11: Stylesheet not injected on change

### ISSUE THREAD

**Issue by ericmorand** [BrowserSync/browser-sync#1514]
### Issue details

When using IE11, browser-sync fails to inject changed stylesheet. The following error is displayed by IE11 console:

`Object doesn't support property or method 'from'`

This is probably coming from the use of the unsupported `Array.from` method.

### Steps to reproduce/test case

Open a browser-sync  managed page on IE11 and make some changes to a stylesheet.

**Comment by shakyShane** [comment]
@ericmorand this has been fixed as part of https://github.com/BrowserSync/browser-sync/tree/client-ts and will be in the next release 👍

**Comment by ericmorand** [comment]
Awesome! Thank you.

**Comment by paullindquist** [comment]
Loading this polyfill seems to fix this.. until it gets updated. 

 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from
