### ISSUE TITLE
middleware route handler response.status not a function

### ISSUE THREAD

**Issue by tysenmoore-xse** [BrowserSync/browser-sync#1515]
I am new to browserSync so I created a very simple example of an application.  I am trying to create a simple middleware handler for a specific route and respond with a status or json.  However, in my handler if I use the response variable with a status or json I get "not a function".  I suspect I am making a simple error, but from the examples I don't see where I went wrong.  Any suggestions would be much appreciated.

The code looks like:
```javascript
var browserSync = require("browser-sync");

browserSync( {
    server: {
        baseDir:    "build",
        middleware: [ {
            route: "/test",
            handle: function( req, resp, next )  {
                console.log( "resp.status=",  typeof resp.status );
                resp.status(501);
            }  }  ]
    }
} );
```

I run the code with a simple:
`node ./browserSyncEx.js`

Then in the browser try:
`localhost:3000/test`

I see the console show my console output: `resp.status= undefined`.  I get the following stack trace in the browser and from the terminal:
`TypeError: resp.status is not a function
   at handle (C:\tmp\ex\browserSyncEx.js:10:22)
   at call (C:\tmp\ex\node_modules\connect\index.js:239:7)
   at next (C:\tmp\ex\node_modules\connect\index.js:183:5)
   at next (C:\tmp\ex\node_modules\connect\index.js:161:14)
   at next (C:\tmp\ex\node_modules\connect\index.js:161:14)
   at respModifierMiddleware (C:\tmp\ex\node_modules\resp-modifier\index.js:80:9)
   at call (C:\tmp\ex\node_modules\connect\index.js:239:7)
   at next (C:\tmp\ex\node_modules\connect\index.js:183:5)
   at C:\tmp\ex\node_modules\browser-sync\dist\snippet.js:76:13
   at call (C:\tmp\ex\node_modules\connect\index.js:239:7)`

- Browsersync [  2.23.6  ]
- Node        [  6.9.2  ]
- Npm         [  3.10.9  ]

Windows 10 64bit executing from the git bash terminal

**Comment by shakyShane** [comment]
It's likely you're expecting some `express`-specific properties to be present on the requests/responses - but Browsersync does not use express (it uses `connect` directly)

take a look at the following example to see how to incorporate express https://github.com/BrowserSync/browser-sync/blob/master/examples/express.js

**Comment by tysenmoore-xse** [comment]
I think that was my confusion, thanks for the clarification.
