### ISSUE TITLE
URLs in XHR are not rewritten (Accept header, --proxy)

### ISSUE THREAD

**Issue by fregante** [BrowserSync/browser-sync#1519]
### Issue details

If the `Accept` header is set to `*/*`, which it is for XHR unless you specify otherwise, URL rewriting fails. It works when `Accept: text/html`

I don't think URL rewriting should depend on the answer but on the response, which in my case is:

```
Content-Type: text/html
```

### Steps to reproduce/test case

```sh
$ browser-sync start --proxy http://bfred.it
[Browsersync] Proxying: http://bfred.it
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.188:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.188:3001
 --------------------------------------
```
```sh
$ curl --header "Accept:text/html" http://localhost:3000/public/18/bs-1519.html
# Notice rewritten URL
<html>
<head>
<meta charset="UTF-8">
<title>Test</title>
</head>
<body><script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.18.13'><\/script>".replace("HOST", location.hostname));
//]]></script>

<a href="bs-1519.html">Link to self</a>
</body>
</html>
```
```sh
$ curl http://localhost:3000/public/18/bs-1519.html
# Notice no BS influence
<html>
<head>
<meta charset="UTF-8">
<title>Test</title>
</head>
<body>
<a href="bs-1519.html">Link to self</a>
</body>
</html>
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.18.13]
- Node        [v8.6.0]
- Npm         [5.7.1]

### Affected platforms

All?

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

All?

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

```sh
$ browser-sync start --proxy http://bfred.it
$ curl http://localhost:3000/public/18/bs-1519.html
```

**Comment by shakyShane** [comment]
@bfred-it this is a deliberate limitation designed to avoid buffering & altering requests that may not be HTML.

You could try providing the paths in the `snippetOptions.whitlist` array - although I think the response modification may be limited to the script injection only - it's worth a shot though

```js
// proxy.js
const bs = require('./').create();

bs.init({
    proxy: 'http://bfred.it',
    snippetOptions: {
        whitelist: ["/public/18/bs-1519.html"]
    }
});
```

```bash
node proxy.js
```

**Comment by bfred-it** [comment]
Granted this can be fixed with config or by changing the script itself (if possible) but I wish the defaults were friendlier. 

If the server returns `Content-Type: text/html` *and* there’s a `body` tag then it’s realistic that proxies handle it as a HTML page. It should be the *lack* of those a reason to ignore the request, not the request
