### ISSUE TITLE
TypeError: value.get is not a function

### ISSUE THREAD

**Issue by corysimmons** [BrowserSync/browser-sync#1520]
Latest browersync cli.

`$ npx browser-sync start -s --proxy=8000`

```bash
...
node_modules/browser-sync/dist/cli/transforms/handleProxyOption.js:13
        target = value.get("target");
                       ^

TypeError: value.get is not a function
...
```

**Comment by shakyShane** [comment]
the value to `proxy` needs to be full url, like `http://localhost:8000`

that being said, your example suggests you're trying to run a server + proxy at the same time, for this you'd want something like 

```bash
browser-sync start '.' --proxy=localhost:8000
```

if you can tell me your specific requirement I can probably help more :)

**Comment by corysimmons** [comment]
Thanks. I'm a newb.

**Comment by malixsys** [comment]
I get this error with a proxy...
`browser-sync start --server --cwd 'maintenance' -w -p 3000 --files 'maintenance'`
