### ISSUE TITLE
Browser Sync External Addresses For A Device Thats Not On Same Network

### ISSUE THREAD

**Issue by AlexMachin1997** [BrowserSync/browser-sync#1525]
### Issue details

Hey everyone,
im try to access browser sync from a different network e.g. 4G or a separate network; Can anyone help me with this problem.

Reproduce:
Run gulp that has browser sync configured and try using the external address from another network.

To download my project go to here - https://github.com/AlexMachin1997/Portfolio 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ unknown ]
- Node        [v9.8.0]
- Npm         [v5.7.1]

**Comment by callaginn** [comment]
I'm having this issue with Shopify Slate v1, which uses BrowserSync. Did you figure out a solution for this?

**Comment by AlexMachin1997** [comment]
@callaginn Did you find my solution useful

**Comment by callaginn** [comment]
@AlexMachin1997 Sorry -- I was hitting last minute deadlines, so didn't have time to implement/test potentially buggy tunneling options. Ended up realizing I could change my workflow slightly to allow for external links. That is, I worked off an internal ip and published to a public url.

**Comment by AlexMachin1997** [comment]
Ah ok. Ill close my issue then
