### ISSUE TITLE
"Asserition failed" when https:true in 2.20.0 and later

### ISSUE THREAD

**Issue by peterjhart** [BrowserSync/browser-sync#1533]
### Issue details

When using browser-sync 2.20.0 and later, the first request made by a browser halts the server with the following message:

> Assertion failed: ((object->InternalFieldCount()) > (0)), function Unwrap, file ../src/util-inl.h, line 196.
> Abort trap: 6

2.19.0 and earlier work without issue. All versions 2.20.0 and later have this error.

### Steps to reproduce/test case

1. Define a simple browserSync server, set `https: true` (without custom key, etc)
2. Start the server
3. Access the url with Chrome (allow security exception)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.20.0  ]
- Node        [  5.0.0  ]
- Npm         [  3.3.9  ]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```
gulp.task('server', function () {
  browserSync({
    server: "./app",
    https: true
  });
});
```

terminal:
```
$ gulp server
```

**Comment by shakyShane** [comment]
@peterjhart Hi! I cannot reproduce this - if you believe it's still a bug, please provide a small sample project that demostrates it - then I can re-open the issue :)
