### ISSUE TITLE
BrowserSync + Express?

### ISSUE THREAD

**Issue by kevinSuttle** [BrowserSync/browser-sync#154]
Wondering about how to use the proxy config of BrowserSync with the routing architecture of Express. I feel like I've seen an example you've posted somewhere, but I can't find it. In my defense, I'm really bad at computers.

**Comment by daslicht** [comment]
How about using BrowserSync + Express and just using npm to run commands and not something like Gulp?

**Comment by damienromito** [comment]
@daslicht you can set the param `--proxy` of `browser-sync start` and specidy the express server
http://stackoverflow.com/questions/37548537/express-and-browsersync-without-gulp

Here a demo : https://github.com/damienromito/express-sync

**Comment by daslicht** [comment]
Thank you !
