### ISSUE TITLE
Injecting not working properly on latest version(s)

### ISSUE THREAD

**Issue by 7iomka** [BrowserSync/browser-sync#1550]
### Issue details
Injecting not working in general or properly;
Latest version: https://cl.ly/1R1h2O3T0U2i
Version 2.18.13: https://cl.ly/1F350K1Q1t44

It seems that in recent versions do not work sockets.emit, but in previously versions - they work through time. Help me please!

### Affected platforms

- [ ] linux
- [+] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

UPD:
Only one solution to make it working is this code (and it works only on previously version):
```
bs.watch(`${build}/**/*.css`, function (event, file) {
				if (event === "change") {
					// reload all css (inject)
					bs.reload('*.css');
					bs.sockets.emit('styles:update');
				}
			});
```

**Comment by shakyShane** [comment]
Fixed in browser-sync@2.24.2 :)
