### ISSUE TITLE
Remote Debug tools do not work

### ISSUE THREAD

**Issue by vindemasi** [BrowserSync/browser-sync#1556]
### Issue details

Remote Debug tools do not work ("CSS Outlining", "CSS Depth Outlining" and "Overlay CSS Grid").

### Steps to reproduce/test case

Enable toggle button and verify nothing change in rendering.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.24.x ] while 2.23.7 is working.
- Node        [ 4.9.1 ]

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

browserSync.init({
        server: './build'
    });

**Comment by shakyShane** [comment]
Fixed in browser-sync@2.24.4 :)
