### ISSUE TITLE
remove sourcemap URLs from client script ?

### ISSUE THREAD

**Issue by lunelson** [BrowserSync/browser-sync#1568]
### Issue details

I am using browser-sync as the core of a middleware-based tool called [penny](https://github.com/lunelson/penny) and in my default setup I'm using `morgan` to log requests. 

I get a line like the following, very frequently:

`GET /browser-sync/FastMap.js.map 404 0.523 ms - 40`

AFAICT, this is due to the client script being served at `/browser-sync/browser-sync-client.js?v=2.24.4`, which contains various `sourceMappingURL` references—the one in question being on line `16010`:

`//# sourceMappingURL=FastMap.js.map`

...and of course the actual sourceMap file not being present. I am *guessing* this is due to the `minify: false` option in the init, which I thought might save some CPU cycles or something; but even if that's the case, couldn't / shouldn't these URLs be removed?

Anyway I'm using BrowserSync via API. The init looks like this:

```js
    bsync.init({
      // online: false,
      notify: false,
      minify: false,
      files: false,
      open: false,
      server: { baseDir, serveStaticOptions },
      httpModule: http2,
      https: true,
      // cors: true, // is this a good option?
      logLevel, // info, warn, debug (ascending verbosity)
      logPrefix: 'penny',
      middleware: [ serveFavicon, logger, srcController ],
    })
```

### Versions

- Browsersync [2.24.4]
- Node        [v8.11.1]
- Npm         [6.1.0]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
@lunelson You're not saving anything with `minify: false` - this just switches which file is served - there's no minification at run time!

the solution is just to remove `minify: false` 👍
