### ISSUE TITLE
Page doesn't automatically open when launching BS from Bash for Windows / WSL

### ISSUE THREAD

**Issue by Kurzdor** [BrowserSync/browser-sync#1573]
### Issue details
Page doesn't automatically open when I am launching Browser-sync instance from Bash for Windows.
But for example in the create-react-app that's possible.

### Steps to reproduce/test case

1. Launch browser-sync from Gulp or directly via CLI with static page project.
2. Page doesn't open in any browsers, also drops this error message in console: 

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  v2.24.4  ]
- node.js        [  v10.4.0  ]
- npm         [  v6.1.0  ]

### Affected platforms
- [x] other _(WSL / Bash for Windows 10 / Windows Subsystem for Linux (Ubuntu 16.04))_

### Browsersync use-case
- [x] Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
{Browsersync init code here}
```
var browserSyncConfig = {
  server: {
    baseDir: dir.builddist
  },
  tunnel: false,
  host: 'localhost',
  port: 9000,
  logConnections: true
};
```

Gulp Task:
```
gulp.task('server', function () {
  bsync.init(browserSyncConfig);
  bsync.watch("tmp/**/*.*").on('change', bsync.reload);
});
```

**Comment by Kurzdor** [comment]
#1581

**Comment by Kurzdor** [comment]
#1581

**Comment by shakyShane** [comment]
fixed via https://github.com/BrowserSync/browser-sync/issues/1581

in the next release
