### ISSUE TITLE
Port gets unnecesarily rewritten in Proxy

### ISSUE THREAD

**Issue by megaxlr** [BrowserSync/browser-sync#1577]
### Issue details

I have a link which needs to link to a specific port (which isnt the port that gets proxied), however browsersync rewrites the URL to the Browsersync port.

### Steps to reproduce/test case

Assuming:
You are running stock browsersync
The port you are proxying  localhost:80 to localhost:3000
You are trying to link to localhost:6426

Write the anchor in the HTML 
```html
<a href="http://localhost:6426">test</a>
```

Observe how the link in the browser gets rewritten to 
```html
<a href="http://localhost:3000">test</a>
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.24.5   ]
- Node        [  10.4.1   ]
- Npm         [  6.1.0  ]

### Affected platforms
I can now only confirm Linux (host and client) but considering the nature of this bug, I suspect it will be all OS's.
- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

(laravel-mix-browsersync-official)

**Comment by megaxlr** [comment]
Are bug reports even taken seriously? We're almost 2 months further and not a single comment has been made.

**Comment by shakyShane** [comment]
@megaxlr hi!

yes they are, but we've been unavailble recently. This weekend we'll be looking at the backlog, thanks for your patience :)

**Comment by megaxlr** [comment]
Good to hear, I was concerned :P

**Comment by shakyShane** [comment]
@megaxlr confirmed bug, it will be looked at :)
