### ISSUE TITLE
Update opn for WSL/Bash on Windows support

### ISSUE THREAD

**Issue by strarsis** [BrowserSync/browser-sync#1581]
### Issue details
[`opn`](https://github.com/sindresorhus/opn) is required with 4.0.2 by browser-sync (used for opening the browser automatically).
However, this version doesn't work in WSL/Bash on Windows. The latest version works correctly in WSL/Bash on Windows. It would be nice if browser-sync could update `opn` to its recent release version `5.3.0`.

### Steps to reproduce/test case
Start browser-sync. Notice this warning:
````
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
````

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.23.6]
- Node        [v8.11.3]
- Npm         [5.6.0]

### Affected platforms

- [ ] linux
- [x] windows
- [x] other: (Windows) WSL/Bash on Windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI
- [x] webpack

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

(not related to this general issue with outdated `opn`)

**Comment by strarsis** [comment]
PR: https://github.com/BrowserSync/browser-sync/pull/1582

**Comment by raymacz** [comment]
I guess, similar issue with my git bash --version 2.18.0.windows.1  [Issue](https://github.com/BrowserSync/recipes/issues/55)

**Comment by Kurzdor** [comment]
You can use special BS version with updated opn package
Here is the GitHub repo: https://github.com/Kurzdor/browser-sync
And here is the npm package page: https://www.npmjs.com/package/browser-sync-wsl
Tested it on my machine, works greatly.
I will delete this BS version when devs will fix this issue.
Thanks a lot!

**Comment by caseywatts** [comment]
Thanks for doing this issue & PR @strarsis !!

This is so minor but so huge 👏

**Comment by strarsis** [comment]
@shakyShane: Awesome! Could a new release be published to npm so I can update browser-sync in the projects?

**Comment by shakyShane** [comment]
yeah I'll get a release out in the next few hours

**Comment by LewisAndrewCampbell** [comment]
Hi, where do I set the browser path? Same issue with browsersync 2.26.7

**Comment by jameh** [comment]
@LewisAndrewCampbell I'm running into the same on WSL - what does "added the path" mean? Where do you add `/mnt/c` to? My chrome executable is at `/mnt/c/Program Files/Google/Chrome/Application/chrome.exe`

**Comment by jameh** [comment]
Ah, I added that full path `/mnt/c/Program Files/Google/Chrome/Application/chrome.exe` to the `browser` option in my `bs-config.js` that was generated using `browser-sync init`, which I am using via the `--config bs-config.js` option, and it was able to open my Windows chrome browser.
