### ISSUE TITLE
Page goes top after refresh on Microsoft Edge

### ISSUE THREAD

**Issue by klocus** [BrowserSync/browser-sync#1586]
### Issue details

Page goes top after browser refresh. Previous scroll position is not saving. Microsoft Edge 42.17134.1.0

### Steps to reproduce/test case

browserSync.reload on change.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.24.6 ]
- Node        [ 8.9.3 ]
- Npm         [ 5.5.1 ]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```
gulp.task('default', function() {
    browserSync.init({
        proxy: 'http://localhost/xyz/',
        host: 'localhost',
        open: false,
        ghostMode: {
            scroll: true
        }
    });

    gulp.watch("./sass/*.scss", ['sass']);
    gulp.watch("./js/theme.js", ['minify-js']);
    gulp.watch(["./*.php", "./functions/*.php"]).on('change', browserSync.reload); 
});
```

**Comment by shakyShane** [comment]
fixed in browser-sync@2.24.7 :)
