### ISSUE TITLE
RE DoS + Prototype pollution vulnerability

### ISSUE THREAD

**Issue by Berkmann18** [BrowserSync/browser-sync#1587]
### Issue details

NPM flagged a vulnerability regarding this package due to a Regular Expression Denial of Service found in its `debug` dependency as follows:
```bash
 Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browser-sync [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browser-sync > localtunnel > debug                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534             
```
There's also an apparent Prototype Pollution in its `lodash` dependency as follows:
```bash
 Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browser-sync                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browser-sync > easy-extender > lodash                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577
```

### Steps to reproduce/test case

```bash
# cd to a project that uses browser-sync as a dev dependency
npm audit #or nsp check
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.24.6]
- Node        [10.7.0]
- Npm         [6.2.0]

### Affected platforms

- [x] linux
- [x] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```js
    if (app.get('browser') || process.env.BROWSER) {
      require('browser-sync')({
        proxy: `localhost:${port}`,
        files: ['public/**/*.{js,css}']
      });
    }
```

**Comment by shakyShane** [comment]
I cannot address the localtunnel one https://github.com/localtunnel/localtunnel/issues/272

**Comment by Berkmann18** [comment]
@shakyShane How come? Aren't you the author and a contributor to that package including BrowserSync ?

**Comment by adamjaffeback** [comment]
FYI, localtunnel updated their dependencies with https://github.com/localtunnel/localtunnel/pull/256 and released to v1.9.1 to fix their end.

**Comment by Berkmann18** [comment]
@adamjaffeback Thanks for info.

**Comment by jt2k** [comment]
@shakyShane Thanks for fixing this! I see the change is tagged with a 2.25.0 alpha release.  When will the final version be released?
