### ISSUE TITLE
application/wasm support in Chrome

### ISSUE THREAD

**Issue by Zambiorix** [BrowserSync/browser-sync#1598]
### Issue details

I am using browser-sync to support my development of WebAssembly modules.
This works in Safari and FireFox, but in Chrome I get the following error:

(index):1 Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

It seems that browser-sync (or the underlying serve-static) does not recognise .wasm files and set the corresponding (application/wasm) Content-Type header.

I tried to define a new MIME type (see below), but that does not seem to work.

How can I solve this?

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.24.7 ]
- Node        [ v6.11.1 ]
- Npm         [ 6.4.0 ]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

browser-sync start --config config/bs-config.js

In my config file, I define a new callback where I update the serve-static mime types.
The output log shows that application/wasm is indeed added, but still I do not get the correct mime-type in my browser...

    "callbacks": {
        ready: function(err, bs) {

            bs.utils.serveStatic.mime.define({ 'application/wasm': ['wasm'] });

            console.log(bs.utils.serveStatic.mime);
        }
    },

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by Zambiorix** [comment]
Actually, I just noticed that I do not get a Content-Type at all ...
Is this a bug?

**Comment by Zambiorix** [comment]
OK, as it usually happens, one finds the solution 2 minutes after posting the question.

I can confirm that the (config options) code below works:

"callbacks": {
    ready: function(err, bs) {

        bs.utils.serveStatic.mime.define({ 'application/wasm': ['wasm'] });

        console.log(bs.utils.serveStatic.mime);
    }
},


... I just had the clean my browser cache, the stored version didn't have the mime yet ... sigh

**Comment by Zambiorix** [comment]
Maybe you could add this example  on your website  on how to add custom mime-types

**Comment by shakyShane** [comment]
@Zambiorix since this is so important, I've decided to add this fix into the core for now. browser-sync@2.26.3
