### ISSUE TITLE
page reloads after debugger is resumed

### ISSUE THREAD

**Issue by Michael-Janke** [BrowserSync/browser-sync#1605]
### Issue details

If chromes debugger stops for a break point and I resume the execution the browser reloads the page.

### Steps to reproduce/test case

- start debugger
- wait 5 seconds
- resume

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.24.7]
- Node        [ 8.11.3]
- Npm         [ 6.3.0]

### Affected platforms

- [ ] linux
- [x] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync
```
gulp.task('browser-sync', ['nodemon'], function() {
	browserSync.init(null, {
		proxy: "http://localhost:3100",
        browser: false,
        port: 7000,
        reloadOnRestart: false
	});
});

```

**Comment by janmattfeld** [comment]
Hi Michael, possibly a duplicate of #1591 ?

**Comment by Michael-Janke** [comment]
@janmattfeld  Hi! Yes, I think so!  Thanks!
