### ISSUE TITLE
How can I get the version number in a script?

### ISSUE THREAD

**Issue by JacobDB** [BrowserSync/browser-sync#1610]
I'm trying to retrieve the version of BrowserSync via JavaScript but cant' seem to locate a way to do it.

**Comment by JacobDB** [comment]
I was able to do this with `const BROWSERSYNC_VERSION = require("browser-sync/package.json").version;`, but not sure if there's a better way to do this.

**Comment by shakyShane** [comment]
cli: 

```bash
browser-sync --version
```

js

```js
const bs = require('./packages/browser-sync').create();

bs.init({
    server: "./app",
    watch: true,
}, function(err, bs) {
    console.log(bs.options.get("version"));
});

```
