### ISSUE TITLE
Missing Access URLs, prints out "Copy the following snippet into your website, just before the closing </body> tag" in console

### ISSUE THREAD

**Issue by baptistebriel** [BrowserSync/browser-sync#1612]
### Issue details

Hello! I'm getting a new issue with browser-sync where it only returns the UI links, it doesn't open the URL of the website anymore. I started getting this issue while updating to Node 10. I installed Node v9.9.0 back and still getting this issue.

### Steps to reproduce/test case

While running the following gulp script, it just prints "Copy the following snippet into your website, just before the closing </body> tag" on the console and no website URL is provided; only browser-sync UI.

![screen shot 2018-09-30 at 8 29 45 pm](https://user-images.githubusercontent.com/2464663/46261183-2b276f80-c4f0-11e8-92c7-e81b88b35aca.png)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync 2.8.2
- Node v9.9.0
- Npm 5.0.0

### Affected platforms

- macOS Mojave

### Browsersync use-case

- Gulp

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

```js
import gulp from 'gulp'
import watch from 'gulp-watch'
import browserSync from 'browser-sync'
import historyApiFallback from 'connect-history-api-fallback'
import modRewrite from 'connect-modrewrite'
import defaults from 'defaults'
import pckg from '../../package.json'
import opts from '../options'
import path from 'path'
import project from '../../project.json'

let serverConfig = {
  server: {
    baseDir: path.join(process.cwd(), 'static'),
    index: 'index.html',
    ghostMode: false,
    // SPA app, redirect requests to index.html
    middleware: [
      // historyApiFallback,
      modRewrite(['!\\.\\w+ /index.html [L]'])
    ]
  }
}

if (opts.useProxy) {
  serverConfig = {
    proxy: project.proxy
  }
}

// Somehow if we set proxy with a value and server to undefined,
// it doesn't want to start the proxy server. So we need to mix BrowserSync's
// options depending on the context (proxy or server).
var config = defaults({
  notify: false,
  minify: false,
  ghostMode: false,
  browser: ['google chrome'],
  port: project.port || 3000
}, serverConfig)

gulp.task('server', ['build'], function() {
  browserSync(config)
  if (opts.watch) {
    // Styles are directly streamed
    watch(['./static/**/*.*', '!./static/**/*.css', '!./static/**/*.svg'], browserSync.reload)
  }
})
```

Thank you!

**Comment by baptistebriel** [comment]
I fixed this issue, honestly have no idea how. I re-installed Node `v10.10.0`, cleared npm cache, updated npm to `v6.4.1`, installed a bunch of other stuffs like `npm install natives` because of some other npm errors, deleted `node_modules` and `package-lock.json`, re-installed all modules, tried to set my computer on fire, and then it worked!

I believe this issue is not directly due to browser-sync, so sorry for the trouble.. 🍻

**Comment by sohrabi2050** [comment]
For all who may come here to find the reason , you need to set proxy `proxy: "http://localhost:8888"` like this : 
```
{
    host: "localhost",
    port: 3000,
    proxy: "http://localhost:8888",
    files: "**/*"
}
```
You can find more details here:
[browsersync](https://coldbox-elixir.ortusbooks.com/browsersync)
