### ISSUE TITLE
Version 2.26.0 broke my dependencies tree

### ISSUE THREAD

**Issue by lazysoftwareman** [BrowserSync/browser-sync#1615]
### Issue details

My module have a dependency to browser-synch version ~2.11.0, and after the publishing of version 2.26 of browser-synch (and browser-synch-client), I've got this error:

Cannot find module 'etag'

Because my dependencies tree is broken

### Steps to reproduce/test case

- I'm declaring a dependency to browser-synch version ~2.11.0 (so I get 2.11.2)
- This version declares a dependency to browser-synch-client version ^2.3.3 (so I got 2.5.1)
- After the publishing of version 2.26.0 of browser-synch and browser-synch-client ^2.3.3 = 2.26.0 of browser-synch-client that is not compatible with browser-synch 2.11.2

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.11.2 ]
- Node        [ 8.12.0  ]
- Npm         [ 6.4.1 ]

### Affected platforms

- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [X] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by selected-pixel-jameson** [comment]
I think that the issue I'm running into is related to this as well. When trying to build I get an error stating that it can't find a reference to the module etag. It looks like this might have been a problem in a previous build as well. https://github.com/BrowserSync/browser-sync/issues/1471

**Comment by shakyShane** [comment]
Hi all, I've published browser-sync-client@2.26.1 which should fix this :)

**Comment by lazysoftwareman** [comment]
Thank you shakyShane
