### ISSUE TITLE
BS becomes unresponsive after two file changes on Node 11

### ISSUE THREAD

**Issue by dimitarnestorov** [BrowserSync/browser-sync#1626]
### Issue details

It seems that there is some kind of endless loop triggered after a couple of file changes.

Here's a video showing off the issue: https://youtu.be/MfnATcrsXt0
It's quite long, here are some timestamps:
[00:00](https://youtu.be/MfnATcrsXt0) - I run Browser Sync
[02:30](https://youtu.be/MfnATcrsXt0?t=150) - I create `test.js`
[02:39](https://youtu.be/MfnATcrsXt0?t=159) - I change `test.js`
[03:16](https://youtu.be/MfnATcrsXt0?t=196) - I change `test.js` again
[03:24](https://youtu.be/MfnATcrsXt0?t=207) - Browser Sync becomes unresponsive

I tested latest Node 10, the issue doesn't occur there.

### Steps to reproduce/test case

1. Clone https://github.com/dimitarnestorov/browsersync-node11.git
2. Install dependencies
3. Run `node script.js`
4. Create a random file inside the build folder
5. Make a change inside the new file
6. Make another change inside the new file

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.26.3  ]
- Node        [  11.0.0  ]
- Npm         [  6.4.1  ]

### Affected platforms

- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [x] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by rawzone** [comment]
Also seeing this when using browsersync with [laravel-mix](https://github.com/JeffreyWay/laravel-mix) running under Linux.

- Browsersync [2.26.3]
- Node [11.0.0]
- Yarn [1.10.1]

Same behavior as on the YouTube video @dimitarnestorov posted how ever the number of times before it stops responding varies for me for each time i relaunch browsersync.

Have tried to disable all ipv6 networking to ensure it was not a problem resolving localhost / 127.0.0.1 but does not seem to have made any difference.

**Comment by joemaller** [comment]
I think I'm seeing the same thing. No luck downgrading browsersync, but after switching node down to v10.x (and rebuilding node_modules) browsersync has been working smoothly for a couple hours.

**Comment by JuanDMeGon** [comment]
Facing the same with Node 11.0.0 on Windows 10 x64.
Just in case. I am using Laravel mix as well (which uses webpack) and Browser-sync ^2.26.3 along to browser-sync-webpack-plugin ^2.2.2.
After removing NPM 11.0.0 and install Node 10.13.0LTS, then remove node_modules and package-lock.json (just in case) it works as expected again.

**Comment by WuglyakBolgoink** [comment]
same :(

**Comment by keithws** [comment]
Same issue here but I am not using Laravel nor weback. I have to configured to watch a few thousand static files. Works fine on Node 10.x. Locks up after a few minutes on Node 11.x. Browser-sync 2.26.3.

**Comment by WuglyakBolgoink** [comment]
FYI: yesterday I upgraded my NodeJS version with v11.1.0 -> BS working again as before. 👍 

Please test this.

**Comment by waltercruz** [comment]
Yes, node 11.1 solved the issue to me.

**Comment by roberthallatt** [comment]
Also solved it for me

**Comment by jmcbee** [comment]
I thought I was going crazy. Thank you!
