### ISSUE TITLE
RESOLVED "TypeError: Cannot read property 'style' of null" with NProgress.js

### ISSUE THREAD

**Issue by stokedout** [BrowserSync/browser-sync#1635]
### Issue details

When using the BrowserSync with nprogress.js the following message appears and prevents the site rendering "TypeError: Cannot read property 'style' of null". I believe the problem is due to BrowserSync only loading a <head> tag containing the browser-sync-client.js code. Forgive me if this is a lack of understanding rather than a bug but I have read the reference material and can't find a solution

### Steps to reproduce/test case

Using Gulp 4.0.0.0 containing a gulpfile.js and BrowserSync 2.26.3
```
const browserSync = require('browser-sync').create();

function serve(cb) {
    browserSync.init({
        proxy: 'app.local'
    });
    cb();
}

exports.serve = serve;

```

Run the following in a terminal instance `gulp serve`

Browser opens with the following errors in the console window.

![image](https://user-images.githubusercontent.com/1408257/48952859-a8dd8980-ef3b-11e8-9652-1403aef4700b.png)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [ 2.26.3 ]
- Node        [ 10.13.0 ]
- Npm         [ 6.4.1 ]

### Affected platforms

- [ ] linux
- [X ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [X ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by stokedout** [comment]
I've fixed my own issue. I had all my app and client scripts injected in the <head> of the page. I've moved them to the bottom of the <body> tag and it works.

**Comment by shakyShane** [comment]
@stokedout ok that's great :)
