### ISSUE TITLE
Bad Request websocket is closed before the connection is established.

### ISSUE THREAD

**Issue by ploutos27** [BrowserSync/browser-sync#1651]
Hi, am not sure what cause this kind of issue. Any ideas welcome;! 

Bad Request web-socket is closed before the connection is established.
![browsersu](https://user-images.githubusercontent.com/12737690/51740442-b8449480-209c-11e9-8f4f-216038c21de8.PNG)
 

Thanks

**Comment by July-** [comment]
Wrong IP in proxy setting was causing same issue for me.
