### ISSUE TITLE
how to run without global install? 

### ISSUE THREAD

**Issue by OlegBrony** [BrowserSync/browser-sync#1661]
I don't want to install it globally. so I ran `npm i browser-sync --save`: 
```
package.json
"dependencies": {
    "browser-sync": "^2.26.3"
  }
```
then `browser-sync --version`, but got `browser-sync: command not found`
```
$ node -v
v11.10.0
```
what am I doing wrong?

**Comment by JosManMx** [comment]
Hi, I guess that the local instalation is only for run with task managers...

If you need to use the command line interface, you need to install globally with `npm install -g browser-sync`
