### ISSUE TITLE
Need an updated version of micromatch to resolve regular expression DOS vulnerabilities

### ISSUE THREAD

**Issue by SailingSteve** [BrowserSync/browser-sync#1673]
### Issue details

npm audit reports:

│ Low                    │ Regular Expression Denial of Service                         │
│ Package            │ braces                                                                            │
│ Patched in         │ >=2.3.1                                                                          │
│ Dependency of │ browser-sync [dev]                                                      │
│ Path                   │ browser-sync > micromatch > braces                        │
│ More info           │ https://nodesecurity.io/advisories/786                       │

### Steps to reproduce/test case

npm audit

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.26.3]
- Node        [10.13.0]
- Npm         [6.4.1]

### Affected platforms
I use a Mac, but this probably affects all users.
- [ ] linux
- [ ] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [x] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
fixed in 2.26.4 :)
