### ISSUE TITLE
Question: How to avoid browser HTTPS exceptions for https://localhost:8181?

### ISSUE THREAD

**Issue by stefanos82** [BrowserSync/browser-sync#1684]
My localhost and any local website I have is using SSL certificate generated with mkcert.

When I run `npm run build`, it opens the page but in order to browse the website, I need to add an exception with any browser.

I have tried to find solutions online, but couldn't find anything.

Here's my `dev/config/themeConfig.js`:

```js
'use strict';

module.exports = {
	theme: {
		slug: 'pirsig',
		name: 'Pirsing',
		author: 'stefanos82'
	},
	dev: {
		browserSync: {
			live: true,
			proxyURL: 'https://stefanos82.local',
			bypassPort: '8181',
            certPath: '/etc/nginx/ssl/stefanos82+1.pem',
            keyPath: '/etc/nginx/ssl/private/stefanos82+1-key.pem',
            https: true
		},
		browserslist: [ // See https://github.com/browserslist/browserslist
			'> 1%',
			'last 2 versions'
		],
		debug: {
			styles: false, // Render verbose CSS for debugging.
			scripts: false // Render verbose JS for debugging.
		}
	},
	export: {
		compress: true
	}
};
```

**Comment by edomato** [comment]
Hello Stefano,

If the certificates you generate are self signed, then you'll always get the warning on the browser for it and you're going to have to do the exception.

Greets.
