### ISSUE TITLE
Multiple instances on one server?

### ISSUE THREAD

**Issue by nicholas-c** [BrowserSync/browser-sync#172]
So, We have installed this on our development server got it working however if a second person runs a server it overwrites because; well, it's the same server I might be missing it however multiple instances would be sweet.

**Comment by basham** [comment]
@shakyShane Glad the [`browser-sync-instance` project](https://github.com/basham/browser-sync-instance) was able to inspire this feature work. Like the additions to the API.

**Comment by SimenB** [comment]
@shakyShane I'm not able to start this using Gulp. Just pasting in your example above fails, as both "UI"s tries to bind to the same port.

```
[10:50:20] Using gulpfile ~/repos/frontend-repo/code/gulpfile.js
[10:50:20] Starting 'browser-sync'...
[10:50:20] Finished 'browser-sync' after 21 ms
[BS] [info] Proxying: http://mylocal.dev
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3003
    External: http://10.2.22.101:3003
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://10.2.22.101:3001
 ------------------------------------
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://10.2.22.101:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://10.2.22.101:3001
 ------------------------------------
[BS] Serving files from: ./app

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.module.exports.startServer [as fn] (/home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/browser-sync-ui/lib/async.js:99:39)
    at /home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/browser-sync-ui/lib/UI.js:126:14
    at iterate (/home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
    at /home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
    at /home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/browser-sync-ui/lib/UI.js:134:13
    at Object.module.exports.setUrlOptions [as fn] (/home/testyo/repos/frontend-repo/code/node_modules/browser-sync/node_modules/browser-sync-ui/lib/async.js:62:9)

Process finished with exit code 8
```

I can't find this in the docs on your website, that's why I ask here :smile: 

Using 2.0.1 release

**Comment by shakyShane** [comment]
@SimenB  - yeah sorry, this hasn't been added to the docs yet, because of this reason (the race condition with the ports).

You could do this though, and it'll work fine

```js

var browserSync = require("browser-sync");

var bs1 = browserSync.create("proxy1");
var bs2 = browserSync.create("proxy2");

bs1.init({
    proxy: "http://mylocal.dev"
}, function () {
    bs2.init({
        proxy: "http://mylocal2.dev"
    });
});
```

... In this case, the first proxy has already resolved 2 ports, 1 for BrowserSync core + 1 for the UI.

The alternative is to provide all ports ahead of time, if you know them.

```js
var browserSync = require("browser-sync");

var bs1 = browserSync.create("proxy1");
var bs2 = browserSync.create("proxy2");

bs1.init({
    proxy: "http://mylocal.dev",
    port: 3010,
    ui: {
        port: 3011
    }
});
bs2.init({
    proxy: "http://mylocal.dev",
    port: 3012,
    ui: {
        port: 3013
    }
});
```

**Comment by SimenB** [comment]
There we go, that works beautifully. Thanks for the quick response!

Additional question, can I serve a subdirectory at root?
E.g. proxying ``http://example.com/subdomain`` at ``http://localhost:3010`` instead of ``http://localhost:3010/subdomain``?

**Comment by shakyShane** [comment]
@SimenB  - that's not currently available I'm afraid - it would involve us having to re-write every single request before it hits your server - doable with middleware maybe? https://github.com/BrowserSync/browser-sync/blob/master/examples/proxy.middleware.js (need latest version for that)

**Comment by shakyShane** [comment]
Closing this thread as this is now possible using the technique described https://github.com/BrowserSync/browser-sync/issues/172#issuecomment-74232625

**Comment by lkraav** [comment]
@shakyShane v2 didn't include any incremental provisions for client-side reconfiguration, for the context-separation idea [comment](https://github.com/BrowserSync/browser-sync/issues/172#issuecomment-68255733) or otherwise, right? Could you give me an indication on how you feel about the concept? I could determine the next step forward then.

**Comment by tkrotoff** [comment]
Here my happy experience with this feature.

I can have in parallel 1 BrowserSync instance for my 'regular' coding and 1 BrowserSync instance on another port for Protractor so they don't interfere with each other. gulpfile.js snippet:

```JavaScript
var browserSync = require('browser-sync');

function browserSyncInit(port, baseDir) {
  var browser = browserSync.create();
  browser.init({
    port: port,
    server: {
      baseDir: baseDir
    },
    ...
  });
  return browser;
}

gulp.task('serve', ['styles', 'scripts'], function() {
  var browser = browserSyncInit(9000, ['.tmp/app', 'app']);
  gulp.watch(['app/*.html'], browser.reload);
  gulp.watch(['app/**/*.scss'], ['styles', browser.reload]);
  gulp.watch(['app/**/*.ts', 'lib/**/*.ts'], ['scripts', browser.reload]);
});

function runProtractor() {
  var browser = browserSyncInit(9001, ['.tmp/app', 'app']);

  gulp.src('.tmp/test/e2e/all.js')
    .pipe($.protractor.protractor({
      configFile: 'protractor.conf.js'
    }))
    .on('error', function(e) {
      // Make sure failed tests cause gulp to exit non-zero
      throw e;
    })
    .on('end', function() {
      browser.exit();
    });
}

gulp.task('test:e2e', ['build:test:e2e', 'webdriver-update'], runProtractor);
```

**Comment by singhmohancs** [comment]
I am facing the same issue. Everything is working perfect on window and mac. But when i run the application on ubuntu 12.4+. gives the following error:

[09:03:54] all files 272.87 kB
[09:03:54] Finished 'scripts' after 4.38 s
[09:03:54] Starting 'inject'...
[09:03:54] gulp-inject 1 files into 404.html.
[09:03:54] gulp-inject 1 files into index.html.
[09:03:54] gulp-inject 77 files into 404.html.
[09:03:54] gulp-inject 77 files into index.html.
[09:03:54] Finished 'inject' after 522 ms
[09:03:54] Starting 'watch'...
[09:03:55] Finished 'watch' after 214 ms
[09:03:55] Starting 'serve'...
[09:03:55] Finished 'serve' after 25 ms
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:8080/
    External: http://192.168.1.4:8080/
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.4:3001
 -------------------------------------
[BS] Serving files from: .tmp/serve
[BS] Serving files from: app

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
bhagat:/var/www/smart-dms/dms/client_side$

My code snippet is as below : 
'use strict';

var gulp = require('gulp');
var browserSync = require('browser-sync');
var browserSyncSpa = require('browser-sync-spa');

var util = require('util');

var middleware = require('./proxy');

module.exports = function(options) {

  function browserSyncInit(baseDir, browser) {
    browser = browser === undefined ? 'default' : browser;

    var routes = null;
    if(baseDir === options.src || (util.isArray(baseDir) && baseDir.indexOf(options.src) !== -1)) {
      routes = {
        '/bower_components': 'bower_components'
      };
    }

    var server = {
      baseDir: baseDir,
      routes: routes,
      port:8080
    };

    if(middleware.length > 0) {
      server.middleware = middleware;
    }

    browserSync.instance = browserSync.init({
      startPath: '/',
      server: server,
      browser: browser,
      port:8080
    });
  }

  browserSync.use(browserSyncSpa({
    selector: '[ng-app]'// Only needed for angular apps
  }));

  gulp.task('serve', ['watch'], function () {
    browserSyncInit([options.tmp + '/serve', options.src],'Google Chrome');
  });

  gulp.task('serve:dist', ['build'], function () {
    browserSyncInit(options.dist, 'Google Chrome');
  });

  gulp.task('serve:e2e', ['inject'], function () {
    browserSyncInit([options.tmp + '/serve', options.src], []);
  });

  gulp.task('serve:e2e-dist', ['build'], function () {
    browserSyncInit(options.dist, []);
  });
};

**Comment by HiZhaoxiaoyang** [comment]
-_- if create different browserSync with diff port,it still a 'cross origin' url,  front-end still invoke it by jsonp and post methot won't work.

**Comment by HiZhaoxiaoyang** [comment]
-_- if create different browserSync with diff port,it still a 'cross origin' url, front-end still invoke it by jsonp and post method won't work.

**Comment by asuh** [comment]
This thread gives me the closest to using multiple subdomains with Browsersync, [via this comment](#issuecomment-74232625).

Is there a way that each BS init can do rewrites when one or the other references each other? 

For example, in his example above, bs1 used for http://mylocal.dev translates into http://localhost:3010. However, there are several links that are the same as bs1, but they are not rewritten in bs1 instance to http://localhost:3012. The opposite is also true.

Any solutions to fix this?

**Comment by mobiledeevloper** [comment]
How we can restrict browser-sync to run on the same port as the backend is running using react gulp and asp.net core.
