### ISSUE TITLE
browsersync.io down for two days so far

### ISSUE THREAD

**Issue by dman777** [BrowserSync/browser-sync#1737]
http://browsersync.io/ has been down for two days now. Any ideas what is going on?

**Comment by Ragers** [comment]
yeah, does anyone have access or a link to theird documentation somewhere? It is anoying as I need to check their documentation for some configurations I need to test.

**Comment by adojck** [comment]
Seems that domain has expired, someone responsible should renew it.

**Comment by dman777** [comment]
I love browser-sync. I hope it is not at it's end of life.

**Comment by xewl** [comment]
> @shakyShane I love browser-sync. I hope it is not at it's end of life.

Probably not at the end of it's life... I'm guessing human-error?
In the meantime you could use Wayback Machine: [Docs](https://web.archive.org/web/20190628074223/http://www.browsersync.io/docs/)

**Comment by kobrix** [comment]
Does this suggest the domain is subject to dispute?
```
Domain Status: clientHold https://icann.org/epp#clientHold 
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited 
```

**Comment by dman777** [comment]
I started a petition to bring back the browserync.io if anyone would like to sign it 

https://www.change.org/p/20129993/preview?source_location=homepage_large_button&sulstate=guest&lsrappv=variation&tag_selected=other_topic

**Comment by wesbos** [comment]
WE DID IT

https://twitter.com/shaneOsbourne/status/1219735944569507841

**Comment by shakyShane** [comment]
Sorry all, it's back!

**Comment by dman777** [comment]
Thank you! :)

**Comment by grapewheel** [comment]
@shakyShane It's down again...

**Comment by dman777** [comment]
@shakyShane  google cloud has a free tier that will handle that website. Or you could also host it here on github.
