### ISSUE TITLE
Proxy flag does not detect multiple URL parameters

### ISSUE THREAD

**Issue by miketalley** [BrowserSync/browser-sync#1744]
### Issue details

When running `browser-sync start` using the `--proxy` flag with a URL that contains >1 parameters, the Access URLs do not recognize any parameters other than the first one.

### Steps to reproduce/test case

Run `browser-sync start --proxy http://example.com/mypage?foo=foo&bar=bar&baz=baz`. Notice that when the browser opens, the only URL parameter is the first one(foo).

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.26.7]
- Node        [v12.12.0]
- Npm         [6.11.3]

### Affected platforms

- [X] OS X

### Browsersync use-case

- [X] CLI

### If CLI, please paste the entire command below

`browser-sync start --proxy http://example.com/mypage?foo=foo&bar=bar&baz=baz`

**Comment by christopherthielen** [comment]
this is a shell quoting issue.  try 
```
browser-sync start --proxy "http://example.com/mypage?foo=foo&bar=bar&baz=baz"
```

**Comment by miketalley** [comment]
Thank you @christopherthielen -- that worked!
