### ISSUE TITLE
Outdated and Vulnerable Dependencies

### ISSUE THREAD

**Issue by chillheart** [BrowserSync/browser-sync#1751]
### Issue details

browser-sync uses yargs@^6.6.0 and localtunnel@1.9.2 that have a child dependency (yarg-parser) that contains a known vulnerability. The vulnerability has been patched and yargs@>13.0.0.0 and localtunnel@2.0.0 use the updated dependency.

The reproduction steps are available on the vulnerability disclosure.

https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.26.7  ]
- Node        [  12.16.1  ]
- Npm         [  6.13.4  ]

### Affected platforms

- [X] linux
- [X] windows
- [X] OS X
- [X] freebsd
- [X] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [X] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

**Comment by shakyShane** [comment]
I believe this is resolved now - please let me know if that's not the case :)
