### ISSUE TITLE
http-proxy denial of service vulnerability

### ISSUE THREAD

**Issue by broksonic21** [BrowserSync/browser-sync#1764]
### Issue details

There is an open ticket for yargs-parser, but a new DOS for http-proxy showed up today:

```┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ http-proxy                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ browser-sync [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ browser-sync > http-proxy                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1486                            │
└───────────────┴──────────────────────────────────────────────────────────────┘```

### Steps to reproduce/test case

add browser-sync to package.json, `npm install`, `npm audit`

### Please specify which version of Browsersync, node and npm you're running

- Browsersync - 2.26.7
- Node        - v14.2.0
- Npm         - 6.14.5

**Comment by fredericpfisterer** [comment]
Patch is available now

**Comment by ainsleyclark** [comment]
Any movement on this?

**Comment by vidhya03** [comment]
I got this in my project using browser-sync 2.26.7
  **High**            **Denial of Service**                                                                         
  Package         http-proxy                                                    
  Patched in      >=1.18.1                                                      
  **Dependency of   browser-sync [dev]**                                            
  Path            browser-sync > http-proxy                                     
  More info       https://npmjs.com/advisories/1486

**Comment by denisbrodbeck** [comment]
The maintainers of http-proxy fixed the issue in this [commit](https://github.com/http-party/node-http-proxy/commit/335aeeba2f0c286dc89c402eeb76af47834c89a3).
They also dropped support for *Node 6* [here](https://github.com/http-party/node-http-proxy/commit/dba39668ba4c9ad461316e834b2d64b77e1ca88e), while `browser-sync` still supports *Node 6*.

**Comment by blachawk** [comment]
Whats the latest?

**Comment by mattshirlaw-finocomp** [comment]
+1 would also like to know whether there is a plan to fix this.

**Comment by edwardjosephbennett** [comment]
@shakyShane Is there a chance we can get this update merged into an update? Thanks :)

**Comment by kahlan88** [comment]
Would be great to get this merged soon :-) For now I'll set resolutions in my package.json, but would be awesome.

**Comment by thasmo** [comment]
Any update on this, @shakyShane?

**Comment by jeffschwartz** [comment]
Just asking due to no responses but Is browser-sync dead?

**Comment by kahlan88** [comment]
judging by latest commit, which was 14 months ago; it might be

**Comment by jeffschwartz** [comment]
@kahlan88 I was thinking the same thing. Unfortunately my node app uses browsersync. Are you aware of a suitable alternative? Have you tried the forked repo requesting a pull request to fix the issue?

**Comment by kahlan88** [comment]
> @kahlan88 I was thinking the same thing. Unfortunately my node app uses browsersync. Are you aware of a suitable alternative? Have you tried the forked repo requesting a pull request to fix the issue?

You can set `resolutions` in the `package.json` file, based on vulnerabilities in the `yarn audit` command. 

Like:
```
  "resolutions": {
    "http-proxy": "^1.18.1",
    "yargs-parser": "^13.1.2"
  }
```

Re-run `yarn audit` `browser-sync` vulnerabilities should disappear.
If you want to get rid of any other warnings - I think it's best to still first check whether there are any upgrades to packages they are caused by.

Hope that helps!

**Comment by ChaosinaCan** [comment]
> Are you aware of a suitable alternative?

@jeffschwartz I recently switched to using https://www.snowpack.dev/ for a project that had been using browsersync. I found it fairly easy to set up and it supports hot module reloading so the experience is pretty similar to browsersync but with some added bonuses like fixing up node_modules imports to work in the browser.

**Comment by kahlan88** [comment]
@jeffschwartz if you look at https://github.com/BrowserSync/browser-sync/pull/1768 - I think it's just been fixed :-) I will certainly try it tomorrow

**Comment by jeffschwartz** [comment]
I was afraid that I'd have to delay the next release of my project so this is awesome news. Thanks to everyone getting this done for the community ♥👍👏.

**Comment by jeffschwartz** [comment]
@kahlan88 yes, it's awesome and I will try later today and post a follow up. Thank you for your previous suggestion.

**Comment by jeffschwartz** [comment]
After running npm update npm audit reports 0 issues and I can also report that the release works for me. Again, thanks to everyone who made this happen.
