### ISSUE TITLE
Support `browserSync.close()` or expose some similar API

### ISSUE THREAD

**Issue by doshprompt** [BrowserSync/browser-sync#177]
There are times when for example you are running browserSync as a server for selenium etc. and would like to shut it down programatically, say for example once a gulp task completes. Currently, browserSync stays alive and keeps the gulp task from finishing.

**Comment by pkyeck** [comment]
mmm, not working for me. am I doing something wrong?

```javascript

var bs;

gulp.task('browsersync', function() {
  // ...

  bs = browserSync({
    // ...
  });
});

gulp.task('browsersync:stop', function(callback) {
  if (bs) {
    bs.cleanup(callback);
  }
});

```

but the gulp task is still active after that and I have to `CTRL` + `C` to kill it

**Comment by shakyShane** [comment]
Cleanup will not exit the process. 

https://github.com/shakyShane/browser-sync/issues/177#issuecomment-47074068
