### ISSUE TITLE
browser-sync refuses to serve file with specific name

### ISSUE THREAD

**Issue by LiteracyFanatic** [BrowserSync/browser-sync#1790]
### Issue details

This is weirdly specific, but `browser-sync` can't seem to serve a file named `plain.html` located in my `out/` directory. All other files in the directory are being served properly. The file is valid HTML and opens fine if I use the file path in the browser. Judging by the error message, `browser-sync` seems to think the file is a directory for some reason.

`Error: ENOTDIR: not a directory, stat '/home/jordan/src/resume/out/plain.html/'`

### Steps to reproduce/test case

Make a file named `plain.html` and try to serve it with `browser-sync`.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.26.12  ]
- Node        [  v14.7.0  ]
- Npm         [  6.14.7  ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

`browser-sync out/ --directory --no-ui --no-notify --no-open`

**Comment by Alexnortung** [comment]
Seems to work fine for me.

**Comment by LiteracyFanatic** [comment]
I can't reproduce it anymore either. I'll close this for now and reopen if I figure out how to reproduce.
