### ISSUE TITLE
malicious Pesticide.io link in remote debug page

### ISSUE THREAD

**Issue by TobiasNickel** [BrowserSync/browser-sync#1799]
### Issue details

On the `Remote Debug` page, there is two times the link to pesticide.io. That link seems rather shady to me.
It redirects a few times, then tell me that flash is out of date asking to download a new version.

it redirects to: 
  - http://bidr.trellian.com/r2.php?e=qzBy2CbrFCx2iAr9Vom1yN%2BNZLyxLOkoEE6FQ%2B7S%2Bd4MwDkfaDeg38FjfOaHjvl3YKJPyxXMZvvrVSFiyQTYFmMy0d39wyrXUIzujx2BhT%2FgB1jzq%2FVZlSgKuTBDwwglJ7ImjwzNWQIsDvTboR3YDruSaGP54JuVRYyBQYwqPUl1Ffq67kCUYLv7a9YsF8h5zfDpDgIZUQrJsSX%2B5crbKDlJPUQaOsQQwMRCfi1TByNCUckSuZ4aGPqi95imlIUVh4%2BZc14w6nGkk%2FPICSjzIHoHrAk27j%2FdU1UiqpaF835rgVfizk%2BquwZA9z1LxaivTXGB6NF0oRRpbsvQcaNKGnZFy3Y4X0FoHJYFD4nBSZ%2FchM16G%2FepFL6qmo5I11LNgFy2v1UKYRNJzrbrUWe5G%2FMHzox9oDR1hjrEupq0QQeu0Kx2DJpZ%2BG1jTtZZPvqZH9XnBzwMJn7UfIBT3sqOJVOTr8wPRQDycDGC8AeoO%2FGKxCtK7B91DK7NvknieKa0rNg9%2F97Di%2BFmBbgOsFYTe9Z2cyjmsMmsJJ0Tz%2Fs5XQAFtucsWEPr%2BIsxqWdscFyVU7VuV%2FGg%2B60sFI4sheMrzYzQPxOd4A8YQKbQEe02ZDn%2FizZWQ3mZemObHUYSy2haLk2H4V8c4FV6QVhEVAxrjO%2BcWlAEV1sMUnrYHLBankkWPY0UKbedgyIeHa32L85eJj3a%2FIauL5WXxnlDBVNM84rZxO%2FkWj%2FCAAhKYGeUWSJQEgEsyMSrsNdHGamJdvK7x%2F76YeZm1BsmAAQh3kPs4Q%3D%3D
  - http://bidr.trellian.com/r.php?u=http%3A%2F%2Fseemlast.monster%2Fi%2F25713%3Fsubid%3D1118065811%26kw%3D.us.02.desktop.nonadult.macos%26cpv%3D0.020&s=j
  - http://seemlast.monster/i/25713?subid=1118065811&kw=.us.02.desktop.nonadult.macos&cpv=0.020
  - http://seemlast.monster/h/s66fZP6UzfQbTr.UyaVUd8TioFnhs.85J_Yz8cITlYI8Gf2fI8WkrxQFuWBHmPyXoBs5MdqlHZRbsUju9XlagX2aaaY3d5cQPktnzF_NAbyHuM25mQ4VFxWq9g_cLHI7LdS.fa.9V71xRH8jDZnSdtAOxXzyQzMPIu2YA_QP6EX_zIS0nhCypemBDfvGBUuj7opFVpMIXRDjD_ig9tj1mAqq.qqqq.qq
  - https://han112.admedit.net/advertise/?adown=6811&cmp=7674&ctrack=8fe04a80-fe0d-11ea-8e75-6b21bbf23750&ptrack=695391c3
  - https://han112.admedit.net/advertise/refine.php?adown=6811&ptrack=695391c3&ctrack=8fe04a80-fe0d-11ea-8e75-6b21bbf23750&cmp=7674&t=1600914481&rh=7&avs=avs4&utm_src=8&sids=6
  - https://softreadynow.findthegoodplayershere.info/?b9zd1=MWE_X3dESyU6qGAaKQEWkzMx1AgUyMN_XwEBtExY5Zc.&cid=8fe04a80-fe0d-11ea-8e75-6b21bbf23750&sid=695391c3

What do you think, should these links be removed or updated?

### Steps to reproduce/test case

I installed eleventy, and started `eleventy --serve`.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  v2.26.12  ]
- Node        [  v12.3.1.  ]
- Npm         [  6.13.6  ]

### Affected platforms

- [ ] linux
- [ ] windows
- [X] OS X, but I think it is on all platform
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below

eleventy --serve

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

eleventy --serve

**Comment by arafalov** [comment]
Looks like project was abandoned long time ago: mrmrs/pesticide#67
