### ISSUE TITLE
https true: "Your connection is not private" on localhost

### ISSUE THREAD

**Issue by mariusa** [BrowserSync/browser-sync#1832]
### Issue details

Using browser-sync via eleventy https://github.com/11ty/eleventy/issues/1583

```
browserSyncConfig = {
    https: true
}
```

This setup will work https://blogjunkie.net/2017/04/enable-https-localhost-browsersync/
but using with `mkcert` and having set NODE_EXTRA_CA_CERTS env var should also work.

### Steps to reproduce/test case

```
Install mkcert
mkcert -install # to create a local CA
cd ~/.ssh
mkcert localhost 127.0.0.1 ::1 # to create a trusted cert for localhost in the current directory
# https://stackoverflow.com/questions/45807049/how-to-run-vue-js-dev-serve-with-https

# You're using node (which doesn't use the system root store), so you need to specify the CA explicitly in an environment variable, e.g: 
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  ^2.26.13  ]
- Node        [  14.15.1  ]
- Npm         [   6 ]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

via eleventy 
https://github.com/11ty/eleventy/issues/1583

**Comment by shakyShane** [comment]
Hi @mariusa - thanks for this.

I didn't even know that env var was something node would use - if you could find or show an example of starting an https server with this env-var then I'll happily support it :)

**Comment by mariusa** [comment]
Actually, I just tried now and the path to the local certificates is still required... I was hoping to being able to simply use `https: true`
https://stackoverflow.com/a/54083405/212736

Thanks for considering!
