### ISSUE TITLE
Vulnerability in axios lib

### ISSUE THREAD

**Issue by nimrodev** [BrowserSync/browser-sync#1835]
### Issue details

Vulnerability has been found in `axios` library, and had been fixed.
They fixed it and upgraded the version to `0.21.1`.
Following that `localtunnel` library has been fixed 9 days ago and now they have the safer `axios` in version `2.0.1`.
`browser-sync` still uses `2.0.0` version. it should be upgraded to version `2.0.1` to close this vulnerability issue.

See here: https://github.com/localtunnel/localtunnel/commits/master

**Comment by shakyShane** [comment]
fixed in 368f89e9c5850559a7b3f920fba9f20929a6f163

**Comment by shakyShane** [comment]
released :) 

https://github.com/BrowserSync/browser-sync/releases/tag/v2.26.14
