### ISSUE TITLE
browser-sync throwing syntax error in ie11

### ISSUE THREAD

**Issue by OktarinTentakel** [BrowserSync/browser-sync#1845]
### Issue details

There seems to be a transpilation bug in the browser-sync js files, since there are arrow functions included although the render target of ts is "es5". This results in a syntac error in IE11 of course, since the client file injected does not get transpiled on the way.

<img width="1418" alt="arrow-function-in-browser-sync-client" src="https://user-images.githubusercontent.com/4561418/106761558-3c8b6400-6635-11eb-9398-50c80579d5ec.png">

### Steps to reproduce/test case

This should always happen using version 2.26.14 and up. Letting BrowserSync inject the client and open the served page in IE11 must result in a syntax error since arrow functions simply do not exist in ie11.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.26.14  ]
- Node        [  12.20  ]

### Browsersync use-case

- [ ] API
- [ x ] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

function serve(done){
	browserSync.init({
		server : {
			baseDir : normalizePath(patternlabConfig.paths.public.root),
			middleware: compression()
		},
		host : '0.0.0.0',
		cors : true,
		open : false,
		snippetOptions : {
			// Ignore all HTML files within the templates folder
			blacklist : ['/index.html', '/', '/?*']
		},
		ghostMode : false
	}, function(){
		done();
	});
}

EDIT: correction, this is newly introduced in browser-sync 2.26.14 where this bug is directly included in the minified client source, didn't see that at first, because I installed .13 manually, but dependencies of .13 install client .14 in sub node_modules anyway and take broken source from there :|

QUICKFIX:
"devDependencies" : {
    "browser-sync": "2.26.13",
    "browser-sync-client": "2.26.13",
    "browser-sync-ui": "2.26.13",
},

"resolutions": {
    "browser-sync-client" : "2.26.13",
    "browser-sync-ui" : "2.26.13"
},

**Comment by shakyShane** [comment]
fixed in `browser-sync@2.29.0` :)
