### ISSUE TITLE
Browsersync won't start, running scripts disabled. Installed globally through npm

### ISSUE THREAD

**Issue by Obspogon** [BrowserSync/browser-sync#1883]
### Issue details

Browsersync won't start, I get this error:

```
browser-sync : File C:\Users\alico\AppData\Roaming\npm\browser-sync.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ browser-sync start
+ ~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

### Steps to reproduce/test case

Whenever I try `browser-sync start`

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.26.14]
- Node        [14.17.1]
- Npm         [6.14.13]

### Affected platforms

- [ ] linux
- [X] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [X] CLI

### If CLI, please paste the entire command below

 `browser-sync start`

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by brandon-promoonly** [comment]
Are you using PowerShell or cmd.exe?
If so, can you enter this into PowerShell and post the results?
`Get-ExecutionPolicy -Scope CurrentUser`

**Comment by ObserverPolygon** [comment]
I'm using VS Code Powershell
The code gives me Undefined

**Comment by Obspogon** [comment]
Changed execution policy, works fine now

**Comment by Gunt-r** [comment]
Simply changing the terminal from powershell to cmd allowed me to bypass the issue

**Comment by soumya9461** [comment]
> Changed execution policy, works fine now

What execution policy you have changed?

**Comment by afaqkhan6699** [comment]
> Changed execution policy, works fine now
how?

**Comment by sahu-SuMiT** [comment]
browser-sync --version works on command prompt but not on Windows Terminal
