### ISSUE TITLE
Resource exhaustion in engine.io dependency from npm audit

### ISSUE THREAD

**Issue by zachleat** [BrowserSync/browser-sync#1926]
Report at https://github.com/advisories/GHSA-j4f2-536g-r55m

https://www.npmjs.com/package/socket.io is currently at 4.4.x but this package is using 2.4.x https://github.com/BrowserSync/browser-sync/blob/a7c14c873b4ad14fdbdc1e07eaac0fc30af2e645/packages/browser-sync/package.json#L63

**Comment by ludofischer** [comment]
According to the [migration guides](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/), it would be possible to upgrade the server to 4 while maintaining compatibility with 2.x clients, so keeping the same supported browsers as before. Don't know if that's worth attempting as they mention only dropping support for IE 8.

**Comment by lachieh** [comment]
Duplicate issue. See #1850 for original.
