### ISSUE TITLE
Security vulnerability with axios

### ISSUE THREAD

**Issue by abbyblachman** [BrowserSync/browser-sync#1938]
### Issue details
I am getting the following message from dependabot: 
**Incorrect comparison in axios** 
The latest possible version that can be installed is 0.21.1 because of the following conflicting dependencies:
browser-sync@2.26.14 requires axios@0.21.1 via localtunnel@2.0.1
browser-sync-webpack-plugin@2.3.0 requires axios@0.21.1 via a transitive dependency on localtunnel@2.0.1
_Please provide issue details here_.

### Steps to reproduce/test case

_Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies)_.

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.26.14]
- Node        [16.13.1]
- Npm         [8.1.2]

### Affected platforms

- [ ] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### If CLI, please paste the entire command below

{cli command here}

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

{Browsersync init code here}

**Comment by Venkatuidevloper** [comment]
Issue still exist.

**Comment by shakyShane** [comment]
fixed in https://github.com/BrowserSync/browser-sync/pull/2059

```shell
npm i browser-sync@3
```

:)
