### ISSUE TITLE
What is the status of browser-sync-ui?

### ISSUE THREAD

**Issue by beenotung** [BrowserSync/browser-sync#1942]
I saw it is updated 4 months ago on npm, but the linked github repo is archived and not updated after 2018.

I saw a bug (wrong import path) but don't know where should I submit the pull request.

For browser-sync-ui@2.27.7, in file `/lib/plugins/network-throttle/network-throttle.js:91:44`
The `require("browser-sync/lib/server/utils")` should be changed to `require("browser-sync/dist/server/utils")` probably due to a recent rename.

**Comment by shakyShane** [comment]
@beenotung within the `packages` folder of this main repo :)
