### ISSUE TITLE
How do you add a route?

### ISSUE THREAD

**Issue by silvenon** [BrowserSync/browser-sync#197]
Excuse my connect newbieshness, but how do you add a route to the BrowserSync server, like you would in connect?

``` js
var connect = require('connect'),
    app = connect()
      .use('/bower_components', connect.static('bower_components'));
```

**Comment by drKnoxy** [comment]
This took me a little while to figure out, so if anyone else is googling around for where to add the "extensions" parameter like you would for express' static-serve module, which sets the default extensions to try.

ie. You are trying to have your urls written like `site.com/features` and the server will try files `site.com/features.html`

```js
server: {
    baseDir: './dist',
    serveStaticOptions: {
        extensions: ['html']
    },
},
```

**Comment by dman777** [comment]
Just to update, browsersync now has this option:

```javascript
// Per-route middleware
// NOTE: requires v2.12.1
middleware: [
    {
        route: "/api",
        handle: function (req, res, next) {
            // handle any requests at /api
        }
    }
]
```

https://www.browsersync.io/docs/options
