### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Rootdiv** [BrowserSync/browser-sync#1974]
Delete

**Comment by jmwebservices** [comment]
Interesting, I am looking for the opposite. I would like the browser windows to close when brower-sync exits. I am using Windows.

**Comment by Rootdiv** [comment]
Version 2.29.3 bug NOT fixed!

**Comment by Rootdiv** [comment]
Version 3.0.2 bug NOT fixed!

**Comment by Rootdiv** [comment]
Delete
