### ISSUE TITLE
Security vulnerability with `qs` dependency

### ISSUE THREAD

**Issue by joyheron** [BrowserSync/browser-sync#1994]
### Issue details

Package installation results in an npm warning.

I am using a package which installs `browser-sync` in version `2.27.10`. When running `npm install`, I get the following warning when I run `npm audit`

```
qs  <6.2.4
# npm audit report

qs  <6.2.4
Severity: high
qs vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-hrpp-h998-j3pp
fix available via `npm audit fix --force`
Will install browser-sync@2.11.2, which is a breaking change
node_modules/qs
  browser-sync  >=2.12.1
  Depends on vulnerable versions of qs
  node_modules/browser-sync

2 high severity vulnerabilities

```

### Steps to reproduce/test case

1. `mkdir browser-sync-bug-reproduction`
2. `cd browser-sync-bug-reproduction/`
3. `npm init -y`
4. `npm install --save browser-sync`
5. `npm audit` (to view the security vulnerability)

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [  2.27.10  ]
- Node        [  v18.11.0  ]
- Npm         [  8.19.2  ]

### Affected platforms

- [ ] linux
- [ ] windows
- [ x ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ x ] API
- [ ] Gulp
- [ ] Grunt
- [ ] CLI

### for all other use-cases, (gulp, grunt etc), please show us exactly how you're using Browsersync

I am currently maintaining a [fork](https://github.com/joyheron/fractal) of the Fractal styleguide in order to be able to keep dependencies up-to-date and use the tool in customer projects. The tool uses Browsersync to be able to test how a component will respond in multiple browsers at the same time.

**Comment by shakyShane** [comment]
incoming...
