### ISSUE TITLE
Using it with asp.net web MVC application

### ISSUE THREAD

**Issue by nim23** [BrowserSync/browser-sync#20]
It is possible to use browser-sync with an asp.net MVC application.

**Comment by DuNuNuBatman** [comment]
You can run something like:
`browser-sync start --proxy "localhost:12345" -files "files/**/*.css"`

This will run browser-sync and proxy the IIS Express instance you have running on port 12345 in the case of the example.

**Comment by atilkan** [comment]
@shakyShane  Can you share an example? Mine doesn't get the port i give because probablt it is used by IIS.
