### ISSUE TITLE
Dependency on specific version of ua-parser-js prevents vulnerabilities in downstream projects from being fixed

### ISSUE THREAD

**Issue by mattwelke** [BrowserSync/browser-sync#2009]
### Issue details

I was addressing a Dependabot security vulnerability but it said that my project could not update to a fixed version of the dependency in question, `ua-parser-js`, because `browser-sync` requires a specific version of it:

```
updater | INFO <job_587648674> Requirements update strategy bump_versions
updater | INFO <job_587648674> The latest possible version that can be installed is 1.0.2 because of the following conflicting dependencies:
updater | <job_587648674> 
updater | <job_587648674>   browser-sync@2.27.11 requires ua-parser-js@1.0.2
updater | <job_587648674>   No patched version available for ua-parser-js
updater | INFO <job_587648674> The earliest fixed version is 1.0.33.
updater | INFO <job_587648674> Finished job processing
```

### Steps to reproduce/test case

1) Create NPM project that uses browser-sync

2) Add dependency on `browser-sync@2.27.11` to project. Observe warning message: `2 high severity vulnerabilities`
3) Run `npm audit fix`. Observe error:
   ```
   ua-parser-js  0.8.1 - 1.0.32
   Severity: high
   ReDoS Vulnerability in ua-parser-js version  - https://github.com/advisories/GHSA-fhg7-m89q-25r3
   fix available via `npm audit fix --force`
   Will install browser-sync@2.27.5, which is a breaking change
   node_modules/ua-parser-js
     browser-sync  >=2.27.6
     Depends on vulnerable versions of ua-parser-js
     node_modules/browser-sync

   2 high severity vulnerabilities
   ```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.27.11]
- Node        [v18.12.1]
- Npm         [9.1.3]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

n/a

CLI is the way it's used in my project but this issue comes up before it is used as a CLI.

**Comment by tkoop** [comment]
Please fix this.  My npm audit is complaining about high severity vulnerabilities.

**Comment by ojvribeiro** [comment]
This can be closed since it was fixed by #2007.

**Comment by shakyShane** [comment]
Fixed in `2.27.12` - thanks for your patience :)

**Comment by mattwelke** [comment]
The change made in #2007 doesn't address this problem because it just updates the dependency to a new specific version. Using a version range would allow consumers of this library to determine the exact version used, which would allow them to address security vulnerabilities in their own projects without waiting for projects in the middle of the dependency chain, like this one, to be updated.

**Comment by shakyShane** [comment]
@mattwelke thanks! I was too eager in closing this - I saw 'ua-parser-js' title and looked no further, my apologies 🙏🏻

**Comment by shakyShane** [comment]
`browser-sync@2.28.1` just uses `^`, let's see how it goes :)
