### ISSUE TITLE
browser-sync tried to access chalk, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound

### ISSUE THREAD

**Issue by kristian** [BrowserSync/browser-sync#2021]
### Issue details

Executing browser-sync with Yarn 2 PnP gives the following error:

> browser-sync tried to access chalk, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### Steps to reproduce/test case

Use browser-sync with Yarn 2

Checked in `package.json` file and indeed `chalk` is only defined as a `devDependency` however, because it is used in the public API, which is exposed to dependent packages it should be a `dependency` instead.

**Comment by shakyShane** [comment]
Can you try `browser-sync@2.28.2` 🙏🏻

**Comment by kristian** [comment]
Mhm, just noticed, that eazy-logger is defined without a `^`  here:

https://github.com/BrowserSync/browser-sync/blob/master/packages/browser-sync/package.json#L48

Meaning it issue still happens in eazy-logger and because it is hard linked to 4.0.0 fixing & bumping eazy-logger won't fix the issue either and another bump of browser-sync will be required. Sorry for that.

**Comment by shakyShane** [comment]
@kristian try `browser-sync@2.28.3`

**Comment by kristian** [comment]
Jep, that fixed it! Thanks @shakyShane 🙏🏻

**Comment by shakyShane** [comment]
@kristian thanks for bringing it to my attention

**Comment by kristian** [comment]
Very welcome, have a good one 👍
