### ISSUE TITLE
debouce option only injects two changed css files

### ISSUE THREAD

**Issue by simshanith** [BrowserSync/browser-sync#203]
When attempting to inject CSS with the debounce option and multiple files change within the debounced interval, only the first and second (or last, not sure) changed files get injected.

Looks like you need to debounce a different function that syncs a queued list of changes. Files would get added to the queue non-debounced, and the queue would be synced on the debounced interval.

**Comment by mhkeller** [comment]
I'm seeing a similar behavior. When I rebuild multiple CSS files, only the last one triggers and injection event. I have a `reloadDebounce` of `750`. 

The queue idea proposed by @simshanith seems like a logical way of fixing this so that all CSS changes are injected at once after the debounce period has ended.

**Comment by dryoma** [comment]
Having the same problem. Out of 3 CSS files only 2 get injected with `reloadDebounce` active.

**Comment by skulden13** [comment]
Hello!

I have the same issue.

### Version of Browsersync, node and npm you're running

- Browsersync [  2.17.5  ]
- Node        [  v6.9.1  ]
- Npm         [  3.10.8  ]

### Affected platforms

- [ ] linux
- [x] windows
- [x] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [x] Grunt
- [ ] CLI

### Code:

grunt/browserSync.js:
```javascript
module.exports = function (grunt, data) {
  var browserSyncOptions = {
    watchTask: true,
    online: true,
    server: {
      baseDir: "./"
    },
    reloadDebounce: 500,
  };

  var projects = data.projects;
  var config = {};

  Object.keys(projects).forEach(function (projectId) {
    config[projectId] = {
      bsFiles: {
        src: [
          projects[projectId].root + '**/*.css',
          projects[projectId].root + '**/*.js',
          projects[projectId].root + '**/*.html'
        ]
      },
      options: browserSyncOptions
    };
  });

  return config;
};
```

Gruntfile.js:
```javascript
// All the tasks' config files are in ./grunt/
module.exports = function(grunt) {
  var data = {
    // project's config
    projects: {
      p1: {
        root: './project/'
      }
    }
  };

  // Just-in-time loading of Grunt plugins; increases spead
  require('jit-grunt')(grunt, {
    'template-tag': 'grunt-scripts/template-tag.js'
  });
  // Measuring and outputting the tasks' execution time
  require('time-grunt')(grunt);
  // Auto-loading Grunt task configs (from files in ./grunt/)
  require('load-grunt-config')(grunt, { data: data });

  // System notification on errors, etc.
  grunt.task.run('notify_hooks');
}
```

Here is my package.json.
```
{
  "name": "project",
  "version": "1.0.0",
  "devDependencies": {
    "autoprefixer": "^6.3.6",
    "grunt": "^0.4.5",
    "grunt-browser-sync": "^2.2.0",
    "grunt-concurrent": "^2.3.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-cssmin": "^0.14.0",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-newer": "^1.1.1",
    "grunt-notify": "^0.4.1",
    "grunt-postcss": "^0.8.0",
    "grunt-sass": "^1.1.0",
    "grunt-shell": "^2.1.0",
    "jit-grunt": "^0.9.1",
    "jsdom": "^9.2.1",
    "load-grunt-config": "^0.17.2",
    "time-grunt": "^1.2.2",
    "underscore": "^1.8.3"
  }
```

Terminal log:
```
    Waiting...
    >> File "project/_res/css/inner-page.scss" changed.
    Running "notify_hooks" task
    
    Running "copy:p1_css" (copy) task
    Created 33 directories, copied 175 files
    
    Running "sass:p1" (sass) task
    
    Running "postcss:autoprefixer_p1" (postcss) task
[BS] File changed: project/_res/css/base.css
    >> 4 processed stylesheets created.
    >> 4 sourcemaps created.
    
    Done, without errors.
    
    Execution Time (2016-11-15 13:00:08 UTC+2)
    loading tasks            783ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 36%
    copy:p1_css              118ms  ▇▇▇ 5%
    sass:p1                  177ms  ▇▇▇▇ 8%
    postcss:autoprefixer_p1   1.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 50%
    Total 2.2s
    
    Completed in 2.491s at Tue Nov 15 2016 13:00:10 GMT+0200 (EET) - Waiting...
[BS] File changed: project/_res/css/inner-page.css
    >> File "project/_res/css/homepage.scss" changed.
    Running "notify_hooks" task
    
    Running "copy:p1_css" (copy) task
    Created 33 directories, copied 175 files
    
    Running "sass:p1" (sass) task
    
    Running "postcss:autoprefixer_p1" (postcss) task
[BS] File changed: project/_res/css/base.css
    >> 4 processed stylesheets created.
    >> 4 sourcemaps created.
    
    Done, without errors.
    
    Execution Time (2016-11-15 13:00:22 UTC+2)
    loading tasks            811ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 34%
    copy:p1_css              140ms  ▇▇▇ 6%
    sass:p1                  295ms  ▇▇▇▇▇ 13%
    postcss:autoprefixer_p1   1.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 47%
    Total 2.4s
    
    Completed in 2.671s at Tue Nov 15 2016 13:00:24 GMT+0200 (EET) - Waiting...
[BS] File changed: project/_res/css/inner-page.css
```

As you can see from the log, I have four css files and only two are reloaded with browser-sync.
Any ideas?

Thanks

**Comment by mhkeller** [comment]
@shakyShane @simshanith Looping you into this one since it seems like it should be reopened. If you have any guidance on where someone could start to try and fix this that would be great.

**Comment by simshanith** [comment]
@mhkeller - agreed; been two and half years and still bothering people :)

A failing test case would be a great place to start -
https://github.com/BrowserSync/browser-sync/blob/master/test/specs/files/files.watching.debounce.js

I think the fix would need to go into the `getObservable` in `lib/file-watcher.js` https://github.com/BrowserSync/browser-sync/blob/master/lib/file-watcher.js#L106

**Comment by shakyShane** [comment]
Hi all!

`debounce` is acting as it should - in that it produces the final event captured after a specified window of time.

in all of these cases, I think what we really need is a buffer - this is how it worked in the past (which was an incorrect implementation of debounce, - dont ask)

so we take all events within a given window, when that time period is up we filter for unique and then file all.

**Comment by shakyShane** [comment]
if theses were the following changes in a 1000ms window, because of a build step, or a git checkout for example

```yaml
core.css
core.css
core.css
core.css
styles.css
styles.css
styles.css
```

then really, you want Browsersync to send `reload(core.css, styles.css)` once after the 1 second...

**Comment by shakyShane** [comment]
it gets more tricky if the captured event included anything which may cause a reload:

```yaml
core.css
core.css
core.css
core.css
styles.css
styles.css
styles.css
index.html
about.html
docs.html
app/scripts.js
```

In this situation, we only care about the 1 single event, a page `reload`.
