### ISSUE TITLE
Not working on node@^20.0.0

### ISSUE THREAD

**Issue by firefoxic** [BrowserSync/browser-sync#2039]
### Issue details

The problem was noticed when using `browser-sync` via `gulp`. But it turned out that it had nothing to do with `gulp`. Both methods I used to start `browser-sync` (CLI and `gulp`), which worked fine up to and including `node@19`, turned out not to work in `node@20`.

### Steps to reproduce/test case

1. Install `node@20` with any node version manager, such as `nvm`, `nvs` or `volta`.

2. Create a test directory and move into it:
	```shell
	mkdir test-bs && cd test-bs
	```

3. Create the minimum required `index.html`:
	```shell
	echo '<!DOCTYPE html>' > index.html
	```

4. Try to start the server:
	```shell
	npx browser-sync start -s
	```

### Please specify which version of Browsersync, node and npm you're running

- Browsersync [2.29.3]
- Node        [20.4.0]
- Npm         [9.7.2]
- Pnpm        [8.6.6]

### Affected platforms

- [x] linux
- [ ] windows
- [ ] OS X
- [ ] freebsd
- [ ] solaris
- [ ] other _(please specify which)_

### Browsersync use-case

- [ ] API
- [ ] Gulp
- [ ] Grunt
- [x] CLI

### If CLI, please paste the entire command below

```shell
npx browser-sync start -s
```

![Screenshot of a terminal with a browser-sync test in different versions of node.js: in v20.4.0 it crashes with `AggregateError` output, but in v18.16.1 it works correctly running the server.](https://github.com/BrowserSync/browser-sync/assets/3382798/feda5087-d4ec-4941-b837-84a10a119d68)

**Comment by trusktr** [comment]
This is pretty critical, people are moving onto Node.js. I happen to be on Node 18, and was considering upgrading, but coincidentally happened to see this.

**Comment by trusktr** [comment]
I tried it, and it worked for me on Node 20 actually!

Maybe it will work if you do this instead:

```sh
echo '<html><body>hello</body></html>' > index.html
```

**Comment by shakyShane** [comment]
Thanks for the ping, yep I'll look at this ASAP :)

**Comment by shakyShane** [comment]
@trusktr 

> I think it is possible browser-sync could simply inject the script regardless

I tried that before, it's way too problematic - I know the restriction is annoying, but you can always configure https://browsersync.io/docs/options#option-snippetOptions to get around it.

I updated the GitHub actions to run on Node 20 now - and everything is passing.

@firefoxic  - could you try with a more realistic HTML example and report back if it's working for you :)
