### ISSUE TITLE
Not working on OSX with Chrome

### ISSUE THREAD

**Issue by mbilyanov** [BrowserSync/browser-sync#2046]
I couldn't get the browser to update. The server is started, the UI is there, but I don't see the connection in the UI and on changing the `*.html` file, I see the `Reloading Browsers...` message, but the actual browser is not updating.

This is my command.
```
browser-sync start --server --cwd --watch --files "site/*.html"
```
This is the output:
```
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.168.1.101:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 --------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] Watching files...
[Browsersync] Reloading Browsers...
```

Not sure why it says `./` where it should be `./site`? That seems also broken.

`browser-sync 2.29.3`
`node v18.12.1`
`macOS Big Sur 11.6.5`

**Comment by mbilyanov** [comment]
My HTML file was just a string `Hello World?`, so not a legit HTML structure in there. When I created a minimal HTML file with the correct formatting, things started to work. So please ignore. Probably some CORS security/protocol thing.

**Comment by trusktr** [comment]
It's browser-sync's fault (not CORS related): browser-sync should be made smart enough to work whether or not `document.body` is ready. (when you do not write `<html>` or `<body>`, the browser will add them dynamically after loading your HTML file, and an HTML file containing only "hello" is valid HTML).

**Comment by shakyShane** [comment]
@trusktr as mentioned on another thread, I've been down this path multiple times, the only thing that worked for the 99% is to just look for a body tag - can be altered with https://browsersync.io/docs/options#option-snippetOptions if needed :)
