### ISSUE TITLE
Getting this error in ubuntu when I try to install browsersync

### ISSUE THREAD

**Issue by jitendravyas** [BrowserSync/browser-sync#207]
~ ❯❯❯ npm install -g browser-sync
npm http GET https://registry.npmjs.org/browser-sync
npm http 200 https://registry.npmjs.org/browser-sync
npm http GET https://registry.npmjs.org/browser-sync/-/browser-sync-1.3.0.tgz
npm http 200 https://registry.npmjs.org/browser-sync/-/browser-sync-1.3.0.tgz
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/browser-sync',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-29-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "browser-sync"
npm ERR! cwd /home/jitendra
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! fstream_path /usr/local/lib/node_modules/browser-sync
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jitendra/npm-debug.log
npm ERR! not ok code 0

**Comment by mambax** [comment]
+1

**Comment by shinnn** [comment]
https://github.com/npm/npm/issues/8058#issuecomment-95821549

**Comment by vedsarkushwaha** [comment]
try sudo.
sudo npm install -g browser-sync

**Comment by shila-panthi** [comment]
how to solve this type of problem?

**Comment by jithendra1798** [comment]
Terminal is prompting 
**sudo: npm: command not found**
when I use the command
**sudo npm install -g browser-sync**
