### ISSUE TITLE
Mobile Device (iPhone) Cant Connect

### ISSUE THREAD

**Issue by seyhunak** [BrowserSync/browser-sync#21]
Hi,

I tried via web interface everything works smootly, but it doesn't work on mobile device 

My setup: 
Rails 4 application

``` js
// browser-sync --config browser_sync.js --server
module.exports = {
    files: "app/assets/stylesheets/*.css, app/assets/javascripts/*.js, app/views/**/*.html.erb",
    host: "127.0.0.1",
    debugInfo: true,
    ghostMode: {
        links: true,
        forms: true,
        scroll: true
    },
    server: {
        baseDir: "app"
    }
};
```

So, on the terminal; I can see only Chrome (web) connected. How to make it work with mobile device on same network?

```
Watching the following:
app/assets/stylesheets/*.css
app/assets/javascripts/*.js
app/views/**/*.html.erb

Browser Connected! (Chrome, version: 31.0.1650.63)
```

**Comment by joshikeerti** [comment]
I am on "version": "1.7.3", and have issues connecting from my iphone or ipad. works fine on desktop browsers.

**Comment by shinnn** [comment]
@joshikeerti Use the latest version.

**Comment by joshikeerti** [comment]
I am using the latest version now ' 2.7. 1' but still have the same issue. on IOS safari I am not able to connect using the external ip, The desktop and the mobile device are on the same wifi network.

**Comment by SandHilt** [comment]
I'm in 2.7.3 and same problem @joshikeerti with my lumia device.
