### ISSUE TITLE
Client going on ssl

### ISSUE THREAD

**Issue by riccardod** [BrowserSync/browser-sync#211]
I noticed that sometimes the browser sync client plugin switches to SSL and then stop refreshing.

I've checked my Gulp configuration and is not very different from the one illustrated at http://www.browsersync.io/docs/gulp/
![screenshot 2014-07-25 18 22 49](https://cloud.githubusercontent.com/assets/128016/3704960/a6e5dfc6-1419-11e4-9de2-0a9942dbea2f.png)

**Comment by iblack10** [comment]
Mine does alternate between the two - is this not supported? At the moment I can only access one or the other depending on whether I include --https or not.
