### ISSUE TITLE
Throw Error when used gulp.watch()

### ISSUE THREAD

**Issue by MillerRen** [BrowserSync/browser-sync#224]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOSPC
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at Gaze._watchDir (/home/xxx/xxx/tools/gulp/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)

**Comment by AdsonCicilioti** [comment]
Same problem :(

**Comment by amoswachanga** [comment]
If on Ubuntu, running the following command might solve the problem: 
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Reference:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by AdsonCicilioti** [comment]
Yes @amoswachanga . I'm using this solution and work fine now. Thx!

**Comment by mager** [comment]
Thanks for the fix @amoswachanga

**Comment by amoswachanga** [comment]
Great it helped @mager  and @AdsonCicilioti

**Comment by AdsonCicilioti** [comment]
:facepunch:
