### ISSUE TITLE
Add CORS option

### ISSUE THREAD

**Issue by thasmo** [BrowserSync/browser-sync#233]
When using the proxy option and loading browser-sync manually via inline script tag it would be nice to have the possibility to check if the server on port 3000 is running, like this:
```js
var url = '//' + location.hostname + ':3000/browser-sync-client.js',
    xhr = new XMLHttpRequest();

xhr.onreadystatechange = function() {
	if(xhr.readyState == 4 && xhr.status == 200) {
		document.write(('<script async="async" src="' + url + '"><\/script>'));
	}
};

xhr.open('HEAD', url, true);
xhr.send();
```
The problem is that sending the head request is not allowed, because the browser treats the request to the server on port 3000 as a cross-domain request. It would be nice to have an option to configure CORS headers for the browser-sync server.

**Comment by thasmo** [comment]
Basically it would be nice to have a simple implementation of CORS into the server of browser-sync. In it's simplest form, the server returns a `Access-Control-Allow-Origin` with the value `*`. A more comprehensive how-to can be found [here](http://www.html5rocks.com/en/tutorials/cors/?redirect_from_locale=de#toc-adding-cors-support-to-the-server); although I don't know if that's up to date regarding the spec. I'm no expert on this either. Maybe @vml-sdaniel can give some good input on what's important and what use-cases for browser-sync could benefit.

**Comment by shakyShane** [comment]
This can added easily as middleware, please see http://stackoverflow.com/questions/17124600/how-can-i-add-cors-headers-to-a-static-connect-server

**Comment by zach-adams** [comment]
For those like me who are using Nginx as the local web server, you can add this block into your Nginx configuration and that will allow CORS support (Also read the comment above the configuration):

https://gist.github.com/Stanback/7145487

**Comment by TeodorKolev** [comment]
No working solution by far. I don't know why this issue is closed....

**Comment by bclinkinbeard** [comment]
@TeodorKolev you need to add this to your BS config:

```js
middleware: function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  next();
}
```

**Comment by shakyShane** [comment]
@bclinkinbeard @TeodorKolev also, since [2.16.0](https://github.com/BrowserSync/browser-sync/releases/tag/v2.16.0) this is supported via the `cors` option.

```js
const bs = require('browser-sync').create();

bs.init({
    server: './app',
    cors: true
});
```

**Comment by scipper** [comment]
@shakyShane: updating browserSync from 2.9 to 2.17 totally did it. thanks!

**Comment by titusfx** [comment]
Is not **cors:true** working? (on version 2.18.8 )
because it doesn't work for me:

 ```
browserSync.init({
        serveStatic: ['.'],
        server: './src/mainApp',
        cors: true,      
    });
```

And I know is only CORS problem, because I have a shortcut to open Chrome with  _--disable-web-security --user-data-dir="D:/Chrome"_ and it possible to make request.

**Comment by ptsimplot** [comment]
@titusfx Same issue here. Did you find a fix? Also tried the middleware solution offered by @bclinkinbeard but no dice. You'd think embedding a youtube link and viewing on localhost would be simple...

**Comment by av09** [comment]
@shakyShane Unable to fix my CORS by enabling cors:true in my Browser sync config Please help.

**Comment by blachawk** [comment]
why  does the following middleware process not work in browser-sync 2.26.14....

```js
function bSync(cb) {
    msync.init({
        server: {
            baseDir: "./pub",
            middleware: function (req, res, next) {
                res.setHeader('Access-Control-Allow-Origin', '*');
                next();
            },
        }
    });
}

```

**Comment by ryanaltvater** [comment]
Neither `cors` or `middleware` solution are working for me.
