### ISSUE TITLE
Auto-Proxy mode

### ISSUE THREAD

**Issue by thasmo** [BrowserSync/browser-sync#234]
Would it be possible to set `proxy` to `auto` or something similar and just use the same hostname which is used in the request when going through the proxy server?

For example opening `my.local.project.dev:3000` would proxy to `my.local.project.dev:80`.
This would be more flexible using browser-sync for a project where multiple developers
work on, without specifying an explicit proxy domain.

The idea behind this is to use browser-sync in proxy mode but without explicitely defining the hostname of the original server, but to use the original Host header.

Or in other words; I'd like to use `browser-sync start --proxy="auto"` or something similar and when opening `my.project:3000` in the browser, it should proxy to `my.project:80`. It would be nice if this then also works with xip.io and localtunnel.me.

**Comment by gansbrest** [comment]
This auto host detection aka `browser-sync start --proxy auto:8080` looks pretty interesting. I don't see why we need to hardcode hostnames here. Especially if we have multiple devs who use different hostnames, but gulp file for browser-sync is commited to the repo.

@thasmo did your request go anywhere?

**Comment by thasmo** [comment]
@gansbrest, I tried to use writing a middleware for this but that didn't work out, at least for me. I'd love to have the possibility to *not* set the proxying host explicitly - as you mentioned, developers use different hostnames for the same project.

If anybody has a nice and simple solution for this, I'd be glad to hear about it. I think middlewares are too late in the request cycle to achieve this, but I could be wrong.
