### ISSUE TITLE
Source maps trigger full page refresh.

### ISSUE THREAD

**Issue by greypants** [BrowserSync/browser-sync#235]
Looks like source maps are triggering a full page reload when enabled in gulp-ruby-sass. See this issue: https://github.com/greypants/gulp-starter/issues/38

I'm assuming it's because the task creates two files: app.css and app.css.map, and only css files and images are flagged for live injection. Just a heads up.

**Comment by fr-olivier** [comment]
Hello,

I have the exact same issue: when my sourcemaps are generated, the full page reloads, instead of doing a css injection.

I tried to make browerSync target specific files or pass a "ignored" option in watchOptions, but it still fully reload the page:
browserSync.init({
    proxy: "http://localhost:8888/css-injection",
    files: ['css/main.css', '*.html'],
    watchOptions: {
		// ignoreInitial: true,
		ignored: '*.map'
	}
});

Someone has an idea how to solve this?
Thanks a lot :)

**Comment by shakyShane** [comment]
@fr-olivier are you using with gulp/grunt ?

**Comment by fr-olivier** [comment]
With gulp

**Comment by shakyShane** [comment]
Please show the entire gulp file

**Comment by fr-olivier** [comment]
Hello shakyShane,

Here is the complete gulpfile I use:
```
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();
// var sass        = require('gulp-sass');
// var less = require('gulp-less-sourcemap');
var sourcemaps = require('gulp-sourcemaps');
var less = require('gulp-less');

gulp.task('serve', ['less'], function() {
	browserSync.init({
	    proxy: "http://localhost:8888/css-injection",
	});

    gulp.watch("less/*.less", ['less']);
    gulp.watch("*.html").on('change', browserSync.reload);
});

// Compile sass into CSS & auto-inject into browsers
gulp.task('sass', function() {
    return gulp.src("scss/*.scss")
        .pipe(sass())
        .pipe(gulp.dest("css"))
        .pipe(browserSync.stream());
});

gulp.task('less', function() {
    return gulp.src("less/*.less")
        .pipe(sourcemaps.init())
        .pipe(less())
        .pipe(sourcemaps.write('../sourcemaps'))
        .pipe(gulp.dest("css"))
        .pipe(browserSync.stream());
});

gulp.task('default', ['serve']);
```

I can create a repo if you want to reproduce the exact same situation. I noticed that I still get the same issue if I use sass instead of less, and gulp-less-sourcemap instead of gulp-sourcemaps.
But if I comment the sourcemap generation line ```.pipe(sourcemaps.write('../sourcemaps'))```, then the css injection works as expected.

**Comment by fr-olivier** [comment]
Hello,

Just to know, should I open another issue?

Have a nice day,
François

**Comment by Nirazul** [comment]
@fr-olivier 
browserSync does a full page reload when it gets anything else than `css` files into `browserSync.stream();`. Make sure to filter out your `*map` files before entering this line:

```
var filter = require('gulp-filter');

<...>
        .pipe(sourcemaps.init())
        .pipe(less())
        .pipe(sourcemaps.write('../sourcemaps'))
        .pipe(gulp.dest("css"))
        .pipe(filter(['**/*.css']))
        .pipe(browserSync.stream());
```

**Comment by fr-olivier** [comment]
Hello @Nirazul,

Thank you for your reply, when I use your code, I get an error ```ReferenceError: filter is not defined```, do I need another npm module?

**Comment by davidlemaitre** [comment]
@fr-olivier You need gulp-filter module. Or you can use the "match" property to filter : 
```
gulp.task('less', function() {
    return gulp.src("less/*.less")
        .pipe(sourcemaps.init())
        .pipe(less())
        .pipe(sourcemaps.write('../sourcemaps'))
        .pipe(gulp.dest("css"))
        .pipe(browserSync.stream({match: '**/*.css'}));
});
```

**Comment by camilocls** [comment]
@davidlemaitre this work perfect, thanks!

**Comment by petebarr** [comment]
@Nirazul That filter worked a treat, ta! I was starting to pull my hair out.

**Comment by Pistil-Studio** [comment]
@davidlemaitre Perfect Thx a lot

**Comment by mhchen** [comment]
I just ran into this exact issue. I feel like this might warrant being added to the documentation. I'd be happy to open a PR if you agree.

**Comment by qm3ster** [comment]
Which is better?
```js
files: ['build/css/*.css', 'build/*.html']
files: '@(build/css/*.css|build/*.html)'
files: 'build/**/*.@(css|html)'
```
