### ISSUE TITLE
Add Webpack HMR support or an example how to make it work

### ISSUE THREAD

**Issue by koistya** [BrowserSync/browser-sync#246]
https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack

**Comment by InSuperposition** [comment]
+1

**Comment by falzhobel** [comment]
Just bringing this back up, maybe point us in a possible solution, I would love to help on this with a Gulp setup.

**Comment by aaronjensen** [comment]
I got webpack w/ HMR + browsersync working by having browser sync proxy webpack.

Here's some copy/paste from my project, hopefully it's useful: https://gist.github.com/aaronjensen/e2a0c72f95e3fd6f3845

**Comment by falzhobel** [comment]
Thanks @aaronjensen, I will look at this and let you know. Could you also share your package.json file so I don't forget a dependency?

**Comment by aaronjensen** [comment]
@falzhobel updated the gist. I'm using some old versions (it's an old project) so hopefully not much has changed. Good luck!

**Comment by stereokai** [comment]
@aaronjensen does all of BrowserSync's features work? (especially live-reload and the syncing between browsers)

**Comment by aaronjensen** [comment]
yes, they did

**Comment by faergeek** [comment]
In case you need it, there's a middleware for just hot reloading https://www.npmjs.com/package/webpack-hot-middleware

You can use it like this:

```javascript
bs.init({
  server: {
    baseDir: 'public',

    middleware: [
      webpackDevMiddleware(bundler, {
        publicPath: webpackDevConfig.output.publicPath,
        stats: { colors: true }
      }),

      webpackHotMiddleware(bundler)
    ]
  },

  files: [
    'public/css/*.css',
    'app/template.html'
  ]
}, cb);
```

**Comment by shakyShane** [comment]
@faergeek - This would make a great [recipe](https://github.com/BrowserSync/recipes) :p

**Comment by stereokai** [comment]
Sweet!

**Comment by shakyShane** [comment]
https://github.com/Browsersync/recipes/tree/master/recipes/webpack.react-hot-loader

**Comment by jitendravyas** [comment]
I'm wondering what Webpack's Hot loader can do which Browsersync can't?

**Comment by faergeek** [comment]
@jitendravyas Webpack's Hot Module Replacement is most useful with react-hot-loader. It can reload react components (rerendering it's markup), without losing UI state. E.g. you open modal, there you open some tab and there you open dropdown. Then you edit code, save, it reloads and you do not need to click though it again, it just applies.

**Comment by jitendravyas** [comment]
@faergeek you mean Webpack's HMR do something useful which Browersync can't and it's makes sense with React only.

**Comment by faergeek** [comment]
@jitendravyas I just don't know of any other plug-and-play implementation of something like that. But you can integrate it manually if you need. It allows you to accept updated module in your code or some plugin code and do whatever you want with it (e.g. replace express middleware without full restart of application).
