### ISSUE TITLE
Add live editing for JS and HTML

### ISSUE THREAD

**Issue by donaldpipowitch** [BrowserSync/browser-sync#250]
IT would be great if this project would support live editing for JS and HTML.

Maybe browser-sync can utilize fb-flo for JS live editing? Brackets supports live editing for HTML - maybe some functionality could be reused from there?

**Comment by PixelT** [comment]
+1
Some news about HTML / JS live edit?

**Comment by thasmo** [comment]
Looks awesome!

**Comment by shakyShane** [comment]
examples of both https://github.com/BrowserSync/recipes

**Comment by thasmo** [comment]
@shakyShane, that's only refering to HTML-injection, right?

**Comment by shakyShane** [comment]
There is js hot reloading too
