### ISSUE TITLE
How can I disable logging events for browser-sync-client.1.3.5.js

### ISSUE THREAD

**Issue by jgatjens** [BrowserSync/browser-sync#252]
![browser-sync](https://cloud.githubusercontent.com/assets/1598461/4346736/eba778f8-4110-11e4-87a8-e384013c68a6.png)

Its really annoying to have to scroll to see my own logs.

**Comment by Liooo** [comment]
Thanks @avanderhoorn

To be more specific for guys facing this problem in the future, type the following in the chrome dev console

```
localStorage["debug"] = null
```

I'm not sure what this value means, but setting it to null, there's no browserify annoying messages, and `console.log` in my app still works well.

**Comment by jgatjens** [comment]
(Y)

**Comment by palmdeezy** [comment]
:+1:

**Comment by ryanxcharles** [comment]
:+1:

**Comment by bennypowers** [comment]
I also had this problem. It's caused by visionmedia/debug, which relies on this localStorage flag to configure logging. currently, there's no option to namespace the config, which means that there's no way to turn logging off for browsersync but keep it on for other components which use `debug`
