### ISSUE TITLE
mod-rewrite support

### ISSUE THREAD

**Issue by oscarotero** [BrowserSync/browser-sync#26]
Hi. I'd like to use this library in a MAMP project with mod-rewrite, so some assets files paths are not the same in the server and in the browser. For example:
`/assets/cache/css/styles.css` in the browser is `/assets/css/styles.css` in the server. There can be also some files pointing to the same file (I have a css preproccessor that inject imported css) so some files in the server (for example: base.css, grid.css, etc) can be just one file in the browser.
Is there any way to map the watched files to create alias between server and browser files?. Some like this (just an idea):

``` js
module.exports = {
    files: {
        "assets/cache/css/styles.css": [
            "assets/css/base.css",
            "assets/css/grid.css"
        ],
        "assets/cache/css/styles2.css": [
            "assets/css2/*.css"
        ]
    }
}
```

**Comment by lessadiogo** [comment]
@jasonmorganson , thats actually amazing! I've spent much time on it... Could you explain some details of regex.. or give some reference? I got part of what u did, but not completely. Thanks for the solution.
