### ISSUE TITLE
Empty white window refresh bug

### ISSUE THREAD

**Issue by mietek** [BrowserSync/browser-sync#277]
Apologies in advance for the fuzziness of this report.  I haven't figured out any clear pattern to the bug, and I'm hoping someone else has seen it as well.

Sometimes, when triggered by BrowserSync, Safari looks like it's refreshing a page, but ends up with an empty white window. A manual refresh is then necessary, which causes the scroll position to be lost.

This is happening in Safari 7.1 on OS X, but I'm pretty sure it's happened in older versions too.

**Comment by shakyShane** [comment]
> To me, this suggests BrowserSync does not wait properly for files to finish building.

BrowserSync can only monitor files when they change on disk. you can omit the file-watching and trigger the reload manually instead via the API.

http://www.browsersync.io/docs/api/

**Comment by mietek** [comment]
To clarify — it seemed to me that BrowserSync *did* notice a file change, which is why a reload was triggered. However, BrowserSync *did not* wait for the file to stop changing within the specified `reloadDelay` or `debounceDelay`, which is why the file was served truncated. Are you closing this as “won’t fix”?

**Comment by eikeco** [comment]
@mietek I'm having the same problem. I guess you never got a response for your last comment...

**Comment by shakyShane** [comment]
@mietek  & @eikeco `reloadDelay` can you both try using `reloadDelay` with the latest version and report back if this is still an issue

```sh
npm install browser-sync@latest
```

**Comment by shakyShane** [comment]
```sh
browser-sync start files="app/*.html" --reloadDelay=2000
```

**Comment by antoniomacs** [comment]
No luck with reloadDelay tho. Still get random blank pages. Using latest version with gulp.

**Comment by mietek** [comment]
I continue to use the workaround I described above — build files in a temporary directory, then move them into the directory monitored by BrowserSync.

**Comment by ivanreese** [comment]
I get the same issue — Safari opens a blank white window (no headers, no body). Latest version, with gulp.

It happens when all three of the following are true:
* "online" is set to something non-default
* "open" is true
* I already have a Safari window open, pointed at localhost:3000

If I change any of those things, then the issue disappears.
