### ISSUE TITLE
BrowserSync is watching, but doesn't track changes to my CSS file

### ISSUE THREAD

**Issue by gentle-media** [BrowserSync/browser-sync#278]
Hi,

I know its here for issues and not for Q&A, but I don't know where else I have to ask a question related to browser sync. Apologies for that, but hopefully someone can assist me

My command line skills are 0.something, but I managed to get everything installed and up & running and have the following output, because I have a localhost with a sub directory 'artisan' (my project)

```
unknown-00-23-6c-99-68-e4:~ user$ browser-sync start --proxy="localhost:8888" --files="artisan/css/*.css"
[BS] Proxying: http://localhost:8888
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.1.64:3000
[BS] Watching files...
```

Like I said it works to some extend... I can open the Artisan website in the browser with the new local and/or external URL and see the 'connected to browsersync' notification, but changes I make and save in the css file, doesn't automatically refresh/change the page that's open and neither do the changes gets added to the command line.

Thus... I'm very confused and hopefully someone can see or can guess where I go wrong. Thanks!

**Comment by karneaud** [comment]
i am experiencing a similar issue using yoeman/grunt grunt-browser-sync on a XAMPP server. Everything works except when auto refreshing when I edit js/ html or css as you explained. Were you able to solve this issue?

**Comment by gentle-media** [comment]
@karneaud - Syncing did work for me too, but I never got the auto refresh part working.

**Comment by gabrielgiordan** [comment]
I have experienced a similar issue, and the solution was too simple. If you are running on windows, be sure to run the cmd as an administrator. After I did this, the sync feature ran fine.

**Comment by ccjmne** [comment]
@gabrielgiordan You just saved my day!

**Comment by LeksorHayabusa** [comment]
Hi there, i had such issue not only with **css** but also **html** or **js** (browsersync doesnt reload pages)
I added some lines to solve this issue: 
```
gulp.task('default', ['syncReload'], ()=>{
  gulp.watch('sass/**/*.scss', ['syncReload']) 
  gulp.watch('**/*.html', ['syncReload'])
  gulp.watch('js/**/*.js', ['syncReload'])
  sync.init({ server: "./" })
})
gulp.task('syncReload', () => {
  sync.reload()
  console.log('reloaded page')
})
```
**But my solution makes my laptop hot, i dont know ho to improve it yet.**
finally i got my _gulpfile.js_ configurations next:

```
const gulp = require('gulp');
const sass = require('gulp-sass')//переменные названия команды
const autoprefixer = require('gulp-autoprefixer')
const sync = require('browser-sync').create();
const jasmine = require('gulp-jasmine-phantom')

sync.stream()

gulp.task('default', ['styles', 'syncReload'], ()=>{
  gulp.watch('sass/**/*.scss', ['styles', 'syncReload']) 
  gulp.watch('**/*.html', ['syncReload'])
  gulp.watch('js/**/*.js', ['syncReload'])
  sync.init({ server: "./" })
})

gulp.task('styles', () => {
  gulp.src('sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(autoprefixer({
            browsers:['last 2 versions']}))
    .pipe(gulp.dest('./css'))
})

gulp.task('tests', () => {
  gulp.src('tests/spec/extraSpec.js')
    .pipe(jasmine({
      integration: true,//if false it tests nodejs code only
      vendor: 'js/**/'
    }))
})

gulp.task('syncReload', () => {
  sync.reload()
  console.log('reloaded page')
})
```
