### ISSUE TITLE
specifying port 80 gives me port 81

### ISSUE THREAD

**Issue by jetlej** [BrowserSync/browser-sync#290]
If I specify port 80 along with a proxy (localhost), the local URL that is spit out is localhost:81, which clearly does not resolve to the right site. Same thing happens with port 8080.

**Comment by jtvjan** [comment]
Sorry for necro'ing, but since this is the top Google result: If you don't know why it's binding to 81, Skype may be the cause. Go to Extra > Settings > Advanced > Connection and disable 'Use port 80 and 443'.

**Comment by bdadieb** [comment]
same problem even skype is not running

**Comment by smrtrnx** [comment]
Hi,

I tried the solutions mentioned above but none of them worked for me. Skype is ain't using the port 80 and nothing else uses port 80 aside from xampp.

So, I was wondering why browser-sync redirects to port 81 even if I assigned port: 80 on its init. I had it working before but after formatting my pc it doesn't work anymore.

can somebody suggest a solution?

**Comment by buhoho** [comment]
I have simler probrem. and solved. 
probrem the always my local mac on brwoser-sync open the 444port useing service.

Of course, the 443 port has already been released. I checked with netstat.
The cause was security software (ESET).
443 was listed in the setting to http protocol check.
