### ISSUE TITLE
document for recursive watching syntax?

### ISSUE THREAD

**Issue by zhuangya** [BrowserSync/browser-sync#294]
i just trace the source code all the way to `gaze`, finally realize, `**` is for recursive watching.

the command `browser-sync start --server --files="styles/**"` is for watch all the files and directories under `styles`, not just one level down.

can someone put this in the `browser-sync` document?

thanks!

**Comment by acicali** [comment]
This is still not in the docs. The double-asterisk is, but the word "recursive" or any explanation of how it works is not. Googling for "browsersync recursive" led me to this github issue instead of the actual documentation.
