### ISSUE TITLE
Script is not injected when HTML is malformed

### ISSUE THREAD

**Issue by edi9999** [BrowserSync/browser-sync#300]
Say I want to debug something, so I add a `console.log` before the rendering of the template.

My resulting HTML might look like this: 

```
DEBUG VALUES ....
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>
```

In this particular case, the script injection doesn't work.

I'm using the "proxy" mode.

Is they a way to work around this ?

**Comment by zanona** [comment]
Coming back to this issue, apparently when a body tag is found inside a script.
The injector will fail:

```
<!doctype html>
<link rel=stylesheet href=main.css>
<script>
    var template = '<!doctype html>\n<title>Title</title>\n<body>…</body>';
</script>
<body>
<h1>Content</h1>
...
</body>
```

The injector will try to inject `browser-sync-client.js` inside the var `template` on the `script` tag and not after the real html body.
