### ISSUE TITLE
Refreshing a proxied host reverts to vhost

### ISSUE THREAD

**Issue by farism** [BrowserSync/browser-sync#302]
If I am viewing a proxied site e.g.

vhost domain: `site1.localhost/test-page`
proxy: `localhost:3001/test-page`

and do a browser refresh on a route, it kicks me back to the vhost domain `(site1.localhost/test-page)`. But this only happens if my URL does not end with a trailing slash. If it does end with a trailing slash `(site1.localhost/test-page/)` - note the trailing slash, the browser remains on the proxied host. I'm not sure if this is an issue with browsersync or with my webserver config. Currently using WAMP/apache.

**Comment by sebastianromero** [comment]
I updated to 2.2.4 and it's happening the same. Everytime I click any link, it goes back to the URL without the port. So it breaks the connection with BS.
That doesn't happen in another project I'm working but with version 2.0.1.
