### ISSUE TITLE
Mock request?

### ISSUE THREAD

**Issue by lazywei** [BrowserSync/browser-sync#311]
Hi,

Can I mock request via browser-sync? I want to mock a RESTful backend so I can focus on frontend development. Just like [puer](https://github.com/leeluolee/puer)'s mocking request.

Thanks.

**Comment by blvz** [comment]
but when [serve-index](https://github.com/expressjs/serve-index/) is enabled, `POST` requests are ignored.

Here: https://github.com/expressjs/serve-index/blob/267913151b334ba1fa6cc273c202b7eda55fa2f1/index.js#L93

```js
browserSync({
    server: {
        directory: true, // serve-index gets enabled by setting directory: true.
        baseDir: "test/fixtures",
        middleware: function (req, res, next) {
            if (mocks[req.url]) {
                mocks[req.url](req, res);
            }
            next();
        }
    }
});
```

**Comment by shakyShane** [comment]
closing as this should be done via middleware - we are also going to add this type of functionality to UI in the future. but it doesn't belong in core.

@blvz  - to overcome that issue, use the api

```js
require("browser-sync")({
    open: false,
    server: {
        baseDir: "src",
        directory: true
    }
}, function (err, bs) {
    bs.addMiddleware('', function (req, res, next) {
        if (mocks[req.url]) {
            return mocks[req.url](req, res);
        }
        next();
    }, {override: true});
});
```

`{override: true}` will push middlewares to the front of the stack and providing you don't call next(), everything will work - even with POST

**Comment by blvz** [comment]
@shakyShane good to know. thank you.

**Comment by thedamon** [comment]
@shakyShane I'm trying to make something like this work on an assemble project (using Grunt). Is it possible to use the bs api the way you demonstrated from within grunt options? or how would I need to approach that?
And will this work with outgoing requests?

**Comment by dman777** [comment]
Just to update, browsersync now has this option:

```javascript
// Per-route middleware
// NOTE: requires v2.12.1
middleware: [
    {
        route: "/api",
        handle: function (req, res, next) {
            // handle any requests at /api
        }
    }
]
```

https://www.browsersync.io/docs/options
