### ISSUE TITLE
Proxy not working for root directory

### ISSUE THREAD

**Issue by kadyjakub** [BrowserSync/browser-sync#313]
Hello,
thanks for good tools.
I use sync with grunt. When I set proxy to my vhost:
proxy: 'domain.loc'
grunt not open this directory, it only works when I set another values:
proxy: '127.0.01/domain.loc'
or when i put some index file to subfolder
proxy: 'domain.loc/subfolder'
I tried to set host but without success. Thanks for reply.

**Comment by shakyShane** [comment]
Can you try latest version and report if this is still an issue for you.

`npm install browser-sync@latest`

**Comment by kadyjakub** [comment]
Hello,

its ok now.

Thank you

 Jakub Kadeřávek  E-mail: info@kady.cz  Skype: kadyjakub  Telefon: +420 603
957 563 (po - pá, 11:00 - 14:00)
 Web: www.kady.cz

2015-02-18 13:07 GMT+01:00 Shane Osbourne <notifications@github.com>:
