### ISSUE TITLE
Using browsersync + WordPress + Yoast SEO Plugin

### ISSUE THREAD

**Issue by donaldallen** [BrowserSync/browser-sync#317]
Not sure if this is an issue with BrowserSync or with Yoast, but incase anyone else has the same problem, I'll just post this.

If you are not getting CSS injections on your WP home page, but you are on other pages, it's likely due to the Yoast SEO plugin. Yoast inserts a script that looks like this:

```html
<script type="application/ld+json">{ "@context": "http://schema.org", "@type": "WebSite", "url": "http://192.168.1.29:3000/", "potentialAction": { "@type": "SearchAction", "target": "http://192.168.1.29:3000/?s={search_term}", "query-input": "required name=search_term" } }</script>
```

This breaks BrowserSync and it is unable to inject anything. To disable feature from Yoast, add the following to your functions.php:

```php
add_filter('disable_wpseo_json_ld_search', '__return_true');
```

**Comment by shinnn** [comment]
@donaldallen Any updates?

**Comment by shakyShane** [comment]
@donaldallen We're choosing to not try and solve possible use-case, given that Browsersync is a development-only tool. Hopefully it's still useful to you :)
