### ISSUE TITLE
Using 'browser-sync' and 'connect-modrewrite'

### ISSUE THREAD

**Issue by antonioOrtiz** [BrowserSync/browser-sync#323]
I am working on a angular.js app. My problem is when working locally, when I refresh my URL i get `Cannot GET /` when a page is refreshed other than the index.html etc.

My problem is solved on my production server using:

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^(.*) /index.html [NC,L]
</IfModule>
```

However I'd like a solution which works with gulp, locally. I have read you can use 'connect-modrewrite' like so:

```
gulp.task('browser-sync', function() {
browserSync({
    server: {
        baseDir: outputDir,
    middleware: function() {
        return [
            modRewrite([
                '^/api/v1/(.*)$ http://localhost:3000/api/v1/$1 [P]'
            ])
        ];
    }
    }
});
});
```

The above doesn't work, so I assume its incorrect. Am I way off?

**Comment by borNfreee** [comment]
@FadelChafai it does not work for me, too

**Comment by Bomavi** [comment]
@FadelChafai thanks, it works perfectly!

**Comment by matinfo** [comment]
@FadelChafai Thanks worked perfectly locally with AngularJS ui-Router with `$locationProvider.html5Mode(true);`
