### ISSUE TITLE
Liberal license

### ISSUE THREAD

**Issue by bsr203** [BrowserSync/browser-sync#324]
Hello,

I am not an expert, but heard the complications of using GPL license in a closed source product. For ease of use outside open source world, do you mind changing the license of browser-sync to more open one (Apache, / MIT / BSD , MPL etc) . Thanks.

**Comment by alvareap** [comment]
Do you intend browser-sync to be an apache license? If so, consider revising easy-extender and eazy-logger GPL license dependencies.
