### ISSUE TITLE
Images are not showing up on server

### ISSUE THREAD

**Issue by mwilc0x** [BrowserSync/browser-sync#326]
Hi,

I have a gulp task which simply copies images into my build folder. These images won't be included in css and/or an image tag in the html but will be needed on the page. A small snippet of the relevant gulp task to do this looks like this:

``` sh
gulp.task('browserSync', function() {
  browserSync({
    server: {
      baseDir: './'
    }
  })
});
gulp.task('image', function () {
  return gulp.src(p.image)
    .pipe(image())
    .pipe(gulp.dest(p.distImage))
    .pipe(reload({stream: true}));
});
```

the full gulpfile for what I am trying to do can be found here: https://gist.github.com/mjw56/c4498bacf767547ec952

What is happening is that the images are not being loaded on the dev server. I double checked that the images are in fact being copied into the dist folder which they are. Everything else is being loaded fine (css, js). I've tried searching through the documentation to see what I am missing, I've tried using config  options such as `files: 'myfilename.png'` to no luck. I'm not sure if this is a bug or if I am just missing something.

OS: OSX Yosemite
version: 1.3.7
server: http://localhost:3000/

Thanks,
Mike

**Comment by islom2202** [comment]
Can you please explain to me what was the issue? I am facing the same problem.
