### ISSUE TITLE
Multiple files changed = multiple reloads. Global debounce?

### ISSUE THREAD

**Issue by bfred-it** [BrowserSync/browser-sync#329]
My gulp workflow sometimes will yield multiple html files (e.g. I change a Jade partial and 3 dependent files are regenerated) within 1-2 seconds. This cause BS to reload as many times as the number of files, sometimes actually missing the last one (incidentally exactly the one I have open in the browser).

Is there a way to debounce these refreshes? Ideally it should happen either:

*  `_.debounce(refresh, 1000)`, a second after the last file changes, or
* `_.debounce(refresh, 1000, {leading:true})`, as soon as the first file changes **and** a second after the last file changes

**Comment by bfred-it** [comment]
Actually, this has become an issue again since I started using BS from the command-line. I googled for a solution and ended up back on this issue :D

**Comment by shakyShane** [comment]
Small sample project highlighting the issue? :)

**Comment by shinnn** [comment]
@bfred-it Any updates?

**Comment by bfred-it** [comment]
This is a sample project that **simulates** the behavior with gulp while launching BS from CLI:
[DOWNLOAD](http://cl.ly/aMZc)

Keep in mind that I wouldn't be able to solve the issue it like I did in my second post (i.e. within gulp itself)

```sh
gulp # in separate window
browser-sync start --server --files "dist/*.html"  --startPath "dist/a.html"
```

Demo. Notice how the timestamp changes 3 times

![demo](https://cloud.githubusercontent.com/assets/1402241/6804795/d9819fe6-d1fc-11e4-9fb3-e121077c1211.gif)

**Comment by shakyShane** [comment]
@bfred-it - thanks!

File watching is undergoing rewrite currently so we'll make sure this is fixed also :)

**Comment by bfred-it** [comment]
Woot!

**Comment by shakyShane** [comment]
`2.6.0` has reload-delay & reload-debounce available on the CLI

**Comment by CYFERIOUS** [comment]
hey my browsersync is reloading every 43 ms, its impossible to work , some help?
