### ISSUE TITLE
Form syncing inside <template> tag

### ISSUE THREAD

**Issue by trystanj** [BrowserSync/browser-sync#333]
BrowerSync has been amazing so far, but I can't seem to get it to sync between windows when the form/inputs are inside a template tag. This is a key aspect of using Polymer / web components.

Here's a tiny example to show what I mean (the webcomponents.js and polymer.js are typically included slightly differently, but this should be a self-contained working version). Should work in Chrome, Firefox, and IE10+.

```html
<html>
	<head>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.1/webcomponents.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/polymer/0.5.1/polymer.min.js"></script>
	</head>

	<body>

		<span>I work :) </span>
		<input type="text"/>

		<test-element></test-element>

		<!-- Declare custom element -->
		<polymer-element name="test-element" noscript>
			<template>
				<span>I don't :( </span>
				<input type="text"/>
			</template>
		</polymer-element>

	</body>
</html>
```

**Comment by shakyShane** [comment]
Closing this as it's not an actual issue with browser-sync, but rather in the way the events in polymer are not accessible to the window through usual methods.
