### ISSUE TITLE
inject css error

### ISSUE THREAD

**Issue by luxueyan** [BrowserSync/browser-sync#334]
hi, when my css url is   http://x.x.x/??/app/assets.css ,the inject not work , i see in the network! 
It requests url is http://x.x.x/ , the filename is gone! may be due to the '??' in url! how can i resolve it please! 

========== 

i modify the RegExp in browser-sync-client swapFIle function . change /^[^\?]+(?=\?)/ to /^[^\?]+(?=\?[^?])/
 resolve my questions

**Comment by shakyShane** [comment]
Closing as this is 1. difficult to get the correct regex  2. a very rare use-case
