### ISSUE TITLE
Proxy not working with PHP's built-in server

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#335]

**Comment by igregson** [comment]
Thank you :)

I was having this same problem (on Arch Linux) and couldn't for the life of me figure it out... using `127.0.0.1` instead of `localhost` did the trick.

**Comment by shakyShane** [comment]
Also `0.0.0.0` works nicely too :)

**Comment by UndergroundLabs** [comment]
Out of interest what is the reason `localhost` doesn't work? Took me hours to figure out the solution was as simple as changing `localhost` to `127.0.0.1`.

**Comment by MichaelBoselowitz** [comment]
@UndergroundLabs this may be due to this issue mentioned on [PHP's documentation](http://php.net/manual/en/features.commandline.webserver.php#120449). It seems to be accurate, if the target is changed to `[::1]:<port here>` it seems to work.
