### ISSUE TITLE
'browser-sync' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by stephane-r** [BrowserSync/browser-sync#341]
Hi community,

I've install Browser Sync, but when i start server, i've this message on my console :+1: 

```
'browser-sync' is not recognized as an internal or external command
```

Screen :

![node-npm](https://cloud.githubusercontent.com/assets/4712791/5183432/55209202-74af-11e4-8785-24f1208419f9.jpg)

Any idea ? :)

Thank you !

**Comment by tuan-karma** [comment]
@Grafikart :+1: Thank you very much, add PATH worked for me!

**Comment by sound-vaish2** [comment]
> Did you add npm bin directory to your path (I guess you are on windows)
> 
> I had to add **C:\Users\USERNAMEHERE\AppData\Roaming\npm** to mine
> If you check using explorer you should have browser-sync.cmd in this directory
@Grafikart it didn't work for me please suggest other method

**Comment by ShrutiC-git** [comment]
@sound-vaish2 if you already have npm added to your path, try installing browser-sync globally
Run this command: `npm i -g browser-sync`
The 'g' tag here will install the module globally.

**Comment by VenoMKaran13** [comment]
> @sound-vaish2 if you already have npm added to your path, try installing browser-sync globally Run this command: `npm i -g browser-sync` The 'g' tag here will install the module globally.

Not working still. I think I have by mistake changed the user variable for PATH and I cant seem to fix it.
@ShrutiC-git
