### ISSUE TITLE
Is there a way to remove "Connected to Browser Sync" and "Injected: style.css"

### ISSUE THREAD

**Issue by corysimmons** [BrowserSync/browser-sync#344]
It pops up over nav bars and such and is just really in the way. I didn't see an option for removing it and it ducks out of the way before I can find it's selector to `display: none` it.

**Comment by EarthmanWeb** [comment]
@corysimmons  - Rather than hide it completely, I wanted it to show up still so I used this css to put it at the bottom right, out of the way :

```#__bs_notify__ {
  top:95% !important;
  right: 10px !important;
  border-radius: 15px !important;
  height:60px !important;
} ```

**Comment by shakyShane** [comment]
also you can style individual properties now

```
notify: {
    styles: {
        top: 'auto',
        bottom: '0'
    }
}
```

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync-client/blob/master/lib/notify.js#L6-L20

**Comment by EarthmanWeb** [comment]
Ahhh, even better - thanks @shakyShane !

**Comment by Kaffesumpen** [comment]
@EarthmanWeb Thanks for suggestion

**Comment by EarthmanWeb** [comment]
@Kaffesumpen  Thanks, but @shakyShane 's method is less kludgy... 

In case it's not clear, the code he provided would go in your bs-config.js file, replacing the existing:   notify:false

Ref:  https://github.com/BrowserSync/browser-sync/wiki/Working-with-a-Config-File

If you are using browsersync with Gulp, then it would be put  in your gulpfile.js file,  inside your 'browser-sync' task definition, within the config object passed to the  'browserSync.init' function:

Ref :   https://www.browsersync.io/docs/gulp/

---

@shakyShane - I noticed that the notify css option is not yet documented in the options page on the website... Is it still in Beta?  If not, what's the process of having that added to the docs, please?

https://www.browsersync.io/docs/options/#option-notify

**Comment by donaldpipowitch** [comment]
@shakyShane I'd like to use `.notify` only for errors. Is there a way to do that?

**Comment by Kaffesumpen** [comment]
@EarthmanWeb Less "kludgy" I don't know, just another way of doing it. The entire point is that you could access it with CSS and that was something I dident think about.
I for one dident want to add something to the js files as I just wanted to shift the position of the alert when I was working with styling to diffrent locations.

**Comment by deepumbabu** [comment]
Hi,

Can you explain to me wher i have to put this command
notify: false

**Comment by EarthmanWeb** [comment]
@deepumbabu : I tried to explain it as best I could in my comment above -
see:
https://github.com/BrowserSync/browser-sync/issues/344#issuecomment-174148375

@shakyshane - do you maybe have a link to more comprehensive documentation
for using the config arguments?  The page in your docs that you linked to
above, with the option details,  does not really explain how to use the
options in the multiple use cases (ie: grunt, gulp, command line, etc) - I
remember it originally took me quite some time to figure it out myself, and
it seems I'm not the only one who has run into issues with it...

T

**Comment by dengxiaozhen** [comment]
```js
browserSync.init({
        server: "./",
        notify: {
            styles: {
                top: 'auto',
                bottom: '0',
                margin: '0px',
                padding: '5px',
                position: 'fixed',
                fontSize: '10px',
                zIndex: '9999',
                borderRadius: '5px 0px 0px',
                color: 'white',
                textAlign: 'center',
                display: 'block',
                backgroundColor: 'rgba(60, 197, 31, 0.498039)'
            }
        }
    });
```
![browser-sync](https://cloud.githubusercontent.com/assets/8529528/15446063/024136d0-1f45-11e6-9d8c-af52cfc7f7fd.jpg)

**Comment by chanakaDe** [comment]
Have a issue.. Where I can add this style ? "notify: false"   ?
I created the project using aurelia CLI and no css files there.

**Comment by anuraag977** [comment]
I encountered this issue while using angular2 quickstart. Ran using '**npm start**'.

The solution : 
-> create a **bs-config.json** file in your root folder
-> file content 
```
{
	"notify" : false
}
```
-> save
-> npm start and the message should disappear
