### ISSUE TITLE
[Q] How to get css injection working through file watch when links are last-access-modified versioned

### ISSUE THREAD

**Issue by inakianduaga** [BrowserSync/browser-sync#350]
I have a problem trying to get CSS injection through browsersync file watcher working. The problem is due to my backend outputing css/js asset links versioned with a last-modified timestamp, (an apache modrewrite rule references the link to the actual physical file).

So the actual file `styles.css` is referenced in the html as 

```html
<link rel="stylesheet" href="styles.1410902537.css">
```

Thus, when the `styles.css` file changes, browser sync correctly detects the change but cannot match the filename to any link tag. Obviously I can disable versioning on the server side, and I might do that for the development environment if I don't find any other solution. But I was wondering if there would be a browsersync/node only solution that would let me fix the problem without modifying the backend.

Mi idea was to add some middleware that would strip the versioning from the link tag, and then it would work (it does indeed when I disable versioning on the backend). 

- Is it possible to use middleware in BS combined with the proxy option? (doesn't seem so)
- How about the [foxy package](https://github.com/shakyShane/foxy)? Seems like what I need but there aren't any examples showing how it would work.

**Comment by shakyShane** [comment]
Proxy has full support for middlewares now.

https://github.com/BrowserSync/browser-sync/blob/master/examples/proxy.middleware.js

:)

**Comment by inakianduaga** [comment]
swwwwwwwweeeeeeeet! Thanks a bunch

**Comment by shakyShane** [comment]
@inakianduaga  - no problems! Be sure to come back and show us what you end up doing with the proxy middlewares :)
