### ISSUE TITLE
Feature Request: Add logDisconnections option

### ISSUE THREAD

**Issue by mnquintana** [BrowserSync/browser-sync#351]
First, I wanted to seriously thank you for creating such an awesome dev tool.

I was thinking it would be really useful to be able to log when a browser disconnects in addition to when it connects. Maybe this could be additional behavior on the existing `logConnections` option, or maybe it would be better as its own separate `logDisconnections` option; I'm not sure. (It does kinda seem like it would be better off in `logConnections` - it would be a bit bizarre to log a browser disconnecting without first logging it connecting.)

This would let you get a sort of high-level overview of how many and what browsers are connected at a given time.

(I'd be happy to submit a PR for this)

Thanks!

**Comment by shakyShane** [comment]
Closing as we have a more robust solution planned for V3
