### ISSUE TITLE
Option to turn off external url?

### ISSUE THREAD

**Issue by noahgrant** [BrowserSync/browser-sync#352]
Maybe I'm missing something, but I don't see anywhere to _not_ assign the dev server to an external url.  Browsersync has been great so far for a dev environment, but if I'm working in a cafe or an airport, I don't want anyone else on the network to have access to my screen.  Does this functionality already exist?  If not, isn't this something we should be able to turn off?

Thank you!

**Comment by abhisekp** [comment]
@shakyShane how come this is not related to BrowserSync? It listens to public request (if firewall doesn't block it). It could chose not to. That'll limit external access.

IMO, BrowserSync must have a limit to local.

**Comment by slavafomin** [comment]
Hello!

The point made by @noahgrant is absolutely valid. It **IS** a serious security flaw to expose the server with possible sensitive information over all available network interfaces by default. This could lead to data leaks when used in unsecure public networks (cafes, airports, etc).

After looking at source code I've found an undocumented option called `listen`, which could be used to limit the http server binding to a specific network interface, e.g.: `listen: 'localhost'` (this actually works).

**My suggestions would be:**

1). Re-open this important issue.
2). Disable listening for all interfaces by default to prevent possible leaks by naive or unaware developers.
3). Document the `listen` option properly.

If the user actually wants to use the external IP she could set `listen: '0.0.0.0'` in her config, but she would do it willingly and will accept the risks.

**Comment by kieranbarker** [comment]
@slavafomin Thank you, I'm currently working from a coffee shop and the `listen` option worked! ⭐️
