### ISSUE TITLE
v1.7.2 drops the "http:" on proxy base-href, kills pager.js system in development environment

### ISSUE THREAD

**Issue by IsDon** [BrowserSync/browser-sync#364]
I'm using browser-sync from gulp, for a site template using knockout.js / pager.js for SPA.

I recently set up a new template (since 1.7.2) and on installing latest versions in npm, the pager.js History state change started to fail, by taking the site base href and duplicating it. (i.e. http://192.168.1.2:3000/192.168.1.2:3000/people instead of http://192.168.1.2:3000/people on all pager page-href links)

I've narrowed it down to browser-sync v 1.7.2 dropping the http://192.168.1.2:3000/ to just <base href="//192.168.1.2:3000/"> where 1.7.1 and earlier (checked down to 1.6.5) leave it as <base href="http://192.168.1.2:3000/">, and since the issue doesn't present when I install 1.6.5, 1.7.0, or 1.7.1 I believe it must have been a change in this version?

Is there a flag to keep the full proxied site url? Or could this be an unwanted side-effect of this change?

Don
Have a great day

**Comment by shakyShane** [comment]
Fixed in latest versions.

```bash
npm install browser-sync@latest --save-dev
```
