### ISSUE TITLE
XHR requests occasionally stop, browser-sync hangs

### ISSUE THREAD

**Issue by noahgrant** [BrowserSync/browser-sync#367]
I have a single-page app, served locally from browser-sync with several proxies (using [proxy-middleware](https://github.com/andrewrk/connect-proxy)).  (gulp is my task runner.)  Every so often, particularly if you refresh the page while a request is still processing, or click a tab or button to trigger an additional request before the previous one has finished, browser sync hangs—no new **proxied** XHR requests are made.  When you refresh the page, all local requests are served up correctly, ie javascript and css files (and their respective maps), but no XHR requests (all proxied requests for my app are ajax) are even pending in the devtools network tab; it's as though it's ignoring all middleware requests.  At first I though this might be a proxy-middleware bug, but I think if that were the case we'd still see a request begun.  

Once you restart the server, everything works as normal again.  The thing is, we're using browserify with watchify, and every time we have to launch a new gulp dev task, it takes ~20 seconds for the initial browserify build.  A temp solution might be to break the gulp tasks up into different terminals: one for the server/watcher tasks, and one for everything else (including browserify/watchify), so that if this happens, we can restart the server/watcher by themselves.  But ideally we can have them all in one command.

Any insight on why this might be happening?  Is there more info I can offer?  

Thanks!!

**EDIT:**  I guess after awhile (several minutes) of hanging, I do see some 500 errors from the proxied XHR requests, with the message: `(failed) net::ERR_EMPTY_RESPONSE`. Until then, manually typing in $.get() into the console queues the request and leaves it in a pending state.

**Comment by shakyShane** [comment]
Can you `npm install browser-sync@latest` and try again? There've been many fixes to the proxy recently.

**Comment by noahgrant** [comment]
thanks, Shane--I do still see it, but I'm no longer sure that it's a browser-sync issue, since multiple people are reporting it on [this connect-proxy issue](https://github.com/andrewrk/connect-proxy/issues/25).

**Comment by noahgrant** [comment]
@shakyShane, this is just a question: if I want to only proxy certain requests, how can i do that with browsersync?  configuring with both a proxy setup AND a server setup errors out with an invalid config.  The only way I see to do it right now is via middleware, and the connect-proxy plugin is still the only middleware I know available (and still gives us the hanging issue).

**Comment by noahgrant** [comment]
ping @shakyShane, any thoughts on how to proxy only certain paths?
