### ISSUE TITLE
How to watch files different than index.html

### ISSUE THREAD

**Issue by ricardozea** [BrowserSync/browser-sync#37]
Hello,

In my config file I have `files: "*",` since I have several HTML files in addition to `index.html`.

But how do I make Browser Sync watch these other files that have different names? i.e. `about.html`, `contact.html`, etc.

I remember when I was learning (and I still am as you obviously tell) how to get Browser Sync to work I was able to just double click on any of my HTML files, make changes to them and they would then get refreshed... but I honestly forgot how I made that happen.

Any help is greatly appreciated.

Thanks.

**Comment by sabroso** [comment]
**### My project is hosted in a folder called flexbox-css.git and inside contains concepts.html, main.css and although I already use this instruction browser-sync start --server --files "*.html" I still get this message Cannot GET / How do I solve it?**

**Comment by AswanthGit** [comment]
use : browser-sync start --server --directory --files "*" to load all.
