### ISSUE TITLE
Notification popover should have pointer-events: none

### ISSUE THREAD

**Issue by C-Benz** [BrowserSync/browser-sync#371]
When working on a mobile device the notifications are very useful but can get in the way a bit. Adding "pointer-events: none" to the inline css would still allow you to click/tap through it.

**Comment by shakyShane** [comment]
You can modify the inline styles applied by setting 

```js
notify: {
    styles: [
        "color: red",
        "background: orange"
    ]
}
```

**Comment by ikixxx** [comment]
There should be easier way to style the notification. Currently you are setting all styles via `js` and there is no way to overwrite them easily. Maybe there should be a flag to let know browser sync no the style the notification , so we can do it via our own css styles ?
