### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by getlot** [BrowserSync/browser-sync#377]
Thank you Shane for cookies!
I have problem with UTF-8
some characters wrong encoded when i use browser-sync
It appears random, the same text could be right encoded or not.
without proxy everything works.
![screenshot- 19 12 2014 - 18 59 12](https://cloud.githubusercontent.com/assets/9390428/5505310/52133d0c-87b1-11e4-8361-b960ecbd274a.png)

example text:
Проснувши��ь
Проснувшись

**Comment by old9** [comment]
Same here, some CJK characters get malformed.

**Comment by shakyShane** [comment]
could you try on the latest version `npm install browser-sync@latest` and report if this problem still exists

**Comment by getlot** [comment]
I have tried and could not reproduce this bug, thank you!

**Comment by OnkelTem** [comment]
The problem persists on BS 2.4.0:
![Screenshot] (https://sc-cdn.scaleengine.net/i/9e55c0a6d02bed9fab80d1fe2ab67134.png)

**Comment by OnkelTem** [comment]
@shakyShane ping :)

**Comment by shakyShane** [comment]
:+1:

**Comment by shakyShane** [comment]
Can someone here provide a sample HTML document that reproduces this bug please. :)

**Comment by OnkelTem** [comment]
[Here] (http://neganov.ru/tmp/bs-utf8.tar.gz) I've upload two files - copies of the same page, first when accessed via hostname (good.html) and second - when through BS (bad.html)

**Comment by rubjo** [comment]
Any luck on this? 

In OS X I have a virtual machine running Windows and IIS. In my gulpfile.js I use the `proxy` option on BrowserSync init with the local IP of the virtual machine to be able to view my site on `localhost:3000` in OS X. This works nicely (apart from the fact that I will have to update the proxy IP when that changes from time to time).

But: when I view my site on `localhost:3000`, the document encoding changes compared to when I just view the page on `local ip:3000`. Does BS change the encoding in some way? Or does it have something to do with the Apache settings on the host?

**Comment by teohhanhui** [comment]
I'm also facing a UTF-8 encoding bug. The character in question is `🗪`. Oddly, it only happens in very rare/specific combinations (e.g. 11th list item on my 2nd page).

**Comment by exah** [comment]
:+1:

**Comment by ksh5** [comment]
If someone encounters a similar issue (as I just did), I figured BrowserSync somehow doesn't like `<meta charset="utf-8">`. So as a workaround **for development** with BrowserSync proxying you could either use the _old_ `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` instead or omit them altogether (since the HTTP Content-Type Header is used anyway)

**Comment by mockey** [comment]
Just faced the same issue (and thought there is something wrong in my WordPress post).
What worked for me is the self-closing version of the meta-tag:
`<meta charset="UTF-8" />`
(with the space before the "/").

**Comment by glafarge** [comment]
Facing same problem only on Chrome (Firefox and Edge are ok) when using browser-sync proxy.
Direct call to the server behind proxy working properly.

The results are inconsistent as sometimes it displays correctly with or without chars before and sometimes not...

![image](https://user-images.githubusercontent.com/670645/89397303-fc900680-d70f-11ea-88d8-1a1a31353669.png)

@mockey solution resolve the issue, but I really don't understand what happen here.

**Comment by ArtoriasVictrix** [comment]
Same problem 😔
