### ISSUE TITLE
Error while installing browser-sync

### ISSUE THREAD

**Issue by 4meFirst** [BrowserSync/browser-sync#379]
Hi, I'm getting an error when installing browser-sync. I tried clearing the cache, upgrated npm to latest version, reinstalled nodejs, restarted pc and stil nothing works, here is the log file and a screenshot. 
Thank you.
![951c139a2f](https://cloud.githubusercontent.com/assets/7072732/5535342/47e4e62e-8a85-11e4-85fb-cdf0de2283e2.jpg)

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'browser-sync' ]
2 info using npm@2.1.14
3 info using node@v0.10.34
4 silly cache add args [ 'browser-sync', null ]
5 verbose cache add spec browser-sync
6 silly cache add parsed spec { raw: 'browser-sync',
6 silly cache add   scope: null,
6 silly cache add   name: 'browser-sync',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed browser-sync@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'browser-sync', range: '*', hasData: false }
11 silly mapToRegistry name browser-sync
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
15 verbose addNameRange registry:https://registry.npmjs.org/browser-sync not in flight; fetching
16 verbose request uri https://registry.npmjs.org/browser-sync
17 verbose request no auth needed
18 info attempt registry request try #1 at 09:04:10
19 verbose request id dfb11f122d05ce32
20 http request GET https://registry.npmjs.org/browser-sync
21 http 200 https://registry.npmjs.org/browser-sync
22 silly get cb [ 200,
22 silly get   { date: 'Tue, 23 Dec 2014 07:04:07 GMT',
22 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"EPRF4P9Z3VK3BY6AFOMNT66NT"',
22 silly get     'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=60',
22 silly get     'content-length': '199185',
22 silly get     'accept-ranges': 'bytes',
22 silly get     via: '1.1 varnish',
22 silly get     age: '0',
22 silly get     'x-served-by': 'cache-fra1241-FRA',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1419318247.731604,VS0,VE169',
22 silly get     vary: 'Accept',
22 silly get     'keep-alive': 'timeout=10, max=50',
22 silly get     connection: 'Keep-Alive' } ]
23 verbose getCacheStat cache creation not in flight; initializing
24 verbose stack TypeError: uid must be an unsigned int
24 verbose stack     at Object.fs.chown (fs.js:865:11)
24 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\chownr\chownr.js:12:43
24 verbose stack     at Object.oncomplete (fs.js:108:15)
25 verbose cwd C:\Windows\System32
26 error Windows_NT 6.2.9200
27 error argv "node" "C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
28 error node v0.10.34
29 error npm  v2.1.14
30 error uid must be an unsigned int
31 error If you need help, you may report this error at:
31 error     <http://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]

**Comment by shinnn** [comment]
http://blogs.msdn.com/b/matt-harrington/archive/2012/02/23/how-to-fix-node-js-npm-permission-problems.aspx

**Comment by shakyShane** [comment]
Also http://www.browsersync.io/docs/#windows-users

**Comment by raganyaYoung** [comment]
sudo npm install browser-sync -g
