### ISSUE TITLE
Issue using browser-sync and really simple captcha WordPress plugin 

### ISSUE THREAD

**Issue by byronyasgur** [BrowserSync/browser-sync#384]
I think there's an issue with **really simple captcha wordpress**. When I have the plugin activated the url wont change from whatever it starts on. I think this is only in Firefox (34.0.5 is my vn)
I am developing my site in AMPPS and I run BS from command line ( win 7 ) like this --

**browser-sync start --proxy mysitelocal --files "wp-content/themes/mytheme/**/*"**

so that opens up a browser with my site and all works fine as long as I have really simple captcha disabled but otherwise I can't browse anywhere in my site

I also used BS via a gulpfile and got the same result.

**Comment by shakyShane** [comment]
BrowserSync does nothing to interfere with the navigation of any links. 

I'd be happy to look into this if you could provide any error logs, screenshots or screenshots showing this bug.

**Comment by byronyasgur** [comment]
Thanks ... it will be a while before I get back to this but I will put data next time I'm working with browser sync
