### ISSUE TITLE
Is Gaze not used..?

### ISSUE THREAD

**Issue by JakeHedman** [BrowserSync/browser-sync#385]
I was having issues with the watch option "mode" which is documented in the gaze docs, looking through the browser-sync code I found no use of gaze at all, just mentions of it in documentation and comments. A library called "glob-watcher" seems to have replaced gaze. Why is this? Is there a way to make glob-watcher check for native file system events instead of stat polling each files every nth second?

**Comment by spillevink** [comment]
Right, the problem I'm having is caused by glob-watcher using an old gaze version.
