### ISSUE TITLE
Some devices can't connect to external URL

### ISSUE THREAD

**Issue by johjacb** [BrowserSync/browser-sync#390]
Hi, thanks for the amazing tool! Such a huge timesaver. 

One issue I'm having is that some devices connect to the external URL and some won't. Maybe there is something very simple that I am overlooking. I am using it with Gulp. 

Localhost works, as does using the external url on desktop
iphone5/iOS8 connects
iphone4/iOS8 does not
iphone4/iOS6 does not
iPad2/iOS8 connects
Galaxy SII does not
Nexus does not

All connected to the same WiFi and load other sites as expected. Node, npm, gulp, browser sync are all up to date. No special customizations in the gulp file for browser sync.

Any ideas? Thanks for your time.

**Comment by johjacb** [comment]
well, I've narrowed it down to the wifi connection. I have two networks I can connect to, one open and one secure.

I cannot connect via the open network.
I can connect via the secure network. 

I've enabled the tunnel feature for now, so I'm able to test. 

Curious to know if anyone has info about open vs. secure.

**Comment by Grafikart** [comment]
I have a similar problem, do you have an infinite loading on device that fail connecting ?

**Comment by johjacb** [comment]
No - it attempts to load for 30secs to 1 minute or so before stopping.

**Comment by shakyShane** [comment]
Sounds like BrowserSync is not selecting the correct IP.

Use a tool such as https://github.com/shakyshane/dev-ip

and if multiple IP's are reported, try each in turn as the 'host' option http://www.browsersync.io/docs/options/#option-host

**Comment by pierrebonbon** [comment]
Was having the same problem, this worked for me. Thanks!

**Comment by I-Smirnov** [comment]
change port https://browsersync.io/docs/options#option-port

**Comment by greycode-007** [comment]
Hi, my external IP is pointing to  ( http://false:3000 )   thereby making website not accessible on mobile phones etc..  Please kindly help with a solution to remove the false tag.. @shakyShane 
<img width="286" alt="Screenshot (8)" src="https://user-images.githubusercontent.com/66443839/169705847-21efb995-e03f-4337-b0b8-36fd833c7587.png">

**Comment by shakyShane** [comment]
@greycode-007 that looks like a possible regression - can you show me your settings or CLI flags?

**Comment by greycode-007** [comment]
Please see attached.  Forgive me if I do not understand your terminology.   I would really appreciate your help in solving this.. Thanks @shakyShane 

<img width="356" alt="Screenshot (9)" src="https://user-images.githubusercontent.com/66443839/169890042-d497182a-36c5-4f7b-a94e-47ed935cf160.png">
<img width="404" alt="Screenshot (10)" src="https://user-images.githubusercontent.com/66443839/169890079-6f2c120b-2446-4e7f-965d-b54ab56c664a.png">

**Comment by greycode-007** [comment]
Thanks Yuichi, this worked... thank you very much..
