### ISSUE TITLE
Won't start the server - dependency incompatibility

### ISSUE THREAD

**Issue by Ijmir** [BrowserSync/browser-sync#393]
running the command on a simple folder that contains only one index.html file:
```bash
browser-sync start --server --files "**/*.html, **/*.js, **/*.css"
```

returns output:
```bash
[BS] Local URL: http://localhost:false
[BS] External URL: http://10.0.0.5:false
[BS] Serving files from: ./
[BS] Watching files...
```
resolved the problem by getting a specific version of portscanner@0.2.2 in portscanner-plus.
otherwise ~0.2.2 gets the 0.2.3 that causes the bug. (new version using socket.destroy instead of socket.end at some place)

node 0.10.35
OS X Yosemite 10.10.1
browser-sync 1.9.0

**Comment by shakyShane** [comment]
Hi, thanks for the report - I have tried, but cannot reproduce this locally so far.

**Comment by shakyShane** [comment]
Please update to 2.6.0 - if the problem persists I can reopen the ticket

**Comment by mrself** [comment]
I have the same error. Instead of port it shows 'false'. When I start debug mode - no errors. All work fine. But it shows wrong link -  Local: http://localhost:false
