### ISSUE TITLE
Wrong external url when multiple network connections

### ISSUE THREAD

**Issue by milanvanschaik** [BrowserSync/browser-sync#395]
When my Mac is connected via ethernet and Airport (WiFi) at the same time, the browserSync server is listening to the ethernet one, but the external address what browserSync is telling me is the IP address of the Airport connection. I'm using the latest version of browserSync at Gulp.

Am I doing something wrong or is this a issue in browserSync?

**Comment by pspaulding** [comment]
Seeing same thing on Windows 7 pro, brand new laptop, except I am plugged into ethernet and am not logged into WiFi.  Tried showing new 2.0 version of browser-sync to a co-worker, and it reported external URL as being http://192.168.1.68:3000/dev, but the actual URL was http://192.168.254.146:3000/dev.  Everything worked externally except for the remote debugging using weinre.

**Comment by shakyShane** [comment]
@milanvanschaik - you're not doing anything wrong. Sometimes, depending on your network, your OS will report multiple external IP addresses. If this happens, currently BrowserSync just picks the first one and hopes for the best.

If you know which one works, you can provide it as an option. http://www.browsersync.io/docs/options/#option-host

**Comment by shakyShane** [comment]
http://localhost:3000/docs/#external-url
