### ISSUE TITLE
angular: sync across browsers doesn't work.

### ISSUE THREAD

**Issue by darekzak** [BrowserSync/browser-sync#396]
I made very simple project to ilustrate this problem. Here is the repo: 
https://bitbucket.org/zakdariusz/browsersync_angular/

The problem appears when field  'this.currentElement' in 'some.factory.js' file is dynamicly changed. I've no idea why.

**Comment by shinnn** [comment]
I ran the app, opened it on Chrome and Firefox, and edited the value of `this.currentElement`, but I couldn't find any problems.

@darekzak Could you elaborate on *sync across browsers doesn't work*?

**Comment by shinnn** [comment]
@darekzak If you still have any issues, feel free to comment the details about "sync across browsers doesn't work".
