### ISSUE TITLE
Https mode for proxy

### ISSUE THREAD

**Issue by banjankri** [BrowserSync/browser-sync#399]
Hi,
I would like to kindly request a feature to be able to proxy pages served on https. I am working on number of projects where I could highly benefit from browser sync goodies, however lack of support for proxying https served pages holds me back.

Thanks

**Comment by shakyShane** [comment]
This is coming in the very near future :)

**Comment by albertfdp** [comment]
@shakyShane is it on development in any branch? Do you have a plan on releasing it soon? Thanks!

**Comment by loktar00** [comment]
:+1: Can't wait for this feature.

**Comment by voor** [comment]
:+1:  also would love this functionality.

**Comment by shakyShane** [comment]
`npm install browser-sync@latest`

:)

**Comment by loktar00** [comment]
This is kickass thanks! :metal:

**Comment by shakyShane** [comment]
You're welcome! Also, as a bonus for everyone's patience - did you know you can now do crazy middleware stuff with the proxy now too?

https://github.com/BrowserSync/browser-sync/blob/master/examples/proxy.middleware.js

**Comment by voor** [comment]
https proxy is working great, I did the following to enable it:
```javascript
{
    proxy: "https://localhost:8443",
    // Enable HTTPS for static file server
    // https: true
  }
````
If I leave off the https from proxy and uncomment https: true then there is an error.
