### ISSUE TITLE
HTML won't reload on browserSync.reload in gulp - Windows only

### ISSUE THREAD

**Issue by jremydeaton** [BrowserSync/browser-sync#407]
Keep getting "Cannot GET /" on browserSync.reload but only on Windows machines.

I have configured my gulpfile.js as sugested [Here](http://www.browsersync.io/docs/gulp/#gulp-manual-reload) "Manual Reload"; As well as the configuration [Here](https://github.com/gulpjs/gulp/blob/master/docs/recipes/server-with-livereload-and-css-injection.md) from the Gulp recipes section. Most current configuration is exactly like the former using the task "bs-reload".

Both configurations run fine on OSX and linux, but not in windows. Anytime, in Windows, I update any html page and save, I get the error mentioned above. This only happens with html files. SCSS files reload the browser and updates as expected. I haven't tried any js files as I am still trying to fix the html reload.

NOTE: All works fine across all OSs when I have a vhost and use proxy instead of baseDir. However this is not ideal, as I will not always have this option.

**Comment by shakyShane** [comment]
Can you show me your exact `gulpfile.js` please :)

**Comment by jremydeaton** [comment]
I have since stopped using browsersync with gulp. Hitting refresh is a tad bit easier than trying to configure a task runner to do so in multiple platforms. But here was my code:
```javascript
var gulp = require('gulp');
var sass = require('gulp-ruby-sass');
var browserSync = require('browser-sync');
var reload = browserSync.reload;

// Start the server
gulp.task('browser-sync', function() {
    browserSync({
        server: {
            baseDir: "./app/"
        }
    });
});

// Compile SASS & auto-inject into browsers
gulp.task('sass', function () {
    return gulp.src('./app/scss/styles.scss')
        .pipe(gulp.dest('css'))
        .pipe(browserSync.reload({stream:true}));
});

// Reload all Browsers
gulp.task('bs-reload', function () {
    browserSync.reload();
});

// Watch scss AND html files, doing different things with each.
gulp.task('default', ['browser-sync'], function () {
    gulp.watch("**/*.scss", ['sass']);
    gulp.watch("**/*.html", ['bs-reload']);
});
```
