### ISSUE TITLE
Support for node-webkit

### ISSUE THREAD

**Issue by chrisronline** [BrowserSync/browser-sync#408]
Hi,

I'm trying to get auto refresh working in my [node-webkit](https://github.com/nwjs/nw.js) app, but it loads the files off "file://" instead of a domain (which is necessary). Because of this, I'm not sure if I can configure an instance of browser sync to inject updated CSS into the node-webkit app - I looked through and tried some of the options without any luck.

Any suggestions?

Thanks,
Chris

**Comment by basicserge** [comment]
Hi! I was also searching for a solution and found [this](https://github.com/nwjs/nw.js/issues/2710#issuecomment-70888870). That works fine for me.

**Comment by shakyShane** [comment]
@chrisronline please try the solution above.

**Comment by chrisronline** [comment]
Thanks guys!
