### ISSUE TITLE
How to have multiple catch all routing with browser-sync

### ISSUE THREAD

**Issue by kosz** [BrowserSync/browser-sync#409]
So I'm trying to adopt browser-sync, but the first issue I ran into was that, there was no server side routing, so if i would visit my start page localhost:3000 then get redirected to some other page localhost:3000/somePage, once the live reload would try to reload localhost:3000/somePage, I would get an error that somePage does not exist ( because index.html needed to be loaded to setup the angular routing which would create the /somePage html5 route ). 

I then came across this issue : https://github.com/shakyShane/browser-sync/issues/204, where everybody seemed to be happy with the suggested workaround of using 'connect-history-api-fallback'. 

The problem I'm having however, is that my app, while it is kind of a SPA app, it does have multiple pages. As a reasonable example, let's say that I have some public app that gathers anonymous information from people, then I'd have a second page(spa), called /admin, which would allow me to view the gathered info ... I don't think one could argue that the admin code should be bundled up in the same page as the public app, nor that these should be two separate applications, when in fact they do share a lot of the code base.

----

In this example I have two pages. 

Once I try to have two index.html's with 'connect-history-api-fallback' everything goes hay wire. 'connect-history-api-fallback' forces any page call to go to the root index html / making the /admin/index.html impossible to reach. 

I have even tried using two browser sync instances, one for the root / and one for the /admin route ... But when using two browser sync instances ( on different ports ), the ''connect-history-api-fallback'' does not work for the second instance >:

----

Is my scenario really bad practice, or is this a reasonable pitfall of browser-sync, not being able to work with more than one single index.html page ? 

Are there any viable work-arounds for this situation ?

**Comment by kosz** [comment]
update here 'connect-history-api-fallback' does work for the second instance, but it fails when urls contain colons. 

I'm trying to serve ngdocs as well as my app page basically. A link like this from the page generated by gulp-ngdocs : 

```http://localhost:4000/api/my-module.controller:exampleController```

breaks 'connect-history-api-fallback', trying to reload the page on that url will make browser-sync say it cannot find that route.

**Comment by shakyShane** [comment]
This all makes complete sense.

However BrowserSync is not designed to be a server-for-all-apps type of project. We offer a basic connect setup, allow you to use middleware & give you access to the `app` object.

For your example, it may be simpler to setup something like a basic express app and then use the proxy option that we provide. 

How does that sound?

**Comment by kosz** [comment]
Thanks for your input. I understand that this is out of scope for BrowserSync, looks like most light weight/live reload development servers have an issue with this. I'll have a look into your suggestion. Thanks for this great project.
