### ISSUE TITLE
Ajax requests failing

### ISSUE THREAD

**Issue by iclanzan** [BrowserSync/browser-sync#41]
I am using _grunt-browser-sync_ and versions newer than _browser-sync@0.4.0_ cause Chrome to refresh as soon as the page gets loaded—to no end.

I am not sure if other browsers behave the same. Will try to do some tests when I have the time.

**Comment by anthonybrown** [comment]
What is the status of this, I'm having issues with loading html from `$.load("../some/file");`

**Comment by anthonybrown** [comment]
I am having some issues with browser-sync.
Just making some simple `$.load('../frag/some.html');
seems like `browser-sync` isn't responding well in Firefox,  the fragments show up in Chrome but
my files are not being refreshed when I make a change in any file.
using this:
`browser-sync start --server --files "index.html,js/*/*.js,js/*/*/*.js,js/*.js,css/*.css"`
