### ISSUE TITLE
Inject middleware generated CSS files instead of reloading

### ISSUE THREAD

**Issue by zanona** [BrowserSync/browser-sync#411]
I have the following middleware that accepts requests to `.less` files and compiles those, serving these file as CSS. However, when the response is sent, the browser reloads instead of injecting the changes.

Since this would be a pure CSS file only with a different extension (since it has already been compiled to CSS) how do I make Browser-sync inject the new styles as per with `.css` files instead of reloading the page?

```html
<link rel=stylesheet href=main.less>
```

```js
...
files: '*.less',
function (req, res, next) {
    if (req.url.match(/\.less$/)) {
        require('child_process').exec('lessc ' + req.url, function (e, o) {
            res.setHeader('Content-Type', 'text/css');
            return res.end(o); //Reloads the browser instead of injecting changes
        });
    } else {
        next();
    }
}

```

**Comment by shakyShane** [comment]
Ahh nice - could you set-up a small example repo where I can test/implement this - I think it would be a cool feature.

**Comment by zanona** [comment]
There you go @shakyShane https://github.com/zanona/bs-mw-inject

**Comment by shakyShane** [comment]
:star:

**Comment by shakyShane** [comment]
Got this working locally and wow, what an awesome workflow...

**Comment by shakyShane** [comment]
it'll end up being 

```js
/*global module, require*/

var url = require("url");

function less(src) {
    var f = require('fs').readFileSync('src/' + src).toString();
    return require('less').render(f);
}

module.exports = {
    files: ['src/*.less'],
    injectFileTypes: ["less"],
    tagNames: {
        "less": "link"
    },
    server: {
        baseDir: 'src',
        middleware: function (req, res, next) {
            var parsed = require("url").parse(req.url);
            if (parsed.pathname.match(/\.less$/)) {
                less(parsed.pathname).then(function (o) {
                    res.setHeader('Content-Type', 'text/css');
                    res.end(o.css);
                });
            } else { next(); }
        }
    }
};

```

**Comment by shakyShane** [comment]
^ you can't just do a match on the url because of timestamps etc

**Comment by zanona** [comment]
wow indeed! just tested on 2.1.6 and it works brilliantly!
Mind the possibilities, no need to flood dev environment by building production files anymore.
Thanks a lot @shakyShane

**Comment by shakyShane** [comment]
Haha! wow - no problem :)

We're creating a 'recipes` section soon and this workflow will be first on the list :)

**Comment by shakyShane** [comment]
^ this will even work with the proxy too

**Comment by shakyShane** [comment]
> It might also be worth it to add .styl as well for the folks using stylus.

yeah - maybe, although any other can be added with 

```js
tagNames: {
    "styl": "link"
}
```

**Comment by zanona** [comment]
Sounds good enough to me :+1:

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/recipes/tree/master/recipes/middleware.css.injection

**Comment by zanona** [comment]
:+1: very nice man! already using like crazy this new feature. And oh boy, it's so much better than less.js in the browser. Thanks again.

**Comment by shakyShane** [comment]
Thanks to you for bringing it to my attention - feel free to contribute any workflows you have to that repo :)

**Comment by zanona** [comment]
hey @shakyShane, just revisiting this functionality after having stumbled upon an issue:

**main.less**
```less
@import 'secondary.less';
body { background: red; }
```

**secondary.less**
```less
body { font-size: 1.2em; color: green; }
```

Everything work as expected when saving **main.less** file. However, unfortunately, when saving **secondary.less**, which is an imported file, Browser Sync won't auto refresh the stylesheet.

I can see this happening due the fact that the request is not yet mapped for **secondary.less** but only for **main.less**, so saving it wouldn't trigger anything?

Is there any way you can think of to allow such imported stylesheets to be updated accordingly when saved?

Thanks in advance.

**Comment by zanona** [comment]
hey @shakyShane, perhaps it would be best if I open a new ticket on this aspect? Please let me know

**Comment by zanona** [comment]
just in case someone is looking for this, I sort of, found a solution.

from my **bs-config.js** file
```js
function reloadLess() {
    exec('browser-sync reload --files="*.less"');
}

module.exports = {
    files: [
        'src/*.html',
        'src/scripts/*.js',
        {
            match: ['src/styles/*.less'],
            fn: function (event, file) {
                if (event !== 'change') { return; }
                reloadLess();
            }
        }
    ],
    injectFileTypes: ['less'],
    ...
};
```

The only thing that would be nice here, since I use the global installation of browser-sync, is that from **bs-config.js** I haven't find any way to reference to the running browser-sync instance anywhere so that from the `reloadLess` method I could simply call `bs.reload();`

It would be nice that we could have a way to retrieve this reference somewhere.
I know that from within the `fn` method from the `files` property, the instance of the fileWatcher library is returned when using `this`.
So perhaps that could be a nice place to also provide browser-sync instance so we don't need to use the command line interface to reload the files.

I hope this can be helpful to someone.

**Comment by shakyShane** [comment]
@zanona - agreed, you should be able to call methods on your instance from within the watcher callback... will certainly add that.

**Comment by zanona** [comment]
Thanks buddy

**Comment by shakyShane** [comment]
@zanona browser-sync@2.7.3 will give you what you want, as seen here https://github.com/BrowserSync/browser-sync/issues/631#issue-78959607

**Comment by zanona** [comment]
Beautiful! Updating…now :+1:

**Comment by lunelson** [comment]
I'm trying to accomplish something similar to this, proxying Harp.js; 

but Harp does all the pre-processing transparently, so I want BS to watch `['**/*.scss', '**/*.jade']` files, while injecting the changed `.css` and `.html`. Can this be done?

My attempt is based on the code here, and in the BS API and Options pages, and [this thread](https://github.com/BrowserSync/browser-sync/issues/631). This code deals first only with `.scss` files.

```js
var bs = require('browser-sync').create();

bs.init({
    proxy: "localhost:9000",
    files: [
        './**/*.jade',
        './**/*.js',
        {
            options: { ignoreInitial: true },
            match: './**/*.scss',
            fn: function (event, file) {
                if (event === 'change') {
                    bs.stream();
                }
            }
        }
    ]
});
```

is this at all on the right track... ?

**Comment by zanona** [comment]
hey @lunelson, have you checked the recipe for middleware CSS injection already?

https://github.com/Browsersync/recipes/tree/master/recipes/middleware.css.injection

Perhaps that can help you further. — I can see the `injectFileTypes` attribute is missing from your code.

All the best

**Comment by lunelson** [comment]
Thanks for that tip @zanona. I seem to have figured it out. `injectFileTypes` doesn't seem to be necessary—or maybe wouldn't have worked anyway—(I think) because from the browser's point of view it's accessing `css` files not `scss`. In other words the whole middleware thing of pre-processing and modifying the request is being handled by Harp. It seems that assuming Harp is running, it just comes down to telling BS what and when to reload/inject. 

The following is working for me, to inject `html` changes from `jade` files, and inject `css` changes from `scss` files. `js` changes cause a full reload of course.

on the command line, in the project dir
```sh
# in one tab
harp server
# in a second tab
node bs.js
```
...and this is the content of `bs.js`. NB this relies on knowing the specific filenames of the `css` files your pages are referencing. You can also just pass a glob `*.css` but the injection is then slower
```js
var bs = require('browser-sync').create();
var bs_html = require('bs-html-injector');

bs.use(bs_html, { files: './**/*.jade'});
bs.init({
  proxy: "localhost:9000",
  files: [
    './**/*.js',
    {
      match: './**/*.scss',
      fn: function (event) {
        if (event === 'change') {
          bs.reload(['style.css', '/global.css']);
        }
      }
    }
  ]
});
```
