### ISSUE TITLE
Page not refreshing on file changes

### ISSUE THREAD

**Issue by isaacalves** [BrowserSync/browser-sync#413]
When using BrowserSync with gulp-connect-php, it sometimes (most of the time) fail to refresh the page, but sometimes it does, I haven't been able to figure out why. Sometimes it works at the beginning but then stops and I have to refresh it manually. That happens with js, sass or php files. I've filed an issue here:

https://github.com/micahblu/gulp-connect-php/issues/2

**Comment by shakyShane** [comment]
Can you set up a small sample project that highlights this issue (reduced test-case) and we will look into it.

**Comment by shinnn** [comment]
@isaacalves 

I read your code in [this issue comment](https://github.com/micahblu/gulp-connect-php/issues/2#issuecomment-70697477).

It seems that you mistake the usage of `baseDir` option. `baseDir` option does nothing when you use `proxy`.
