### ISSUE TITLE
Redirecting ajax requests to external urls

### ISSUE THREAD

**Issue by cliren** [BrowserSync/browser-sync#414]
The app runs on 3000 port and was able to point the ajax requests to other ports on localhost fine. But when I want to point a CORS request to an external url, I get a connection refused error. There is a great need for this if there is a way to achieve it. 

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

```js
var proxyMiddleware = function(req, res, next) {
  var httpProxy = require('http-proxy');
  //target: "http://localhost:8000/" or some other port works fine.
  var proxy = httpProxy.createProxyServer({
    target: 'http://mycompany.qa.com/' 
  });

  if (req.url.indexOf('api') != -1) {
    proxy.web(req, res);
  } else {
    next();
  }
};

browserSync: {
    server: {
      baseDir: [dest],
        middleware = proxyMiddleware
    },
    files: [
      dest + '/**'
    ]
  }
```

**Comment by shakyShane** [comment]
Would there be any way you could set up a sample project that illustrates this problem?

**Comment by shinnn** [comment]
@cliren https://github.com/BrowserSync/browser-sync/issues/414#issuecomment-73764432

> Would there be any way you could set up a sample project that illustrates this problem?

**Comment by shinnn** [comment]
@cliren Please feel free to comment about details if you still running into this issue.
