### ISSUE TITLE
Proxy not opening specified folder

### ISSUE THREAD

**Issue by Mellivora** [BrowserSync/browser-sync#420]
Hello,

thanks very much for your work on this plugin, it's great.

I have just installed v2.0.0-rc4 and the proxy is only opening the main localhost folder rather than the directory I specified in my gulp task.

It is only going to http://localhost:3000 rather than http://localhost/susy-test/dist/

I installed v1.9.1 and it works fine. My gulp task is below and I am on windows 7.

```JavaScript
gulp.task('browser-sync', function() {
	plugins.browserSync({
		proxy: 'localhost:3000/susy-test/dist/'
	});
});
```

**Comment by shakyShane** [comment]
Thanks for reporting. :)

**Comment by Mellivora** [comment]
No problem

**Comment by Mellivora** [comment]
Sorry, just noticed a mistake it is meant to be going to http://localhost:3000/susy-test/dist/

**Comment by shakyShane** [comment]
updated

**Comment by shakyShane** [comment]
`npm install browser-sync@2.0.0-rc5 --save-dev`

:)

**Comment by Mellivora** [comment]
That's great, many thanks @shakyShane, working fine for me.
