### ISSUE TITLE
Cannot provide coverage reports

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#422]
@shinn - no idea why, but using the current scripts I can no longer generate coverage reports. Any idea?

**Comment by shakyShane** [comment]
friendly ping, @shinnn  :)

**Comment by shinnn** [comment]
@shakyShane I've tried to find the cause, but I'm still not able to.

**Comment by shakyShane** [comment]
Ahh ok, no problem - I believe it may be something to do with moving the repo to the org...

**Comment by shinnn** [comment]
Yay, I found the cause.

After I removed `process.removeAllListeners()` from [this line](https://github.com/BrowserSync/browser-sync/blob/179da6bb58d6549c11d08bc8a058623a228143ff/index.js#L284), `npm run cover` command provides the coverage.

@shakyShane Is there any reason why browser-sync calls `process.removeAllListeners`?

**Comment by shakyShane** [comment]
Hi @shinnn - I'll look into that, I actually cannot remember right now but I have a feeling it was something to do with the test suit..

**Comment by shakyShane** [comment]
I think it was because of this https://github.com/BrowserSync/browser-sync/blob/179da6bb58d6549c11d08bc8a058623a228143ff/lib/public/exit.js#L17

**Comment by shinnn** [comment]
So, this is good enough.

```js
process.removeAllListeners("SIGINT");
```

**Comment by shakyShane** [comment]
@shinnn - Excellent!
