### ISSUE TITLE
Scroll sync doesn't work if no body

### ISSUE THREAD

**Issue by LeG3nDz** [BrowserSync/browser-sync#423]
Hi community,

Do you know if can i use the "scoll sync" (with --proxy url) with another scrollable container ? Let me explain :)

On my projet, i've big container for scroll my page for technical reasons. I guess in the browserSync script , only the body is listening. Do you know if I can change it ?

Thank you :)

**Comment by shakyShane** [comment]
Have a look at this

https://github.com/BrowserSync/browser-sync/issues/273#issuecomment-57427711

**Comment by LeG3nDz** [comment]
Hi @shakyShane :)

Thank you for the link. I've just one question : where i add this code ? In my app.js ?

**Comment by shakyShane** [comment]
Are you running BrowserSync from the command line?

**Comment by LeG3nDz** [comment]
Yep :

browser-sync start --proxy url.lan

**Comment by shakyShane** [comment]
Create two files, one called `bs.js` and put this in it

```
var browserSync = require("browser-sync");

browserSync.use({
    plugin: function (opts, bs) {},
    hooks: {
        "client:events": function () {
            return ["div:scroll"]
        },
        "client:js": require("fs").readFileSync("./example-plugin.js")
    }
});

browserSync({
    proxy: "url.lan"
});

```

Then create another in the same directory called `plugin.js` and put this: 

```js
/**
 * Plugin example.
 */
(function ($window, $document, bs) {

    var $elem  = $document.querySelector(".scroller");
    var socket = bs.socket;

    // Listen to the scroll event on your element
    $elem.addEventListener("scroll", function(evt) {
        // Emit the event
        socket.emit("div:scroll", evt.srcElement.scrollTop);
    });

    // Listen for the event in other browsers
    socket.on("div:scroll", function (scrollTop) {
        // Set the element scroll position to match
        $elem.scrollTop = scrollTop;
    });

})(window, document, ___browserSync___);
```
now, on the command line, just run

```bash
node bs.js
```

**Comment by shakyShane** [comment]
Make sure this matches the container you want to scroll

`var $elem  = $document.querySelector(".scroller");`

**Comment by LeG3nDz** [comment]
Work very fine, thank you !

Just a detail, the scroll from the PC does't work, however, on iPad or smartphone, the syncro is present.

Thank again :)

**Comment by shakyShane** [comment]
No problem - I am thinking of offering an option for select the default scroll container, as this issue has come up before.

**Comment by ocyedwin** [comment]
This no longer works as browserSync.use(...) API no longer exists? What is the workaround?
