### ISSUE TITLE
Fails with miltiple comma-separated globs

### ISSUE THREAD

**Issue by ferhtgoldaraz** [BrowserSync/browser-sync#425]
```bash
browser-sync start --proxy "somevirtualhost:8070" --files '**/.php, **/*.css, **/*.js'
```
Fails to watch files. It seems no files are resoved, so it succeeds watching no file.  Also, I was forced to create the vitualhost, url-path after port number was being ignored.

This worked:
```bash
browser-sync start --proxy "somevirtualhost:8070" --files '**/*.@(js|php|css)'
```

Any other try with the comma separation failed. Tried without commas, failed too.

**Comment by shakyShane** [comment]
```npm install browser-sync@2.0.0-rc7```

Thanks for reporting :)
