### ISSUE TITLE
Multiple patterns from command line doesn't work

### ISSUE THREAD

**Issue by levani** [BrowserSync/browser-sync#426]
I'm unable to apply multiple patterns from command line. I use the following command:

`browser-sync start --proxy "localhost/web" --files "dist/styles/*.css, *.html"`

and nothing happens when I change css or html files, but if I apply only one pattern (only css or only html) both of them works fine.

Any ideas?

**Comment by shakyShane** [comment]
```npm install browser-sync@2.0.0-rc7```

Thanks for reporting :)
