### ISSUE TITLE
https option is member of "server" option, not standalone

### ISSUE THREAD

**Issue by yourcelf** [BrowserSync/browser-sync#427]
The docs (in the [example here](https://github.com/BrowserSync/browser-sync/blob/9087e547cb193edd2ebebdb17ddfbd5c32ee7626/examples/server.secure.js), and also in the main options documentation) show https as a standalone option, e.g.:

```js
browserSync({
    server: {baseDir: 'app/'},
    https: true
});
```

However, this doesn't work.  ``https`` is only read as a member of the ``server`` option, e.g.

```js
browserSync({
    server: {baseDir: 'app/', https: true}
})
```

The only [spec testing this](https://github.com/BrowserSync/browser-sync/blob/9087e547cb193edd2ebebdb17ddfbd5c32ee7626/test/specs/utils/utils.updateOptions.js) puts the ``https`` option within the ``server`` option.

Perhaps of note: it seems that the method ``getScheme`` in ``lib/utils.js``, which appears to read ``https`` as a standalone option, is not called on server startup.

Running `2.0.0-rc7`.

**Comment by shakyShane** [comment]
Thanks for reporting.

There's been some confusion here - but rest assured the correct way in v2.0 > is 

```js
browserSync({
    server: {baseDir: 'app/'},
    https: true
});
```

**Comment by shakyShane** [comment]
```npm install browser-sync@2.0.0-rc8```
