### ISSUE TITLE
undefined is not a function / Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by RayPS** [BrowserSync/browser-sync#428]
![qq20150206-2](https://cloud.githubusercontent.com/assets/1941540/6072104/7038f9c8-add8-11e4-9c7a-44437c5fff84.png)

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report
