### ISSUE TITLE
Use browser-sync on one port for multiple projects

### ISSUE THREAD

**Issue by akilham** [BrowserSync/browser-sync#431]
I am trying to set up a development server for my work. I want to be able to work on multiple projects at a time, but I am leaning away from using something like Vagrant - I would rather have all projects on the one machine.

I'm using gulp for my projects, but the problem I'm having is needing to use a different port for browser-sync for each project. This is a problem because I start getting confused about which project belongs to which port so I can't just view the project in my browser quickly.

I was hoping that it might be possible to run browser-sync as a daemon on the server, and then have each gulp file just use the daemon process? That way I could just use one port. Or is there any other option for me?

Also, I installed browser-sync  globally but when I run it from the command line with this (and any options that I pass in):

`browser-sync start`

It exits after a second without any output.

Running it with "--logLevel debug" shows this:

`[BS] [debug] -> Starting Step: Finding an empty port`

It seems that something is going wrong, but I'm not getting any errors. Any ideas?

**Comment by shakyShane** [comment]
Currently you would not be able to use the same port for multiple projects - doing so would mean sharing the server resources & web sockets and would have the potential to slow everything down dramatically.

RE: the bug report - can you try `2.0.1` and let me know if that fixes the problem.

**Comment by akilham** [comment]
No worries, thanks for the info.

Here's what I get with 2.0.1:

`browser-sync start --logLev`
`[BS] [debug] -> Starting Step: Finding an empty port`
`true`

**Comment by shakyShane** [comment]
can you try setting the port explicitly 

```js
port: 3000
``` 

and let me know if that works?
