### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by KyleGobel** [BrowserSync/browser-sync#432]
Hey guys,

Not sure if someone already mentioned in another issue or anything but...

If using Windows without having vs2010 tools installed (I imagine most windows devs would be using 2013 by now) node-gyp will have some trouble, to get around the issues you can install like

```
npm install -g browser-sync --msvs_version=2013
```

Would this be worth throwing in the docs or something?

Idk, maybe this is known to most windows users, but I have had this same problem with so many node packages it's almost amazing I forget about it everytime and have to google search for 20 min.

**Comment by marocas** [comment]
````
'use strict';

module.exports = function(grunt) {

  var browserSync = require("browser-sync");

  var globalConfig = {
  grunt.initConfig({

    cfg: globalConfig,
    pkg: grunt.file.readJSON('package.json'),

/* all your tasks */

  });

  // Still watch files as you did before.
  grunt.registerTask("bs-init", function () {
    var done = this.async();
    browserSync({
      watchTask: true,
      open: true,
      // Show me additional info about the process
      logLevel: "debug",
      // Multiple base directories
      server: {
          baseDir: ['html','html/pages'],
      },
      // multiple globs
      files: ["html/css/**/*.css", "html/pages/**/*.html", "html/scripts/**/*.js"]
    }, 
     function (err, bs) {
      done();
    });
  });

 // Launch Browser-sync & watch files
  grunt.registerTask('server', ['bs-init', 'watch']);
};
````

Hi, i dont know if this helps you, but i installed browser-sync to my project and not globaly, and made it work perfectly with this config. Hope this helps you in any matter.

**Comment by shakyShane** [comment]
Added a note here http://www.browsersync.io/docs/#windows-users

If you think the tips can be improved, please feel free to contribute https://github.com/BrowserSync/browsersync.github.io

**Comment by karland** [comment]
I think it should read: 

```
# Windows users

Having trouble installing BrowserSync on Windows? The most common reason for  `npm` to throw
errors when compiling BrowserSync is that some of the dependencies
(e.g. [node-gyp](https://github.com/TooTallNate/node-gyp) need Visual C++ runtime libraries. 

The way to resolve this is to install [Visual Studio](http://www.visualstudio.com/). 
At the time of this writing (Feb 2015) the compilation works fine with 
[Visual Studio 2013 Update 4](http://www.visualstudio.com/en-us/news/vs2013-update4-rc-vs.aspx). 
You can then tell `npm` which version of Visual Studio you are using by the following command:

    npm install -g browser-sync --msvs_version=2013

After installation `npm` should not throw errors any longer, but only issue warnings. 
As far as we can tell, they do not impact BrowserSync.
```

**Comment by shakyShane** [comment]
Done, thanks :)

**Comment by aolin480** [comment]
So if we're using the grunt version of browser-sync, do we still need to run npm install -g browser-sync --msvs_version=2013 and THEN npm install grunt-browser-sync --save-dev? I am having so much trouble now with grunt-browser-sync, and it's never been this bad to install it with my grunt configuration. I had to resort back to 1.9.1
