### ISSUE TITLE
browser-sync-client js not found for Gulp

### ISSUE THREAD

**Issue by dansecrest** [BrowserSync/browser-sync#433]
I am unable to get BrowserSync to refresh the browser using Gulp because the browser is not finding the client js. I do not have this issue when using the Grunt plugin.

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/browser-sync/browser-sync-client.1.9.1.js

browser-sync --version results in 2.0.0-rc9
node node_modules/browser-sync/bin/browser-sync --version results in 2.0.0-rc9

Any thoughts as to the issue? Thanks.

**Comment by dansecrest** [comment]
I had noticed the version difference in my last post between what I had installed (2.0.0-rc9) and the file the browser was reporting not found (1.9.1). When I run BrowserSync with Grunt or Gulp, it adds /browser-sync/browser-sync-client.1.9.1.js to the html page. Grunt works fine but Gulp results in the file not found.

Here may be a clue. If I run BrowserSync with Grunt and then start Gulp, both work fine. Grunt uses /browser-sync/browser-sync-client.1.9.1.js and in this scenario Gulp uses /browser-sync/browser-sync-client.2.0.0-rc9.js. If I stop both and start Gulp again by itself, then the file not found problem returns because it is again looking for 1.9.1.

I am going to try using 1.9.1. Any thoughts beyond this?

**Comment by shakyShane** [comment]
Sounds like you have conflicting versions installed and the browser is caching the wrong ones.

update both with this for gulp

```bash
npm install browser-sync@latest --save-dev
```

and this for grunt.

```bash
npm install grunt-browser-sync@latest --save-dev
```
Then clear the browser caches and try again.
