### ISSUE TITLE
Site links not clicking through

### ISSUE THREAD

**Issue by aolin480** [BrowserSync/browser-sync#435]
This only happens in firefox, but I am running browsersync and a watch task only. I run the Grunt command, and the browser loads fine. The website pulls up at http://localhost:9999, but when I try to click on a menu item to go to another page, it just reloads the home page. I have to CTRL-CLICK the menu item to actually go to the page I am wanting to go to. In Chrome, everything works as expected. Is there anything in my browsersync task that could be causing this? This happens on multiple projects as well. I tried everything from restarting the computer, restarting grunt, and restarting my ampps server, but nothing fixes it. Below is my browsersync task:

```js
browserSync: {
    default_options: {	    
	    bsFiles: {
	      src: [
	        "library/css/*.css",
	        "*.php"	        
	      ]
	    },        	    
	    options: {			
			watchTask: true,				
			proxy: "local.mydomain.com",
			port: 9999	
			
	    }
    }
},

```

Thanks in adavance!

**Comment by shakyShane** [comment]
Try making a reduced test-case with only the following HTML

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<a href="http://google.com">Link</a>

</body>
</html>
```

Does the problem still occur?

**Comment by aolin480** [comment]
External links are working fine in my wordpress installation. It's the local pages that are not clicking through. I just created a new virtual server and had plain .php files and launched grunt, and when I click on the menu items, they are clicking through now, but the wordpress sites are just not for some odd reason, and only in firefox, chrome is perfect. I just didn't know if there are other options I might be missing in my gruntfile that would be causing this issue. I am going to install a virtualbox and install a vanilla firefox to see if it happens in that environment.

**Comment by shakyShane** [comment]
BrowserSync does absolutely nothing to halt any clicks. We listen to them, but we never interfere with them. I suspect some other Javascript or a browser plugin is the culprit.

Closing this as it can't be reproduced in a testable way. Please feel free to continue commenting with your finding though :)

**Comment by aolin480** [comment]
Sounds good Shane. Thanks for your help!

**Comment by CaesarSchinas** [comment]
@shakyShane I was unable to use BrowserSync for the same reason.

To enlarge upon what @aolin480 said: all clicks are disabled *if the page takes more than a second or so to load*. If it loads faster, it's fine.
(However, when using the proxy it always takes around 20s to load...)

The problem only occurs in Firefox.

I don't have much time to troubleshoot this at the moment but you may like to see my report at http://stackoverflow.com/questions/27761775/browsersync-prevents-navigation-in-firefox-os-x/29214591.

**Comment by aolin480** [comment]
@CaesarSchinas  - Thanks for taking this issue further, I didn't even think to try slowing down my webpage loads (I know you didn't do that, but I can try that out and see). I have a program called Charles Proxy, and I can limit the bandwidth so it slows down the page. Maybe I will try that on a regular HTML file to see if the clicks register. To be honest with you, BrowserSync is awesome, and I could not find anything better, so I just got in to the habit of just holding CTRL and clicking on a link to open a new tab. It then works fine! Not a useful solution, but I can still use browsersync in FF

**Comment by lkraav** [comment]
@shakyShane this is real, and I'm experiencing the same thing on my WP dev environment. I was actually going to bring this up with you to take a look together at our magic WP installation that we set up for that other ticket, but I haven't had time to look at much there yet.

But yes, I'm confirming this is def. for real and it is BS. As soon as I disable my BS-loading helper plugin, all site navigation works fine, and always has in the pre-BS-era. Right now I'm also doing a lot of Ctrl-clicking just like the OP is saying.

**Comment by shakyShane** [comment]
Try setting reloadOnRestart:false and report if it's fixed, thanks :)

**Comment by asapach** [comment]
> Try setting reloadOnRestart:false and report if it's fixed, thanks :)

Worked for me.

**Comment by lkraav** [comment]
I confirm, haven't seen this issue again since.

**Comment by aolin480** [comment]
It's still not working in wordpress for me. Below are the options I am setting.
```javascript
        browserSync: {
            default_options: {
                reloadOnRestart: false,
                bsFiles: {
                    src: ["MyTheme/css/*.css", ]
                },
                options: {
                    watchTask: true,
                    proxy: "www.mysite.local",
                    port: 40
                }
            }
        },
```

**Comment by shakyShane** [comment]
@aolin480 can you show the result of running 

```sh
npm ls browser-sync
```

**Comment by aolin480** [comment]
```javascript
├── browser-sync@2.7.1
└─┬ grunt-browser-sync@2.1.2
  └── browser-sync@2.6.5
```

**Comment by shakyShane** [comment]
```sh
npm rm browser-sync grunt-browser-sync && npm install grunt-browser-sync
```

Then try again :)

**Comment by aolin480** [comment]
Cool.. I am running a npm update now, and noticed that grunt-browser-sync is now at 2.1.3, but I will do your command after it's done

**Comment by aolin480** [comment]
Boo ya! That worked perfectly! Thank you, thank you, thank you!

**Comment by shakyShane** [comment]
any time :)

As a thank you, perhaps you could [vote for us](https://thenetawards.com/vote/open-source/browsersync/)

**Comment by aolin480** [comment]
Just voted!

**Comment by shakyShane** [comment]
Yay!

**Comment by baybara-pavel** [comment]
I have this issue again and all recipes doesn't work for me.

MacOS Sierra
Firefox 50.0
BrowserSycnc 2.17.6

```
"browserSync": {
      "startUrl": "/",
      "reloadOnRestart": false,
      "port": 3004,
      "proxy": "localsite.dev",
      "open": true,
      "notify": true,
      "browser": "default",
      "injectChanges": true
}
```

**Comment by ScorpioCoding** [comment]
Hi I've got the same issue

package.json file
`"browser-sync": "^2.18.8",`


My gulpfile.js
```
gulp.task('browserSync', function () {
  browserSync({
    server: {
      baseDir: './public/',
    },
  });
});
```

index.html
```
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="UTF8"/>
    <title>Index -page</title>
  </head>
  <body>
    <h1>Index Page</h1>
    <cite>welcome to our test Page <br /></cite><a href="test.index">Test Page</a>
  </body>
</html>
```

My test page
```
<html>
  <head>
    <title></title>
  </head>
  <body>
    <h1This>is the test page</h1This>
  </body>
</html>
```

Browser output Index page
![output_index](https://cloud.githubusercontent.com/assets/20724826/23571889/ef2752c4-006b-11e7-9e4d-fdbd096282e7.PNG)

Browser output test page
![output_test](https://cloud.githubusercontent.com/assets/20724826/23571910/fefeff58-006b-11e7-845f-33bc856d07a3.PNG)
