### ISSUE TITLE
browser-sync-client script 404 when using <base> tag

### ISSUE THREAD

**Issue by LukeAskew** [BrowserSync/browser-sync#437]
When I include a `<base href="http://www.website.com/" />` tag, the `browser-sync-client.1.9.1.js` makes a request to that base url rather than localhost, causing a 404.

Is it possible to use `<base>` with BrowserSync?

Running `1.9.0`.

**Comment by shakyShane** [comment]
Hi - I'm not entirely sure what you mean.

You could provide a small, reduced test-case html page showing me exactly what you mean?

**Comment by LukeAskew** [comment]
Sure.

```html
<!doctype html>
<html>
<head>
	<base href="http://www.google.com/" />
</head>
<body>

    <h1>Hello World!</h1>
    <img src="images/srpr/logo11w.png" alt="Google">

</body>
</html>
```

The base tag throws off the `browse-sync-client-x.x.x.js` reference; it tries to pull from the base url, e.g. `http://www.google.com/browser-sync/browser-sync-client.1.9.1.js `

**Comment by shakyShane** [comment]
Fixed in `browser-sync@2.1.2`

**Comment by LukeAskew** [comment]
Confirmed :+1:

**Comment by shakyShane** [comment]
![tumblr_m0osrrhqmk1qzcv7no4_250](https://cloud.githubusercontent.com/assets/1643522/6232985/bdd1ded2-b6c7-11e4-98b5-0eb2d1387125.gif)

**Comment by shakyShane** [comment]
OUCH!

This actually caused a huge regression in BrowserSync and has been reverted in `2.2.0`

To mimic the fix though, you can easily use this option to get the same result.

```
scriptPath: function (path, port, options) {
    return options.get("absolute");
}
```

http://www.browsersync.io/docs/options/#option-scriptPath

**Comment by mj1618** [comment]
Yes I get the same issue in 2.2.0

**Comment by evolutionxbox** [comment]
Is there a way to set `scriptPath` using the cli?

**Comment by evolutionxbox** [comment]
Can we re-open this issue? It is still a problem.

**Comment by majster** [comment]
just use **routes** property and rewrite context served

```
browserSync.init({
    server: {
        baseDir: '.',
        port: 3000,
        middleware: [jsonPlaceholderProxy1, jsonPlaceholderProxy2],
        routes: {
            "/my-base-path": ""
        }
    },
    startPath: '.',
    open: false,
    injectChanges: true,
    files: ['**/*.html', '**/*.js', '**/*.css'],
    watchTask: true
});
```
