### ISSUE TITLE
Bookmarklet injection

### ISSUE THREAD

**Issue by marcobiedermann** [BrowserSync/browser-sync#442]
It would be great if there would be a textfield in the UI to inject some JavaScript bookmarklet.

Some Bookmarklets:
* [DebugCSS](http://yahoo.github.io/debugCSS/)
* [PerfMap](https://github.com/zeman/perfmap)
* [PerformanceBookmarklet](https://github.com/nurun/performance-bookmarklet)

**Comment by shakyShane** [comment]
Yep, that's definitely coming - the ability to add external scripts/css already exists (as you can see with the pesticide css files), it's just not exposed in the UI yet :)

**Comment by marcobiedermann** [comment]
@shakyShane Nice, I am excited! :)

**Comment by shakyShane** [comment]
Moved to https://github.com/BrowserSync/UI/issues/9
