### ISSUE TITLE
BS won't reload the page if an SVG is included via <iframe>, <object>, <svg>

### ISSUE THREAD

**Issue by bfred-it** [BrowserSync/browser-sync#444]
I was trying to get BS to live reload an SVG file, but it didn't work, so I embedded it in an HTML file via `<iframe>`, `<object>` and `<svg><use>`.

BS detects the SVG change but doesn't reload the page or the referenced file. The only tag that works is the `<img>` tag.

---

I'm running BS from CLI:

    browser-sync start --server --logLevel debug --files "*.svg,*.html"

[SVG from Wikipedia](http://upload.wikimedia.org/wikipedia/commons/5/52/Emblem_of_the_United_Nations.svg) and his is the HTML:

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Included SVG reload test</title>
</head>
<body>

<!-- <img> is the only tag that will reload the page -->
<!-- <img src="un.svg" alt=""> -->

<iframe src="un.svg" frameborder="0"></iframe>

<svg><use xlink:href="un.svg#svg2"/></svg>

<object type="image/svg+xml" data="un.svg"></object>

</body>
</html>
```
---

[Screencast (1.5MB)](http://i.imgur.com/sn22L3L.gifv)

**Comment by shakyShane** [comment]
Thanks for the detail @bfred-it - I'm looking into it.

**Comment by shakyShane** [comment]
What would be the IDEAL markup that you'd want to work with?

**Comment by bfred-it** [comment]
Do you mean which one is more likely to be used? <svg><use> is definitely the most used, given [this article](http://css-tricks.com/svg-symbol-good-choice-icons/). Then there's probably `<object>` and then `<iframe>` (unusual in this case)

**Comment by shakyShane** [comment]
Ok, either way, in `browser-sync@2.1.4` you can pass the flag `no-inject-changes` which will force all file changes to trigger a reload.

so you'll still need to embed it somehow in an html file, but when you modify the SVG file, it will simply reload the page

```bash
browser-sync start --server  --files="*.svg,*.html" --no-inject-changes
```

**Comment by bfred-it** [comment]
I was hoping for a non-optional reload/injection like it happens with `<img>` and `<iframe src="*.html">`, but this could work
