### ISSUE TITLE
Errors in Safari: "Deprecated attempt to access properties on a non-Location object"

### ISSUE THREAD

**Issue by prodelay** [BrowserSync/browser-sync#445]
Hi, I get those errors in Safari 8.0.3:

>Deprecated attempt to access property 'origin' on a non-Location object.
Deprecated attempt to access property 'ancestorOrigins' on a non-Location object.

at `browser-sync-client.2.0.1.js:3:34126`

**Comment by RobertCordes** [comment]
I'm on Safari 8.0.2 and I get the same errors.

**Comment by tristyb** [comment]
+1 on this in Safari 8.0.3

**Comment by shakyShane** [comment]
Confirmed bug

**Comment by ram89** [comment]
+1 with 8.0.3

**Comment by Ensive** [comment]
Would be good to resolve this bug

**Comment by vjanssens** [comment]
+1 on 8.0.3

**Comment by stevenceuppens** [comment]
+1 Safari 8.0.3

**Comment by FabrizioA** [comment]
+1 Safari 8.0.3

**Comment by roylines** [comment]
+1

**Comment by hallas** [comment]
Yup :) +1

**Comment by oivinds** [comment]
+1

**Comment by wimva** [comment]
+1

**Comment by Oxicode** [comment]
+1

**Comment by shakyShane** [comment]
fixed in `browser-sync@2.3.2`

**Comment by prodelay** [comment]
Yeah.
Thank you!

**Comment by Ensive** [comment]
Thanks a lot
