### ISSUE TITLE
I need shortcut key.

### ISSUE THREAD

**Issue by Jinkwon** [BrowserSync/browser-sync#446]
Hi, browser-sync.
First of all, thanks for your good product.
This is really useful.

BTW, I need shortcut key about reload all.
Everytime I should click top of realod all button. but I want reload all by shortcut key.
Could you please add this feature?

And I have one more idea.
Most of FrontEnd developers using chrome. (or some others)
If we have chrome extension tool, it will be really helpful.

Thanks.

**Comment by shakyShane** [comment]
The [file-watching](http://www.browsersync.io/docs/options/#option-files) feature is designed specifically for this.

If you mean in the UI though, please post an issue here https://github.com/BrowserSync/UI
