### ISSUE TITLE
Server does not handle streams very well

### ISSUE THREAD

**Issue by austinpray** [BrowserSync/browser-sync#447]
Say you have a build script that looks like this:

```js
var sass = require('node-sass')
var neat = require('node-neat');
var Stream = require('stream');


var source = new Stream();

source.pipe = function(css, dest) {
  dest.write(css);
  return dest;
};
var out = fs.createWriteStream('dist/app.css');

sass.render({
  file: './styles/main.scss',
  success: function(compiled){
    source.pipe(compiled.css, out);
  },
  error: function(error) {
    console.log(error);
  },
  includePaths: neat.includePaths,
  outputStyle: 'compressed'
});
```

Run the server from the CLI and run this build script like 10 times with `node path/to/script.js`.

About 9/10 times it will inject correctly. However, intermittently it will just strip all the styles from the page and render naked html.

This might be an issue with whatever watch module you are using or some kind of platform specific issue. This happens on the latest version of browsersync, OSX yosemite, and node v0.10.36.

Have you seen any cases where it injects improperly and strips all the styles from the page?

**Comment by shakyShane** [comment]
You example does show/explain how you use BrowserSync at all?. If this problem can be reproduced however, please feel free to create a small example project that shows it & I'll take a look

**Comment by austinpray** [comment]
Sure thing!

**Comment by shinnn** [comment]
@austinpray Any updates?

**Comment by austinpray** [comment]
I've made a note to come back to this.
