### ISSUE TITLE
Feature Request: option to set query string params

### ISSUE THREAD

**Issue by kaesetoast** [BrowserSync/browser-sync#448]
Hey folks,

I just tried the new BS version and have to say that it's freaking awesome :-)

While integrating it into our frontend workflow, I was wondering how difficult it would be to implement an option that lets you set certain query string params for every request. My usecase is like the following:

I have a server set up at `project.dev`, which I use through BrowserSyncs proxy option. The site I am working on has server side caching enabled by default and I can disable it by passing a no_cache param in the query string. If I could configure BS in a way, that it automatically appends the no_cache param to the query string it sends to my server (like project.dev?no_cache=1 instead of project.dev), I'd get a pretty nice development setup, just by starting `BrowserSync`.

I guess this might not be that hard to implement. I'd give it a try as soon as I got time, but I wanted to hear your guys opinions on this. Is this a feature you'd be interested in? And if so, maybe you could point me in the right direction.

**Comment by shakyShane** [comment]
This already works.

```js
require("browser-sync")({proxy: "http://project.dev?no_cache=1"});
```

:)

**Comment by shakyShane** [comment]
or just 

```bash
$ browser-sync start --proxy http://project.dev?no_cache=1
```

**Comment by kaesetoast** [comment]
Yeah, but this only works as long as you are not navigating. As soon as you click a link on your website (which will most likely not have the query string params set), the query string is gone. That's why I thought it would be great if the proxy appends this automatically for each request.

**Comment by shakyShane** [comment]
ahh - yeah sorry I see what you mean.

**Comment by shakyShane** [comment]
I've now added middleware support to the proxy, which means you could do something like this:

```js
browserSync({
    proxy: {
        target: "http://yourlocal.dev",
        middeware: function (req, res, next) {
            req.url = req.url + "?no_cache=1";
            next();
        }
    },
});
```

Of course, you may need to be a little more clever about appending that query string, but you get my point :)

version > 2.1 required

:)

**Comment by kaesetoast** [comment]
Yay, that worked like a charm :-)

Thanks a bunch!

**Comment by falzhobel** [comment]
@shakyShane Beware you wrote `middeware` instead of `middleware` in your example :wink:

By the way I tried it with version `2.6.4` and the query string I'm appending isn't being kept when I navigate:

```
proxy: {
  target: 'mysite.dev',
  middleware: function (req, res, next) {
    req.url = req.url + '?webpack';
    next();
  }
}
```

Any clue? :)

**Comment by falzhobel** [comment]
Nevermind, I investiguated a little further by logging `req.url` and saw that the query string was indeed being appended, it's just not showing in the browser URL field or in the page source :wink:
