### ISSUE TITLE
support gzip ?

### ISSUE THREAD

**Issue by suhaotian** [BrowserSync/browser-sync#451]
I try use a middleware to gzip ,like express's compression middleware ,but it did'nt work :(

**Comment by suhaotian** [comment]
done with：
var compress = require('compression');
var browserSync = require('browser-sync');
browserSync({
    server: {
        baseDir: './',
        middleware: function(req,res,next){
             var gzip = compress();
              gzip(req,res,next);
        }
    }
})

**Comment by ngryman** [comment]
Thanks @suhaotian :)

**Comment by shakyShane** [comment]
```js
var compress = require('compression');
var browserSync = require('browser-sync');
browserSync({
    server: {
        baseDir: './',
        middleware: [compress()]
    }
})
```

**Comment by suhaotian** [comment]
@ngryman  :)

**Comment by suhaotian** [comment]
@shakyShane  nice work!!

**Comment by suksant** [comment]
@shakyShane This seems to compress everything except for html files. My settings is through a proxy though:

```javascript
var compress = require('compression');
var browserSync = require('browser-sync').create();

browserSync.init({
  proxy: {
    target: "localhost:3000",
    middleware: [compression()]
  },
  port: 10000
});
```

**Comment by GurovDmitriy** [comment]
Sorry, I don’t understand how to think in order to work. Help.

```    
browserSync: {
      serverSyncDev: {
        bsFiles: {
          src: ['build/*.html', 'build/css/*.css', 'build/js/*.js'],
        },
        options: {
          server: 'build/',
          watchTask: true,
        },
      },
    },

    compress: {
      dist: {
        options: {
          mode: 'gzip'
        },
        expand: true,
        cwd: 'build/',
        src: ['**/*'],
        dest: 'build/'
      }
    },
```
```
// Multiple Global Middlewares
middleware: [
    function (req, res, next) {
        /** First middleware handler **/
    },
    function (req, res, next) {
        /** Second middleware handler **/
    }
]

// Per-route middleware
// NOTE: requires v2.12.1
middleware: [
    {
        route: "/api",
        handle: function (req, res, next) {
            // handle any requests at /api
        }
    }
]

// Per-route + global middleware
// NOTE: requires v2.12.1
middleware: [
    require("compression")(), // global
    {
        route: "/api", // per-route
        handle: function (req, res, next) {
            // handle any requests at /api
        }
    }
]
```

**Comment by vicckm** [comment]
> ```js
> var compress = require('compression');
> var browserSync = require('browser-sync');
> browserSync({
>     server: {
>         baseDir: './',
>         middleware: [compress()]
>     }
> })
> ```

Hi, @shakyShane. Can you explain why you put the function compress() inside the brackets or recommend some articles about it? 

Thank you!

**Comment by ecfaria** [comment]
> > ```js
> > var compress = require('compression');
> > var browserSync = require('browser-sync');
> > browserSync({
> >     server: {
> >         baseDir: './',
> >         middleware: [compress()]
> >     }
> > })
> > ```
> 
> Hi, @shakyShane. Can you explain why you put the function compress() inside the brackets or recommend some articles about it?
> 
> Thank you!

Probably you already know the answer by now, but that's because you can pass multiple middlewares to the server. It's inside brackets because it's an array.
