### ISSUE TITLE
browser-sync not syncing directory indexes

### ISSUE THREAD

**Issue by karland** [BrowserSync/browser-sync#452]
I am running Windows 7-64bit, with browser-sync 2.0.1.
I have generated a static site with a pretty standard setup, which looks in prinicipal like so:

```
mySite
mySite/css
mySite/fonts
mySite/img
mySite/js
index.html
```

and some directory indexes
```
dir1/index.html
dir2/index.html
...
```

The relevant browser-sync section from my gulp config.coffee is

```js
var developmentWebsite = 'mySite'

...

  browsersync:
    development:
      open: true,
      logLevel: "debug"
      logFileChanges: true
      browser: [ 'chrome', 'firefox' ]
      server: baseDir: [
        developmentWebsite
        # developmentWebsite + '/dir1'
        # developmentWebsite + '/**/*'
        # developmentWebsite + '/**/index.html'
      ]
      files: [
        developmentWebsite + '/**/*'
      ]
```

Now, browser-sync is perfeclty refreshing my root index.html, when content or a `.css`-file changes. The debugger also tells me correctly, that a file in a directory index has been changed, but browser-sync is not refreshing the directory indexes. I have tried to add all the directories from the directory indexes to the `server: basedir` but without success. Also I have tried some more general approaches (all in comments). So here are my questions?

* Is this a bug?
* Is this not possible with browser-sync?
* what is the setting to make browser-sync refresh all directory indexes in folders and subfolders?

Please note that google chrome under Windows is opened only when calling it with `chrome` and not with `google chrome`. `google chrome` is not recognized and the page opens in my default browser `firefox`.

Thank you. Cheers.

**Comment by shakyShane** [comment]
Could you set up a small sample project highlighting this issue?

**Comment by karland** [comment]
I have super trimmed down my website to the bare-bones to construct the test case, but now the problem is gone away. So, I have to build up more and more complexity until the error reappears. Sorry for the trouble. I am happy to close the issue for now until I can narrow down the issue and re-open. Thanks, anyway.

**Comment by karland** [comment]
I have found my error. I was using a static site generator. For some reason the generator left out the `<body>`-tags (only the tags why it was hard to spot) and only for the directory indexes. All browsers can live with that situation and are displaying the pages perfectly correctly. The moment I entered the `<body>`-tags browser-sync refreshed as expected. Cheers.

**Comment by shakyShane** [comment]
@karland - excellent news :)

**Comment by shakyShane** [comment]
It catches a lot of people out, so we've just added a note about it to http://www.browsersync.io/docs/#requirements

**Comment by shotanet** [comment]
I have faced same issue and resolved.  Thank you.
