### ISSUE TITLE
Browsersync doesn't set the right local url

### ISSUE THREAD

**Issue by omargourari** [BrowserSync/browser-sync#453]
Here's an issue (already posted on http://stackoverflow.com/questions/28500695/browsersync-doesnt-set-the-right-local-url) regarding the local url configurations option.

As described in the so question I'm working on a wp theme project using the starter theme [roots](https://github.com/roots/roots).

My main concern is about the possibility to set the local url based on the url created by Mamp pro.
I, basically, don't do any change in the hosts file but I just set up a local development website through Mamp and the resulting url is http://mywebsite:8888.

Now, setting the port number as 8888 give me, correctly, the following url http://localhost:8888 but, even if I'm able to see the changes and the page keep refreshing alongside my changes, I'd like to have the local url set as http://mywebsite:8888.

Any similar concern?

Thank you

**Comment by shakyShane** [comment]
The only way to do this would be manually injecting the snippet into your site's footer.

run BrowserSync with neither server or proxy options and you'll be presented with a snippet that you can paste into your website. 

:)

**Comment by zackphilipps** [comment]
Pasting the snippet as-is didn't work for me, and no amount of modification works for me either. Is there something I'm missing? Here's the snippet I was given:

    <script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.8.2.js'>   <\/script>".replace("HOST", location.hostname));
    //]]></script>

and here's another one I tried:

    <script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:PORT/browser-sync/browser-sync-client.2.8.2.js'><\/script>".replace("HOST", location.hostname).replace(/PORT/g, location.port));
    //]]></script>

I'm using BrowserSync with a Gruntfile and MAMP PRO. Please advise.

**Comment by zackphilipps** [comment]
Nevermind. I don't think me and OP are experiencing the same problem, so this fix won't work for me.
