### ISSUE TITLE
windows thow  error with fs.js

### ISSUE THREAD

**Issue by Alexkwang** [BrowserSync/browser-sync#456]
when i use the new version there an error as following, but the V1.9.1 is ok.

==========================================================================

fs.js:1488
      throw new Error('start must be <= end');
            ^
Error: start must be <= end
  at new ReadStream (fs.js:1488:13)
  at Object.fs.createReadStream (fs.js:1449:10)
  at SendStream.stream (C:\Users\aw78\Desktop\angular Demo\bad word\ss - Copy\no
de_modules\browser-sync\node_modules\serve-static\node_modules\send\index.js:668
:19)
  at SendStream.send (C:\Users\aw78\Desktop\angular Demo\bad word\ss - Copy\node
_modules\browser-sync\node_modules\serve-static\node_modules\send\index.js:576:8
)
  at onstat (C:\Users\aw78\Desktop\angular Demo\bad word\ss - Copy\node_modules\
browser-sync\node_modules\serve-static\node_modules\send\index.js:600:10)
  at Object.oncomplete (fs.js:107:15)

==========================================================================

I found this problem is to upgrade from serve-static version。
the right version is 1.8.1 but now the version is 1.9.0

**Comment by pascalduez** [comment]
Same issue here but on OSX.

It's happening when one of the linked files is empty. In my case `main.js`:

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    <script src="assets/js/main.js"></script> 
  </body>
</html>
```

```js
browserSync({
  server: {
    baseDir: './'
  }
});
```

**Comment by shakyShane** [comment]
yerp, on it.

Thanks for reporting.

**Comment by shakyShane** [comment]
also confirmed that downgrading serve-static to 1.8.1 fixes the issue.

**Comment by shakyShane** [comment]
traced it right back to this https://github.com/pillarjs/send/pull/73

**Comment by dougwilson** [comment]
I'm getting this fixed in the necessary dependencies now, as an update.

**Comment by shakyShane** [comment]
thanks @dougwilson  :+1:

**Comment by dougwilson** [comment]
done :)

**Comment by dougwilson** [comment]
sorry for the trouble, @shakyShane

**Comment by shakyShane** [comment]
Not at all!

Everyone else, you're safe now to `npm rm browser-sync && npm install browser-sync` - this will ensure you get the fixes from our dependencies :)

**Comment by Alexkwang** [comment]
thanks
