### ISSUE TITLE
Watch for smarty .tpl files not working

### ISSUE THREAD

**Issue by littlbr** [BrowserSync/browser-sync#458]
I'm using Gulp and try to reload the browser when *.tpl files are modified and cannot for the life of me make it work.
I have the following task : 

```js
gulp.task('browser-sync', function() {
    browserSync({
        proxy: "mysite.dev"
    });
});

gulp.task('bs-reload', function () {
    browserSync.reload();
});

gulp.task('default', ['browser-sync'], function() {
    gulp.watch(['*.tpl', '*.php'], ['bs-reload']);
});
```

When php files are modified, the browser does reload correctly, but not when saving a .tpl file.
Any idea anyone?
Thanks!

**Comment by shakyShane** [comment]
Are you `.tpl` files located in your root directory?

**Comment by shakyShane** [comment]
`*.tpl` would not match `whatever/file.tpl` for example.

you'd need 

```js
gulp.task('default', ['browser-sync'], function() {
    gulp.watch(['whatever/*.tpl', '*.php'], ['bs-reload']);
});
```
