### ISSUE TITLE
Snippet with HTTPS

### ISSUE THREAD

**Issue by leigeber** [BrowserSync/browser-sync#459]
Looking over recent activity I got the impression that injecting a snippet with HTTPs should work. However with the following config and loading a site through MAMP locally with HTTPs the snippet does not load. The snippet is correctly loading from ```https://domain.dev:3000/browser-sync/browser-sync-client.2.1.4.js``` however it only works if requested from HTTP.

Here is the server config object we're passing to the browserSync method:

```javascript
{
    https: true,
    files: [
        'public_html/assets/**/*.{min.css,min.js,gif,jpg,png,svg}',
        'public_html/**/*.html'
    ],
    port: 3000,
    logPrefix: 'Wee',
    open: 'external',
    notify: false,
    ui: {
        port: 3001,
        weinre: {
            port: 3002
        }
    }
}
```

Am I missing something with the settings or is this not supported currently? Thanks!

**Comment by shakyShane** [comment]
No this is bug, I missed the HTTPS support for the snippet only (as it's a different server)

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/lib/server/snippet-server.js :(

**Comment by leigeber** [comment]
Look straightforward enough, if you want a pull request to squash this one let me know.

**Comment by shakyShane** [comment]
Sure - that would be great.

You can see how it's done here with the static server.

https://github.com/BrowserSync/browser-sync/blob/master/lib/server/static-server.js#L72-L79

For tests, you could add to, or copy this https://github.com/BrowserSync/browser-sync/blob/master/test/specs/e2e/e2e.snippet.js

:)
