### ISSUE TITLE
Feature Request: setting proxy url in the UI

### ISSUE THREAD

**Issue by risto1913** [BrowserSync/browser-sync#465]
I really love what you have done here!!!

I would like to make use of browser-sync as a replacement for [Remote-Preview-Node](https://github.com/vwxyz/Remote-Preview-Node)

This would require the proxy url to be an input field that could set the proxy url on the server.

What are your thoughts on this?

**Comment by nickcolley** [comment]
I'm interested in impliementing this if it's possible: https://github.com/BrowserSync/UI/issues/6

**Comment by shakyShane** [comment]
Closing in favour of keeping this in the correct repo & is a dupe of https://github.com/BrowserSync/UI/issues/6. 

Please continue discussions there.
