### ISSUE TITLE
gulp-less + inline SVG referencing external file breaks BrowserSync reload

### ISSUE THREAD

**Issue by cbracco** [BrowserSync/browser-sync#466]
Hi there,

Thanks for building such a fantastic tool! I've been experiencing an odd bug and wanted to bring it to your attention.

I am trying to use `browsersync (^1.5.2)`, `gulp-less (^3.0.0)`, and an inline SVG referencing an external file. When a refresh is triggered from a watched file changing, BrowserSync refreshes successfully on my machine (MacBook Pro), but unsuccessfully on my mobile device (iPhone, iOS8). iOS Safari displays the following error message after BrowserSync attempts to refresh:

![img_3028](https://cloud.githubusercontent.com/assets/1480677/6280485/fe313b70-b87b-11e4-8f3a-d8d8e33a9771.PNG)

I do not experience this issue when using `gulp-sass` instead of `gulp-less`. I also do not experience this issue if I only remove the inline SVG from the HTML source. It seems the combination of `browsersync`, `gulp-less`, and the inline SVG referencing an external file that's causing the bug in this particular instance.

For now, I've been including my entire SVG icon file at the top of my HTML source, and referencing the `<symbol>` internally. This does not cause the above error, but is undesirable because I am no longer able to cache the external SVG file since its included in the HTML of every page.

I put together a [Gist of related project files](https://gist.github.com/cbracco/c940fb27418cf306144f). This project is derived from [gulp-tutorial](https://github.com/kogakure/gulp-tutorial/), so if I've missed anything you can use that as a reference as well.

Any help or insight is greatly appreciated. 

Cheers!
Chris

**Comment by shinnn** [comment]
Could you update browser-sync to the latest version? You are using too older version.

**Comment by cbracco** [comment]
I just updated to 2.2.1, and I am still experiencing the same problem. :disappointed:

**Comment by shinnn** [comment]
@cbracco Why your HTML doesn't have `<DOCTYPE>`, `<html>`, `<head>` or `body`?

**Comment by cbracco** [comment]
It does, I omitted it in my example before for brevity. Updated that part of my example here: https://gist.github.com/cbracco/c940fb27418cf306144f#file-index-html

**Comment by shinnn** [comment]
@cbracco I'd like you to create a small repository that can reproduce the error, instead of Gist.

**Comment by cbracco** [comment]
@shinnn I actually just figured out the issue a few days, and it is not related to browsersync ... believe it or not it was CSS that was crashing iOS8: https://twitter.com/cbracco/status/594196248468533248

simple removed the ::selection styles from my CSS and iOS no longer crashed. Apologies for the false alarm here!

**Comment by shinnn** [comment]
@cbracco No problem!
