### ISSUE TITLE
Version number in script include

### ISSUE THREAD

**Issue by Nooshu** [BrowserSync/browser-sync#472]
Hello,

I've had an issue over the past couple of weeks where whenever browser sync is updated via `npm`, the version number in the HTML code snippet needs to be updated manually due to the version number change:

```
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.2.2.1.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
//]]></script>
```

Is there any way to automate this process? Or is there a version where the version number isn't included?

Thanks,
Matt

**Comment by shakyShane** [comment]
If you're using the snippet manually, you can simply omit the version number and it will still work.

```html
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='//HOST:3000/browser-sync/browser-sync-client.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
//]]></script>
```

**Comment by Nooshu** [comment]
Perfect! That's exactly what I needed.

Thanks.

**Comment by shakyShane** [comment]
:+1:
