### ISSUE TITLE
no CSS reload when using -prefix-free

### ISSUE THREAD

**Issue by di5abled** [BrowserSync/browser-sync#475]
Hello,

I have a problem while using browser-sync with [-prefix-free](http://leaverou.github.io/prefixfree/) included on my site.

The new generated CSS does not update while -prefix-free is included, when I remove it from the page all works great. 

I think livereload also had a similar problem and solved it, would be great if you could do something about this. [LiveReload Infos](http://feedback.livereload.com/knowledgebase/articles/86176-handling-vendor-prefixes)

**Comment by shinnn** [comment]
IMO -prefox-free is too outdated solution for CSS vendor prefixes. I recommend using CSS compilers such as [autoprefixer](https://github.com/postcss/autoprefixer). BrowserSync team should not spend a time to support -prefix-free, I think.

**Comment by di5abled** [comment]
I use autoprefixer when I finished active developing on projects, but I still use -prefix-free while developing because is much faster in the feedback cycle when I don't have to wait for autoprefixer to do his job when I could just update the site and prefix-free can do the rest. hope this makes sense and can be fixed. maybe its an easy fix when livereload already know how to fix this :)

**Comment by di5abled** [comment]
nevermind, I'm using autoprefixer for everything now
