### ISSUE TITLE
logFileChanges has no effect

### ISSUE THREAD

**Issue by thebuilder** [BrowserSync/browser-sync#479]
Hi

I set up a basic BrowserSync server task in a gulp project, and i set the option **"logFileChanges"** to _false_. This however seems to have no effect. It still logs out whenever a file change:

```
[BrowserSync] File changed: css/app.css
```

My BrowserSync task currently looks like this:
```javascript
module.exports = function(done) {
	var browserSync = require('browser-sync');
	var watch = require('gulp-watch');
	var config  = require('../config');

	//See http://www.browsersync.io/docs/options/ for all options
	var options = {
		server: {
			baseDir: "./" + config.dist
		},
		port: config.server.port,

		logLevel: 'info',
		logPrefix: "BrowserSync",
		logFileChanges: false,
		notify: true
	};

	//Start the BrowserSync server
	browserSync(options, function(err, bs) {
		//BrowserSync running
		done();
	});

	//Watch for changes and reload BrowserSync
	watch(config.dist + '**/*.*', function(file) {
		browserSync.reload(file.relative);
	})
};
```

**Comment by thebuilder** [comment]
Tried monitoring the _file.reload_ event:

```javascript
browserSync.emitter.on("file:reload", function (e) {
	console.log(e);
});
```

In the output event, log is **true**, so the logger of course logs the change.
```javascript
{
  assetFileName: 'app.css',
  fileExtension: 'css',
  cwd: ...,
  path: 'css/app.css',
  type: 'inject',
  log: true 
}
```

**Comment by thebuilder** [comment]
Tried to change the browserSync.reload to use stream. This results in the file.reload event not triggering at all, so now the logFileChanges doesn't log anything even if it's set to true.

The notifications in the browser still show the file that changed. Is this intended for streaming?

```javascript
watch(config.dist + '**/*.*')
	.pipe(browserSync.reload({stream:true}));
```

**Comment by shakyShane** [comment]
`logFileChanges` currently only applies when using BrowserSync's internal file-watcher, but yes, it should also apply to stream-initiated events. 

Thank for reporting, we'll get it fixed asap

**Comment by thebuilder** [comment]
Any progress on this?:) It's a general issue for all **browserSync.reload** calls. 
Trying to declutter the terminal output, it is a bit annoying to have it filled with lines of `"[BrowserSync] Reloading Browsers..."`

I would be more interested in knowing if it failed to reload the browsers.

On a similar note, setting logLevel to "warn" appears to have no effect. 
I do like the "Access URLs" log snippet, but would prefer to keep the remaining output to warnings.

**Comment by shakyShane** [comment]
This is scheduled for next round of bug fixes :)

**Comment by shakyShane** [comment]
Or if you would like to make this happen sooner, we love pull requests. 

I'm thinking the issue is mainly here https://github.com/BrowserSync/browser-sync/blob/master/lib/logger.js#L41-L56

Could be as easy as checking the option along with the `data.log` property

**Comment by shakyShane** [comment]
Also https://github.com/BrowserSync/browser-sync/blob/master/lib/logger.js#L66-L68

and https://github.com/BrowserSync/browser-sync/blob/master/lib/logger.js#L80-L89

**Comment by redwan10** [comment]
Thanks guys. With your discussion, I find the solution. Thanks a lot

**Comment by redwan10** [comment]
Thanks, guys. Your discussion helps me to find a solution. Thanks a lot
