### ISSUE TITLE
Middleware with cookies

### ISSUE THREAD

**Issue by cliren** [BrowserSync/browser-sync#481]
Middleware solution described in https://github.com/BrowserSync/browser-sync/issues/471 works fine but I can't get it working when target api requires cookies. How can I get it working like nginx/apache rewrites?

var httpProxy = require('http-proxy');

var proxy = httpProxy.createProxyServer({
   target: 'http://localhost:8080/'
 });

var proxyMiddleware = function(req, res, next) {
   if (req.url.indexOf('api') != -1) {
     proxy.web(req, res);
   } else {
     next();
   }
};

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/issues/471#issuecomment-84943510

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/issues/471#issuecomment-100403054
