### ISSUE TITLE
GET-Requests not working when using v2.2.1

### ISSUE THREAD

**Issue by dschu-lab** [BrowserSync/browser-sync#486]
I just noticed when using v2.2.1 my seach input isn't working anymore. When browser-sync is disabled, everything is working fine. But as soon as it is enabled, the GET-Requests aren't sent anymore. Any idea why?

Even when a GET var is already in my URL, it won't get replaced with the new value after sending the new GET-Request.

Update:
Even clicking on links doesn't seem to work anymore. When hovering over, the correct link is shown in the lower left corner of my browser (FF36@Ubuntu14.04). However, clicking on it will just cause the page to reload instead of opening the link. When clicking with the scroll wheel it opens the correct link in a new tab. So, what is going on? Don't know how to debug this on my own.

**Comment by shakyShane** [comment]
Is this Firefox only? Try setting reloadOnRestart: false

**Comment by dschu-lab** [comment]
Could you fix it? I had no time to test your solution, because I'm working on another project right now.
