### ISSUE TITLE
Script injection seems to break Firefox

### ISSUE THREAD

**Issue by robdodson** [BrowserSync/browser-sync#488]
I'm using the `browser-sync` gulp plugin and noticed that I can't load pages in Firefox. [Related issue](https://github.com/yeoman/generator-polymer/issues/152#issuecomment-76075881). I'm having a hard time reproducing the bug on Mac to give you a reduced test case unfortunately. But it seems like disabling browserSync does fix the issue in my projects.

**Comment by shakyShane** [comment]
This is a known bug in BrowserSync, please use reloadOnRestart: false as a temporary fix - this will be made default in an upcoming bugfix release
