### ISSUE TITLE
browserSync.reload() delay?

### ISSUE THREAD

**Issue by hydrotik** [BrowserSync/browser-sync#489]
Is there a way to pass a param to a specific call of browserSync.reload()? I don't want the delay to fire all the time with some of the watch tasks, but for a nodemon restart I would like to delay the refresh.

**Comment by shinnn** [comment]
> Is there a way to pass a param to a specific call of browserSync.reload()?

Yes. http://www.browsersync.io/docs/api/#api-reload

> for a nodemon restart I would like to delay the refresh.

1. Set a variable (for example `nodemonRestarted`) `true` when nodemon restarts.
2. Use `setTimeout` or something else only when `nodemonRestarted` is `true`.

-------

Please read the contributing guide before creating a new issue. https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
