### ISSUE TITLE
URL sync should work with back buttons and other methods of navigation

### ISSUE THREAD

**Issue by hugobessaa** [BrowserSync/browser-sync#49]
Browser-sync just synchronize URLs between gadgets when you click a link. It should work with back history buttons and other methods of navigation, such as hard entered addresses.

**Comment by shakyShane** [comment]
This problem is somewhat solved with the new UI featuers. Given how buggy previous attempts have been, happy to close this and simply say `Use the UI`

**Comment by aristidesfl** [comment]
This should be re-opened. Without it pages get out of sync too quickly.

**Comment by kmbeard** [comment]
I agree this should be reopened.
