### ISSUE TITLE
When browser-sync inject javascript to an existing website?

### ISSUE THREAD

**Issue by ntas1310** [BrowserSync/browser-sync#491]
I want to test a website which heavily use javascript. I had a problem when trying using browser-sync with this website in proxy mode. However, it seems that injecting the bs script causes the page failed to load. Hence, I would like to ask whether there is a way to config browser-sync to inject the script ONLY after the page is completely loaded. 

Thanks very much, 
Andy

**Comment by shinnn** [comment]
> it seems that injecting the bs script causes the page failed to load

Could you show us the complete HTML of your website?

**Comment by shinnn** [comment]
@ntas1310 Any updates?
