### ISSUE TITLE
open should accept a string address

### ISSUE THREAD

**Issue by doshprompt** [BrowserSync/browser-sync#494]
Hi,

I have an issue where, when running locally, I must mask my localhost as a subdomain to bypass CORS issues.

so I would like to start the browser and open x.y.z.com which is in my etc/hosts file defined as 127.0.0.1

It would be nice if open accepted a url address and opened that in the browser on start

**Comment by ai** [comment]
@shakyShane I need this option too. I have a port forwarding from 80 to 3000. So I can open `site.dev`.

Right now I used:

```js
browserSync({
    proxy: 'amplifr.dev:2999',
    host: 'amplifr.dev',
    open: 'external'
});
```

But BrowserSync add `:3000` port to address, which broke some scripts with bad domain check.

**Comment by shakyShane** [comment]
Given that this is *really* simple to add yourselves manually and also being what I would consider to be a rare use case, I don't think it belongs in core.

Try this though, it'll work just fine :)

```js
var opn = require('opn');
var browserSync = require('browser-sync');

browserSync({
    proxy: 'site.dev:2999',
    host: 'site.dev',
    open: false
}, function () {
    opn('http://site.dev');
});
```

**Comment by ai** [comment]
@shakyShane problem is not with open. I could open this page manually.

But BrowserSync proxy will not handle `http://site.dev`, only `http://site.dev:3000`. Seems like it has some port check inside.

**Comment by doshprompt** [comment]
@shakyShane Your example works but not if I also want browserSync to be the server.
