### ISSUE TITLE
Firefox + Proxy - Navigation not working

### ISSUE THREAD

**Issue by VoodooPrawn** [BrowserSync/browser-sync#495]
I've got BrowserSync all set up and working and it's working perfectly in Chrome. However in Firefox, navigating between pages doesn't seem to work, going anywhere seems to basically redirect you straight back where you came. 

In the net console it seems that the request for "localhost:3000/inner-page" gets marked as "Aborted", then it just requests "localhost:3000" again.

I'm pretty sure it's not a set up or server issue as Chrome works as expected.

This seems to be exactly what I'm seeing (except for Windows): http://stackoverflow.com/questions/27761775/browsersync-prevents-navigation-in-firefox-os-x

Any ideas?

**Comment by shakyShane** [comment]
try setting

```
reloadOnRestart: false
```

**Comment by VoodooPrawn** [comment]
Great! Seems to be working, any ideas why this was needed?

Thanks for your speedy reply and help :)

**Comment by shakyShane** [comment]
> any ideas why this was needed?

I've not had chance to debug this yet unfortunately! :(
