### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mietek** [BrowserSync/browser-sync#499]
Recently, BrowserSync started causing my browser to use up to ~20% CPU.

It looks like `browser-sync-client.2.2.1` is calling `onHeartbeat`, `setPing`, and `write` many times per second.

This is a regression, most likely introduced together with the UI layer.  Sadly, I can’t seem to be able to cure the high CPU usage with the otherwise excellent `--no-ui` option.

**Comment by shakyShane** [comment]
Fixed in `browser-sync@2.2.3`

Thanks for reporting.

:)

**Comment by mietek** [comment]
Excellent. Thanks!

**Comment by larvanitis** [comment]
@shakyShane Thanks! You are the boss!
