### ISSUE TITLE
Cannot GET 

### ISSUE THREAD

**Issue by normanlove222** [BrowserSync/browser-sync#5]
I can't get around the browser saying:
Cannot GET /mvyc/add-members.php

my config file is:
module.exports = {
    files: "*.css",
    debugInfo: true,
    host: "192.168.1.65",
    ghostMode: {
        links: true,
        forms: true,
        scroll: true
    },
    server: {
        baseDir: "./mvyc"
    },
    open: true
};

ive tried different variations of the directory im in for baseDir setting. ive set it at:

mvyc, and ./, and nothing and at most the command line says its watching 1 file, but the browser doesn't seem to be able to connect. is this a firewall thing or something else.

**Comment by augbog** [comment]
This is coming up on google searches but for those wondering, if you are running MAMP and simply want to browsersync your localhost from MAMP, you can just do a proxy

`browser-sync start --proxy localhost:8888`

At least that helped me. Hope this helps other people.
