### ISSUE TITLE
using browser sync with rails - asset pipeline

### ISSUE THREAD

**Issue by fionnbharra** [BrowserSync/browser-sync#50]
I'm trying to use browser sync with rails, using the asset pipeline. 

Rails compiles css when they are requested, so it's not possible to give a path to the file before compilation. 

```
files: ["rails/doesnt/have/the/css/yet/application.css", ],
```

If I point the config towards the sass file, the page reloads rather than injecting the changes. 

```
files: ["assets/application.scss", ],
```

this may be more of an issue with rails rather than an issue with browser sync but is it possible to avoid the page reload when watching sass rather than css files?

**Comment by snuggs** [comment]
Thanks for the update. We have done the same.

**Comment by greypants** [comment]
@jhoffner I FINALLY came up with a solution that works, and DID get around to blogging: http://viget.com/extend/gulp-rails-asset-pipeline

**Comment by SeanRoberts** [comment]
https://github.com/shakacode/react_on_rails

This gem seems to be focused on getting npm + webpack working within a Rails app.  I don't think it would be difficult to ignore or rip out the React stuff if you don't want it.  At that point you can either use BrowserSync with webpack or use webpack HMR.  Hopefully within the next couple of years we'll have a more standardized way to parcel this kind of thing out of the asset pipeline without all these workarounds.

**Comment by greypants** [comment]
I've also added an [extras folder to gulp-starter with a Readme and extra files](https://github.com/vigetlabs/gulp-starter/tree/master/gulpfile.js/extras/rails) for working with rails. It's more up to date than what's referenced in the blog post.
