### ISSUE TITLE
Socket connected but doesnt work

### ISSUE THREAD

**Issue by Oldwo1f** [BrowserSync/browser-sync#500]
hi every one.

I use browser-sync thought grunt with this option

```
options: {
                    // watchTask: true, // < VERY important
                    proxy: "localhost:1337",
                    socket: {
                        path: '/socket.io',                        
                    }
                }
```
My application is a Sails.js app

When i access my app thought the sails port (1337), i got my socket connect an i can request my server via a socket connexion.
But when i access my app thought the bower-sync proxy (port 3000), i got my socket connected but the request fail after.

Any idea?

Thanks

**Comment by shinnn** [comment]
@Oldwo1f 

* Which OS?
* Node/browser-sync version?
* Could you create a small repository that can reproduce the error?
