### ISSUE TITLE
Need a delay before the browser refreshes.

### ISSUE THREAD

**Issue by marknelsonengineer** [BrowserSync/browser-sync#501]
I'm using BrowserSync with an application that uses the Play framework.  One of the characteristics of the framework is that it takes a while to compile.  Is there a way to get Browser Sync to pause for some number of seconds/milliseconds before refreshing the page?

Thank you,
Mark

**Comment by shakyShane** [comment]
Please try: http://www.browsersync.io/docs/options/#option-reloadDelay
