### ISSUE TITLE
How to restart the server itself?

### ISSUE THREAD

**Issue by binarykitchen** [BrowserSync/browser-sync#506]
Is there an API call to restart the server itself? This just in case if the attached middleware has changed?

**Comment by shakyShane** [comment]
you have access to the httpServer instance, so you could just do it manually :)

```js
browserSync({
    server: "./app"
}, function (err, bs) {
    bs.server.close();
    bs.server.listen(bs.options.get("port"));
});
```

**Comment by binarykitchen** [comment]
hmmm, i see but that would not get on well with gulp. i have custom middleware attached and want the server to be restarted whenever they change.

this with `gulp.watch()` from another gulp task, without having a reference to `bs`.

something like this would be cool

```js
gulp.watch('middleware/**',  [browserSync.restartServer])
```

**Comment by binarykitchen** [comment]
@shakyShane ping?

**Comment by binarykitchen** [comment]
Furthermore I realised that doing a `bs.server.close()` and a `bs.server.listen()` does not really reload the new code when any changes are made. The old code still resides in the memory ...

**Comment by shakyShane** [comment]
@binarykitchen - this is out of scope for the BrowserSync project I'm afraid - you need something similar to [nodemon](https://github.com/remy/nodemon) to achieve this.

**Comment by binarykitchen** [comment]
Sorry, but I have to disagree @shakyShane 

Inside BrowserSync, `connect` is used and respects any custom middleware you define under BrowserSync options. What if I change some middleware code lines while it's running? It must restart automatically (at least in development mode). I do not see how nodemon could help here. Running nodemon in addition to BrowserSync is overkill I think. Or won't work at all because we have no node.js server here, just static files and some custom middleware for BrowserSync during development and that's is.

BrowserSync already comes with all the dependencies to implement such a feature I guess. Ultimately, BrowserSync *synchronizes*. Hence, for the sake of synchronization, I believe changes in the code, middleware here, should become effective asap.

Motto of BrowserSync is: *"BrowserSync makes your tweaking and testing faster by synchronising file changes and interactions across multiple devices."* - this is not entirely true because currently you do not synchronize changes in the middleware ;)

**Comment by shinnn** [comment]
>  just static files and some custom middleware

1. Create your own server by using `connect` module
2. Add `.restartServer` method to the server (as you expected)
2. Integrate it with your middleware
3. Call `.restartServer` method when your middleware files are modified

> this is not entirely true

Motto is just a motto. I think it sufficiently represents browser-sync.

**Comment by binarykitchen** [comment]
Hmm, and how do you link your own server with BrowserSync?

I see no such option under http://www.browsersync.io/docs/options/#option-server how to link both. And won't this cause a conflict? Do not want to end up, BrowserSync and the server, both serving the same frontend assets. Or having a port conflict.

**Comment by shinnn** [comment]
> how do you link your own server with BrowserSync

Use `proxy` mode. http://www.browsersync.io/docs/options/#option-proxy

----------

https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#question

**Comment by binarykitchen** [comment]
thx

**Comment by shakyShane** [comment]
Also worth noting, if you need direct access to the middleware stack you can do it through

```js
browserSync({
    server: "./app"
}, function(err, bs) {
    // bs.app = connect object
});
```

That's how we add/remove middlewares on the fly for the UI.

https://github.com/BrowserSync/browser-sync/blob/master/lib/browser-sync.js#L341-L404

**Comment by shakyShane** [comment]
@binarykitchen - Some other responses to your comment

> What if I change some middleware code lines while it's running?

This is *exactly* what nodemon is designed for - because your JS code is compiled at run time, there's no other way than rebooting the process for your changes to take effect.

That's what I meant when i said it's out of scope - we reload static assets into browsers, we are not in the business of watching/restarting your process.

> Or won't work at all because we have no node.js server here.

Nodemon just runs any script - it doesn't care whether it's a server,cli tool or anything else.

**Comment by binarykitchen** [comment]
Alright. I do not want to use nodemon. It's overkill for our project.

Think I will use `usefresh-require` and add middleware on the fly in that callback you mentioned.

**Comment by shakyShane** [comment]
@binarykitchen sounds good :+1:

**Comment by binarykitchen** [comment]
Here for the world, to share, a working example that reloads middleware from gulp within when watching:

```coffee
gulp.task('server', ... , (cb) ->

  # see https://github.com/BrowserSync/browser-sync/issues/506
  reloadMiddleware = (bs) ->

    bs.removeMiddleware('redirector')

    # Bypass the require cache
    getDevServerRedirector = freshRequire('./src/middleware/redirector', require)

    # Redirects mostly queries, blabahh ...
    bs.addMiddleware('*', getDevServerRedirector(...), id: 'redirector')

  browserSync(
    ...
    server:
      baseDir: [paths.public]
      middleware: [
        proxy(proxyOptions)
      ]
  , (err, bs) ->
    if (err)
      cb(err)
    else
      reloadMiddleware(bs)

      if isMainTask('watch')
        gulp.watch([
          "#{paths.middleware}/**"
        ], interval: config.watchInterval, ->
          reloadMiddleware(bs)

          bs.server.close()
          bs.server.listen(bs.options.get("port"), ->
            gutil.log('Dev server restarted.')
          )
        )
  )

  # Register callback to kill server on task completion.
  gulp.on('stop', ->
    browserSync.exit()
    gutil.log('Dev server shut down.')
  )

  cb() unless isMainTask('server')
)
```
