### ISSUE TITLE
browser-sync + PhantomJS???

### ISSUE THREAD

**Issue by blackjyn** [BrowserSync/browser-sync#507]
Can I use browser-sync with PhantomJS? 
I like the auto reload from browser-sync but instead of render it in browser, I'd like to render using Phantom.. how to achieve this ?

**Comment by thalesfsp** [comment]
:+1:

**Comment by shakyShane** [comment]
Hi! I'm not really sure why you would need to use BrowserSync + PhantomJS?

Whatever the reason, you should just provide the URL given to you by BrowserSync to PhantomJS?

Please let me know if there's something specific I'm not thinking of here...

**Comment by thalesfsp** [comment]
@shakyShane you answered my need on this [question](https://github.com/BrowserSync/browser-sync/issues/521#issuecomment-82815229)

**Comment by pgangwani** [comment]
Hey @shakyShane and team,
I am working on tool for testing team to do cross browser testing, used browser-sync --proxy option 
next huddle for me to take screenshots on all the viewports(breakpoints) using phantomjs. pretty unlear on this integration and implementation . Could you please guide on the same ?

This actually is providing you the reason in your comment: 
"Whatever the reason, you should just provide the URL given to you by BrowserSync to PhantomJS"
