### ISSUE TITLE
Valid HTML5 document causes snippet injection failed

### ISSUE THREAD

**Issue by nightire** [BrowserSync/browser-sync#508]
Following HTML is totally valid HTML5 code:

```html
<!doctype html>
<title>Test</title>

<article>
  <h1>Heading</h1>
</article>
```

Unfortunately, BS doesn't know how to inject snippet in this document, server is running fine only without any syncing/reloading actions.

**Comment by nightire** [comment]
BTW, solution is simple, just add a `<body></body>` tag will do the trick.

**Comment by peterblazejewicz** [comment]
@nightire btw have you tried this?
https://github.com/BrowserSync/browser-sync/issues/496

**Comment by shakyShane** [comment]
Solution:
https://github.com/BrowserSync/browser-sync/issues/496#issuecomment-77230744

http://www.browsersync.io/docs/#requirements
