### ISSUE TITLE
Always points to localhost:4000 when launching the browser

### ISSUE THREAD

**Issue by skdzines** [BrowserSync/browser-sync#510]
browser-sync module setup:

```js
module.exports = function(config) {
	gulp.task("browser-sync", function() {
		if(config.production) {
			return;
		}
	    browserSync({
	        proxy: config.site + ":3000", // local node app address
	        port: 4000, // use different port than above
	        browser: ["google chrome"]
	    });
	});
}
```
Example proxy being passed in (config.site) could be something like "mysite" or "template".  My hosts file would contain a matching entry of 127.0.0.1  mysite.

Every time I run gulp and the server starts and browser-sync is ran, the page always launches with the url http://localhost:4000.  I can easily change the url to point to http://mysite:4000 and all works fine.  However I would like it to automatically launch the site pointing to http://mysite:4000.  Not sure what I'm missing or why it always points to localhost.

**Comment by shakyShane** [comment]
The `http://localhost:4000` url is the one that BrowserSync provides so that we can auto-inject the JS snippet.

If you would rather still access your site through your original address, simply omit the proxy option and you'll be provided with a HTML snippet with which you can paste into your websites footer.

**Comment by forestjohnsonilm** [comment]
This isn't really resolved. I am using a special name for localhost in my hosts file to allow me to trick the browser into making requests to external servers (same origin policy). There really is a missing option in BrowserSync, maybe it should be called localhostUrl or urlToOpenInBrowser. It doesn't matter if BrowserSync's server thinks it is running on localhost. My hosts file says localhost and  localhost.examplecorporateempire.com are one and the same, so if BrowserSync opens the browser to localhost.examplecorporateempire.com, it will hit the proxy server just fine. 

I would volunteer to make a pull request for this option but I don't really have the time.

**Comment by forestjohnsonilm** [comment]
NEVERMIND! 

here is the solution:

browserSync.init({
     open: "external",
     host:"localhost.examplecorporateempire.com",
     proxy: "localhost.wsj.examplecorporateempire:8080",
     port: 4000
   });

**Comment by phillipswdc** [comment]
> NEVERMIND!
> 
> here is the solution for my case:
> 
> browserSync.init({ open: "external", host:"localhost.examplecorporateempire.com", proxy: "localhost.wsj.examplecorporateempire:8080", port: 4000 });

this worked for me also, thank you!!
