### ISSUE TITLE
All files without one extension?

### ISSUE THREAD

**Issue by PixelT** [BrowserSync/browser-sync#513]
I would like to sync all files (using command line) without one extensions - it il possible?
The command line something like this:
```
browser-sync start --proxy mydir --files "**/*"  --exclude "**/*.scss"
```
At now, I must define all extension individually:
```
browser-sync start --proxy mydir --files "**/*.html, **/*.php, **/*.css, **/*.js"  --exclude "**/*.scss"
```

**Comment by declandewet** [comment]
You can use [Globtester](http://www.globtester.com/#p=eJzT19LS19LTAgAE3gE1&r=eJx1jcENgCAQBFsxFMA1gHZgESecAT2BcEQtX4wfH%2FrbZGayxoW9s4wivdqwWq8G2AMdAg7FTwmL075ubKCJg%2FmwMWewKdaSmKm8u%2Bzzf2ZFIERHp27rX1vkPtDLh9LoiCvNgemBFy2ZR9k%3D&) to test glob/minimatch patterns. The text in blue are the paths that are matched.

For multiple extensions: `**/*.*`

**Comment by shakyShane** [comment]
You can negate a pattern with `!` but it needs escaping on the command line

```
browser-sync start --proxy mydir --files "**/*, \!scss/**/*.scss" 
```

:)

**Comment by igregson** [comment]
Just a note that might be helpful for other (not so quick folks like myself :)

`!` doesn't need to be escaped inside of json files. In my case, 

I'm using NPM's `package.json` script object for building. Here's my core browserSync task: 

```
"browserSync": "browser-sync start --proxy 127.0.0.1:7000 --logLevel 'info' --no-open --no-notify --files '**/*, !src-*/**, !js/**'",
```

**Comment by shinnn** [comment]
See https://github.com/BrowserSync/browser-sync/issues/513#issuecomment-84108911.

Thanks.
