### ISSUE TITLE
BrowserSync UI not working with Gulp

### ISSUE THREAD

**Issue by grafikkaos** [BrowserSync/browser-sync#516]
Is there a way I can get BrowserSync's UI to work with gulp?  So far I have had no luck as when I start my gulp process, the UI web address is not provided.

Any tips will would be appreciated.

Thanks

**Comment by shakyShane** [comment]
There's nothing specific to gulp in BrowserSync, so just ensure you are using the latest version with 


```bash
npm install browser-sync@latest --save-dev
```
