### ISSUE TITLE
Css changes is not reflecting on moodle themes

### ISSUE THREAD

**Issue by bogatisuman** [BrowserSync/browser-sync#519]
I do apology, there is doubt for it's being an issue. I have posted this issue on stakoverflow before 2 days but there is only one response which is not useful.

According to browser-sync, I did all setup,  and for my requirement I changed the css of moodle theme. The changes of css is showing in command prompt but reflect of changes is not showing in browser without page refresh. Why it's happening?

Here I am going to put the  [stakoverflow link](http://stackoverflow.com/questions/28992107/why-browser-sync-is-not-working-with-moodle-theme).

**Comment by shakyShane** [comment]
Have you checked the requirements?

http://www.browsersync.io/docs/#requirements

**Comment by bogatisuman** [comment]
Yes there is fulfill all requirement. For run browser-sync in moodle we need link to css file by <link > tag not through the config.php
