### ISSUE TITLE
Proxy not working with apache VHOST

### ISSUE THREAD

**Issue by unbug** [BrowserSync/browser-sync#520]
Here is my config,if I open it with `http://ilabs.mozat.com`,browserSync won't work,but if I open it with `http://ilabs.mozat.com:3000` it works.
```js
 browserSync({
      "proxy": "http://ilabs.mozat.com"
    })
````
or
```js
 browserSync({
      "proxy": "http://ilabs.mozat.com:80"
    })
````
My apache vhost is :
```shell
<VirtualHost *:80>
    ServerName ilabs.mozat.com
    //...
</VirtualHost>
```
Looks like browserSync does't response for port 80.

**Comment by nvioli** [comment]
That looks like expected behavior to me. browser-sync sets up a proxy on 3000 and communicates from there to your already-running server on 80. You need to connect to port 3000 to interact with browser-sync.
