### ISSUE TITLE
Just server files

### ISSUE THREAD

**Issue by thalesfsp** [BrowserSync/browser-sync#521]
How to server static files but **don't** launch/open the browser?
@shakyShane 

Thanks!

**Comment by shakyShane** [comment]
```js
require("browser-sync")({server: "./app", open: false});
```

:)

**Comment by thalesfsp** [comment]
Perfect! Amazing! :)
PS: Where's it on the docs?
Cheers!

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/options/#option-open
