### ISSUE TITLE
How to make Weinre works?

### ISSUE THREAD

**Issue by serraventura** [BrowserSync/browser-sync#523]
I'm wondering how to make Weinre works. I didn't find any mention on README file. Do I need to install Weinre separately?

I'm running browser-sync in a proxy way.

*browser-sync amazing tool!!!

**Comment by luisfmsouza** [comment]
Hi @serraventura,

You just need to access the UI URL. Chek on your command line.

After that, you just need to enable the Remote debugger.

Good luck!

**Comment by shakyShane** [comment]
as @luisfmsouza said :)

**Comment by serraventura** [comment]
That's why I opened this issue. I did that but the inspect elements tool from Weinre is not loading the html/css elements. I know if you use Weinre directly you have to include a js file in your website. Do I need to do the same with browser-sync?

Sorry, I didn't provide all the infos. I thought was setup missing.

**Comment by serraventura** [comment]
I think I'm getting confused. If I want to inspect element of my app running on Ipad in my desk machine. How should it work?

I remember I could do that with Weinre. It recognized which device loaded the js file then you could inspect the elements of that device.

**Comment by serraventura** [comment]
Hi guys,

I understood the issue now. Actually is not a big issue.

What happens is that if you open Weinre by first and then open your app after it, Weinre will not recognize your your app running. But if you do the opposite it works nicely.

So, run the commands, open the link for your app by first and afterwards you go to Weinre. In these steps it works fine.

my 1 cent

:)

**Comment by serraventura** [comment]
Another thing I've just realized.

When browser-sync disconnect your app Weinre lose the target and does not get it again. So, you need restart all the process from commands.

**Comment by b4z81** [comment]
thank you @serraventura
