### ISSUE TITLE
Navigation breaks when using AngularJS routes

### ISSUE THREAD

**Issue by lpelov** [BrowserSync/browser-sync#524]
Navigation between the opened tabs/browsers does not work with AngularJS application using routes. For example if the main application has following URL:

http://localhost:3000/app#/index

and when switching from this to:
http://localhost:3000/app#/index/5501a487b317c3ac316d10d0

the rest of the browsers does not follow this navigation.

**Comment by shakyShane** [comment]
We cannot support every frameworks flavour of navigation between routes - but you can give this a try

https://github.com/BrowserSync/browser-sync/issues/524

Also, you can use that project as a guide for how you can write your own plugins :)

**Comment by lpelov** [comment]
It was actually the normal AngularJS ngRoute, however I posted this because the issue could be probably not the Angular framework itself but the way you handle the URL change. 
Browser-Sync is really good tool the way it is, don't see reason to write own plugins for Angular. Looking after the code is no problem too, however you could fix this much faster, as you work with the code more frequently, and the issue I posted above is easy to reproduce, should not cost you much work.

**Comment by koomai** [comment]
@shakyShane I stumbled upon this because I'm having the same issue. Did you mean to link to another issue above in your comment? It links back here.
