### ISSUE TITLE
External URLs with Vagrant

### ISSUE THREAD

**Issue by adam-beck** [BrowserSync/browser-sync#526]
I have a Ubuntu Vagrant VM machine running on a Windows host and I'm using PuTTY as my SSH client. I have ports 3000 and 3001 mapped to the host machine so I have no problems accessing the Browser-Sync server and I'm able to see updates as they happen. 

My problem is that I want to take advantage of some of the other features like remote debugging but they are being sent to an odd IP address. For instance, once browser-sync runs it lists a `local` and `external` URL. I can access the `local` URL in my phone by using the IP address of my guest machine (`192.*:3000`). The `external` URL is `http://10.0.2.15:3000`. Is there a way for me to access that address externally? It seems *that* should be the one I use on my phone but it never connects.

I realize this may be a networking issue or a Vagrant issue, but was wondering if somebody else has come across this. I will admit I don't know much about networking and add on a visualization layer and I'm definitely out of the loop. My VM is reporting multiple adapters: `eth0`, `eth1`, and `lo`. `eth0` has the `10.0.2.15` IP address while `eth1` has the `192*` one.

**Edit**: This most likely seems like a Vagrant issue. It looks like browser-sync just uses the first available network adapter. I believe the default settings in Vagrant make the NAT connection the first. I was able to workaround this problem by switching the NAT to the 2nd adapter and the Bridged-Connection to the 1st. Now my `external` URL is using the `192.*`.

**Comment by adam-beck** [comment]
This can all be fixed by providing the ip of the VM in the `host` option. Duh!

**Comment by samsfisher** [comment]
I use vagrant VM on windows  too. but for some reason i am unable to see the browsersync ports 3001 or 3002. I have forwarded 3000,3001, 3002 to the host machine and i can see the website being served at localhost:3000

Can you please share your browsersync init settings.
Also did you set a static ip for your vagrant box.
