### ISSUE TITLE
running two servers?

### ISSUE THREAD

**Issue by sturobson** [BrowserSync/browser-sync#529]
I've got a project where I'm importing (via Bower) a (php based) pattern library that (as a standalone) works with BrowserSync (using connect-php). Is it possible to spin up a server for this subdirecty and one for the 'project' itself. So, for example I'd go to 

- localhost:3000 for the working library
- localhost:3001 for the UI
- localhost:3300 for the pattern library.

I'm using Gulp, and I'm guessing (if this is possible) that I'll be running the tasks from the project's Gulpfile.js rather than the one that's imported with the pattern library via Bower.

Is this possible? I can't seem to work it out from the splendid docs provided so I'm guessing I'm aiming a little too high in what I'm wanting.

If not possible, any other idea as to how to do this? Should I just have 

- localhost:3000 for the working library
- localhost:3001 for the UI
- localhost:3000/patterns for the pattern library

and just have anything needing to be watched or processed via their neccesary gulp plugins.

Thanks in advance <3

**Comment by shakyShane** [comment]
Hi @sturobson - Can I ask why you need `connect-php` at all? Why not just run the pattern library via php directly or through mamp/wamp etc?

If you did that, you could just have two php servers runnings (using different sub directories as their web root) and two instances of BrowserSync running also...

**Comment by shinnn** [comment]
> Why not just run the pattern library via php directly or through mamp/wamp etc?

@sturobson I want to hear your answer, too. The @shakyShane's way would be better.
