### ISSUE TITLE
Improve serving GZipped files

### ISSUE THREAD

**Issue by mietek** [BrowserSync/browser-sync#532]
It would be great if BrowserSync’s internal HTTP server could set the `Content-Encoding: gzip` and `Content-Type: …` headers for GZipped files, such as `*.css.gz`, `*.html.gz`, `*.js.gz`, and `*.svg.gz`.

Here’s what happens right now:
```
$ curl -I http://localhost:3000/_scripts.js.gz
HTTP/1.1 200 OK
Accept-Ranges: bytes
Date: Tue, 24 Mar 2015 17:33:50 GMT
Cache-Control: public, max-age=0
Last-Modified: Tue, 24 Mar 2015 17:33:18 GMT
ETag: W/"302d5-1171523850"
Content-Type: application/octet-stream
Content-Length: 197333
Connection: keep-alive
```

**Comment by shakyShane** [comment]
Sure you can, just need to add a little middleware and you'll be good to go.

I even made a recipe to show it in full working order. 
https://github.com/BrowserSync/recipes/tree/master/recipes/server.gzipped.assets

Enjoy :)
