### ISSUE TITLE
Manually tell BrowserSync a file has changed through CLI

### ISSUE THREAD

**Issue by hgl** [BrowserSync/browser-sync#533]
I'm using [watchman](https://github.com/facebook/watchman) to watch files, and once files changed, it will run my build step.

Currently, I ask BrowserSync to watch the build directory, which seems to be inefficient (watch source file change -> run build step -> watch build file change -> refresh browser).

I wonder if it's possible to manually tell BrowserSync to refresh the browser after my build step is done (watch source file change -> run build step -> refresh browser)?

Maybe something like:

```
$ browser-sync start --server app &
$ browser-sync refresh # browsers will be refreshed after this command is done

or by sending signal to the running browser-sync instance

$ browser-sync start --server app &
$ kill -HUP $!
```

Or I'm doing it wrong? What's the correct way to use BrowserSync when there is a build step involved?

**Comment by shakyShane** [comment]
@hgl - we want to implement this asap - but we are stuck on how to send signals between two node processes. https://github.com/BrowserSync/recipes/issues/2#issuecomment-88119183

If you could shed some light, we'd be extremely greatful.

**Comment by hgl** [comment]
I guess we can send signals via direct http requests? For example, `browser-sync start` starts a server, `browser-sync refresh` talks to the server via http to ask it to refresh. [karma](https://github.com/karma-runner/karma) uses this architecture for its `karma start` and `karma run` commands.

However, I now do realize a downside of manual refreshing:  BrowserSync is no longer able to know which files are changed. So it's no longer able to do a quick css update. Every manual fresh must fresh the whole page.

I now find out that by setting `reloadDelay` to `0`. It's actually pretty fast for BrowserSync to notice build file changes. The only problem I encounter is that if the html page is updated by the build step, BrowserSync sometimes refresh the browser to a blank page, manually refresh the browser again fixes the problem. I'm still yet to identify the cause. But fixing this should make BrowserSync very pleasant to use.

**Comment by shakyShane** [comment]
Ahhh the, http idea sounds perfect.

We could also send a bunch of files in the request no problem, why not

```js
# kick it off
browser-sync start --server --port 3000

# for file injection
browser-sync reload --port 3000 --files="core.css,styles.css"

# for normal reloading
browser-sync reload --port 3000
```

This sounds totally do-able to me - the only downside being that the port must be given each time to identify the running instance

**Comment by hgl** [comment]
> the only downside being that the port must be given each time to identify the running instance

`browser-sync reload` can read the same config file as `browser-sync start` does to find the port.

> browser-sync reload --port 3000 --files="core.css,styles.css"

How does this file injection work? To me it looks like telling BrowserSync to only reload those files.

**Comment by shakyShane** [comment]
Docs coming soon, but this is in 2.6.0 check the release notes
