### ISSUE TITLE
No browser change without reload (Gulp & Drupal)

### ISSUE THREAD

**Issue by alex4allofyou** [BrowserSync/browser-sync#534]
I am working on a Drupal-site, locally via Wamp, I use Gulp to watch and process Less-files. Problem is, I do not see any changes when editting files, only with reload of browser... I have tried Livereload too, but that one only works the first time, than it crashes.

This is the url of a site in wamp: http://localhost/sitename/

I start Gulp watch, than I open Browser-sync in CWD with this line:
browser-sync start --proxy "http://localhost/sitename/" --files "css/*.css"

When I do it opens the site, I see "Connected to Browsersync" with this url:
http://localhost:3000/sitename/

It watching files and also register editted files, yet, not browserinjections... The UI can be opened, everything seems to be working, but the most important part it leaves out. Very frustrating. 

I also downloaded Visual Studio as recommended, site has a Body-tag, the only thing that is different with Drupal is that the css-files are not seen as a link when you look at the sourcecode, but plain text, but that is normal for Drupal, could that be the cause?

OS: Windows 7
Browser: Latest Firefox

**Comment by OnkelTem** [comment]
Howdy!
I'm a Drupal user too. Recently had the similar issue. Drupal uses quirky ```@import``` for adding CSS, and this is not supported by BS afaik. Please try with this simple module:
https://www.drupal.org/project/link_css
It will replace ```@import```s with normal ```<link>```s

**Comment by alex4allofyou** [comment]
That did the trick! 

The stupid thing is, I did notice those imports, like I wrote, but because BS did change the addresses I thought it was not the major cause. 

Thanks for the help and module-link !!!

**Comment by hkirsman** [comment]
Nice! This works!
