### ISSUE TITLE
BrowserSync Notify

### ISSUE THREAD

**Issue by NgYueHong** [BrowserSync/browser-sync#538]
I hope that the notify setting can be upgraded to be able to disable default message but still can display specially requested to notify message.

I personally found that every time when page reload, it shows "Connected to BrowserSync" is very annoying, but I want to be able to display custom message from gulp when needed. Currently when the notify is disabled, the custom message will also not displayed as well.

Hope there will be an upgrade for this soon. Thank you.

**Comment by shakyShane** [comment]
@NgYueHong - the convention in other areas of the api is to have an override option.

I propose 

```js
var bs1  = require("browser-sync").create();

bs1.init({
    server: "./app"
});

// later in your code...
bs1.notify("Compiling templates, please wait...", {override: true});
```

**Comment by shakyShane** [comment]
browser-sync@2.6.9 will work as expected.

```js
var bs1  = require("browser-sync").create();

bs1.init({
    server: "./app",
    notify: false
});

bs1.watch('./app/*.css').on('change', function (file) {
    bs1.notify(file + ' changed');
});
```

**Comment by NgYueHong** [comment]
Great! Thanks a lot for your great work.

**Comment by olets** [comment]
@shakyShane I'm running some compilation, and then trigger browserSynch.reload(). Trying to set up a `(file + 'changed')`-type notification, but can't figure out where to build it in. The basic idea is

    var browserSync = require('browser-sync');
    gulp.task('browser-sync', function() {
        browserSync.init({
            server: {
                baseDir: 'compiled/'
            }
        })
    });
    gulp.task('browser-sync:reload', function () {
        browserSync.reload();  
    });
    // more tasks that call browser-sync:reload

How would this work?

**Comment by AlexGalays** [comment]
I see can't see any custom notifications if notify = false with @2.15.0

**Comment by cmalven** [comment]
I'm having the same issue in `2.18.7`. `bs.notify()` doesn't show anything if `notify: false` is in the config.

**Comment by shakyShane** [comment]
Fixed - will be released at some point today

**Comment by hlolli** [comment]
I'm on `2.23.6` if I do notify: false, I can't in any way send notifications, with or without override: true.

**Comment by mathisonian** [comment]
I'm seeing the same issue as @hlolli in 2.26.3.
