### ISSUE TITLE
UTF-8 support (attempt #2)

### ISSUE THREAD

**Issue by OnkelTem** [BrowserSync/browser-sync#541]
The original issue #377 is closed now and seems to not getting feedback. I'm opening this new one.
As I've reported [there] (https://github.com/BrowserSync/browser-sync/issues/377#issuecomment-84612079), the problem with UTF-8 persists on BS 2.4.0:
![Screenshot] (https://sc-cdn.scaleengine.net/i/9e55c0a6d02bed9fab80d1fe2ab67134.png)

**Comment by shinnn** [comment]
> #377 is closed now and seems to not getting feedback

This is not enough reason to open a new one. You shouldn't create duplicated issues.

**Comment by OnkelTem** [comment]
> This is not enough reason to open a new one. You shouldn't create duplicated issues. Just ping to the maintainer on #377.

What do you mean - under ping?
I've post my report here but the issue doesn't seem to be opened. Maybe I'm too quick, but yesterday another issue was closed w/o resolution, see the story here: https://github.com/BrowserSync/browser-sync/issues/540

**Comment by shinnn** [comment]
@OnkelTem 

I always post like below if the maintainer doesn't reply for a long time.

------

@shakyShane ping

------

This is widely used method to notify the user again and would be better than recreating issues :)

https://github.com/BrowserSync/browser-sync/issues/506#issuecomment-86788381
https://github.com/BrowserSync/browser-sync/issues/422#issuecomment-74709032
https://github.com/BrowserSync/browser-sync/issues/19#issuecomment-30044354

**Comment by shakyShane** [comment]
@shinnn is correct, please simply ping on an existing issue and we'll get around to it eventually - I know this doesn't seem ideal but we only have limited windows of time to work on issues - try to be patient with us :)

**Comment by OnkelTem** [comment]
@shinnn 
Gotcha! Didn't know ```@``` works here. Thanks!
