### ISSUE TITLE
BrowserSync and react

### ISSUE THREAD

**Issue by LynxDelli** [BrowserSync/browser-sync#543]
I try to use browser-sync with react app. It partially works but I have issues on state refresh.

```javascript
<input type="text" name="email" onChange={this.handleEmailChange} />{this.state.email}
```

input field change but not this.state.email binding. Any idea why the sample is not working?

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/5b4061e1def8e19e8df557937fdb9bccd3fce913/CONTRIBUTING.md#question
