### ISSUE TITLE
Embeder for browser-sync

### ISSUE THREAD

**Issue by LynxDelli** [BrowserSync/browser-sync#544]
Does it have something similar for gulp and browser-sync
https://www.npmjs.com/package/gulp-embedlr

**Comment by LynxDelli** [comment]
http://www.shakyshane.com/javascript/nodejs/2014/08/05/browser-sync-snippet/

**Comment by shakyShane** [comment]
you can also use the inline syntax for plugins now too, which makes it a little nicer.

```
browserSync({
    proxy: "local.dev",
    plugins: [
        {
            "bs-snippet-injector: {
                file: "path/to/your-footer.html"
            }
        }
    ]
});
```

:)
