### ISSUE TITLE
Do jQuery scripts not work in the tunnel?

### ISSUE THREAD

**Issue by srikat** [BrowserSync/browser-sync#548]
I am using Backstretch jQuery to display an image as a background for an element on my localhost site. I ran BrowserSync with tunnel option and checked in another computer and see that the the image background is missing.

Here's what it appears as: https://www.dropbox.com/s/q4jlt5pjhcxf342/Capture%20d'%C3%A9cran%202015-04-01%2019.16.38.jpg?dl=0

Here's what it should appear as: http://d.pr/i/175Z1

Viewing the HTML source, it shows the relevant code like this: http://pastebin.com/raw.php?i=vFU7qQcA

Any ideas?

**Comment by srikat** [comment]
Got it to work by changing the source of backstretch image in .js file from

`http://genesis.dev/wp-content/uploads/dynamik-gen/theme/images/picjumbo.com_austriaroad1.jpg`

to

`/wp-content/uploads/dynamik-gen/theme/images/picjumbo.com_austriaroad1.jpg`

**Comment by shakyShane** [comment]
@srikat - yep, the problem here is that links within your JS files are not rewritten - the solution as you've seen is to not put the domain in the links :+1:
