### ISSUE TITLE
Open pre-configured browsers

### ISSUE THREAD

**Issue by donaldpipowitch** [BrowserSync/browser-sync#551]
Is it possible for browser-sync to open pre-configured browsers on start-up? Similar like Karma and Protractor open browsers for tests.

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/options/#option-browser

**Comment by donaldpipowitch** [comment]
Sweet, thanks.

**Comment by shinnn** [comment]
@donaldpipowitch Also see https://github.com/BrowserSync/browser-sync/blob/eb76ac8ed934bfcd1ce66365446a295ee0ff6ecd/CONTRIBUTING.md#question
