### ISSUE TITLE
Feature Request: a way to pass options in BrowserSync Command Line

### ISSUE THREAD

**Issue by cachaito** [BrowserSync/browser-sync#552]
Instead of using the flag `--conf` to create whole new bs-config.js, I'd rather add one/ pack of options just from CLI. For example : `browser: "Chrome"` :-)

**Comment by shinnn** [comment]
Does the issue title really express what you're requesting? If so, yes, you're able to pass options to CLI. http://www.browsersync.io/docs/command-line/#command-line-options

This issue is very specific to `browser` option, right?

**Comment by cachaito** [comment]
I meant these [options](http://www.browsersync.io/docs/options/). Any idea how to change topic more accurate?

**Comment by shakyShane** [comment]
@cachaito - many of those options are already available, 'browser' is not currently one of them though - we'll look to add it.

**Comment by cachaito** [comment]
@shakyShane glad to hear! :-)

**Comment by cachaito** [comment]
It works like a charm :clap:
Please update documentation about this 'new' superb option for CLI and we can close ticket :-)
