### ISSUE TITLE
Cannot disable browser-sync injection into iframe

### ISSUE THREAD

**Issue by tomgenoni** [BrowserSync/browser-sync#553]
Ultimately, I am trying to prevent browser-sync (v2.5.2) from injecting into an iframe with a src of local content. 

I've tried to disabled it completely with:

    gulp.task('browser-sync', function() {
      browserSync({
        snippetOptions: {
          rule: {
              match: /xxx/
          }
        },
        server: {
          baseDir: [__dirname] + '/_build/',
        }
      });
    });

I've also tried ignoring all files:

    gulp.task('browser-sync', function() {
      browserSync({
        snippetOptions: {
          ignorePaths: "*.html"
        },
        server: {
          baseDir: [__dirname] + '/_build/',
        }
      });
    });

But these don't work (also tried `blacklist`) and the snippet is injected to both the parent and iframe. Am I missing something?

**Comment by AlbertRAR** [comment]
Same problem, trying to figure it out

**Comment by shakyShane** [comment]
Please provide a minimal working example that highlights this bug.

**Comment by askesian** [comment]
+1 Same problem here as well

**Comment by tomgenoni** [comment]
Set up a repo that demos the problem. Make a change to the parent `index.html` and browser-sync is injected into both the parent and iframe. I'd like to iframe to be ignored by browser-sync.

https://github.com/tomgenoni/browser-sync-iframe

**Comment by shakyShane** [comment]
@tomgenoni may thanks!

**Comment by shakyShane** [comment]
@tomgenoni - there was an error in your original gulpfile. `snippetOptions` is a separate option, but you had it nested under the `server` property.

Either way, in your example, with the latest update (2.7.2), this will work as expected.

```js
gulp.task('browser-sync', function () {
    browserSync({
        server:         {
            baseDir: [__dirname] + '/dist/'
        },
        snippetOptions: {
            blacklist: ["/iframe/index.html"]
        }
    });
});
```

**Comment by tomgenoni** [comment]
Thank you @shakyShane. I can confirm this works.
