### ISSUE TITLE
Url in ajax are not updated

### ISSUE THREAD

**Issue by stephanedemotte** [BrowserSync/browser-sync#557]
Hi !

I have (homestead/vagrant) with browsersync, everything works great except when i make a ajax call to a new page.

All the link in the new page are not updated. So when i click on it, i get redirect to the proxy url.
But when i refresh the page, all the link looks goods.

I make the call with jquery.

Anyone have a idea ?

thanks.

EDIT: 
I think the issue it's with proxy:

When i refresh the page all my link inside my page looks like :
href="//localhost:8001/en/test"

When i call the this page via ajax, i got: 
href="http://myproxyapp.app/en/test"

It's the same with all assets (videos, img etc...)
We got the proxy url.

**Comment by stephanedemotte** [comment]
nobody can help ?

It's relatively a serious bug :)

**Comment by shakyShane** [comment]
It's a bit mis-leading and we will be improving the interface for rewriting soon, but for now you can use `snippetOptions.whitelist` to force link-rewriting. 

**example from supporting ajax-loaded content in wordpress**

```js
browserSync({
    proxy: "local.dev",
    snippetOptions: {
        whitelist: ["/wp-admin/admin-ajax.php"], // put your ajax url here.
    }
})
```

**Comment by stephanedemotte** [comment]
but if all my link is in ajax ? i have to put all my link in the whitelist ?
or i can do something like that : whitelist: ["*"] ?

Thanks

**Comment by stevepiron** [comment]
`whitelist: ['/**']` works for me! (Craft CMS)

However, webfonts downloaded over localhost:3000 (`host:port` in the config) are not decoded properly:

```
Failed to decode downloaded font: https://localhost:3000/_assets/dist/80c2aeea6fe294d138b512b0795ae09e.woff2
OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Failed to decode downloaded font: https://localhost:3000/_assets/dist/32677772db32f111de3084ec7acc018c.woff
OTS parsing error: incorrect file size in WOFF header
Failed to decode downloaded font: https://localhost:3000/_assets/dist/107bddf8be449e12a66dcee270d70079.woff2
OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Failed to decode downloaded font: https://localhost:3000/_assets/dist/337265fe00c864f444529b9f96622ece.woff
OTS parsing error: incorrect file size in WOFF header
```

(both on my computer which is the host and on devices I'm testing the site on thanks to BrowserSync)
