### ISSUE TITLE
Open browser to a custom URL

### ISSUE THREAD

**Issue by dangelion** [BrowserSync/browser-sync#558]
Hi,
I'd like to automatically open the browser to a specific URL like `my-project.com:3000`, and not to `localhost:3000`.
I can't do it with `tunnel` option. Is it possible?

**Comment by shakyShane** [comment]
The `open` [option](http://www.browsersync.io/docs/options/#option-open) is for auto-opening one of the BrowserSync URLs. 

If you need a specific URL, just set `open: false` and perform that action yourself with something like the [opn](https://www.npmjs.com/package/opn) module :)

**Comment by Nirazul** [comment]
Hey! Sorry to necromancing this post, but does `open` work to open custom URLs as stated in the [Command Line Documentation](https://www.browsersync.io/docs/command-line/)?

> Choose which URL is auto-opened (local, external or tunnel), or provide a url

I've tried following command: `browser-sync start --proxy "10.0.1.166:8080" --files "WebClients" --open "http://some-custom-url"`

**Comment by gfdesign** [comment]
I have a similar question...
How do you specify an specic page when you init your Gulp project?

**Comment by coderofsalvation** [comment]
startPath seems to get mentioned in the docs, however it doesnt work for me:

```
gulp.task('browser-sync',  >() {
    browserSync.init({
      server: {
        baseDir: "./web",
        startPath: 'index.html#test'                                                                                                                                                                                               
      }
    })
})
```

**Comment by DrakeXiang** [comment]
@coderofsalvation The ```startPath``` is a sibling option of ```server```, not a child

**Comment by julius** [comment]
@dangelion This seems to work for me `{ "host": "my-project.com", "open": "external", "port": 3000 }`

**Comment by ctcpip** [comment]
in the hopes of saving someone else some time, later:

```
  browserSync.init({
    server: {
      baseDir: 'baseDirPath',
      index: 'index.html',
    },
    startPath: `index.html?query=something`
  });
```

**Comment by dancingfrog** [comment]
@ctcpip 
Such a joy to have someone actually comprehend _and_ answer a question. Thank you!

**Comment by mufaddalmw** [comment]
@ctcpip Thank you!

Just another example - 
`browserSync.init({
        server: "./dist",
        startPath: '/en/index.html',
});`
