### ISSUE TITLE
Usage of both `chalk` and `cli-color` packages

### ISSUE THREAD

**Issue by jbnicolai** [BrowserSync/browser-sync#563]
Is there a reason `browser-sync` depends on both [`cli-color`](https://github.com/medikoo/cli-color) and [`chalk`](https://github.com/sindresorhus/chalk)?

I ran into this running BrowserSync through Gradle, which (stupidly enough) doesn't tell the node subprocess it's running in a tty environment. Because of this color support is assumed absent. Luckily chalk supports the environment variable [`FORCE_COLOR`](https://github.com/sindresorhus/supports-color/blob/master/index.js#L5). Cli-color doesn't though, it seems.

Would a PR removing the cli-colors dependency be accepted?

**Comment by shinnn** [comment]
> Would a PR removing the cli-colors dependency be accepted?

Yes, really nice.

**Comment by jbnicolai** [comment]
@shinnn happy to.

I've done some searching, but is `cli-color` even used inside BrowserSync? I seem unable to find any reference.

**Comment by shakyShane** [comment]
No it isn't, maybe some dependency of another module?

**Comment by shakyShane** [comment]
cli-color is a dep of yui docs, which, being a devDependency, is not something we're worried about.

Just make sure, if you're installing browser sync manually to always give the `--production` flag - that's what npm does when you install and it will skip all development dependencies

:)
