### ISSUE TITLE
Password-protected pages on WordPress don't work when proxied

### ISSUE THREAD

**Issue by fregante** [BrowserSync/browser-sync#564]
URL: http://browsersyncprivatewp.altervista.org/password-protected-browser-sync-test/
1. Run `browser-sync start --proxy="http://browsersyncprivatewp.altervista.org/password-protected-browser-sync-test/"`
2. Enter the password `a`
3. Enjoy a blank page

Unsure if this issue applies to all POSTed urls.

Since you were actively advertising WP support, I thought you might be interested in knowing this bug.

**Comment by shakyShane** [comment]
Interestingly, the login actually works (if you try to view the post after it white-screened) - it looks like it was just the redirect that was handled incorrectly.

Thanks for the report & for especially for the live demo - this is invaluable to us :+1:
