### ISSUE TITLE
Issues with CORS in proxy mode

### ISSUE THREAD

**Issue by GregOriol** [BrowserSync/browser-sync#57]
In proxy mode, there seems to be possible to get into issues with CORS : if the code on the server side checks for Origin and sends the Access-Control-Allow-Origin header accordingly, the request could fail.

Would it be possible (or event a good idead) to make browser-sync detect and rewrite the header to match its own address ?

**Comment by Mattnificent** [comment]
The link isn't there anymore............

**Comment by arnevankauter** [comment]
is there any fix for this?
