### ISSUE TITLE
Needs newer version of gaze@0.6.4 to fix stat error but gaze won't compile on node@0.12 and iojs yet

### ISSUE THREAD

**Issue by jeffbski** [BrowserSync/browser-sync#570]
I am running into an issue with browserSync dying on hidden links created by emacs which is supposedly fixed in newer version of gaze@0.6.4. However gaze@0.6.4 won't compile on node@0.12.0 nor io@1.6.4, so probably need to wait on that to be fixed before upgrading gaze.

https://github.com/shama/gaze/issues/58 - this is the emacs fix that is in gaze@0.6.4
https://github.com/shama/gaze/issues/173 - this is the non-compiling on iojs issue. I think that non-compiling on node.js will also be fixed when this is resolved.

Here is an example stack trace of gaze throwing an exception in browserSync
```
(function (exports, require, module, __filename, __dirname) { // Maintainers,

Error: ENOENT: no such file or directory, stat '/Users/jeff/working/react-ex1-list/assets/.#site.less'
    at Error (native)
    at Object.fs.statSync (fs.js:843:18)
    at Gaze._addToWatched (/Users/jeff/working/react-ex1-list/node_modules/browser-sync/node_modules/glob-watcher/node512 bytes written to dist/bundle.js (0.60 seconds) assets/** -- npm run build-css
_modules/gaze/lib/gaze.js:277:14)
    at Gaze._internalAdd (/Users/jeff/working/react-ex1-list/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:191:10)
    at /Users/jeff/working/react-ex1-list/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:400:16
    at Array.forEach (native)
    at /Users/jeff/working/react-ex1-list/node_modules/browser-sync/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:396:12
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by shakyShane** [comment]
hi @jeffbski  - thank you for your report.

1. Gaze > 6.0 is not going to happen for the reasons you mentioned.
2. We are switching file-watching to chokidar VERY soon anyway which should solve this issue.

**Comment by jeffbski** [comment]
excellent. Thanks for the update.
