### ISSUE TITLE
UI interface

### ISSUE THREAD

**Issue by dhenriet** [BrowserSync/browser-sync#571]
Hi, can't find how to use UI interface ? In the http://www.browsersync.io/docs/command-line/ there is an option "--no-ui", that seems UI it is running but I do not have it ? How to launch it from the Command Line with Browser sync in global ?

**Comment by shakyShane** [comment]
Which mode are you running in? Server, proxy or snippet?

**Comment by dhenriet** [comment]
Hi, I am running with proxy

```php
browser-sync start --proxy "mywebsite.local" --files "assets/css/**/*.css, assets/js/**/*.js, views/**/**/*.php"
```

**Comment by shakyShane** [comment]
Just add `--open ui`

:)

**Comment by dhenriet** [comment]
thanks :)

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/options/#option-open
