### ISSUE TITLE
Add BrowserSync version number into UI

### ISSUE THREAD

**Issue by PJL101** [BrowserSync/browser-sync#577]
Hi,

This is a small idea but it would be lovely if BrowserSync mentioned its version number somewhere when using the UI.

Thanks!

**Comment by shakyShane** [comment]
Yes! Agreed.

**Comment by PJL101** [comment]
Could this be extended to do some sort of checking for update facility?

Phil Lennon | Frontend & WordPress Developer
0333 444 1250
http://akuda.co.uk

**Comment by shakyShane** [comment]
Grab the latest version & this is in the header :)

```sh
npm rm browser-sync && npm install browser-sync@latest --save-dev
```

**Comment by PJL101** [comment]
Amazing! Thanks for this.

**Comment by shakyShane** [comment]
No problem!

Don't forget to [vote for us](https://thenetawards.com/vote/open-source/browsersync/) if you're happy with the support/tool :)

**Comment by PJL101** [comment]
Done! browser sync is awesome. I use it in my frontend kit for freelancing with agencies and stuff: https://github.com/Akuda/fedkit-assemble

**Comment by shakyShane** [comment]
Very nice :)
