### ISSUE TITLE
Error: Cannot find module 'inherits'

### ISSUE THREAD

**Issue by RakanNimer** [BrowserSync/browser-sync#580]
Hey !

I'm using browser-sync version 2.6.4 on OSX Yosemite to proxy my node server. 
I got this error while running gulp browser-sync.
JS code : 
```js
gulp.task('browser-sync', function() {
  browserSync.init(null, {
    proxy: "http://localhost:8080",
        files: ["public/*"],
        browser: "google chrome",
        port: 8080,
  });
});
```
I Fixed it by installing inherits module : 
```
npm install inherits
```
As soon as I did that it worked.

Any idea if the module is missing from browser-sync or one of it's dependencies ?

Thanks !

**Comment by thebuilder** [comment]
Try and do a clean npm install. (Delete node_modules, and install again). It might have missed the dependcy when you installed browser-sync, but a clean install will find it.

**Comment by shakyShane** [comment]
as @thebuilder says...

These automated tests ensure we don't mess up on installs https://travis-ci.org/BrowserSync/browser-sync/builds
