### ISSUE TITLE
Chrome Canary and Firefox Developer Edition

### ISSUE THREAD

**Issue by svsudhir** [BrowserSync/browser-sync#582]
How to use the Browser Option to load Chrome Canary and Firefox Developer Edition instead of regular Chrome and Firefox?

Thanks

**Comment by shinnn** [comment]
Platform dependent.

**Comment by ZuBB** [comment]
Hi @shinnn 

Is it possible to pass into config name of other browser?

```
// here 
var browserSync = require('browser-sync').create();
...
// or here
     browserSync.init({                                                          
           files: cadreonConsole_dist_folder + '/*',                               
           server: {                                                               
               baseDir: cadreonConsole_dist_folder                                 
           }                                                                       
       });                                                                         

```

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum

**Comment by shakyShane** [comment]
@shinnn - can we choose a new default response for this type of situation as the line `You are likely to be ignored, or written off as a loser, if you:` can come across quite rude to english speakers.

I appreciate the need to lock down question-based issues like this, but I think we can do it in a way that has zero chance of offending anyone :)

**Comment by shinnn** [comment]
@shakyShane Ah, OK. I'll try to be kind next time.

**Comment by shakyShane** [comment]
![thumbs up](http://i.giphy.com/lFlZd7ZmoUqVa.gif)
