### ISSUE TITLE
--config does not take absolute path

### ISSUE THREAD

**Issue by xkxx** [BrowserSync/browser-sync#583]
Hello,

Currently --config does not take absolute paths. For example, doing something like this throws an error:

```
> browser-sync start --config /etc/bs-config.js

module.js:318
    throw err;
    ^
Error: Cannot find module '/path/to/cwd/etc/bs-config.js'
```

This is caused by `browser-sync/lib/cli/cli-info.js:28`:

```js
        return require(path.resolve(process.cwd() + "/" + filePath));
```

Which tries to resolve relative url by prepending process.cwd(), but that's the job of `path.resolve`.
Changing this line to the following does the correct thing, and fixes the issue:

```js
        return require(path.resolve(process.cwd(), filePath));
```

Thanks,

Kexiang

**Comment by shinnn** [comment]
Confirmed. Thanks for your detailed reporting, @xkxx.

**Comment by shakyShane** [comment]
thanks @xkxx - but where is the PR ? :p

**Comment by xkxx** [comment]
I thought about it, but then thought it was too trivial to be worth a PR - hope I have provided enough info for you guys to fit it :)

**Comment by shakyShane** [comment]
Nothing is too trivial for a PR :)

**Comment by xkxx** [comment]
Speaking of trivial PRs, would you mind taking a look at https://github.com/shakyShane/html-injector/pull/5?
It fixes a problem with browser-sync failing when ui is disabled. Travis CI test is failing, but I don't really know about the inner-workings of the module to get what's going on.

**Comment by shakyShane** [comment]
Ahh yeah I saw that - it's on the list for the next round of bug fixes / pr's :)
