### ISSUE TITLE
How  can i set alias

### ISSUE THREAD

**Issue by huazone** [BrowserSync/browser-sync#584]
Whether can set up an alias to the server data interface alias, for example

Listen 1088
<VirtualHost *:1088>
    ServerName localhost
    DocumentRoot "D:/wintour/root/xm_baixiang_group/html"
    Alias /assets/ "D:/wintour/root/xm_baixiang_group/assets/"

    ProxyPass /saas http://192.168.0.9:7002/Saas
    ProxyPassReverse /saas http://192.168.0.9:7002/Saas
    ProxyPass /DossmAPI http://192.168.0.14:997
    ProxyPassReverse /DossmAPI http://192.168.0.14:997
</VirtualHost>

I have to set "Alias" and "ProxyPass", but In the browser - sync, I don't know how to set up

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#writewell
