### ISSUE TITLE
Don't insert snippet in proxy mode when it inserted by backend.

### ISSUE THREAD

**Issue by generalov** [BrowserSync/browser-sync#586]
I use this regexp to prevent insertion of `__bs_script__` snippet in proxy mode when it inserted by backend.
```JavaScript
snippetOptions: {
        rule: {
                match: /<body[^>]*>(?![\s\S]*__bs_script__)/i
            }
        }
```
Perhaps it should be the default?

**Comment by shakyShane** [comment]
BrowserSync is designed to be used in either snippet, server or proxy mode - your solution is sound should you want to combine the proxy with the manual snippet, but it's not a common enough use-case for us to modify the core.

:)
