### ISSUE TITLE
PHP Browser Reload

### ISSUE THREAD

**Issue by jackfearing** [BrowserSync/browser-sync#591]
Hi Shane, I've been using the following function (see below) for awhile now which triggers the browser to reload once a PHP file has been changed. I recently updated the browser sync plugin to the latest version and I noticed the function no longer works. I'm also using the same function to run a sass function which works perfectly but for some reason browser sync doesn't want to reload the browser if PHP files have changed. I've tested to make sure the function was working by adding a notify message which does fire when the PHP file changes. I'm wondering if something in the function below has been deprecated? Any help you could provide would be great.

```js
gulp.task('php', function () {
	gulp.src('./')
		.pipe(watch(['*.php','**/*.php','!node_modules/**/*.php','!library/translation/*']))
		.pipe(browserSync.reload({stream:true}))
		.pipe(notify({ message: 'PHP task complete'}));
});
```

**Comment by shakyShane** [comment]
With the latest version this works fine for me (2.6.9).

Feel free to provide a sample repo that demonstrates this bug if you still cannot get it working & we'll re-open the ticket.
