### ISSUE TITLE
atom-shell asar package support

### ISSUE THREAD

**Issue by popopome** [BrowserSync/browser-sync#592]
I'm developing windows desktop application with [electron](https://github.com/atom/electron) (aka atom-shell). My app uses `browser-sync` inside. 
When I created asar package(a kind of tar package) and then launched my app,
it was crashed. I got an stack trace, and found the source of problem was `'File Not Found exception'` at `node_modules/browser-sync-ui/lib/hook.js`, `Ln: 11`.

I found the final path for template file had mixed path separators as `/` and `\`. I believe the normal file access case has no problem, but `asar` package cannot handle well when path separators are mingled.

So I changed the code by using `path.join` method, then the problem was fixed.
```
function templateFile (filepath) {
    return fs.readFileSync(path.join(__dirname, "/../templates", filepath || ""), "utf-8");
}
```

Please check the path has valid form for the template file.

**Comment by shakyShane** [comment]
thanks @popopome  - all fixed in latest
