### ISSUE TITLE
updates changes only once 

### ISSUE THREAD

**Issue by Maxlufs** [BrowserSync/browser-sync#593]
![screenshot from 2015-04-27 09 53 51](https://cloud.githubusercontent.com/assets/3827048/7352782/534b6c36-ecc3-11e4-8a56-c6f6ead1fdeb.png)

Hi, not sure what went wrong or how to debug this.
So everytime i start browser-sync (either globally or locally), the server stops watching after the first change.
Any input would be helpful. Thank you!

I tried using both npm version and github version.

**Comment by shinnn** [comment]
I cannot reproduce the problem on my Mac OS X.

* Which OS?
* Please show use the result of:
  
  ```
  $ node -v
  $ npm -v
  $ browser-sync --version
  ```

**Comment by Maxlufs** [comment]
Linux ubuntu 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```sh 
$ npm -v
1.3.10
$ node -v
v0.10.25
$ browser-sync --version
2.6.5
```

**Comment by shinnn** [comment]
You're using too outdated `node` and ancient `npm`. Could you update them to the latest stable versions and try again?

Regardless of this issue I recommend updating them.

**Comment by Maxlufs** [comment]
```sh
$ node -v
v0.12.2
$ npm -v
2.7.4
$ browser-sync --version
2.6.5
```

still not updating after the first change... same thing in different browsers.
Is there a possibility that port binding is wrong or maybe a way to debug it?

Thanks a lot!
PS. Thanks for reminding me to update node.

**Comment by Maxlufs** [comment]
![screenshot from 2015-04-29 15 32 22](https://cloud.githubusercontent.com/assets/3827048/7402862/fb277f18-ee84-11e4-927c-ef6af14915cc.png)

**Comment by shinnn** [comment]
@Maxlufs Have you run into any errors when installing browser-sync?

**Comment by Maxlufs** [comment]
![screenshot from 2015-04-29 15 55 30](https://cloud.githubusercontent.com/assets/3827048/7403201/3563960a-ee88-11e4-8f4e-d9fbb1a47c23.png)

**Comment by Maxlufs** [comment]
@shinnn 
![screenshot from 2015-04-29 15 56 49](https://cloud.githubusercontent.com/assets/3827048/7403214/5d4e3d46-ee88-11e4-9c81-75ac627db5f8.png)

**Comment by Maxlufs** [comment]
interestingly i solved the problem when using `--files: "*"`..
only using `--files:"index.html"` stops reloading page after the first time,

Any ideas?

**Comment by shinnn** [comment]
Glad to hear you solved the problem, but I don't know why your solution works. And, I still cannot reproduce the problem.

@shakyShane Any idea?

**Comment by shakyShane** [comment]
I cannot reproduce this, but even if we could it's likely an issue with chokidar (the watcher we use) and *not* directly a bug with Browsersync.

@Maxlufs - can you try reproduce this using the [chokidar](https://github.com/paulmillr/chokidar) library directly - if you can, you should head over to their issue tracker and report the problem :)
