### ISSUE TITLE
Release 2.6.6 is not appearing on NPM

### ISSUE THREAD

**Issue by vinnymac** [BrowserSync/browser-sync#595]
When I check [Browser-Sync's npm](https://www.npmjs.com/package/browser-sync) the latest version is 1.9.2.
I tried `npm outdated browser-sync` and this is what I see.

![Browser-Sync 1.9.2](http://i.imgur.com/2ffWAga.png)

**Comment by shakyShane** [comment]
Please run `npm install browser-sync@latest --save-dev` again :)
