### ISSUE TITLE
Vagrant Shared Folder Editting

### ISSUE THREAD

**Issue by MByteIO** [BrowserSync/browser-sync#596]
I have Vagrant set up as a proxy and it appears to work as long as I am editing on the Vagrant box which I have browser-sync installed on. However, when I edit the file using a shared folder that connects to the web root of the project that browser sync is monitoring, browser-sync does not recognize the edits I make. On top of that, the edits that I make (and save) are not being displayed even if I refresh the website. However, the edits do appear if I go to the web address that's not behind the browser-sync proxy. It's almost like browser-sync is caching the file or something?

Can anyone recommend a fix for this?

**Comment by shakyShane** [comment]
Thank you taking the time to report this problem.

This could be an issue with BrowserSync, but right now I cannot be sure - so I'll close this for now.

Should you be able to reproduce this issue in a small sample project, please link us to the repo with details about how to set it up & how to see the issue. Once we've verified this is an issue with BrowserSync itself - we'll re-open this ticket and work to resolve it asap. Thank you,  you're helping everyone in the community by reporting any issues you come across :)

**Comment by adam-beck** [comment]
I'm seeing this problem as well. I have a feeling this isn't an issue related to browser-sync but more of a filesystem/OS/VM software issue (but I only do front-end work so take this with a grain of salt). I don't know how you want me to go about setting up a repo for you to reproduce this issue. It would require setting up a vagrant machine as well.  But it's as if, when you have a synced folder between VM and Host, it doesn't recognize that the file has changed on the *adjacent* machine. Browserync does not produce any log output that a file has changed *unless* the change came from the machine that launched browsersync. 

For instance, I can run BS from my Host OS and then changes appear but when I edit and save the same file in my VM it is not recognized. And if I run BS from my VM and make changes it works but not when I make changes to the same file from the Host OS. 

@TimeTravelersHackMe are you on a Windows host?

**Comment by adam-beck** [comment]
Okay I'm only seeing this when using the `files` option. If I use `gulp.watch` the changes seem to be noticed from either end (VM or host).

**Comment by joaovpmamede** [comment]
@adam-beck Are you using BS on your Host? Is it fast?
Mine is really slow, even on opening the page.

Every change that I make takes more than 40sec but I can see on my terminal that the file was generated almost instantaneously (e.g. running node-sass).

**Comment by TimeTravelersHackMe** [comment]
what software does browser-sync use to setup the localhost website?

**Comment by TimeTravelersHackMe** [comment]
@adam-beck I was on a Mac before but now I plan on getting this to work on Ubuntu VM <-> Windows environment and a Ubuntu VPS <-> Windows environment
