### ISSUE TITLE
Emit an event when browserSync is about to exit

### ISSUE THREAD

**Issue by binarykitchen** [BrowserSync/browser-sync#597]
Would be useful for our project, so that we can do some cleanup, i.E. kill other backend processes. Thx

**Comment by shinnn** [comment]
`bs.server` emits the `close` event.

```js
var browserSync = require('browser-sync');

browserSync({server: 'dist'}, function (err, bs) {
  bs.server.close();
  bs.server.on('close', function() {
    console.log('closed');
  });
});
```

**Comment by binarykitchen** [comment]
Not really. I mean an event for when `browserSync.exit()` is called, with the cleanup inside.

**Comment by binarykitchen** [comment]
Because `bs.server.close()` is not really exiting and can be used for restarting the server.

**Comment by shinnn** [comment]
> I mean an event for when `browserSync.exit()` is called

If you expect a faster and more correct answer, you should write it in the first issue comment. 

Read this article again and again. http://www.catb.org/esr/faqs/smart-questions.html

**Comment by binarykitchen** [comment]
right, sorry

**Comment by shinnn** [comment]
Perhaps [exit-hook](https://github.com/sindresorhus/exit-hook) module meets your requirements.

```js
var exitHook = require('exit-hook');
var browserSync = require('./');

exitHook(function() {
  console.log('exiting');
});

browserSync.exit();
```

**Comment by binarykitchen** [comment]
could do @shinnn but why the need for an additional module when browserSync already comes with event emitter handling?

**Comment by shinnn** [comment]
You can also add a listener to the `service:exit'` event.

```js
var browserSync = require('browser-sync');

browserSync.emitter.on('service:exit', function() {
    console.log('exiting');
});

browserSync.init();

setTimeout(function() {
    browserSync.exit();
}, 400);
```

**Comment by binarykitchen** [comment]
yes, that's what i am after, thanks! maybe you want to document this for others?

**Comment by shinnn** [comment]
@shakyShane The `service:exit` event is a public event and won't be changed/removed in the future? If it's just an internal event, my suggestion to use the event https://github.com/BrowserSync/browser-sync/issues/597#issuecomment-97628835 is wrong.

**Comment by shakyShane** [comment]
Whilst poorly named, some plugins are already using them - so `service:running` & `service:exit` are here to stay.

2 things worth noting here

1. [if Browsersync was never running, the event won't fire](https://github.com/BrowserSync/browser-sync/blob/master/lib/public/exit.js#L10-L13)
2. all public API methods are deliberately separate from the main code base, so have a poke around and you'll often find the answer https://github.com/BrowserSync/browser-sync/tree/master/lib/public
