### ISSUE TITLE
New Hotness doesn't do css injection

### ISSUE THREAD

**Issue by peterfoeng** [BrowserSync/browser-sync#601]
Hi @shakyShane,

I am referencing this issue #573 and trying out the new hotness as per your comment, but could not get the css injection to work. However the old school way is working just fine. Here is my setup:

```
OS: Yosemite (10.10.3)
Gulp: 3.8.11
browser-sync: "~2.6.9
node: 0.12.2
npm: 2.8.3
```

```js
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();
var config      = require('../config').browserSync;

gulp.task('browserSync', function() {
  browserSync.init({
    proxy: 'http://local.dev'
  });
});
```

```js
var gulp         = require('gulp');
var sass         = require('gulp-sass');
var sourcemaps   = require('gulp-sourcemaps');
var handleErrors = require('../util/handleErrors');
var config       = require('../config').sass;
var autoprefixer = require('gulp-autoprefixer');
var browserSync  = require('browser-sync').create();

gulp.task('sass', function () {
  return gulp.src('sass/main.scss')
    .pipe(sourcemaps.init())
    .pipe(sass(config.settings))
    .on('error', handleErrors)
    .pipe(sourcemaps.write())
    .pipe(autoprefixer({ browsers: ['last 2 version'] }))
    .pipe(gulp.dest(config.dest))
    .pipe(browserSync.stream({match: "*.css"}));
});
```

I must be doing something wrong here, otherwise the old school way without create instance is working as expected. Cheers

**Comment by shakyShane** [comment]
should be `browserSync.stream({match: "**/*.css"})` :)

**Comment by shakyShane** [comment]
Updated the release notes to reflect this

**Comment by joemaller** [comment]
Those two asterisks just totally tripped me up as well. 

Is there an ETA for updating the docs site to include the new stream method? Do you want PRs for that?

**Comment by shakyShane** [comment]
Updating docs as we speak - but yeah for future reference all PRs are welcome - especially documentation fixes which are in most cases more useful than code fixes for me

**Comment by shakyShane** [comment]
Updated http://www.browsersync.io/docs/api/#api-stream
