### ISSUE TITLE
/browser-sync/socket.io 404ing

### ISSUE THREAD

**Issue by OwenMelbz** [BrowserSync/browser-sync#602]
Hi Guys,

I'm trying to use grunt and browersync 2.6.9 together, its nearly working.

I believe my issue stems from the fact we need to access the proxy url to develop on rather than the localhost:3000 generated.

this is the task from my gruntfile
```js
browserSync: {
            default:{
                files: {
                    src : _config.views_watch.concat([_config.less_bundle])
                },
                options: {
                    watchTask: true,
                    open: false,
                    proxy: (_config.proxy || 'localhost'),
                    ghostMode: {
                        clicks: _config.clicks,
                        forms: _config.forms,
                        scroll: _config.scroll
                    }
                }
            }
        },
```

so when I run grunt it launches http://localhost:3000/ and everything runs fine.

However the apache server vhost I'm proxying (owen.fatfriday.com) is the url we need to access.

so when this launches the browsersync JS kicks in (hardcoded in the footer)

```
<script type="text/javascript" id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://localhost:3000/browser-sync/browser-sync-client.2.6.9.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

However browserSync then tries to poll the proxy url, which 404's on socket.io
```
GET http://owen.fatfriday.com/browser-sync/socket.io/?EIO=3&transport=polling&t=1430652663423-0 404 (Not Found)
```

when I manually visit http://localhost/browser-sync/socket.io the file exists, however due to browserSync using the `document.location` I'm guessing this is causing the issue.

I noticed the socket option in the docs -> http://www.browsersync.io/docs/options/#option-socket

However cannot find the correct mixture to allow me to view the website using browsersync and livereload via the apache powered url.

Help would be apperciated

**Comment by shakyShane** [comment]
If you're using the snippet manually and are happy with accessing your website via your original address, then you shouldn't be using the proxy option at all. Just remove `proxy: (_config.proxy || 'localhost')` and you'll be in 'snippet' mode where everything will work as expected.

**Comment by OwenMelbz** [comment]
Ah, you sir are a fking wizard! thanks been pulling my hair out for hours with that

**Comment by shakyShane** [comment]
:+1: 

I'm interested to hear how this could've been clearer for you though.

**Comment by OwenMelbz** [comment]
To be honest, a simple note within the documentation on the proxy option suggesting in a situation where you want to use the external domain to access it rather than the proxy itself then to use just the static snippet would suffice, then at least while reading through the options to understand them it would be pointed out.

**Comment by OwenMelbz** [comment]
Actually picking back up on this, today I noticed that now that the proxy is completely disabled, there is no way for other machines on the network to be able to access the site.

So I guess could we re-open to find a solution to allow the proxy to be turned on but work with the vhost as well.

Thanks
