### ISSUE TITLE
Changing a markdown file in Grav CMS

### ISSUE THREAD

**Issue by Wikunia** [BrowserSync/browser-sync#603]
Hey guys,

I would like to change an article of my blog (by changing a markdown file) and see the change directly inside the browser. Tried `browser-sync start --proxy "localhost:81/Wikunia/blog" --files "*"` which doesn't work. Am I doing something wrong or isn't it possible at all? 
I am using the grav cms (http://getgrav.org)
Thanks for any ideas!
Have a nice weekend.

**Comment by shakyShane** [comment]
`--files "*"` will only match files in the root.

Try `browser-sync start --proxy "localhost:81/Wikunia/blog" --files "path/to/markdown/**/*.md"

**Comment by Wikunia** [comment]
Perfect thanks!
