### ISSUE TITLE
Help with freeing browser-sync ports on sub-process exit

### ISSUE THREAD

**Issue by thasmo** [BrowserSync/browser-sync#605]
When running browser-sync in a sub-process and killing it, it seems like that browser-sync doesn't stop running.

I'm using the following task to start a gulp sub-process (running browser-sync) and if the Gulpfile changes, the process gets restarted:
``` js
gulp.task('default', function() {
	var process,
	    watch = function () {

		    // kill running process
		    if(process) {
			    process.kill();
		    }

		    // spawn new process
		    process = child.spawn(os.platform() === 'win32' ? 'gulp.cmd' : 'gulp', ['watch'], {
			    stdio: 'inherit'
		    }).on('exit', function () {
			    console.log('Restarting watch task');
		    });
	    };

	// start watch task
	watch();

	gulp.watch(['gulpfile.js'], watch);
});
```

The watch task looks like this (simplified):
``` js
gulp.task('watch', function() {
	server.init(config.plugin.server, function() {
		gulp.watch('public/**').on('change', function(file) {
			if(!file.path.match(config.task.watch.exclude)) {
				server.reload(file.path);
			}
		});
	});
});
```

On the initial run browser-sync opens a browser window on port 3000 and the UI runs on port 3001. When the `watch` function runs a second time the process gets killed and a new one gets started, the problem is that browser-sync now runs on port 3001 and the UI on 3002. The *old* browser-sync server still runs. On ports 3000 and 3001.

Shouldn't the old browser-sync instance exit when the process gets killed?

**Comment by shakyShane** [comment]
Fixed in v2.9.2

https://github.com/BrowserSync/browser-sync/commit/d1c26148199f0cc71cc203b49523b1bdb24d0333
