### ISSUE TITLE
2.6+ shows Disconnected from BrowserSync message

### ISSUE THREAD

**Issue by newelement** [BrowserSync/browser-sync#606]
I also noticed it keeps polling instead of using websockets like 2.5 does. I'm using this with a Wordpress site and proxy. You can test this by downloading the https://roots.io/sage/ theme. Roots will want to install 2.5, but if you install 2.6.11 or 2.7 and run gulp watch you will see the issue.

**Comment by shakyShane** [comment]
fixed in 2.7.1

Sorry for any problems this caused.
