### ISSUE TITLE
BS v.2.6.11 stops injecting/reloading in proxy mode

### ISSUE THREAD

**Issue by Nirazul** [BrowserSync/browser-sync#607]
I have a Python-Django Server setup with Gulp + BS as frontend stack. When I was updating dependencies I noticed that browser-sync stopped injecting/reloading. I pinned the last working version down to 2.6.10, so the problem must have been introduced in 2.6.11.

My logfile shows that regularly a call is made that ends in a 302 redirect on the localhost:
```
[05/May/2015 09:30:48] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=1XR565zCORghirTzAAAA HTTP/1.1" 302 0
[05/May/2015 09:30:50] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=9XHtEJIVMfeMufGVAAAB HTTP/1.1" 302 0
[05/May/2015 09:31:58] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=DRHl4Tp1u1ZS2wFUAAAC HTTP/1.1" 302 0
[05/May/2015 09:33:05] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=uTvod25BO6oyimG_AAAD HTTP/1.1" 302 0
[05/May/2015 09:34:13] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=r_APjfeW8M2p0vyXAAAE HTTP/1.1" 302 0
[05/May/2015 09:35:21] "GET /browser-sync/socket.io/?EIO=3&transport=websocket&sid=wnCTnoiD6gOByqArAAAF HTTP/1.1" 302 0
```

gulpfile (sass relevant part): 
```
module.exports = function(gulp, $, config, util) {
    //** Dependencies **//
    var browserSync = require('browser-sync');
    var path = require('path');

    //** Task **//
    gulp.task('sass', [], function(){
        var env = util.env();
        var hasError = false;

        return gulp.src(config.sass.src.files)
            // Report errors and keep watching
            .pipe( $.plumber({ errorHandler: util.error }) )
            // Compile sass
            .pipe( $.sass() )
            // Write stream
            .pipe( gulp.dest(config.sass[env.name].path) )
            // Update browser
            .pipe( $.gulpif( function(){ return hasError; },
                    $.gutil.noop(),
                    browserSync.reload({ stream: true })
                )
            );
    });
}
```

bs config:
```
{
    proxy: 'localhost:8000',
    snippetOptions: {
        ignorePaths: "**/{admin}/**",
        rule: {
            match: /<\/body>/i,
            fn: function (snippet, match) { return snippet + match; }
        }
    }
}
```

Additionally I've got a question regarding my gulpfile which is split up into multiple subfiles. I'm not sure how to handle the "new" way of using BS. Do I need to initialize the plugin at evey location with `require('browser-sync').create()` ?
It appears to me that the documentation in various places lacks behind the current code.

**Comment by shakyShane** [comment]
Please try `2.7.1` - there was a regression with the proxy that is now resolved.

**Comment by Nirazul** [comment]
I'll be damed... I'm almost totally sure that I tried the latest version yesterday and it failed...
Sorry for wasting your time and thanks for the quick help :)

**Comment by shakyShane** [comment]
I released a patch  this morning :)

**Comment by Nirazul** [comment]
Ah well that explains it, thanks :)

Could you answer my question at the bottom of my first post regarding what to do on split up gulpfiles?
I'm using `require-dir` to load my tasks and don't know if I need multiple instances of browser-sync by using `require('browser-sync').create()` or if no, how I should share the bs instance accross my task files.

**Comment by shakyShane** [comment]
You can name each instance, so in the entry file.

```js
var bs = require('browser-sync').create('awesome-name');
```

and then elsewhere you can do 

```js
var bs = require('browser-sync').get('awesome-name');
```

**Comment by Nirazul** [comment]
Nice, thank you!
