### ISSUE TITLE
Not auto refreshing

### ISSUE THREAD

**Issue by karneaud** [BrowserSync/browser-sync#609]
So i was able to install browser-sync on my windows 7 and while i'm running a local xampp server i entered on the cmd line....

`browser-sync start --proxy="http://localhost/cxc" --files="index.html, wp-content/themes/cxc/style.css"`

then i got

`[BS] Proxying: http://localhost
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000/cxc
    External: http://192.168.0.2:3000/cxc
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.2:3001
 ----------------------------------------
[BS] Watching files...
`
Accessed the url and the UI as i should....however when updating the file the browsers are not "auto refreshing" 

is there something else I should have done?

**Comment by shinnn** [comment]
@karneaud

Could you tell us:

* Node version
* browser-sync version

**Comment by karneaud** [comment]
Hi!,

Think I figured it out.... I needed to watch files OUTSIDE of the current working directory(which I thought was the directory set by "proxy" and NOT where I executed browser-sync) 

Seems like I have things running successfully now. Just for the record I'm using yoeman/  grunt-browser-sync

**Comment by shinnn** [comment]
@karneaud Glad to hear you've solved the problem.
