### ISSUE TITLE
browser-sync http server too slow or pending when gulp task is running

### ISSUE THREAD

**Issue by camsong** [BrowserSync/browser-sync#614]
I'm using BrowserSync as a http server together with gulp, my workflow is nothing special, whenever I made a `scss` change, it will rebuild scss and reload the browser.

However, every time after I made a `scss` change, it will take around `10s` to build, at the same time, when I refresh the browser to manually reload, it will keep pending for about `15s`, but the `html` files is just there, so I suppose it should work as a simple http server always. Is this doable or not?
thanks!

```
gulp.watch(['src/sass/**/*.scss'], ['build:sass']);
# did a reload in `build:sass` task.
```

```
gulp.task('browserSync', function(){
  return browserSync.init({
    server: {
      baseDir: './public'
    },
    reloadDelay: 1000
  });
});
```

**Comment by shinnn** [comment]
> every time after I made a `scss` change, it will take around `10s` to build

That's an issue with the `build:sass` task.

> the `html` files is just there,

Whether HTML files exist or not has nothing to do with this issue.

------------------------

Could you create a small repository that can reproduce the problem you're running into?

**Comment by shinnn** [comment]
@camsong https://github.com/BrowserSync/browser-sync/issues/614#issuecomment-100289137

> Could you create a small repository that can reproduce the problem you're running into?

**Comment by camsong** [comment]
not big issue after we optimised sass task.
