### ISSUE TITLE
CSS is not getting applied when file is not in same folder as index

### ISSUE THREAD

**Issue by eternalstudent2015** [BrowserSync/browser-sync#615]
Hi,

Greetings.

I have issues with CSS not getting applied on html elements. 

styles.css ->
```css

label {
  color: GREEN;
  font-weight: bold;
  display: block;
  width: 150px;
  float: left;
}
```
And
gulpfile.js
```javascript

'use strict';
var gulp = require('gulp');
var browserSync = require('browser-Sync').create();

gulp.task('bs', function() {
    browserSync.init({
        server: {
            baseDir: 'src/client'
        }
    });
});

```
And index.html
```html

<!DOCTYPE html>
<html>
  <head lang="en">
      <meta charset="UTF-8">
      <title></title>

    <link rel="stylesheet" href="../../.tmp/styles.css">

  </head>
  <body>
      <label> This will succeed!</label>
  </body>
</html>
```
And folder structure is: -
![folderstructure](https://cloud.githubusercontent.com/assets/12291261/7531194/85e499a2-f573-11e4-89eb-923296ea6c13.jpg)

The problem is with the CSS link. When I run gulp task

$ gulp bs

index.html opens BUT CSS is not applied on html element.

I tried with all permutation and combination with respect to href link, using following web page instructions (just to find out where I am making mistake)
http://www.mediacollege.com/internet/html/hyperlinks.html

Also, tried adding .tmp folder to base directory, as below but it has not change on end result:-
```
baseDir: ['.tmp', 'src/client']
```
But, in all above scenarios, if I open the index.html either using IDE, or directly typing folder in path in browser, index.html opens AND CSS is applied on html, but not from gulp task.

NOW, if I move the CSS file to the folder where index.html is located and in index.html, change the path of CSS TO
```
 <link rel="stylesheet" href="styles.css">
```
Now, CSS gets applied both when run from GULP task and also when index.html is opened directly (without gulp command)

Why CSS is not getting applied when styles.css is NOT in same folder of index.html?

Thanks in advance,

Regards,

**Comment by shinnn** [comment]
We cannot access ancestor directories of the site root. For example, we cannot access `https://github.com/../` and it redirects to `https://github.com/`.

It would work:

```js
'use strict';
var gulp = require('gulp');
var browserSync = require('./').create();

gulp.task('bs', function() {
    browserSync.init({
        server: {
            baseDir: ['.tmp', 'src/client']
        }
    });
});
```

```html
<!DOCTYPE html>
<html>
  <head lang="en">
      <meta charset="UTF-8">
      <title></title>

    <link rel="stylesheet" href="styles.css">

  </head>
  <body>
      <label> This will succeed!</label>
  </body>
</html>
```

**Comment by shinnn** [comment]
@eternalstudent2015 Close https://github.com/gulpjs/gulp/issues/1061 too.

**Comment by eternalstudent2015** [comment]
Thank you shinnn, problem resolved with your suggestions.
Intitialy,  I was having
```
baseDir: ['src/client']
```
And index.html, was having
```
<link rel="stylesheet" href="../../.tmp/styles.css">
```
But by adding .tmp as basedir and also changing href (as if styles.css is residing not in .tmp but in same folder as index.html)
```
<link rel="stylesheet" href="styles.css">
```
resolved the problem. Thanks, once again.
