### ISSUE TITLE
browser-sync cannot read property 'sockets' of undefined

### ISSUE THREAD

**Issue by whdigger** [BrowserSync/browser-sync#617]
I  want using BrowserSync as a http server together with gulp, but at start gulp receive error:
```
node_modules/browser-sync/lib/browser-sync.js:622  bs.io.sockets.emit("browser:reload");
TypeError: Cannot read property 'sockets' of undefined
    at null._onTimeout (/home/user/Projects/PHP/static/cbvdiz/node_modules/browser-sync/lib/browser-sync.js:622:22)
    at Timer.listOnTimeout (timers.js:110:15)
```
Sometimes this error can not be, when not use *tunnel: true*
With config work perfectly
```
browserSync: {
        server: {
            baseDir: configData.buildPath
        },
        host: 'localhost',
        port: 9000
    }
```
Thanks!

**Comment by shinnn** [comment]
* Which OS?
* Could you show us the result of:

    ```
    $ node -v
    $ npm -v
    $ npm ls browser-sync
    ```

**Comment by whdigger** [comment]
```
$ uname -a
Linux voyage 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u1 i686 GNU/Linux
$ node -v
v0.12.2
$ npm -v
2.7.4
$ npm ls browser-sync
project@0.1.0 /home/necrom/Projects/PHP/static/cbvdiz
└── browser-sync@2.7.1 
```

**Comment by shinnn** [comment]
I cannot reproduce the error though I use `tunnel: true`.

@whdigger Could you create a small repository that can reproduce the error?

**Comment by whdigger** [comment]
Maybe error in dynamic ip adress?
Уes of course

**Comment by whdigger** [comment]
Create [Small-Project](https://github.com/whdigger/gulp)

**Comment by shinnn** [comment]
Not small...

**Comment by whdigger** [comment]
What should be the small? ;)
Use command gulp and will be error, after img

**Comment by shinnn** [comment]
Commented. https://github.com/whdigger/gulp/commit/da9ae07fe97912c663742dd4b0905a7e0abb31d7#commitcomment-11124281 https://github.com/whdigger/gulp/commit/da9ae07fe97912c663742dd4b0905a7e0abb31d7#commitcomment-11124286

**Comment by whdigger** [comment]
Great! it has helped ) Thans a lot
