### ISSUE TITLE
Inject custom code along with BS

### ISSUE THREAD

**Issue by te-gpm** [BrowserSync/browser-sync#619]
I'm currently using a globally installed instance of Browser Sync over the command line as a debugging tool with the proxy option, which works like a charm. Only thing I couldn't figure out yet: 

Is it possible to inject the target site not just with the BS snippet, but my own custom code while just using the command line version? I have several small js snippets that help me during the debugging process that I can't always store in the target code, so piggy-backing on the BS injection would be awesome! Most options require there to be a build process like gulp :(

**Comment by shakyShane** [comment]
`rewriteRules`

```js
require("browser-sync")({
    proxy: "http://www.bbc.co.uk",
    rewriteRules: [
        {
            match: new RegExp(/Sign in/g),
            fn: function () {
                return 'browserSync';
            }
        }
    ]
});
```
