### ISSUE TITLE
reload browser by url in one instance

### ISSUE THREAD

**Issue by adyballa** [BrowserSync/browser-sync#622]
I have the need for one server to reload different browsers by url and made this so-question:
http://stackoverflow.com/questions/30213789/is-it-possible-to-reload-certain-urls-in-browser-sync

If there is a solution in the current version, it would be glad if someone put it out.
On the other side I would suggest this as a feature.

I found one solution and tested it: 
browser-sync.instance adminstrate a parameter-bag for socket-communication.
The server sends it by emitting the event, the client is receiving it by nature.
browser-sync-client has to react on the parameters and reload if permitted.

**Comment by adyballa** [comment]
I made 2 forks:
  - https://github.com/adyballa/browser-sync
  - https://github.com/adyballa/browser-sync-client

I did no tests, since I dont know node-tests and since I dont know if someone needs it like me.

It works for a reload like:
bs.reload("*test.html?user=otto&project=vollgas");

bs.reload(<path>)
path: just works with *-wildcard - its not a full glob

**Comment by shinnn** [comment]
> question: http://stackoverflow.com/questions/30213789/is-it-possible-to-reload-certain-urls-in-browser-sync

Yes, that's a more proper place for support questions as we wrote in [the contribution guide](https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem). Your question on StackOverflow needs more detailed information if you want to make it more answerable though.

**Comment by adyballa** [comment]
I can make an example. There are two files a/a and b/b. Lets assume there are the website
www.example/a/a which correspond to a/a and www.example/b/b which correspond to b/b.
If I edit a/a, I like to reload www.example/a/* and not www.example/b/b

Can I achieve this with a single instance?

If it is not possible, consider my fork.

If you have to have a concrete example. 
Consider a website, which has different user - like www.bmx.com/axel/profile. If axel edit some pages in his directory like profile.top.html, he doesnt want berta to send browser reload.
Another example would be a bigger project where you can map the file to specific websites. If 10 developer edit pages they dont want to disturb their neighbours.
