### ISSUE TITLE
How to proxy API requests?

### ISSUE THREAD

**Issue by iyel** [BrowserSync/browser-sync#624]
Hi, I need to run server from my ```public``` folder and to proxy requests to ```/api``` to the proxy server with ```Cookie``` header set.
How can I achieve this?

**Comment by shinnn** [comment]
* https://github.com/indexzero/http-server/issues/153
* https://github.com/andrewrk/node-proxy-middleware/issues/37
* https://github.com/BrowserSync/browser-sync/issues/624

http://www.catb.org/esr/faqs/smart-questions.html#forum

> ## Choose your forum carefully
> 
> Be sensitive in choosing where you ask your question. You are likely to be ignored, or written off as a loser, if you:
> 
> * post your question to a forum where it's off topic
> * post a very elementary question to a forum where advanced technical questions are expected, or vice-versa
> * cross-post to too many different newsgroups
> * post a personal e-mail to somebody who is neither an acquaintance of yours nor personally responsible for solving your problem
> 
> Hackers blow off questions that are inappropriately targeted in order to try to protect their communications channels from being drowned in irrelevance. You don't want this to happen to you.
