### ISSUE TITLE
Broken URL in documentation

### ISSUE THREAD

**Issue by jhubsharp** [BrowserSync/browser-sync#626]
In the BrowserSync documentation, http://www.browsersync.io/docs/api/#api-browserSync has a link to options in the browserSync( config, cb ) subject. "available options" is hyperlinked to http://www.browsersync.io/docs/api/%7B%7Bsite.links.options%7D%7D, which does not exist. It should link to http://www.browsersync.io/docs/options/.

**Comment by shinnn** [comment]
Duplicate: https://github.com/BrowserSync/browsersync.github.io/issues/16

=========

Please read [the contribution guide](https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md) before opening new issues. https://github.com/BrowserSync/browser-sync/blob/bd51551e01b08114f19b408631b72e2984b8c295/CONTRIBUTING.md#-want-a-doc-fix

Thanks for reporting though.
