### ISSUE TITLE
Why is browser-sync's dependency socket.io not always installed !?

### ISSUE THREAD

**Issue by hawkerboy7** [BrowserSync/browser-sync#627]
In my project `browser-sync` is a 2nd (deep) dependency. It looks like this:
 ```
my-main-project/
	node_modules/
		my-helper-project/
			node_modules/
				browser-sync/
					node_modules/
						socket.io
```
Now when I install socket.io in __my-main-project__, socket.io __doesn't__ get installed anymore.<br>
__browser-sync__/node_modules/[where-is-socket.io?:(]

Why does this happen and how can I fix it?

**Comment by shakyShane** [comment]
newer versions of NPM prevent installing duplicate versions of the same package, so this is expected behaviour :)

**Comment by hawkerboy7** [comment]
Ok thanks, I'll have to solve it another way then :)
