### ISSUE TITLE
Losing remote debugger Targets

### ISSUE THREAD

**Issue by ronilaukkarinen** [BrowserSync/browser-sync#629]
My remote debugger Targets are constantly cleared up, even when I see the devices connected successfully all the time. Sometimes even in between of inspecting I lose the connection to remote debugger. I know it might not be stable yet, but decided to report anyway. Have to stick with Ghostlab in the meantime. I hope this gets fixed, since BrowserSync is faster and more in everyday use for me. Thanks in advance!

**Comment by shakyShane** [comment]
Hi @ronilaukkarinen - the remote debugger bundled with Browsersync (weinre) does not seem to be actively maintained unfortunately. The knock-on effect of this is that we're also not actively maintaining our integration of it.

We are looking to replace it with a better alternative going forward, but for now, if you really need the remote debugging feature we'd say stick with Ghostlab for that :)

**Comment by shakyShane** [comment]
Closing here as this is a [UI](https://github.com/BrowserSync/UI) issue

**Comment by ronilaukkarinen** [comment]
Thank you for the information, @shakyShane, I really appreciate it.

**Comment by ronilaukkarinen** [comment]
Hi, just checking back on this. How is this UI issue? Not needing Remote Debugger that much, but noticed it's working better in the latest version. Occasionally it loses targets on reload and doesn't display CSS much.

What's the status with weinre?
