### ISSUE TITLE
watch callbacks should have access to public instance

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#631]
re: #411

Example use-case, when using `bs-config`

```js
module.exports = {
    server: './app',
    files: [
        './app/*.html',
        './app/js/*.js',
        {
            options: {
                ignoreInitial: true
            },
            match: './app/css/*.css',
            fn: function (event, file) {
                if (event === 'change') {
                    this.reload(file);
                }
            }
        }
    ]
};
```

**Comment by zanona** [comment]
Hey @shakyShane may I ask what does Chokidar `ingoreInitial` option does in this case?
I read their docs but couldn't quite figure out. Thanks

**Comment by shakyShane** [comment]
it fires `add` events for each file that it finds on the initial file system scan.

**Comment by shakyShane** [comment]
remove it, & put a log in to see what i mean

```js
module.exports = {
    server: './app',
    files: [
        './app/*.html',
        './app/js/*.js',
        {
            match: './app/css/*.css',
            fn: function (event, file) {
                console.log(event);
            }
        }
    ]
};
```

**Comment by zanona** [comment]
Ah yes. Got, so setting it to `true` will basically ignore those `add` events which is nice once only focusing on `change` events. Thanks man.

**Comment by lunelson** [comment]
I'm trying to accomplish something similar to this, proxying Harp.js; 

but Harp does all the pre-processing transparently, so I want BS to watch `['**/*.scss', '**/*.jade']` files, while injecting the changed `.css` and `.html`. Can this be done?

My attempt is based on the code here, and in the BS API and Options pages, and [this thread](https://github.com/BrowserSync/browser-sync/issues/631). This code deals first only with `.scss` files.

```js
var bs = require('browser-sync').create();

bs.init({
    proxy: "localhost:9000",
    files: [
        './**/*.jade',
        './**/*.js',
        {
            options: { ignoreInitial: true },
            match: './**/*.scss',
            fn: function (event, file) {
                if (event === 'change') {
                    bs.stream();
                }
            }
        }
    ]
});
```

is this at all on the right track... ?
