### ISSUE TITLE
File browser-sync-client.2.7.1.js not found

### ISSUE THREAD

**Issue by thomashermant** [BrowserSync/browser-sync#632]
Hi I've this strange issue today, my browser can't found the
/browser-sync/browser-sync-client.2.7.1.js
anymore...

Great job guy!
This project is awesome!

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by shinnn** [comment]
If you use broswer-sync@{VERSION}, it injects the script file `/browser-sync/browser-sync-client.{VERSION}.js` into your HTML.

**Comment by shakyShane** [comment]
also, `/browser-sync/browser-sync-client.js` will always work with any version

**Comment by lkraav** [comment]
Massive +1 to the evergreen loading ability :) I've had to hand-update the version number in my WP plugin.
