### ISSUE TITLE
Sync broken by a comment

### ISSUE THREAD

**Issue by mtman** [BrowserSync/browser-sync#633]
Placing ```<!-- <body> -->``` before ```<body>``` breaks live reload. 

https://gist.github.com/mtman/92d3ba942fbdee10d5d0

grunt-browser-sync 2.1.3, Win7

**Comment by shakyShane** [comment]
Please review [this thread](https://github.com/BrowserSync/browser-sync/issues/555) for our thoughts on this issue.

Thanks :)
