### ISSUE TITLE
bsReload is slower with large amount of watched files

### ISSUE THREAD

**Issue by HugoHeneault** [BrowserSync/browser-sync#634]
Hi,

I'm using grunt-browser-sync for a while and I noticed that more I have file watched (by `grunt-contrib-watch`) and more `browserSync`become slow...

Is it normal that the delay between end of `grunt-sass` / `grunt-autoprefixer` and browser injection increase when `grunt-contrib-watch` has more file to watch (from ~100ms to 1200ms)?

I have 1s delay between end of css processing and browser injection. :disappointed: 

Thanks for your great tool, by the way! :+1:

**Comment by HugoHeneault** [comment]
Here is my config if it can help: 

````js
watch: {
	options: {
		spawn: false
	},
	sass_app: {
		files: appCss,
		tasks: ['sass:app', 'autoprefixer:app', 'bsReload:css']
	},
	img: {
		files: 'img/**/*.png', // this contains 1200+ files
		tasks: ['tinypng']
	}
},
browserSync: {
	dev: {
		options: {
			background: true,
		}
	}
},
bsReload: {
	css: {
		reload: "css/*.css"
	}
}
````

**Comment by shinnn** [comment]
BrowserSync doesn't seem to be a root cause. Probably [time-grunt](https://github.com/sindresorhus/time-grunt) tells you which task actually makes your build slower.
