### ISSUE TITLE
Browser-sync hide proxy subfolder

### ISSUE THREAD

**Issue by NgYueHong** [BrowserSync/browser-sync#638]
We can use browser-sync to proxy our localhost subfolder project with something like this:

    // Using localhost sub directories
    proxy: "localhost/site1"

The browser-sync URL will look something like `http://localhost:3000/site1`. It would be great if the subfolder can be hidden so that when I browse `http://localhost:3000`, it will actually accessing `http://localhost/site1`.

Really hope to see such feature to be build-in. Maybe with the option for us to choose to hide the subfolder or not.

**Comment by shinnn** [comment]
> hope to see such feature to be build-in

-1. It would be enough to set your server to use `./site1` as a site root.

**Comment by shakyShane** [comment]
as @shinnn says, this would be better suited to a configuration within your server. Meaning you first set up a virtual host that has the web root set to the directory you require & then use Browsersync to proxy that.

**Comment by NgYueHong** [comment]
Yeah, but I have lots of projects folder in my server. And it would be troublesome to set a folder as site root every time I run each individual project. 

Also, sometimes the folder structure can be complex and long such as:

    http://localhost/clientA/projectA/moduleA/public/

It would be great if browser-sync comes with hide sub-folder feature, so that once I run browser-sync from my project folder, I will get clean URL for my project.

**Comment by NgYueHong** [comment]
@shakyShane  Yes, I have tried with virtual host. But browser-sync seems to be having problem with it. You may refer it at issue #637.

So now, I am thinking to not use virtual host as the alternative solution. I truly believe this feature will also be beneficial to others who have trouble / don't run virtual host.

**Comment by shinnn** [comment]
Of course I hope browser-sync could suit various needs and help every developer, but I'm concerned that   the browser-sync project will be overcomplicated if we accept all the feature requests we've received almost every day.
