### ISSUE TITLE
Disable outputting to console

### ISSUE THREAD

**Issue by robertbaker** [BrowserSync/browser-sync#641]
I'm using BS in a gulp task where my serve task that spawns BS is ran, then my code coverage tasks are ran.

However I have a problem where browser sync server info gets written to the console in the middle of running my coverage tests.  Is there a way I can disable BS from outputting to the console on startup and completely (on file changes)?

**Comment by shakyShane** [comment]
`logLevel: 'silent'`

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/options/#option-logLevel
