### ISSUE TITLE
Breaking change from 2.7.2 to 2.7.3

### ISSUE THREAD

**Issue by serapath** [BrowserSync/browser-sync#643]
```
...browser-sync/lib/file-watcher.js:47
her = watch(item.match, item.options || defaultWatchOptions, item.fn.bind(bs.p
                                                                    ^
TypeError: Cannot read property 'bind' of undefined
...
```
There is a problem with `atomify` which uses `browser-sync@^2.6.4`
Is it possible to fix that?
[atomify#80](https://github.com/atomify/atomify/issues/80)

I'm not sure, but i guess [this commit](https://github.com/BrowserSync/browser-sync/commit/d7c96e4fd4089d05952644a4213d1a95b4b6fa0e) broke it. If not that one, then it should be one close to it.

**Comment by shakyShane** [comment]
fixed in 2.7.5

Thank you for reporting this bug.
