### ISSUE TITLE
Image don't show, like blank image

### ISSUE THREAD

**Issue by stephanedemotte** [BrowserSync/browser-sync#645]
Hi,

I have update browsersync a couple of day, and everything works great, but today with an update,
All my image don't show.

here my settings: 

```javascript
		modules.browserSync({
			host: '192.168.10.10',
			server: false,
			proxy: 'http://myapp.app',
			open: false,
			snippetOptions: {
                           whitelist: ["/**"],
			},
		});
```

When i lunch my app without browsersync, all my images show correctly.

I don't have a 404 not found, but only a blank image instead 
![screen shot 2015-05-27 at 08 50 05](https://cloud.githubusercontent.com/assets/2158130/7830467/df35b458-044d-11e5-97d0-025fa8d02438.png)

Any idea ?

Thanks !

**Comment by shakyShane** [comment]
@stephanedemotte please create a reduced, minimal example and provide us with the HTML that's output (from view source) when viewed at your original address & then also the HTML from view source on the Browsersync url. 

I'm thinking there's an issue with the link rewriting.

**Comment by stephanedemotte** [comment]
Hi, 

When i remove
```
snippetOptions: {
   whitelist: ["/**"],
},
```

All my image appear, but when i use it, all the image are like a blank image.
It's not about the html, because this issue appear when i open the image directly in the browser.

http://localhost:3000/assets/myimages.png <- don't work
http://myapp.app/assets/myimages.png <- work

Any idea ?

**Comment by shakyShane** [comment]
`whitelist` should not be used in this context.

By providing `/**` you're attempting to inject the snippet into every file served. Instead, provide only paths that will contain html.

**Comment by stephanedemotte** [comment]
Hi @shakyShane 

All my website is in ajax, i don't have path with html and i use Laravel.
How i can allow to rewritte href from from ajax loaded page, but keep my images ?

Thanks

**Comment by maxackerman** [comment]
@stephanedemotte you ever solve this?

Im in the same position, using `whitelist: ["/**"],` to rewrite ajax page requests, but need to filter out images and other assets

**Comment by stephanedemotte** [comment]
i have to switch to vue/webpack, no need browsersync anymore ;)
