### ISSUE TITLE
files option doesn't properly watch symlinks

### ISSUE THREAD

**Issue by lookfirst** [BrowserSync/browser-sync#651]
I'm not sure what the issue is, but if I point at a directory structure under a symlink, bS doesn't pick up changes.

Right now, I build into `target/js` and then symlink the `js` folder to `target/webapp/js`. 

If I set `files: 'target/js/**/*.css'` things work. If I set `files: 'target/webapp/js/**/*.css'`, things don't work.

It is unclear to my why this isn't working as chokidar seems to follow symlinks by default?

OSX 10.10.4

**Comment by shinnn** [comment]
BrowserSync uses [chokidar](https://github.com/paulmillr/chokidar) for file watching and this problem should be fixed in that. Please wait [paulmillr/chokidar#293](https://github.com/paulmillr/chokidar/issues/293) to be fixed.

Thanks for reporting.

**Comment by lookfirst** [comment]
Thanks!
