### ISSUE TITLE
Injecting wrong CSS file on change.

### ISSUE THREAD

**Issue by trevcor** [BrowserSync/browser-sync#653]
I'm using a windows 7 VM to run the browser sync task via gulp.  My workspace is on a shared folder that exists on my mac.

I'm using a wild card to look for css changes in my project.  Whenever I make a change to a file in the directory a different file will be injected into the browser.

So the first time I make a change to file3.css it injects file1.css.  Then the next time I make a save it injects file2.css.  So instead of injecting the actual file that changed it iterates through the files returned from the wildcard "WebContent/css/*.css".  This is pretty strange behavior.  

My file structure looks like:

    - WebContent
       -css
         - file1.css
         - file2.css
         - file3.css

My config looks like:

    gulp.task('browser-sync', function() {
          browserSync.init({
              proxy: "http://localhost:8085/#/",
              files: 'WebContent/css/*.css',
              logLevel: "debug",
              browser: "chrome"
          });
      });

**Comment by shinnn** [comment]
@trevcor Could you tell us your Node version and Browsersync version?

**Comment by shakyShane** [comment]
@trevcor please provide a minimal sample project that demonstrates this bug
