### ISSUE TITLE
Trouble simulating offline

### ISSUE THREAD

**Issue by totaskin** [BrowserSync/browser-sync#654]
Is there any way to return real status from proxy? If i close backend and try develop offline functionality I get status code 500. Heres snippet what i tried: 
```
middleware: [proxy(proxyOptions), function (req, res, next) {
                console.log('status', res.statusCode)
                if( res.statusCode == 500){
                    res.statusCode = 0;
                }
                next();
            }]
```

this middleware function is not getting called if backend is closed/unreachable. Getting error: 
```
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

```

**Comment by shakyShane** [comment]
That's because when you call `next()` the [finalHandler in the foxy module](https://github.com/shakyShane/foxy/blob/master/lib/server.js#L91-L113) will be called.

you should end the response in your middleware to avoid it making it that far.

**Comment by totaskin** [comment]
Thanks for you response. 

Problem is that it doesn't even get to this middleware. This console.log is not reached to end response..

If backend is online it gets there and I can see this debug logging, if I kill it doen't. 

```
 require(scheme).get(target, function (res) {
        res.on("data", function (data) {
            chunks.push(data);
        });
    }).on("error", function (err) {
        if (_.contains(["ENOTFOUND", "ECONNREFUSED"], err.code)) {
            logError();
        }
    }).on("close", function () {
        if (!chunks.length) {
            logError();
        }
    });
```

could it be this? could it be fixed?
