### ISSUE TITLE
Feature Request: Notifications via web notifications api

### ISSUE THREAD

**Issue by febLey** [BrowserSync/browser-sync#656]
I'd love to have the option to get the notifications via the web notifications api instead of the inpage notifications: https://developer.mozilla.org/en/docs/Web/API/notification

This should be opt-in, because of the browser-support.

**Comment by shakyShane** [comment]
not only opt in, but it should be a plugin until there's much broader support.

**Comment by shakyShane** [comment]
Closing as 'out of scope' - but more than happy to create/advise on a plugin to create this.
