### ISSUE TITLE
Feature Request: Dynamic proxy target

### ISSUE THREAD

**Issue by lookfirst** [BrowserSync/browser-sync#659]
I'd like to be able to setup the proxy to go to the same Host: as in the request, but on a different port.

```
www.foo.com:8080 -> www.foo.com:9090
www.bar.com:8080 -> www.bar.com:9090
```

I could see the bS configuration being as simple as:

```
	port: 8080,
	proxy: ':9090'
```

The usecase is that I'm creating a site which can be white-labeled on different domains. During development, I just edit my /etc/hosts to point at `127.0.0.1` for both `www.foo.com` and `www.bar.com` and the server listening on 9090 knows what to do automatically based on the value in the path of the url.

**Comment by lookfirst** [comment]
Looking into the implementation of how things are done, this might be rather difficult as it would require changing the internal API to create the proxy server on each request. This would also mean multiple proxy server instances being created. This seems like a rather arduous change. I think what I will do as a workaround will be to create separate bS instances on different ports and do the redirection that way. Feel free to close this issue unless you agree that this is something useful.

**Comment by shakyShane** [comment]
@lookfirst yep, that's my initial reaction - it sounds a little out of scope for core.

Let me know if you need any help setting up multi instances :)

**Comment by lookfirst** [comment]
@shakyShane I setup the [multiple instances](https://github.com/lookfirst/gulp-helpers/blob/master/src/TaskMaker.js#L12), which is working great. The only bummer is that it now requires processing multiple file change messages (one for each instance). Oh well, it isn't the end of the world.

**Comment by shakyShane** [comment]
hmm, do you mean both instances are watching the same files? if so, there's a better way to do it..

**Comment by shakyShane** [comment]
or if it's just the logging that's annoying, try  `logFileChanges: false`

**Comment by lookfirst** [comment]
Yes, effectively watching the same files. Well, stream() is getting the notifications. I'll try logFileChanges: false.

**Comment by shakyShane** [comment]
ahh, if you're streaming into it, it'll just be the logging as Browsersync is not watching those files anyway, only picking up the names from the stream

**Comment by lookfirst** [comment]
Yup, [streaming](https://github.com/lookfirst/gulp-helpers/blob/master/src/tasks/babel.js#L75)...

logFileChanges worked well enough.

Thanks!

**Comment by shakyShane** [comment]
Great!

**Comment by lookfirst** [comment]
@shakyShane Meh, this issue came up again for me... would be nice...
