### ISSUE TITLE
Installing on Windows without Visual Studio? 

### ISSUE THREAD

**Issue by blackjyn** [BrowserSync/browser-sync#665]
Well, I know this-> #432 , but would you please make Browser-Sync available on windows without Visual Studio? Maybe the next version? 
That's REALLY Annoying:  you want to install small tools but should have ~9GBs of VS installed on your Machine. :-1: 
Or can someone tell me how to Install on Windows without VS et.all?

**Comment by shinnn** [comment]
It should be fixed in the upstream socket.io-related projects. If socket.io team updates `ws` dependencies in various projects, this issue would be fixed.

Subscribe this issue. https://github.com/Automattic/socket.io/issues/2107
