### ISSUE TITLE
command line argument --exclude is not considered 

### ISSUE THREAD

**Issue by carlo-colombo** [BrowserSync/browser-sync#667]
I have tried with different type of parameters (glob, no glob, absolute, relative ) and every time the option is ignored, a log about the changed file is issued and the browser refresh the page.

this is the commands I am running 
```browser-sync start --files '*.js' --exclude toignore.js --server --no-open```
```browser-sync start --files '*.js' --exclude 'toignore*' --server --no-open```
```browser-sync start --files '*.js' --exclude /tmp/test-bs/toignore.js --server --no-open```

Am I doing something wrong?

**Comment by shakyShane** [comment]
Sorry this is an error within the documentation. 

The `--exclude` flag is deprecated, you can provide negated patterns by prefixed them with `!` - although on the command line, you'll need to escape it.

```sh
browser-sync start --files '*.js, \!toignore.js' --server --no-open
```

**Comment by shakyShane** [comment]
You can also separate them if you prefer, like

```js
browser-sync start --server --files="*.js" --files="\!example.js"
```

**Comment by carlo-colombo** [comment]
Thank you.

**Comment by shakyShane** [comment]
Docs updated to reflect this http://www.browsersync.io/docs/command-line/
