### ISSUE TITLE
PHP Script returns 404 on $http request.

### ISSUE THREAD

**Issue by mikehuebner** [BrowserSync/browser-sync#672]
Using angularjs I am getting a 404 when I try to run an image modification script via PHP. Is there a way around this? I want to keep the PHP local as it is a single running script that resizes images.
![image](https://cloud.githubusercontent.com/assets/6125123/8097033/050abdea-0f93-11e5-814b-cd338b52a0a8.png)

```
function modifyImages(images) {
            $http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8';

            return $http({
                url: 'imageCreation.php',
                method: 'POST',
                data: images
            }).then(function (res) {
                console.log(res);
            });
        }
```

**Comment by shinnn** [comment]
@mikehuebner Why do you think this is browser-sync issue?

**Comment by shakyShane** [comment]
as @shinnn says, this is unlikely to be a bug in Browsersync. Feel free to provide more information or a sample project that can illustrate the bug & we'll re-open accordingly.
