### ISSUE TITLE
Enable to disable notifications on Firefox

### ISSUE THREAD

**Issue by CoreFloDev** [BrowserSync/browser-sync#673]
Hey,

I write this little gulpfile and I am enable to disable the notifications. With the option `notify: false` , the notifications are removed on chrome but on Firefox only the first notification is removed. On Firefox, each time the page is reloaded a notification come out but not on chrome. Is it a bug or it is only a misconfiguration from me ?

```javascript
'use strict';

var config = {
    appFolder : 'app/',
    distFolder : 'dist/',
    serverPort : 8000,
    serverRouter: 'router.php'
};

var gulp = require('gulp'),
    connect = require('gulp-connect-php'),
    browserSync = require('browser-sync');


gulp.task('serve', function() {
  connect.server({
      port: config.serverPort,
      base: config.appFolder,
      router: config.serverRouter
    }, function (){
    browserSync({
      proxy: 'localhost:8000',
      notify: false
    });
  });
 
  gulp.watch('**/*.{php,html,js,png,jpg,svg,css}').on('change', function () {
    browserSync.reload();
  });
});
```

Thanks

**Comment by shakyShane** [comment]
Fixed the [client lib](https://github.com/BrowserSync/browser-sync-client/commit/ad78a8d3ced849379fc50954a50be888ea7151ca) - please run: 

```sh
npm rm browser-sync && npm install browser-sync@latest
```

to get the fix
