### ISSUE TITLE
Wordpress Admin Screen

### ISSUE THREAD

**Issue by jackfearing** [BrowserSync/browser-sync#676]
Hello, I seem to have found an issue issue with the latest release of browser sync version 2.7.10 and accessing links within the Wordpress backend screen. When I login into Wordpress then click on the Wordpress dashboard button which takes me to the backend however I get redirected to the to 404 pages when I click on any of the tabs links such as "Pages" or "Posts". When I look at the URL it seems browser sync is 2.7.10 is removing the wp-admin for the url string.

Browser Sync 2.7.6
http://localhost:3000/wp-admin/edit.php

Browser Sync 2.7.10
http://localhost:3000/edit.php

Is there a function or something I should be using?

Thanks, 
Jack

**Comment by shakyShane** [comment]
What's the hostname you are using?

**Comment by jackfearing** [comment]
The hostname I'm using is  proxy: "local.joints"

**Comment by shakyShane** [comment]
Can you copy the `view source` of both the Browsersync url where this problem exists & then also via your regular hostname.

**Comment by domtra** [comment]
I seemed to have tracked down the issue. It was introduced in v2.7.4 when foxy was bumped to 11.0.0.
Since that version the proxy server removes tailing slashes in the urls which leads to problems in the wordpress admin area.
If you downgrade browser-sync to v2.7.3 it should be working again.

**Comment by shakyShane** [comment]
@jackfearing if you installed Browsersync locally, please run

```sh
npm rm browser-sync && npm install browser-sync@latest
```

... and then try again.

@domtra  - thanks for the investigation work

**Comment by jackfearing** [comment]
Thanks guys for figuring this out. One question, do I run the npm command globally or from the directory where my files are located?

**Comment by shakyShane** [comment]
Depends how you're using Browsersync. 

Are you using gulp/grunt/api? Or directly from the command line?

**Comment by jackfearing** [comment]
I'm using GULP and a task to run browser sync. I'm on a MAC and use terminal to run the gulp task.

**Comment by shakyShane** [comment]
Ok cool, so that first command should update you to the latest version

```sh
npm rm browser-sync && npm install browser-sync@latest
```

**Comment by jackfearing** [comment]
Just updated to the latest version and everything is working perfectly! Thanks!!!

**Comment by jackfearing** [comment]
Sorry, I found one additional item. After I init BrowserSync it launches the website with localhost:3000. I click on the Wordpress admin bar to access the dashboard from the front-end it take me to the dashboard screen with the address of localhost:3000... (Perfect). However, if I click the visit site or any of the top menu bar items from the dashboard screen it takes me to local.{domainname} and not back to localhost:3000. All the other menu items located on the left hand side work as expected, the issues seems to be limited to the top menu bar located on the dashboard screen.

**Comment by domtra** [comment]
@jackfearing I think this is unrelated to BrowserSync. Wordpress by default uses absolute Urls for most of its links. It is possible to customize this behavior via some hooks but this needs some additional setup from your site. Hope you find something to solve your issues. If not, pm me for more info.

**Comment by shakyShane** [comment]
Does wordpress add the admin bar via JS?

**Comment by jackfearing** [comment]
Sorry, I'm not sure if Wordpress adds the admin bar via JS. Also, the reason I brought this up in this ticket as opposed to generating a new one was because it seems to deal with the URL strings. Lastly, in previous versions of browser sync (Browser Sync 2.7.6) the URL's were generated and worked as expected. The latest version fixes the left hand side links but the main toolbar still goes to the local.domain name and not the localhost:3000 domain name. Here is a screenshot which hopefully help explain the issue. Any help Obi Wan?
![screen shot 2015-06-19 at 8 53 47 am](https://cloud.githubusercontent.com/assets/6834687/8257241/126a3e64-1661-11e5-84b4-2898d8a7c7e9.png)

**Comment by jackfearing** [comment]
Hey fellas, any additional thoughts on my previous comment?

**Comment by jackfearing** [comment]
+1

**Comment by jackfearing** [comment]
Hey fellas, any additional thoughts on my previous comment?

**Comment by shakyShane** [comment]
Only that I cannot reproduce the problem yet.

**Comment by jackfearing** [comment]
Thanks for taking another look Shane. I'm wondering if it has to do with my gulp setup below:

// Proxy to existing vhost (version 0.7.0 & greater)
gulp.task('browser-sync', function() {
    browserSync.init({
        proxy: "local.lti",
        notify: false,
        browser: ["Safari"],
        snippetOptions: {
            ignorePaths: ["wp-admin/**"]
        },
    });
});

**Comment by shakyShane** [comment]
Hmm - yes, try removing the `ignorePaths`

**Comment by jackfearing** [comment]
That did it! -- I originally put it in there to stop the backend admin screen from refreshing when I updated my watch files. So far it doesn't seem to be effecting it. In the future is there a better way to prevent gulp from refreshing the admin screen?

**Comment by shakyShane** [comment]
Not currently - although this is an area we'd like to improve.
