### ISSUE TITLE
IE conditional tags interfering with browser-sync injection

### ISSUE THREAD

**Issue by deanc** [BrowserSync/browser-sync#677]
Hi all,

I am having problems getting browser sync running due to IE conditionals on the <body> tag. This is my actual HTML source before browser-sync:

    
    

This is what happens after running browser-sync:

**Comment by shakyShane** [comment]
Browsersync just looks for the fist body tag on the page.

Please see all of the previous issues around this. https://github.com/BrowserSync/browser-sync/issues?q=is%3Aissue+snippetOptions+is%3Aclosed

Basically you can override the regex that's used to place the snippet, so if you add this configuration, it will act only on a closing body tag instead

```js
snippetOptions: {
    // Provide a custom Regex for inserting the snippet.
    rule: {
        match: /<\/body>/,
        fn: function (snippet, match) {
            return snippet + match;
        }
    }
}
```

**Comment by deanc** [comment]
Hi @shakyShane 

I found a similar issue literally after posting this, so my apologies. I've since tried snippetOptions with my grunt configuration and it's still injecting it in the same place:

**browser-sync --version**
2.7.10

**Grunt configuration**

                browserSync: {
                    dev: {
                        options: {
                            watchTask: false,
                            debugInfo: true,
                            proxy: "ts-rediscovery.dev"
                        },
                        snippetOptions: {
                            // Provide a custom Regex for inserting the snippet.
                            rule: {
                                match: /<\/body>/,
                                fn: function (snippet, match) {
                                    return snippet + match;
                                }
                            }
                        }
                    }
                },

**Grunt usage**

`grunt browserSync:dev`

Output is still the same as original issue.
