### ISSUE TITLE
Pass function to process files.

### ISSUE THREAD

**Issue by keithamus** [BrowserSync/browser-sync#679]
It'd be great if we could combine pre-processors like LESS, SASS, or Browserify without having to use gulp and without effecting the filesystem.

Right now the only option is to use middleware, which means implementing a lot of what feels like existing functionality - for example filtering based on URL, finding files based on the baseDir globs, reading files through disk, and sending them back. It'd be great to have the following API:

```js
server.init({
    files: [
        {
            match: /\.less$/,
            process: function (filename, contents, callback) {
                callback(less(contents));
            }
        },
        {
            match: /\.js$/,
            process: function (filename, contents, callback) {
                browserify(filename).bundle().on(...);
            }
        }
    ]
});
```

This way we can process files before they get served up or injected, without having to go down the middleware route which adds a lot more (duplicate) code.

**Comment by shinnn** [comment]
-1

I don't think Browsersync is in charge of that. Instead you can launch your own server with [connect](https://github.com/senchalabs/connect) and use a lot of connect middlewares, like [sass-middleware](https://github.com/sass/node-sass-middleware) and [browserify-middieware](https://github.com/ForbesLindesay/browserify-middleware).

**Comment by shakyShane** [comment]
@shinnn - agreed that it should be be part of core, although I would suggest there's an opportunity here for a nice plugin.

**Comment by keithamus** [comment]
For me this fixes 2 problems I'm having with browsersync:

### No way to lookup/deal with files the same way browsersync does:

If, for example if I have 2 `baseDirs` in my `server` config, then in a middleware I have to implement the lookup logic for which files are which myself. There seems to be no way to do this with the current code. I have this:

```js
function getFile(url) {
  var dirs = this.instance.options.getIn(['server', 'baseDir']);
  if (this.instance.utils.isList(dirs)) {
    dirs = dirs.toArray();
  } else {
    dirs = [dirs];
  }
  return dirs.map(function transformDirToAbsolute(dir) {
    return path.join(dir, url);
  }).filter(fs.existsSync)[0];
}
```

### No way (it seems) to intercept the contents that browsersync "injects" at runtime

I have a server running, with a set of middleware that intercept css files and compile them with PostCSS. The problem is that when I change a file, the browsersync injector seems to ignore the middleware, and so my raw less gets injected (which of course, breaks the page because the new css it has is incompatible with the browser's CSS parser - hence why I'm using PostCSS). The only ways around this that I've seen is to set up a connect server and use browsersync as a proxy (a sad amount of code for me to write) - or disable browsersync's injection feature and have it reload the whole page when anything changes (losing out on cool features).

The aim of the code in the OP was to introduce a way to solve both of these problems transparently, without introducing reams of new code. If you can tell me a better way to solve the two problems I have, them I am all ears :smile:

**Comment by shakyShane** [comment]
What about taking a look at this. https://github.com/Browsersync/recipes/tree/master/recipes/middleware.css.injection

**Comment by keithamus** [comment]
I had a fairly in depth look at that example. It seems relatively straightforward - but would not work for me as the injected CSS skips the middleware. Here's my code (effectively the same as the LESS example):

```js
var fs = require('fs');
var path = require('path');
var browserSync = require('browser-sync');
var cssnext = require('cssnext');
function cssMiddleware(request, response, next) {
  if (/\.css$/.test(request.url)) {
    return response.end(cssnext(fs.readFileSync('.' + request.url, 'utf8'), {
      compress: true,
      sourcemap: true,
    }));
  }
  next();
}

var server = browserSync.create();
server.init({
  logLevel: 'debug',
  logConnections: true,
  files: '*.css',
  server: '.',
  injectedFileTypes: ['css'],
  middleware: cssMiddleware,
});
```

On the page's first load, the CSS is compiled and everything works excellently. However, if I edit the css file and hit save, we can see in my network requests panel, that the raw file has just been sent to the server:

![screen shot 2015-06-17 at 11 16 13](https://cloud.githubusercontent.com/assets/118266/8204733/945285c4-14e2-11e5-9802-a988181431d9.PNG)

**Comment by shakyShane** [comment]
It's because this is failing

```js
/\.css$/.test(request.url)
```

subsequent requests have timestamps appended - which is why I linked that example, so you could see how to get around it by first parsing the url

```js
    var parsed = require("url").parse(req.url);
    if (parsed.pathname.match(/\.less$/)) {
        ....
```

https://github.com/BrowserSync/recipes/blob/master/recipes/middleware.css.injection/app.js#L10-L11

**Comment by keithamus** [comment]
Yes of course... how dumb of me.

I guess my other issue still remains - that it'd be great to have an API for retrieving the file name that browsersync *would serve* based on the pathname, without having to duplicate glob logic.

**Comment by shakyShane** [comment]
Closing as 'out of scope' - I am however extremely interested in creating a plugin for this.
