### ISSUE TITLE
Don't include the version number in the client js file

### ISSUE THREAD

**Issue by jeffijoe** [BrowserSync/browser-sync#681]
After I update my packages I always have to remember to change the version number in the script tag snippet because a new version of BS has been released (a good thing! :) ).

```
        <script type='text/javascript' id="__bs_script__">
//<![CDATA[
            document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.7.12.js'><\/script>".replace("HOST", location.hostname));
            //]]></script>

```

Do you absolutely *have* to include the version number? :)

**Comment by shakyShane** [comment]
If you're manually adding the snippet, just use `http://HOST:3000/browser-sync/browser-sync-client.js` instead. It will still work.
