### ISSUE TITLE
How do you get the snippet code?

### ISSUE THREAD

**Issue by callumlocke** [BrowserSync/browser-sync#686]
I'm using the BrowserSync JS API, but I'm not using it to serve my site for me. I'm just using it to run a BrowserSync server, and then I call `.reload()` whenever my files change.

If I go to the BS UI site, it tells me the snippet I need to put in my HTML.

But how do I get this snippet programatically?

```js
var bs = require('browser-sync').create();

bs.init();

console.log(bs.getSnippet()); // is anything like this available?
```

**Comment by shakyShane** [comment]
Either wait for the callback and do

```js
var bs = require('./').create();

bs.init({
    server: 'test/fixtures'
}, function (err) {
    console.log(bs.getOption('snippet'));
});
```

or listen to the `service:running` event.

```js
var bs = require('./').create();

bs.init({
    server: 'test/fixtures'
});

bs.emitter.on('service:running', function (data) {
    console.log(data.options.get('snippet'));
});
```
