### ISSUE TITLE
watchOptions don't seem to get passed to Chokidar

### ISSUE THREAD

**Issue by Nirazul** [BrowserSync/browser-sync#688]
I'm running into some problems with the latest browser-sync version (2.7.12).
Here is my gulp setup (a little bit simplified):

#### gulpfile:
```js
    var browserSync = require('browser-sync').create('server');
```

#### main task:
```js
    var browserSync = require('browser-sync').get('server');

    gulp.task('server:proxy', ['build', 'server'], function() {
        console.log(config.sync.proxy.watchOptions);   // returns { ignoreInitial: true }
        browserSync.init(config.sync.proxy);
        gulp.start('watch');
    });
```

#### watch task:
```js
    var browserSync = require('browser-sync').get('server');

    gulp.task('watch', function() {
        browserSync.watch([config.watch.images])
            .on("add", function() { gulp.start('images:dirty'); })
            .on("change", function() { gulp.start('images:dirty'); })
            .on("unlink", function() { gulp.start('images:clean'); });
    }
```

When I start the server, `add` events trigger another reload. However, when I initialize watch like that:

```js
    browserSync.watch([config.watch.images], {
        ignoreInitial: true
    })
```

...everything works as expected.

Do I miss something important in my initialisation?

**Comment by shakyShane** [comment]
`watchOptions` are only passed to chokidar when providing watching patterns in the init options.

the public method `.watch()` does not re-use the options so you'll have to pass them again as you did in the final snippet.

**Comment by Nirazul** [comment]
Ah, ok. Thanks for clearing that up.
Maybe you could add this information in the documentation. I instantly was under the impression that `bs.watch()` and `watchOptions` go hand in hand.

**Comment by shakyShane** [comment]
@Nirazul good point, I'll make a note of that

**Comment by demisx** [comment]
Just spent about an hour troubleshooting this issue. Would be great if documentation could be udpated here https://www.browsersync.io/docs/options/#option-watchOptions to mention that. Wasn't obvious why it wasn't working when passed in `bs.init` options.

**Comment by shakyShane** [comment]
updated https://www.browsersync.io/docs/options/#option-watchOptions
