### ISSUE TITLE
Proxied host port is stripped from HTTP_HOST

### ISSUE THREAD

**Issue by KevinRay** [BrowserSync/browser-sync#689]
When I use version 2.7.6 PHP's $_SERVER['HTTP_HOST'] returns localhost:3000 but on the latest version, 2.7.12, it returns just localhost, without the port number. This is breaking my sites.

Example config:

``` js
gulp.task('serve', ['stylesDev'], function () {
  browserSync.init({
    notify: false,
    proxy: 'localhost/src/'
  });
  gulp.watch(['src/**/*.php'], reload);
  gulp.watch(['src/styles/**/*.{scss,css}'], ['stylesDev', reload]);
  gulp.watch(['src/scripts/**/*.js'], reload);
  gulp.watch(['src/images/**/*'], reload);
});
```

**Comment by shakyShane** [comment]
Can you explain what you mean by 'breaking my sites' - or even better provide a small sample project that highlights this issue.

**Comment by KevinRay** [comment]
Shane, what I mean is that my sites use the value returned by
$_SERVER['HTTP_HOST'] to create navigation links and when the port value is
omitted, the links don't work properly. I don't have a sample to provide
since this occurs on my local development machine when proxying localhost.

It seems like this issue is similar to a previous one (
https://github.com/BrowserSync/browser-sync/issues/166) that was resolved
and was working for me as well until more recent versions.


*Kevin Ray                         *Clicks Web Design Inc.
905 Pingree Rd. Suite E
Crystal Lake, IL 60014
815-566-0001
http://clickswebdesign.com

**Comment by shakyShane** [comment]
The host is not modified, so I'm assuming you're talking about links in the HTML?

If so, could you provide a copy/paste of the view source with & then without Browsersync so we can see what's being rewritten

**Comment by KevinRay** [comment]
I'm referring to the value returned by the PHP $_SERVER variable when using browser-sync's proxy:
    //in gulpfile.js
    browserSync.init({
        proxy: 'localhost/'
    });

Here's an example:

//Without browser-sync
<?php echo $_SERVER['HTTP_HOST'];?>
//returns localhost

//With Browser-Sync v2.7.6
<?php echo $_SERVER['HTTP_HOST'];?>
//returns localhost:3000

//With Browser-Sync v2.7.12
<?php echo $_SERVER['HTTP_HOST'];?>
//returns localhost


The issue I have is that, with the latest browser-sync version, it loads the site to http://localhost:3000/ on startup but the links in the site, which are generated dynamically by using $_SERVER['HTTP_HOST'] are using http://localhost/. The difference, not appending the :3000, raises browser errors related to cross-origin requests for resources.

**Comment by elimc** [comment]
Possible related issue when I try to save a WP post:

```javascript
XMLHttpRequest cannot load http://127.0.0.1/jump_start/wp-admin/admin-ajax.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Here's the relevant gulpfile.js code:
```javascript
        browserSync.init({
            proxy: 127.0.0.1/jump_start/,
            tunnel: "tunnel"  // Set the SSH tunnel for mobile testing.
        });
```

However, this is only an issue on an older site. I created a brand new site and had no issues. When I create a WP site, I install it at 127.0.0.1/mydir/. I run Gulp and it loads as localhost:3000/mydir/ just fine. Not sure if that helps @KevinRay.
