### ISSUE TITLE
socket option not working properly

### ISSUE THREAD

**Issue by diagramatics** [BrowserSync/browser-sync#690]
Hi. This is a complicated issue, hopefully I'll be able to explain it correctly.

So I want to use BrowserSync on a live website where I have no access to the code. I'm not using the proxy so I can still maintain the cookies needed for login and other kinds of things, so I managed to create a Chrome extension to append the needed script tag into the DOM and replacing the `src` to localhost instead of using `.replace()` with the hostname. 

All goes well, script gets executed, but I noticed the GET requests to socket.io are using the hostname instead. Is there any way to override it somehow? I was expecting the requests to be based on the location where the initial .js file is at.

**Comment by diagramatics** [comment]
So I narrowed the problem down and it seems the only way I can solve this is by changing the `socket` option. Tried following one of the examples in the docs, changing the namespace to localhost:3000 and the polling requests are definitely coming through. 

The weird part though is that even though the requests have statuses of 200 (and 101 for the websocket) it doesn't seem to work after the namespace change. No notification of BrowserSync being connected, even after enabling debug logs. Seems like a duplicate of #621. 

Help?

**Comment by shakyShane** [comment]
Confirmed this is not working correctly.

We'll look at this asap.

**Comment by diagramatics** [comment]
Ah, I guess a title change is in order. Thanks.

**Comment by shakyShane** [comment]
Fixed in `v2.7.13`

The original implementation was completely broken (where setting the namespace allowed a url, doh!).

now, to achieve what you want, it's the domain property you want.

```js
socket: {
    domain: "localhost:3000"
}
```

**Comment by diagramatics** [comment]
Yep, confirmed working. Thanks!
