### ISSUE TITLE
Is BrowserSync replacement for livereload?

### ISSUE THREAD

**Issue by alex93ushakov** [BrowserSync/browser-sync#691]
I had tried to launch BrowserSync from this app.js file
```js
var browserSync = require('browser-sync');

browserSync({
    server: "app",
    files: ["app/*.html"]
});
```
But after code changing page did not  auto-reloaded.

It's correct?

**Comment by shakyShane** [comment]
Do you see 'cConnected to Browsersync` message in the browser?

**Comment by alex93ushakov** [comment]
No.

**Comment by shakyShane** [comment]
Ok, please check http://www.browsersync.io/docs/#requirements :)

**Comment by alex93ushakov** [comment]
All looks ok.
On BrowserSync dont work on localhost on a single machine, external ip is not interested now.
Browser sync starts the server, but not reloads after code changing.

Problem is not solved.

**Comment by shakyShane** [comment]
It is, yes.

The fact that you don't see 'Connected to Browsersync' in your browser window suggests your website does not meet the requirements detailed in that link.

If you believe it does, please feel free to provide a sample of the HTML/JS & configuration and we'll be happy to help

**Comment by alex93ushakov** [comment]
It was my mistake. I am hurry and don't insert body tag.

All works, thanks for help!

So, there is no need to install live reload extension in browser for quick preview now )

**Comment by shakyShane** [comment]
Exactly. Browsersync 'just works' out of the box
