### ISSUE TITLE
BS CLI multiple reload triggered on save

### ISSUE THREAD

**Issue by Granze** [BrowserSync/browser-sync#692]
I'm running BS via CLI in my NPM script (browser-sync@2.7.12)

```browser-sync start --files 'dist/' --server```

Every time I save my CSS file, reload is triggered 4 times

[![asciicast](https://asciinema.org/a/5s4ww7vqhtx1021fs1yibbngv.png)](https://asciinema.org/a/5s4ww7vqhtx1021fs1yibbngv)

I tried to add the --reload-debounce as well but nothing changed.

**Comment by shakyShane** [comment]
1. Do you have a build process writing the css file?
2. Which editor are you using?
3. Does the same thing happen when you try https://github.com/BrowserSync/recipes/tree/master/recipes/server
4. If the recipe the recipe above does not also do this, then please provide a small sample project that highlights this issue & we'll re-open/investigate

Thanks

**Comment by Granze** [comment]
Hi @shakyShane, as I wrote, I use plain npm scripts for my building process. So I use the cli version of BS. I use Webstorm but I was trying Atom as well.
The recipe you linked is not for the cli.

Thanks anyway

**Comment by shakyShane** [comment]
@Granze I'd be willing to help out should you be able to provide an example project.

I suspect your build process is simply writing to the css file multiple times.

**Comment by Granze** [comment]
@shakyShane I'm trying different combinations/solutions to figure out what's the source of the problem.
I'll provide an example app if I'll not able to solve the problem. :)

**Comment by shakyShane** [comment]
@Granze great, thanks :)
