### ISSUE TITLE
connection was interrupted in firefox

### ISSUE THREAD

**Issue by newtonianb** [BrowserSync/browser-sync#694]
I have an app working in Chrome and browsersync but it's not working with firefox (latest) when I load the page I get.

```
The connection to ws://localhost:3001/browser-sync/socket.io/?EIO=3&transport=websocket&sid=L_ERCeYuLINqcWnrAAAB was interrupted while the page was loading.
```

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#tips

This one sounds app specific so feel free to provide a sample project as mentioned in the contributing guide. Otherwise we have no way of knowing if this is a problem with us, or you.
