### ISSUE TITLE
Proxy injection issue with "<body>" in head script

### ISSUE THREAD

**Issue by KokeClassic** [BrowserSync/browser-sync#696]
I'm working with a proprietary form builder app in our CMS that spits out a massive script (I'm assuming for form validation) in the &lt;head&gt; that has a "&lt;html&gt;&lt;body&gt;" in it. I saw from another ticket that BS uses regex to find the first instance of the body tag which in this case hits the body tag inside the head script instead of the real one. I can't modify the script unfortunately and this ends up breaking the script and css on the page.

Demo of the issue:
browser-sync start --proxy "http://s.codepen.io/Koke/debug/rVYgPv?"

Possible regex fix that ignores the &lt;head&gt; if it's there: '/(&lt;\/head&gt;)?[\s\S]\*(&lt;body[^&gt;]\*&gt;)/i'
demo of regex fix: https://regex101.com/r/zD1dM9/1

**Comment by Nirazul** [comment]
You can use your own regex:

```
    snippetOptions: {
        rule: {
            match: /<\/body>/i,
            fn: function (snippet, match) { return snippet + match; }
        }
    }
```

**Comment by shakyShane** [comment]
exactly as @Nirazul 

We are deliberately using a simple regex & you're free to override it :)
