### ISSUE TITLE
Reading Gulp/Browser-Sync status via server-side page

### ISSUE THREAD

**Issue by zslabs** [BrowserSync/browser-sync#698]
Using Gulp and Browser-Sync, my specific setup requires me to add the snippet BS suggests to the bottom of my PHP files:

    <script type='text/javascript' id="__bs_script__">//<![CDATA[
        document.write("<script async src='http://localhost:3000/browser-sync/browser-sync-client.2.7.13.js'><\/script>".replace("HOST", location.hostname));
    //]]></script>

This works fine, but I'd only like to add this to those files based on if my `watch` task (which starts the Browser-Sync server) is actually running. I originally thought if I set an environment variable via Gulp that I'd be able to access it in PHP, but I don't believe I can do that. What I'm thinking I could do is look for a file generated by my `gulp watch` command that would be deleted on error or stoppage of that task. Any suggestions on the best way to accomplish this or is there an easier way to listen to Browser-Sync from server-side languages like PHP? Thanks!

**Comment by shakyShane** [comment]
There's a plugin for doing exactly that.

```sh
npm install bs-snippet-injector --save-dev
```

Then, simply provide the path to a template file that contains a closing `</body>` tag.

```js
var bs = require('browser-sync').create();

bs.init({
    files: ["app/whatevers/views/**/*.php", "public/**"],
    plugins: [
        {
            module: 'bs-snippet-injector',
            options: {
                file: 'public/includes/foot.php'
            }
        }
    ]
});
```

alternative method

```js
var bs = require('browser-sync').create();

bs.use(require('bs-snippet-injector'), {
    file: 'public/includes/foot.php'
});

bs.init({
    files: ["app/whatevers/views/**/*.php", "public/**"]
});

```

**Comment by zslabs** [comment]
Thanks, will look into it!
