### ISSUE TITLE
Cannot GET/

### ISSUE THREAD

**Issue by dagolinuxoid** [BrowserSync/browser-sync#699]
Hey there! 
```
linux@linux-desktop:~/Templates/browsersync-project$ ls 
brow.html  css
linux@linux-desktop:~/Templates/browsersync-project$ browser-sync start --server --files="css/*.css"
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.2:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.2:3001
 ------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
```
In browser (Firefox http://localhost:3000/) I see only : Cannot GET/  
any suggestions?

**Comment by dagolinuxoid** [comment]
Interesting! When I rename bower.html to index.html I had no troubles, but why custom naming html file (in my case bower.html)  get Cannot GET )

**Comment by Turqueso** [comment]
@dagolinuxoid I guess is because it looks for index as a normal server would? try with `startPath` example:
`gulp.task('browser-sync', function() {  
  browserSync({  
    server: {  
      baseDir: "./"  
    },  
    startPath: "/html/bower.html"  
  });  
});`

**Comment by shakyShane** [comment]
@dagolinuxoid it looks for an `index.html` file in the directory you specify (or the cwd, if you didn't)

solutions:

1. either use an index.html
2. use the `index` option like so


```sh
browser-sync start --server --index bower.html --files="css/*.css"
```

**Comment by dagolinuxoid** [comment]
Got it, thanks a lot!

**Comment by wikilike7** [comment]
Thanks, i solve it follow your answer

**Comment by alexfrize** [comment]
Thanks!

**Comment by Real-Mayer** [comment]
Thanks guys
