### ISSUE TITLE
Serve content on a context

### ISSUE THREAD

**Issue by jvassev** [BrowserSync/browser-sync#700]
Is it possible to make server serve resource on a context path, for example /portal/app1
Can it be done using configuration only?

**Comment by patrickjaja** [comment]
Do you mean this?

browserSync({
      startPath: 'portal/app1',
      open: true,
      notify: false
  });

**Comment by shakyShane** [comment]
If you want certain paths to be loaded from different directories, use the `routes` property of server http://www.browsersync.io/docs/options/#option-server

If this is not what you what you needed, please respond back with much more information re: your setup https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by jvassev** [comment]
Thanks @patrickjaja,
Your suggestion together with modRewrite middleware does the job:
 middleware: [
        modRewrite([
           '^/portal/app1/(.*)$ http://localhost:3000/$1 [P]'
        ])
      ]

**Comment by mlaffargue** [comment]
For those not willing to use modRewrite I finally came up with a simple solution :

Just create a symbolic link from `some/multi/level/path` directory to `your app files`. Then going to `localhost:9000/some/multi/level/path` will provide the same files as going to `localhost:9000``
