### ISSUE TITLE
Character replacement, possibly an encoding issue

### ISSUE THREAD

**Issue by colinrotherham** [BrowserSync/browser-sync#701]
Hi,

I've noticed the following HTML markup is being replaced from this:  
`<p class="scroller__description">Video’s your choice, available when your visitors and agents want.</p>`

To this (over the Browsersync proxy):  
`<p class="scroller__description">Video���s your choice, available when your visitors and agents want.</p>`

i.e. A curly single quote is becoming `���`

Other single quotes, double quotes or other unicode characters are displaying correctly—perhaps this is a string replacement or regex issue? Changing the class attribute fixes the issue.

Could possibly be related to issue #661

Thanks

**Comment by shakyShane** [comment]
@colinrotherham Can you provide an example repo showing this bug? I'm unable to reproduce it.

**Comment by colinrotherham** [comment]
Sorry, I can no longer reproduce it on the latest version. Feel free to close this one.

Changing `scroller__description` to `scroller__text` avoided the issue at the time. I did wonder if it was matching `script` within the class attribute and doing something it shouldn't have been.

Thanks

**Comment by MrVoltz** [comment]
I have the same issue and my suspicion is that Browsersync decodes the incoming stream in chunks and sometimes the chunk boundary lies in the middle of an UTF-8 character.
