### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by welly** [BrowserSync/browser-sync#702]
I've been having an issue when creating a new file which browsersync watches that is causing a segmentation fault (on OSX Yosemite). I had originally thought it was a gulp issue but I've removed the call to browsersync/removed browsersync gulp tasks and the problem has gone. If I'm updating an existing page (in Jekyll) or css file, then there isn't a problem, it's just when creating a new file. Does anyone have any suggestions why this might be occurring?

I'm calling browsersync in two tasks:

```
gulp.task('browsersync', ['jekyll'], function() {
  browsersync(config);
});
```

and 

```
gulp.task('jekyll:rebuild', function() {
  browsersync.reload();
});
```

Browsersync config looks like:

```
  browsersync: {
    server: {
      baseDir: [dev, build, src]
    },
    files: [
      devAssets + '/css/*.css',
      devAssets + '/images/**'
    ]
  },
```

So not doing anything unusual (I don't think).

Cheers

**Comment by welly** [comment]
Ok, this can be closed. It was a node.js issue. All working now.

**Comment by homerjam** [comment]
Hi @welly can you explain what you did to overcome this? I'm facing a similar problem. Thanks
