### ISSUE TITLE
scroll event cannot be captured with fullPage.js

### ISSUE THREAD

**Issue by lgh06** [BrowserSync/browser-sync#706]
scroll event cannot be captured with fullPage.js

so the two browser's page is not sync.

**Comment by shakyShane** [comment]
Hi! 

Please provide a sample project (jsbin/gist/repo) that demostrates this problem. When we can confirm it's a Browsersync bug we'll reopen this issue and work to resolve it.

**Comment by lgh06** [comment]
a source code is at https://github.com/lgh06/bed_official ,
and the page demo is like http://www.shuiqian.cc/ (something modified).
thanks.
