### ISSUE TITLE
Changing everything that has my proxy name, on all pages, by localhost:3000 

### ISSUE THREAD

**Issue by brunoti** [BrowserSync/browser-sync#707]
I'm using Browser Sync with an MAMP server with a virtual host called ``http://dote`` and i have some CSS classes with "dote" in the name like: ``.dote-logotipo``. 

So it should be like this: 
![screenshot 2015-07-03 09 45 31](https://cloud.githubusercontent.com/assets/6011421/8499355/4e0e060a-2168-11e5-92d1-bdcb891ce7f1.png)

And not like this:

![screenshot 2015-07-03 09 46 52](https://cloud.githubusercontent.com/assets/6011421/8499379/7e693720-2168-11e5-89a4-0a7310652a3e.png)

I don't know if i'm doing something really wrong, but i think that this is a bug.

Thanks!

**Comment by shakyShane** [comment]
Browsersync is trying to replace links with the proxy url.

It's not bullet proof, as you can see, but an easy solution is to use a TLD in your hostname. `dote.dev` fro example.

**Comment by brunoti** [comment]
Ok :(. Thanks for the attention

2015-07-03 10:01 GMT-03:00 Shane Osbourne <notifications@github.com>:

> Browsersync is trying to replace links with the proxy url.
>
> It's not bullet proof, as you can see, but an easy solution is to use a
> TLD in your hostname. dote.dev fro example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrowserSync/browser-sync/issues/707#issuecomment-118342362>
> .
>



-- 
---
BruNo Oliveira - Desenvolvedor Web

Cel: (16)991-731-135
