### ISSUE TITLE
Not serving files from parent folders

### ISSUE THREAD

**Issue by pensierinmusica** [BrowserSync/browser-sync#709]
Hi,

I've setup Browsersync with Gulp as follows:

```
gulp.task('default', function() {
  browserSync({
    server: {
      baseDir: "./app",
    }
  });
});
```

Part of my assets are located in the parent folder under `../bower_components`:

```
<script src="../bower_components/webcomponentsjs/webcomponents.min.js"></script>
```

Unfortunately when the server receives a request for these assets it seems to strip away the double dots and look only in the "baseDir" path, generating a `404 (Not found)` error.

Any idea how this could be fixed?

**Comment by shinnn** [comment]
Duplicate: #615

**Comment by pensierinmusica** [comment]
It looks like the way to go is to use the `server.routes` option as shown here: http://www.browsersync.io/docs/options/
