### ISSUE TITLE
Conflict when webpage also uses Socket.io

### ISSUE THREAD

**Issue by nghuuphuoc** [BrowserSync/browser-sync#71]
Browser-sync v0.5.7 works perfectly if I proxy the PHP server. But when using with my nodejs server from the command line (`browser-sync --proxy "localhost:5000" --files "public/asset/css/*.css"`, where my NodeJS site runs under `localhost:5000`), the webpage looks as following:

![browser-sync-nodejs](https://f.cloud.github.com/assets/4226036/2168014/76cf9dc6-952b-11e3-8a6f-8a6e21d82e77.png)

**Comment by iboozyvoozy** [comment]
I have nodejs server with socket.io runned on localhost:9000
After proxyng this on 9001 port with browsersync, i've got on client this error:
`WebSocket connection to 'ws://localhost:9001/socket.io/?EIO=3&transport=websocket&sid=ziwM1jRZVVFPpD5qAAAE' failed: Connection closed before receiving a handshake response`

server:
```
app = express()
server = http.createServer(app)
io = socketio(server)
server.listen(9000)
```

config:
```
proxy: "localhost:9000"
port: 9001
```
