### ISSUE TITLE
Wrong gulp example?

### ISSUE THREAD

**Issue by MattDiMu** [BrowserSync/browser-sync#711]
I've integrated browser-sync in my gulp tool chain like this: http://www.browsersync.io/docs/gulp/#gulp-reload. The part I'm questioning is this one:

```js
// create a task that ensures the `js` task is complete before
// reloading browsers
gulp.task('js-watch', ['js'], browserSync.reload);
```

Basically gulp is watching the js-directory and this 'js-watch' should be called every time a change is detected. 

The problem I've experienced is, that this task never ends, looks like browserSync.reload never returns anything (in the command line i never see any 'finished js-watch' information) and the browser therefore reloads only once. Every change after the first one, won't result in any browser reload, as the 'js-watch'-task is still running.

The following code fixed this for me:
```js
	gulp.task('js-watch', ['scripts'], function(){
		browserSync.reload();
		return;
	});

```

**Comment by shakyShane** [comment]
The technique you've mentioned works well in my tests. I also use it in [this recipe](https://github.com/BrowserSync/recipes/blob/master/recipes/gulp.jade/gulpfile.js#L25) for compiling dog-slow jade templates.

Perhaps there's something else in your gulpfile.js setup that's causing this issue - I'd be more than happy to look at a sample repo highlighting this problem though.

**Comment by Enalmada** [comment]
+1.  The current doc format only works once on the first reload after gulp first starts.  After the first file change, the browser will not reload any more.  The console after that point only says "Starting js:  Finished js:"...it never says "Starting js-watch" again.   I have been pulling my hair out trying to figure out how and why it could be skipping js-watch.  Changing to anonymous function made it work every time!
```
gulp.task('js-watch', ['js'], function() {
    browserSync.reload();
});
```

So something in gulp must be being too smart for its own good and caching the relationship between the gulp watch *.js and the ultimate js task skipping the js-watch in the middle entirely.    
(windows 8.1, using the latest version of browsersync, node, gulp, etc)

http://stackoverflow.com/a/30438407/1502448

**Comment by dongseok0** [comment]
Same here. I think this should be reopen.

**Comment by revxx14** [comment]
@Enalmada thank you so much for that! I was running in to the same issue and making it an anonymous function solved it. Spent two hours trying to figure this out.

**Comment by devinus** [comment]
Wow this took me forever to debug. Where are the docs for this http://www.browsersync.io/docs/gulp/#gulp-reload so I can change them myself.

**Comment by devinus** [comment]
`gulp.task('js-watch', ['js'], browserSync.reload);` does NOT work.

**Comment by fegemo** [comment]
+1 - it should be fixed in the docs

**Comment by adrinux** [comment]
Having this issue too. I wonder which gulp version people are using – I'm using Gulp 4.

**Comment by Lorthirk** [comment]
I faced this issue as well. Changing
```
gulp.task("reload", ["build"], browserSync.reload);
```
to:
```
gulp.task("reload", ["build"], function() {
    browserSync.reload();
});
```
fixed it.

**Comment by lgladdy** [comment]
For what it's worth, I came here after having this issue, but it wasn't related to an anonymous function.

It was due to a change in how gulp processes watch tasks, which was way over my head, but explained in https://github.com/gulpjs/gulp/issues/1623 and https://github.com/gulpjs/gulp/issues/1624

**Comment by haluvibe** [comment]
Igladdy is 100% correct! This example worked for me. Note: Using Gulp 4

`function reload(done) {
  browserSync.reload();
  done();
}

gulp.watch('src/styles/*.css', gulp.series(postCss, reload));
`

**Comment by chenxijywc** [comment]
@haluvibe  it works like a charm !!!

**Comment by krmao** [comment]
@haluvibe it works like a charm !!!

**Comment by matheus-moreira** [comment]
@lgladdy thanks for this!
