### ISSUE TITLE
Using BrowserSync with Rails in Vagrant?

### ISSUE THREAD

**Issue by simkessy** [BrowserSync/browser-sync#712]
I am running my Rails application in a VM using Vagrant. Vagrant forwards the post 3000 so I can access my site from localhost:3000. 

This is my vagrantfile:

```rb
Vagrant.configure('2') do |config|
	config.vm.box      = 'ubuntu/trusty64'
	config.vm.hostname = 'rails-dev-box'

	config.vm.network :forwarded_port, guest: 3000, host: 3000

	config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true

	config.vm.provider "virtualbox" do |v|
		v.name = "RubyDev"
	end

	config.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 4
	end

	# Host manager settings
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = true
  config.hostmanager.include_offline = true
  config.vm.define 'default' do |node|
    node.hostmanager.aliases = %w(devbox.local playtoday.com dev)
  end

end
```

In my vm, I run `browser-sync start --config bs-config.js` and that file is the default that comes from `init` but I've changed these properties:

```
    "files": ["app/assets/stylesheets/*.scss, app/views/*.html.erb", "*/**/*.html.erb","*/**/*.scss"],
    "watchOptions": {},
    "server": false,
    "proxy": "localhost:3000",
    "port": 3000,
```

Yet, when I make a change, nothing shows in [BS] it just keeps saying `watching files...` and my page never reloads when I make changes. 

Do I need to forward port 3001 as well in vagrant?

**Comment by shakyShane** [comment]
Hi - this sounds more like an issue with file mappings between host/vagrant. If you could provide a tiny sample project showing this issue then I'd be happy to help
