### ISSUE TITLE
Multiple virtualhosts

### ISSUE THREAD

**Issue by Glaived** [BrowserSync/browser-sync#714]
Hello, if I have two virtualhosts, **test1.dev** pointing to `C:/test1`, **test2.dev** that points to `D:/doc/test2`

Are I bit into a single browser-sync server be listening, observing, both vhosts same time?

**Comment by shakyShane** [comment]
You can run multiple instances, each pointing at a separate directory.

Alternatively, you can provide multiple base directory from which to serve files.

Please review `baseDir` from the [server options](http://www.browsersync.io/docs/options/#option-server)
