### ISSUE TITLE
rewriteRules does not appear to work (2.7.13)

### ISSUE THREAD

**Issue by replete** [BrowserSync/browser-sync#715]
Running on Windows 8.1 64-bit in git-bash.

```bash
$ node --version
v0.12.4
```

```javascript
'use strict';

var gulp = require('gulp');
var browserSync = require('browser-sync');
var reload = browserSync.reload;


gulp.task('watch', ['serve'], function () {
    gulp.watch('./**/*.*', reload);
});

gulp.task('serve', function () {
    browserSync.init(null, {
        server: {
            baseDir: './',
            directory: true
        },
        port:5000,
        ghostMode: {
            clicks: false,
            location: false,
            forms: false,
            scroll: false
        },
        rewriteRules: [
            {
                match: /WebsiteUrl/g,
                fn: function (match) {
                    return 'TEST';
                }
            }
        ],
        injectChanges: false,
        notify: false,
        reloadDelay: 0//1000
    }, function (err, bs) {
        require('opn')(bs.options.getIn(["urls", "external"]));
        console.log('Started connect web server on ' + bs.options.getIn(["urls", "external"]));
    });
});

gulp.task('default', [], function () {
    gulp.start('serve');
});
```

```javascript
{
  "name": "emailtemplates",
  "version": "1.0.0",
  "description": "Email Templates for the Website project",
  "author": "",
  "devDependencies": {
    "browser-sync": "^2.7.13",
    "opn": "^3.0.2"
  }
}
```

Any ideas? Really frustrating. It seemed to work a few times, but not globally.

**Comment by replete** [comment]
It was working sometimes on subsequent page reloads. May be something to do with watch.

**Comment by shakyShane** [comment]
version of Browsersync?

```js
npm ls browser-sync
```

**Comment by shakyShane** [comment]
@replete also, if it's a simple string replacement, don't use regex - you can give a string.

```js
rewriteRules: [
            {
                match: 'http://some.string',
                replace: 'http://some.other.string'
            }
        ],
```

**Comment by replete** [comment]
@shakyShane That is great - I just wish that was in the documentation ;)

However, the issue was it only worked _sometimes_.

Anyway, I'm sure this bug will crop up somewhere else.

Thanks.

**Comment by shakyShane** [comment]
Are you running at least 2.7.13?

**Comment by replete** [comment]
Yes, it's in the package.json I included above.

Was very flakey, I'm assuming something to do with the windows environment perhaps?

**Comment by atalis** [comment]
I'm having a similar issue with v.2.11.1, running as a proxy to an Express server.  I need to do something like this: when a link to '/redirectExample' is clicked, I want it to be redirected to index.html.  Here is my code snippet:

    var browserSyncOptions = {
      proxy: {
        target: "https://localhost:"
      },
      rewriteRules: [
        {
          match: '/auth/provider',
          replace: '/'
        }
      ]
    };

According to the server, index.html is the file that is being loaded:
    GET /index.html 200 0.775 ms - 1056

however, the browser still shows an empty page with the URL https://localhost:3000/redirectExample.  I tried various ways of such a redirect, by providing a brute-force middleware for the proxy itself, such as 

    var browserSyncOptions = {
      proxy: {
        target: "https://localhost",
        middleware: function (req, res, next) {
          console.log(req.url);
          if (req.url.indexOf('/redirectExample') > -1) {
            req.url = '/';
          }
            next();
        }
      }
    };

OR by using the connect-history-api-fallback plugin:
   var history = require('connect-history-api-fallback');

    var browserSyncOptions = {
      proxy: {
        target: "https://localhost:" + port,
        middleware: history({
          rewrites: [
            { from: '/redirectExample', to: '/'}
          ],
          verbose: true
        })
      },
    };

but nothing works.  Any ideas of what am I doing wrong?

**Comment by digeomel** [comment]
I'm having a similar problem as described above with version 2.18.7.
rewriteRules doesn't work at all, doesn't seem to intercept any string or regex I pass to it.
middleware works when I specify the route and handle parameters, but I have no clue how to redirect the request to what I want. Setting the req.url parameter as @atalis is doing in his example above doesn't seem to have any effect. I assume I have to modify the res object, but I don't know how... :slightly_frowning_face:

**Comment by digeomel** [comment]
Please ignore my last comment, I just realized that rewriteRules is about rewriting HTML, not HTTP requests! :blush:

**Comment by digeomel** [comment]
The question now is how can I redirect a request using the middleware configuration? The documentation for middleware in browsersync leaves a lot to be desired and the recipe you have with LESS is great, but not really a redirection. What I'm trying to do is something like redirect all requests of type `/getmehere?a=1&b=2` to `/gothere/a1/b2`

Or, is there another way to redirect requests in browsersync?

Thanks

**Comment by digeomel** [comment]
Finally got it to work by reading this article:
https://vinaygopinath.me/blog/tech/url-redirection-with-browsersync/
I had to specify middleware directly as a function, as described in the article above. When middleware is defined as described in the documentation, as an array of objects, it doesn't work (i.e. trying to redirect by setting req.url doesn't work).
