### ISSUE TITLE
Cannot get middleware to work with xhr requests

### ISSUE THREAD

**Issue by kotfilemon** [BrowserSync/browser-sync#716]
Hi,

following https://github.com/BrowserSync/browser-sync/issues/471 I tried to proxy all my request to backend API to avoid cors. What supprised me, the calls to the API donot go throught browser sync. 

my config:

```javascript
module.exports = {
    dev : {

        bsFiles: {
            src: '<%= folder.build %>/**/*.*'
        },
        options: {
            watchTask: true,
            server : {
                baseDir: '<%= folder.build %>',
                middleware: [function (req, res, next) {
                    console.log(req.url);
                    next();
                }]
            },
            port: 4000,
            logLevel: 'debug'
        }
    }
};
```

it shows me only the static calls to scripts are made so I cannot proxy the call to the url

```javascript
[BS] Browser Connected: Chrome, version: 43.0.2357.130
/
/my-app.css
/my-app-vendor.js
/my-appjs
[BS] Browser Connected: Chrome, version: 43.0.2357.130
/assets/i18n/lang-en.json
/assets/fonts/glyphicons-halflings-regular.woff2
/assets/flags//4x3/gb.svg
/assets/fonts//fontawesome-webfont.woff2?v=4.3.0
/favicon.ico
```

any one managed to do it what I try to achieve?

**Comment by shakyShane** [comment]
Only urls served via Browsersync are accessible to middlewares - this issue suggests that your endpoints are not running through the address Browsersync gives you.

If I'm incorrect, please reply with more info such as the Browsersync URL given to you along with the full path to your endpoints
