### ISSUE TITLE
Can i inject DOM String content directly to get it reflected in browser-sync server

### ISSUE THREAD

**Issue by saurshaz** [BrowserSync/browser-sync#724]
I am having DOM markup in a string.
I want to start a server and serve that on /test url
Is it even possible using browser-sync ?

**Comment by shinnn** [comment]
1. Create and launch your own server that supports DOM markup.
2. Use [`proxy` mode](http://www.browsersync.io/docs/options/#option-proxy) to integrate it with Browsersync.

**Comment by saurshaz** [comment]
Thanks @shinnn . WIll give that a try. Do you have a reference example handy ? or is this rarest of rare use case :-) ?

**Comment by saurshaz** [comment]
http://www.browsersync.io/docs/options/#option-proxy Does not seem to be related to what i need. I think browser-sync does not have an option to monitor string DOM content, only has  file sync changes syncing options. 

Here's what I am after - stackoverflow.com/questions/31224280/can-i-start-browser-sync-with-a-specified-string-dom-content

**Comment by shinnn** [comment]
> Do you have a reference example handy ? or is this rarest of rare use case :-) ?

Read the [contribution guide](https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem) before:

> We're trying to keep the Issues thread for actual bugs with code & implementation.

Or, other maintainers interested in this use case may answer this if they have enough time.

I'm confused that your first comment https://github.com/BrowserSync/browser-sync/issues/724#issue-94951711 and [the question on StackOverflow](https://stackoverflow.com/questions/31224280/can-i-start-browser-sync-with-a-specified-string-dom-content) seem quite different for me.

**Comment by saurshaz** [comment]
>>Read the contribution guide before: 
Thanks. Did that. Sorry if the breach disturbed things

>> I'm confused that your first comment #724 (comment) and the question on StackOverflow seem quite different for me.

Maybe I was unclear, but Iw as looking at the stackoverflow scenario fix only.whether browser-sync has a capability for that was the question. seems it needs to be a 'feature built' on the cards
