### ISSUE TITLE
windows 8 browser-sync install > Socket.IO Node-GYP issue

### ISSUE THREAD

**Issue by dhenriet** [BrowserSync/browser-sync#728]
Hi, I can't install browser-sync without errors on windows 8.1 64 bits. It was working before. 
I saw this fork https://github.com/cchamberlain/browser-sync, so is browser-sync is always working for windows users ?

![screenshot_1](https://cloud.githubusercontent.com/assets/4640027/8772986/0252697e-2ed1-11e5-91f1-af493743df48.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/4640027/8772987/0254b2d8-2ed1-11e5-9088-7f6eff62b28d.jpg)

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/issues/542#issuecomment-87436021

**Comment by dhenriet** [comment]
@shinnn sorry, I've read comments, try browser-sync fork and nothing is working. So it means that browser-sync is not compatible with a global installation on windows 8, why you don't notify it on http://www.browsersync.io/ ?

**Comment by shinnn** [comment]
> I am using browser-sync's npm globally and not socket.io's npm ?

Socket.IO is one of the dependencies of Browsersync.
