### ISSUE TITLE
How to start one of many browsers.

### ISSUE THREAD

**Issue by libook** [BrowserSync/browser-sync#732]
I have a development team. MACOS users are using chrome. And Linux users are using chromium.
I should set the 'browser' option to 'google chrome' for MACOS, and 'chromium' for Linux.
If I set the 'browser' option to '["google chrome","chromium"]', I will get 'spawn ENOENT' error both on MACOS and Linux.
Is there any way to let BrowserSync start 'google chrome' or 'chromium'? Or can it start both of them without errors?

**Comment by shinnn** [comment]
Read the contributing guide before opening new issues. https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

=======

https://nodejs.org/api/process.html#process_process_platform

```js
browser: process.platform === 'dawin' ? 'MAC_OS_X_SPECIFIC_BROWSER' : 'OTHER'
```

**Comment by peteruithoven** [comment]
This can also be achieved in bash / a Makefile using something like:
``` bash
ifeq ($(shell uname), Linux)
	$BROWSER='chromium-browser'
else
	$BROWSER='google chrome'
endif
```
