### ISSUE TITLE
Error while building on Windows

### ISSUE THREAD

**Issue by dstout** [BrowserSync/browser-sync#734]
Installed Visual Studio Community 2015 to build browser-sync on Win7. When installing browser-sync on local project, it's throwing an error:

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to files "Release\obj\bufferutil\bufferutil.tlog\bufferutil.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\workspace\templates\public\responsive\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]

**Comment by shinnn** [comment]
Use npm@3. https://github.com/npm/npm/issues/3697
