### ISSUE TITLE
Errors during installation: Can't find executable "python"

### ISSUE THREAD

**Issue by nickpfisterer** [BrowserSync/browser-sync#739]
**OS**
Windows 7 Professional

**BrowserSync Version**
2.8.0

**Issue**
When I install BrowserSync, whether as a local or global module, I see these errors in the log during the installation process:

![browser-sync-python-error](https://cloud.githubusercontent.com/assets/1567037/8895568/caf3334c-3393-11e5-95be-7031d2303ebc.PNG)

It looks like the `utf8-validate` and `bufferutil` dependencies are unable to find a Python executable. This happens twice during the installation process because `socket.io` depends on two modules that depend on `utf8-validate` and `bufferutil`.

The installation process continues and finishes otherwise successfully. BrowserSync _appears_ to work fine despite the errors. I have not yet run into any missing or broken functionality. However, I'm sure you'd rather there be no errors during installation so I felt I should still report this.

**Comment by DustinJackson** [comment]
Same for me on 

windows 8.1 Pro
browser-sync 2.8.0

**Comment by shakyShane** [comment]
thanks @nickpfisterer, but luckily, as you say, it still works :)

This is an issue for the socket.io team, I can see why you've reported here & I appreciate that, but it's not a Browsersync issue so I'll close for now :)

**Comment by nickpfisterer** [comment]
Good point, @shakyShane. Thanks for the response. Looks like Dustin has opened an issue over at socket.io, so we'll continue the conversation there. :smile_cat:

**Comment by gillius** [comment]
On my home machine I could install browser-sync, but not at work. It might be because I'm using a very new node (5.0.0) and npm (3.3.6), maybe it can't (or chooses not to) continue despite these errors. However, I found that if I run `npm -g install browser-sync --no-optional` that it installs and also does not show the errors.

**Comment by Jishaxe** [comment]
Same here. Windows 10!

**Comment by istrau3** [comment]
+1 same issue.
+1 for the --no-optional fix. Not sure what that does though.
