### ISSUE TITLE
Browser-Sync: Command not found

### ISSUE THREAD

**Issue by Jordane-L** [BrowserSync/browser-sync#741]
Hi everybody,

I want to try browser sync ! I downloaded it with the command `npm install -g browser-sync` and now when I use a command of browser-sync as `browser-sync start --proxy`, `browser-sync start --server` or `browser-sync --version` I have an error > -bash: browser-sync: command not found.

I use Mac OS X mavericks!

An idea ? :) Thanks

**Comment by shinnn** [comment]
@Jordane-L Can you correctly install other npm-based CLI tools, like `babel` and `gulp`?

**Comment by Jordane-L** [comment]
@shinnn I tried to edit my .bash_profile and to create this line : export PATH="$HOME/npm-global/bin/:$PATH"
Now, Browser Sync works :). 

I must to install gulp with this command: **npm install browser-sync gulp --save-dev** or this command: **npm install --global gulp** ? Because when I use the first command I have errors:
![capture d ecran 2015-07-29 a 16 30 30](https://cloud.githubusercontent.com/assets/7188658/8957393/479b756c-360f-11e5-917c-9658c42fd7f6.png)

Thank you!
