### ISSUE TITLE
Move to eslint (instead of both jshint + jscs)

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/browser-sync#745]
@shinnn - I'm tried of using two tools for lint/correctness, [eslint](https://github.com/eslint/eslint) seems to do both - any experience?

**Comment by shinnn** [comment]
:+1: 

Yes, I was just planning exactly the same thing, and happy to see you posted this issue. Recently I use ESLint instead of those two linters, whenever I create a Node module.

**Comment by shakyShane** [comment]
Ok cool - Are you happy to take this on?

**Comment by shinnn** [comment]
Sure. I'll check corresponding rules between ESLint and JSHint/JSCS, then create `.eslintrc` for this project.

**Comment by shakyShane** [comment]
Excellent - I also want to remove gulp too, so that's next on the list

**Comment by shakyShane** [comment]
Also want to swap mocha for tape, but that's a bigger deal given there's over 400 tests

**Comment by shinnn** [comment]
> want to swap mocha for tape

+1000

**Comment by shakyShane** [comment]
I'll take that one on as I want a huge refactor for tests also

**Comment by IanVS** [comment]
Let me know if you guys need any help moving to ESLint.  I don't have bandwidth right now to do a full PR, but I can help answer questions and address ESLint issues if you run into any.

**Comment by stevemao** [comment]
@shinnn You do that just because you don't wanna maintain two modules to lint? I do this mainly just for this reason as I found maintain two meta data files is just harder :)

**Comment by shakyShane** [comment]
@stevemao - It's simply reducing 2 tools to 1, nothing more complicated than that :)

**Comment by stevemao** [comment]
Just very surprised that you guys doing this for the same reason lol. Usually I like smaller modules with limited scope but this is one exception :)

**Comment by IanVS** [comment]
From a cursory search, I've seen several projects doing this.  Nobody really likes the overhead of maintaining two essentially identical tools when one will do the job.

**Comment by shakyShane** [comment]
@IanVS - yep! And there's 1 feature in eslint that completely won me over in other/work work project - when there's a failure, it gives you the exact rule name right there in the CLI output - no searching docs for rule names! ha!

**Comment by shakyShane** [comment]
:heart: eslint

**Comment by IanVS** [comment]
Thanks for the feedback.  Glad you are liking it. 

Have you seen any of the custom formatters? For example, `eslint-friendly-formatter` will give you a clickable link which will open your editor to the offending line (if your terminal supports it).

**Comment by shakyShane** [comment]
@IanVS ohh nice! I've only used the bundled reporter so far.

**Comment by shakyShane** [comment]
:tada: 

It's a small rule set to just get us going, but at least it's there now :)
