### ISSUE TITLE
changes in real time !

### ISSUE THREAD

**Issue by Jordane-L** [BrowserSync/browser-sync#748]
Hi!,

I have 1 question ! Why in Browsersync must save the file (ctrl+s/cmd+s) to see the changes? For example in Brackets editor, if using the live preview, you can edit CSS properties without saving the file, and changes are made in the browser in real time. It's complicated to implement such technology? This is a suggestion to improve browsersync and save time. Thanks

**Comment by shinnn** [comment]
1. Enable your editor's auto-saving option.
2. Set the auto-saving rate to the extremely high frequency.
