### ISSUE TITLE
Styles broken on remote IP. Remote debugger lists `Targets: None`. 

### ISSUE THREAD

**Issue by janaspage** [BrowserSync/browser-sync#751]
Desktop browser (Mac Chrome) connected to localhost works. Live reload works. 

Desktop browser connected to remote debugging IP/port works. 

Mobile devices (Android, iOS) connected to remote debugging iP/port load markup only, **no styles**. Synced scrolling works across desktop and mobile. 

Weinre remote debugging tool in desktop browser reads `Targets: None`. 

Remote debugger is toggled to `on` in the BS desktop dashboard. 

I've tried refresh, reload, and reset.

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by janaspage** [comment]
I've resolved the issue by connecting both machines to wifi, rather than letting the desktop device browse by ethernet. My office uses two slightly different IP addresses for each. Thank you.

**Comment by shinnn** [comment]
Glad to hear you solved the issue.
