### ISSUE TITLE
Invalid certificate regarding localhost

### ISSUE THREAD

**Issue by juergenzimmermann** [BrowserSync/browser-sync#754]
browser-sync 2.8.2 provides a new certificate https://github.com/browsersync/browser-sync/issues/750 because the old one was expired. However, when using this certificate with https, then I get an error as shown in the attached screenshot.
The translation in English:
* title: data security Violation
* Verbindung = Connection
* "Die Identität ..." = "The identity of this web site wasn't verified. The Server certificate doesn't confirm with the URL".
![certificate-url](https://cloud.githubusercontent.com/assets/734334/9026325/7493adfe-392b-11e5-9d9e-79cd2b55383a.png)

**Comment by lindleywhite** [comment]
I have this issue as well. I don't think that the SSL Certificate was signed to localhost.

**Comment by shakyShane** [comment]
@lindleywhite, @juergenzimmermann 

I've just been testing this issue again and can no-longer reproduce it. Can either of you?

**Comment by juergenzimmermann** [comment]
@shakyShane I just downloaded and installed the fresh browser-sync 2.8.3. The issue still exists. The certificate looks as follows:
![cert browser-sync](https://cloud.githubusercontent.com/assets/734334/9660453/038531ca-5256-11e5-860e-3b6d3d2fa3de.png)
However, it should look like this example:
![cert http-server](https://cloud.githubusercontent.com/assets/734334/9660529/5a5e4630-5256-11e5-9481-efab4deb53db.png)
The difference is: in your certificate you have "Internet Widgits Pty Ltd", but it should be "localhost" for local development

**Comment by shakyShane** [comment]
@juergenzimmermann could you please now try browser-sync@2.9.1

**Comment by juergenzimmermann** [comment]
You are almost there. Now Chrome only complains about the SHA-1 key to be an old algorithm (see below). I also attach a screenshot how Chrome looks when the cert is based on SHA-512.
![browser-sync sha1](https://cloud.githubusercontent.com/assets/734334/9664680/ba088d42-526b-11e5-89ae-f3caa9f76a0e.png)
Now the screenshot with a SHA-512 based cert:
![sha512](https://cloud.githubusercontent.com/assets/734334/9664683/bf4c7fb6-526b-11e5-9b31-1a65146d9a03.png)

**Comment by shakyShane** [comment]
Could you provide details about how you created that cert? Having trouble with that bit

**Comment by juergenzimmermann** [comment]
I guess you are using OpenSSL (another Option would be "keytool" from a Java installation). So here are my 2 commands for OpenSSL with line continuation for Windows (^):

```
openssl genrsa -out mykeyfile.pem 8192
openssl req -new -x509 -sha512 -key mykeyfile.pem ^
  -out config/http-server.cer -days <NumberOfDays> ^
  -subj "/emailAddress=my.name@foo.org/CN=localhost/OU=My Organizational Unit/O=My Organization/L=MyCity/ST=MyState/C=de"
```
"C" means country code with 2 characters. Of course, you can omit the email address or the city (L = location) from the subj(ect) parameter.
I took the infos from the man pages of OpenSSL:
* https://www.openssl.org/docs/manmaster/apps/genrsa.html
* https://www.openssl.org/docs/manmaster/apps/req.html

**Comment by shakyShane** [comment]
Thanks!

**Comment by shakyShane** [comment]
PR? :p

**Comment by juergenzimmermann** [comment]
Can you give me a pointer where you're generating the cert?

**Comment by shakyShane** [comment]
https://github.com/BrowserSync/browser-sync/tree/master/lib/server/certs

**Comment by shakyShane** [comment]
If you could also update that `gen.sh` file with the exact command you use also (only used for later reference)

**Comment by shakyShane** [comment]
Ignore the `.pfx`
