### ISSUE TITLE
tunnel error

### ISSUE THREAD

**Issue by pokaxperia** [BrowserSync/browser-sync#755]
After a few minutes, I receive this error:
![screen shot 2015-08-03 at 14 50 33](https://cloud.githubusercontent.com/assets/1803166/9046282/2a2aea9c-39ef-11e5-8cc9-4a0f69e6e7fb.png)

Thank you.

**Comment by shinnn** [comment]
Discussion related to this problem goes to https://github.com/localtunnel/localtunnel/issues/81.
