### ISSUE TITLE
bs.exit() should not kill current process, it should kill the bs server process

### ISSUE THREAD

**Issue by j-funk** [BrowserSync/browser-sync#757]
Running this in my build tool had me pulling my hair out until I realized it was killing the whole build and not just the browser-sync server.

**Comment by fusepilot** [comment]
Just went though the same thing. There should definitely be a way to kill bs and keep the current process alive.

**Comment by shakyShane** [comment]
A fix is coming shortly

**Comment by shakyShane** [comment]
v2.9.2

https://github.com/BrowserSync/browser-sync/commit/d1c26148199f0cc71cc203b49523b1bdb24d0333

**Comment by fusepilot** [comment]
@shakyShane works great. Thanks!

**Comment by shakyShane** [comment]
@fusepilot You're welcome
@j-funk sorry for the delay

**Comment by davej** [comment]
The server still loiters around for a while if there are client connections open. This can lead to strange behaviour when spinning up a new browsersync instance on the same port.

Perhaps it's worth considering destroying the client connections when `exit` is called. Something like: https://github.com/isaacs/server-destroy/blob/master/index.js

**Comment by j-funk** [comment]
Thanks for taking care of this!
