### ISSUE TITLE
Load the project specific .browsersync.{yml|json} file

### ISSUE THREAD

**Issue by shivapoudel** [BrowserSync/browser-sync#758]
It will be awesome if we can set the projects in dotfile and configs from it for global purpose.
Also `.browsersync.{yml|json}` file in the project dir to launch project specific settings for browser-sync xD

**Comment by shinnn** [comment]
`bs-config.js` file meets your requirements. https://github.com/BrowserSync/browser-sync/wiki/Working-with-a-Config-File

=====

`bs-config.js` should be documented on the website.

**Comment by shinnn** [comment]
@shakyShane `bs-config.js` should be documented on the website.

**Comment by shakyShane** [comment]
@shinnn yep, also I don't think it automatically loads bs-config by default either, which it should.

**Comment by shivapoudel** [comment]
@shakyShane If documented on website let me know here too :)

**Comment by shivapoudel** [comment]
@shakyShane If I use `browser-sync start` then the config is not loaded but it loads on `browser-sync --start --config bs-config.js`. IMO if the directory has config file then the `browser-sync start` should load the config from there xD

**Comment by shinnn** [comment]
> IMO if the directory has config file then the `browser-sync` start should load the config from there

https://github.com/BrowserSync/browser-sync/issues/758#issuecomment-128359229

> If documented on website let me know here

You can [watch](https://github.com/BrowserSync/browsersync.github.io/watchers) the [site repo](https://github.com/BrowserSync/browsersync.github.io).

**Comment by shakyShane** [comment]
This be an easy PR for someone. 

If this fails, you could look in cwd for bs-config.js https://github.com/BrowserSync/browser-sync/blob/master/bin/browser-sync.js#L61
