### ISSUE TITLE
Multiple base directories with the CLI

### ISSUE THREAD

**Issue by tbassetto** [BrowserSync/browser-sync#762]
If we use BrowserSync programatically we can have multiple directories for the server options:

```javascript
// Multiple base directories
server: {
    baseDir: ["app", "dist"]
}
```

But is it possible to do the same with the CLI? I can't find the right way to format the arguments.

**Comment by shakyShane** [comment]
Actually yes.

because this also works via the api

```js
server: ["app", "dist"]
```

that means you can provide multiple server flags and Browsersync will receive it as an array.

so..

```js
browser-sync start --server app --server dist
```

is identical to the first example
