### ISSUE TITLE
Ability to disable sync functionality

### ISSUE THREAD

**Issue by mikehaas763** [BrowserSync/browser-sync#763]
Essentially what I would like to do is have the ability through configuration to disable all the sync functionality so that Browsersync becomes just a web server. The way I can do this now is to use the `scriptPath` option to return a path that does not exist. However, that still results in a request it just ends up being a 404. It would be nice if there was a better way. Does this functionality already exist and I just missed it?

I use the Protractor E2E testing framework and that's why I want this feature. A regularly started up Browsersync server causes Protractor to timeout. With educated guessing, I believe this is because Protractor sees the socket connection open and believes that the page is not yet ready to be tested. I could be wrong about that. What I do know is that using a false scriptPath results in Protractor working. So essentially when Browsersync's script is not loaded.

**Comment by shakyShane** [comment]
http://www.browsersync.io/docs/options/#option-ghostMode

```js
ghostMode: false
```

**Comment by shakyShane** [comment]
Oh, just read that again, are you saying it's just the loading of the script file you want to cancel

**Comment by shakyShane** [comment]
If yes, then you want `snippetOptions.blacklist`

```js
snippetOptions: {
    blacklist: ["/", "**/*"]
}
```

**Comment by mikehaas763** [comment]
@shakyShane Yes

**Comment by shakyShane** [comment]
Ok, then my comment above will work as you need :)

**Comment by mikehaas763** [comment]
Does the client script serve any purpose if the socket connection was disabled? I'm wondering if the ability to just disable the socket connection is a less drastic option.
