### ISSUE TITLE
Server multiple baseDir not working

### ISSUE THREAD

**Issue by ssylvia** [BrowserSync/browser-sync#765]
I'm trying to set up a live reload site through browserSync. I have a src/ directory that contains all my javascript file, swig templates, scss files, and images. I also have a build/ directly with the scss files get converted to css files and swig templates get converted to html files.

I'm using this setup on grunt:

```
browserSync: {
    dev: {
        bsFiles: {
            src : ['src/','build/']
        },
        options: {
            server: {
                baseDir: ['./build','./src']
            }
        }
    }      
}
```

However, browser sync only sees the first base directory although both are being outputted in the terminal.

**Comment by shakyShane** [comment]
Hi! Thanks for your issue report.

There's a high probability that this is not actually an issue with Browsersync - the baseDir option is well tested and it's possible that you're expectations may be incorrect. 

For these reasons I will initially close this issue, but should you provide us with a small sample repo demonstrating this problem we'l happily re-open it and investigate. Thanks again.
