### ISSUE TITLE
HTTP/2 support 

### ISSUE THREAD

**Issue by Globegitter** [BrowserSync/browser-sync#766]
I started playing around with HTTP/2, seeing as all major browsers already support it or are going to support it very soon. It makes a lot of things easier with sending multiple files to the client so could possibly make file injections easier/faster. 

There's a great module for that,  https://github.com/molnarg/node-http2, which seems to be backwards compatible with node's HTTP module and supports old browsers/clients as well. 

What do you think?

**Comment by shakyShane** [comment]
@Globegitter looks great! 

We don't do anything fancy with server atm, so I imagine this could be just a drop-in replacement.

**Comment by shinnn** [comment]
I'm really glad if Node itself has HTTP/2 support and it's discussed in https://github.com/nodejs/NG/issues/8.

**Comment by chrismbeckett** [comment]
+1 - would really love to see HTTP/2 support. Sounds like it could be really easy by using node-http2 as noted by @Globegitter

**Comment by bmayen** [comment]
:+1:

**Comment by christophehurpeau** [comment]
:+1:

**Comment by sklar** [comment]
:+1:

**Comment by frederikschubert** [comment]
+1

**Comment by SuperMartas** [comment]
:+1:

**Comment by Webjin** [comment]
+1

**Comment by nmocruz** [comment]
+1

**Comment by OlsonDev** [comment]
+1

**Comment by anzeznidarsic** [comment]
+1

**Comment by shintonik** [comment]
+1

**Comment by Slumber86** [comment]
+1

**Comment by Slumber86** [comment]
Serving many many files in develop this would save me A LOT of time

**Comment by Itrulia** [comment]
Any updates? :D

**Comment by zakjan** [comment]
+1

**Comment by glen-84** [comment]
@zakjan Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) now, instead of +1 comments.

**Comment by artdias90** [comment]
+1

**Comment by amitev** [comment]
Progress on this one?

**Comment by lgdexter** [comment]
Any word on this? It would really help given that I'm using System.js and it's making tons of XHR requests.

**Comment by shakyShane** [comment]
The only hold up here is the fact I've never used, or even played around with any HTTP2 implementations yet.

If someone wants to send a PR with changes to https://github.com/BrowserSync/browser-sync/blob/master/lib/server/utils.js#L34-L47 I'd be more than happy to merge it.

https://www.npmjs.com/package/spdy etc

**Comment by lgdexter** [comment]
@shakyShane I will try my best to make an implementation of HTTP/2 today. From my understanding, we just need to generate a key and certificate and add it to an options object when using the `http2.createServer` function. I've already identified where it's being used (`utils.js`).

**Comment by zakjan** [comment]
@lgdexter There is a dummy default certificate for HTTPS, you can use the same for HTTP2.

**Comment by m-andrew-albright** [comment]
+1 

Would really love to be able to test my app's loading performance in development in browser-sync in both http and http/2!

**Comment by supermoos** [comment]
+1

**Comment by Itrulia** [comment]
For the love of god, please stop commenting just +1, just use the emoji reactions please

**Comment by el-davo** [comment]
I have got http working with express and to be honest it was actually slower serving 1000 javascript files than over regular http. Am hugely dissapointed by this.

**Comment by amitev** [comment]
@el-davo Is your app an SPA? What dependency loading library do you use?

**Comment by el-davo** [comment]
Yes I am using angularjs with systemjs and jspm. The http2 library's is node-http2 with express server

**Comment by amitev** [comment]
@el-davo To gain the performance of http2 you can try the [depcache](http://jspm.io/docs/production-workflows.html#creating-a-dependency-cache) functionality of jspm

**Comment by el-davo** [comment]
Thanks! I will give that a go today and report back

**Comment by el-davo** [comment]
Just tried it there. That method shaves about 3 seconds roughly off loading time. thanks @amitev . Every little helps :)

**Comment by amitev** [comment]
@el-davo So there could be a benefit in using http2, right?

**Comment by jakeNiemiec** [comment]
+1

**Comment by avilde** [comment]
+1
