### ISSUE TITLE
class not registered 

### ISSUE THREAD

**Issue by TNT-Likely** [BrowserSync/browser-sync#767]
my os is win 10pro ,when i start server,it show error class not registered,

![qq 20150809192137](https://cloud.githubusercontent.com/assets/9278923/9154611/e99d4d26-3ecb-11e5-80bc-e23629bbd0fd.png)

how do you reslove?

**Comment by shakyShane** [comment]
Are you sure this an error caused from Browsersync?

Try this recipe, https://github.com/Browsersync/recipes/tree/master/recipes/server - if the error still occurs for you on that example, I'll re-open the ticket :)

**Comment by TNT-Likely** [comment]
thanks,it work correct now.
