### ISSUE TITLE
Rebuilding main css file on changes in imported css

### ISSUE THREAD

**Issue by ismay** [BrowserSync/browser-sync#768]
I was wondering if there's a recommended approach for dealing with css that's imported (like a [scss partial](http://sass-lang.com/guide), or a [postcss import](https://github.com/postcss/postcss-import)). The problem is that while browser-sync detects the change in the partial correctly (let's say a change in `partial.css`, it doesn't know that subsequently it should actually be triggering a rebuild of the main file (which imports the partial, `main.css` for example).

So the css isn't rebuilt, and changes only show up after a change to something else (the html for example). What's the recommended approach here?

(For reference, [this](https://github.com/ismay/ismaywolff.nl) is my current setup)

**Comment by connorjsmith** [comment]
Using an scss compiler (like compass or sass) and a `--watch` flag would work wouldn't it? Never liked the native css imports

**Comment by ismay** [comment]
Yeah my sass example wasn't a good one. The postcss import isn't a native one, it looks like a native css import, but it actually inlines the import's content (so it behaves exactly like a sass import). Any ways to deal with that?

**Comment by shakyShane** [comment]
@ismay I think you've misunderstood the purpose of Browsersync - it is not a task runner and there should not be responsible for triggering any kinds of rebuilds.

So, you should compile css (in anyway, with any tool) and then have Browsersync *only* watching the resulting CSS. So, Browsersync doesn't care about `partial.css`, that's the job of post-css or whatever. Browsersync only cares about the final result, `main.css` - then it can issue a command to each browser to re-fetch it.

**Comment by ismay** [comment]
I see. I was assuming that browser-sync was similar to metalsmith-browser-sync (which does trigger rebuilds), but that makes sense. Thanks for explaining!
