### ISSUE TITLE
gulp scss with gulp-rev injection not working - proxy setup

### ISSUE THREAD

**Issue by Marcel-Robitaille** [BrowserSync/browser-sync#769]
I am using gulp-rev to cache-bust my compiled scss files. This means the css injections works only when I don't change anything in my css file. If I change anything, gulp-rev will give it a different name and browserSync won't know to inject it. Here is the scss task in my gulpfile:

````javascript
Object.keys(styles).forEach(function(key){
	gulp.task('css-' + key, function(){
		del.sync([
			'./public/' + styles[key].dir +  manifest[key + '.css'],
			'./public/' + styles[key].dir + '/maps/' + manifest[key + '.css'] + '.map'
		]);
		return gulp.src('./source/' + styles[key].dir + key + '.scss')
			.pipe(plumber())
			.pipe(sourcemaps.init())
			.pipe(sass())
			.pipe(minifycss())
			.pipe(autoprefixer())
			.pipe(rev())
			.pipe(sourcemaps.write('maps/'))
			.pipe(tap(updateManifest))
			.pipe(gulp.dest('public/' + styles[key].dir))
			.pipe(gulpif(
				function(file){return path.extname(file.path) === '.css'},
				browsersync.stream({match: "**/*.css"})
			));
	});
});
````

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by Marcel-Robitaille** [comment]
Well, this is sort of a bug. It seems like `browsersync.stream()` is not working.

**Comment by devboxr** [comment]
This is totally something that should be worked on, every decent project does this. I'm using Laravel with Elixir e.g. and have exactly the same problem.
