### ISSUE TITLE
Add an option to let me specify the base/public directory in proxy mode

### ISSUE THREAD

**Issue by axefrog** [BrowserSync/browser-sync#771]
The only option I could find to specify the "root" public folder of my application was in server mode, but I'm running in proxy mode, so I can't use it. Nevertheless, I can't see any reason why I shouldn't be able to tell BrowserSync that a specific folder is my public root and therefore it will know that if it detects file changes there, that it can inject them into my browser instances. It is already successfully detecting changes to my css file, so why not reload/inject while it's at it, as long as it knows how those files map to my application?

For context, I'm building ASP.NET 5 application and the public path is at `./wwwroot`, with my css files at `/wwwroot/css` relative to my project directory and `/css` relative to the browser root.

**Comment by shakyShane** [comment]
Just specify `files: './wwwroot'` and changes that can be injected, will be (such as css) - any other changes will cause a reload (template files, etc)

**Comment by shakyShane** [comment]
^ that will recursively watch all files, so be careful if you have thousands of files - you might want to limit it to template files, or some specific folder to ASP.NET dev

**Comment by axefrog** [comment]
Hmm, I'll test it out, but my observation was that I was watching the css files I cared about and no injection was happening...

**Comment by axefrog** [comment]
So... it works now. I have no idea why it wasn't working earlier. Thanks for the help though :)

**Comment by axefrog** [comment]
Ok, I'm not sure what changed. I put this project down for a few days, came back, had fix a different configuration issue, and css injection is no longer working. Here is video evidence of that:

http://screencast.com/t/nZllO3AQb6

Just as a test, I changed it from this:
```
files: ['./Views', './wwwroot/**/*.css', './wwwroot/**/*.js']
```
to this:
```
files: './webroot'
```
and there was no difference in behaviour.

My configuration is:
```
browserSync: {
  files: ['./Views', './wwwroot/**/*.css', './wwwroot/**/*.js'],
  reloadDelay: 250,
  reloadDebounce: 1000
}
```
