### ISSUE TITLE
Not refreshing on changes

### ISSUE THREAD

**Issue by ismay** [BrowserSync/browser-sync#773]
[This](https://github.com/ismay/ismaywolff.nl) is my current setup (and more specifically, the configuration for browser-sync is [here](https://github.com/ismay/ismaywolff.nl/blob/master/Makefile#L3)). 

Now from what I understand browsersync tries to match changes to the actual contents of the page it's serving. Which is where I think it's going wrong, because I'm cache-busting my css (unfortunately also in development), and compiling templates from .nunjucks to .html. So when I make changes browser-sync doesn't notice them, and I have to manually refresh (after which the changes *are* visible).

How can I fix this (I've already tried forcing a full-page refresh, doesn't help)? It's a little weird that it tries to be intelligent about file-changes. Wouldn't it be better if it just refreshed/injected on all changes in the watched files? Or am I doing something wrong?

**Comment by shakyShane** [comment]
Yep, this is totally possible, just add the flag `--no-inject-changes` - this will skip any kind of file injection and will just reload each browser.

http://www.browsersync.io/docs/command-line/#command-line-options

**Comment by ismay** [comment]
Thanks for the reply. I've tried that option, but the results are the same. It doesn't pick up any changes, to either css or html.

**Comment by ismay** [comment]
I'll see if I can find any mistakes. I'll let you know if it doesn't work out.

**Comment by shakyShane** [comment]
Do you see any `file changed` messages in the terminal?

**Comment by ismay** [comment]
I think I understand what's going on. Because of the cache busting new css and js files are created for every edit (with an appended hash). And browser-sync doesn't pick up the creation of new files in the directory it's watching (if I'm not mistaken).

When I make manual changes to the files that were there when it started watching it picks up the changes without a problem.
