### ISSUE TITLE
Browser options alternatives / fallbacks?

### ISSUE THREAD

**Issue by peteruithoven** [BrowserSync/browser-sync#777]
Browser-sync has the [browser option](http://www.browsersync.io/docs/options/#option-browser) to enable specifying the browser that should be started. Is there any way to specify alternatives / fallbacks? 
I'm working on both OS X and Linux and dev development is slightly better on Google Chrome and Chromium so I'd like to have browser-sync open the eighter google chrome or chromium, depending on what's available. 
Is this possible? Is there a more general name I could use? 
I've tried `chrome`

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/issues/732#issuecomment-123564581

> https://nodejs.org/api/process.html#process_process_platform
> 
> ```js
> browser: process.platform === 'dawin' ? 'MAC_OS_X_SPECIFIC_BROWSER' : 'OTHER'
> ```

**Comment by peteruithoven** [comment]
Thanks!
