### ISSUE TITLE
very slow npm install :(

### ISSUE THREAD

**Issue by AveVlad** [BrowserSync/browser-sync#782]

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

======

Use [time-require](https://github.com/jaguard/time-require) to find out the real cause and open an issue to its repo instead.
