### ISSUE TITLE
Temporarily disable browsersync using query/hash param

### ISSUE THREAD

**Issue by davej** [BrowserSync/browser-sync#785]
I'd like to be able to disable BrowserSync on a page by adding a query/hash param to the url when requesting the page.

For example:
```
http://localhost:3000/?disable-browsersync
```

This would load the page without the BrowserSync snippet included. Subsequent calls to `http://localhost:3000/` would load the page with BrowserSync included as usual.

Is it possible to do something like this currently? If not, would a PR be accepted for this functionality?

**Comment by shakyShane** [comment]
Sure, use `snippetOptions.blacklist`

```js
var bs = require('browser-sync').create();

bs.init({
    server: './app',
    snippetOptions: {
        blacklist: ['**/*?disable-browsersync']
    }
});
```

You'll need to clear your browser's cache also.

**Comment by davej** [comment]
Thanks! :+1:
