### ISSUE TITLE
HTML5 PushState

### ISSUE THREAD

**Issue by syarul** [BrowserSync/browser-sync#787]
Is there anyway to set up browser-sync server to send my app at every non-static-asset url?

or browsersync to support HTML5 PushState

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report

**Comment by syarul** [comment]
ok I try to look into it, btw tinkering with express with the same issue.

**Comment by syarul** [comment]
Alright I manage to solve by looking to [pushstate-server](https://github.com/scottcorgan/pushstate-server) by [scottcorgan](https://github.com/scottcorgan). 
To solve this I need to create a middleware with express, I did try to use serve-static middleware but get some errors with request to root path. So this might be good as additional setup in the example folder
```javascript
/**
 *
 * Install:
 *      npm install browser-sync pushstate
 *
 * Run:
 *      node <yourfile.js>
 *
 * This example will create a middleware to serve files from within a given root directory
 * with mod rewrite and compression, this will enable push state and history location callback
 * 
 */

"use strict";

var bs      = require("browser-sync").create();
var express = require('express');
var modRewrite = require('connect-modrewrite');
var compression = require('compression');
var path = require('path');
var app     = express();

//the root directory of serve static files
var publicPath = path.resolve(__dirname, 'public');


/**
 * Register with serve-static
 */
app.use(serveStatic(publicPath));

app.use(modRewrite([
      '!\\.html|\\.js|\\.json|\\.ico|\\.csv|\\.css|\\.png|\\.svg|\\.eot|\\.ttf|\\.woff|\\.appcache|\\.jpg|\\.jpeg|\\.gif /index.html [L]'
    ]));
app.use(compression());



/**
 * Start the Browsersync server and
 * load the express app as middleware
 */
bs.init({
    server: "./app",
    middleware: [app]
});
```

If you ok with this, I send a a pull request

**Comment by syarul** [comment]
heh but console keep spewing socket.io pool errors..
