### ISSUE TITLE
Suggestion: less-intrusive notifications

### ISSUE THREAD

**Issue by bfred-it** [BrowserSync/browser-sync#794]
Often the notification on the top right covers the navigation, especially on mobile, forcing me to wait for it to disappear before being able to use it.

I suggest to at least make it click-through (via `pointer-events`) but I set mine to appear across the bottom as well:

```js
{
'display: none',
'padding: 15px',
'font-family: sans-serif',
'position: fixed',
'font-size: 0.9em',
'z-index: 9999999',
'right: 0px',
'left: 0px',
'bottom: 0',
'background-color: #1B2032',
'margin: 0',
'color: white',
'text-align: center',
'-webkit-pointer-events: none',
'-moz-pointer-events: none',
'-ms-pointer-events: none',
'pointer-events: none'
}
```
![style preview](https://cloud.githubusercontent.com/assets/1402241/9534182/8a006a0c-4ccb-11e5-9c5a-fba27a671e7d.png)

**Comment by shakyShane** [comment]
The notifications system is getting an overhaul very soon & will have a few default options re: placement

Until then, you can actually provide your own styles within the Browsersync config, should you desire.

```js
var bs = require("browser-sync").create();
bs.init({
    server: "./app",
    notify: {
        styles: [
            "display: none",
            "padding: 15px",
            "font-family: sans-serif",
            "position: fixed",
            "font-size: 0.9em",
            "z-index: 9999",
            "right: 0px",
            "top: 0px",
            "border-bottom-left-radius: 5px",
            "background-color: #1B2032",
            "margin: 0",
            "color: white",
            "text-align: center"
        ]
    }
});
```
