### ISSUE TITLE
Have Command Line options override the config options?

### ISSUE THREAD

**Issue by peteruithoven** [BrowserSync/browser-sync#796]
There are cases where you'll want to put some general configuration into a config file but you want to change the `startPath` for example. For example to fix file watching on Linux (https://github.com/paulmillr/chokidar/issues/343) I have to enable the usePolling (this can only be done through a config file). Then I have a Makefile with a `start` and `test` command in which I want to reuse the same configuration but I want to alter the `startPath`. It would be great if I could simply do the following: 

```
start:
	./node_modules/.bin/browser-sync start --config bs-config.js
test:
	./node_modules/.bin/browser-sync start --config bs-config.js --startPath test.html
```

Currently the config overrule the commandline options, which seem counter intuitive in general?

**Comment by shakyShane** [comment]
agreed

**Comment by shakyShane** [comment]
this was added in 2.12
