### ISSUE TITLE
Cannot integrate with Django

### ISSUE THREAD

**Issue by mikew** [BrowserSync/browser-sync#797]
We are trying to use browser-sync as an aid during front-end development of a Django app.

So far we've manually added the snippet to Django's HTML file

```html
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://localhost:3000/browser-sync/browser-sync-client.2.8.2.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

And set some options for browser-sync:

```js
{ notify: false,
  ghostMode: true,
  server: { baseDir: [ '../admin/core/static', '../admin/core/static/admin' ] },
  port: 3000,
  host: 'localhost' }
```

The issue is reloading doesn't actually work, browser-sync is still using the django server's IP and port:

```
GET http://192.168.99.100:8000/browser-sync/socket.io/?EIO=3&transport=polling&t=1440778150174-3 net::ERR_CONNECTION_REFUSED
(every second)
```

Is there something we're missing?

**Comment by mikew** [comment]
So we decided on using the proxy option, but now we've got to pragmatically change the value (the server its proxying is in Docker, which is localhost on Linux but a 192.168 IP elsewhere)

If there was a way to tell browser sync the IP and port for websockets this wouldn't be necessary

**Comment by mikew** [comment]
So I've just learned about the `proxy` option, which does work (albeit a little strange, devs still expect to go to Django's server)

but it also provides another issue, now we have to change the proxy option from `192.168.99.100:8000`

**Comment by mikew** [comment]
Setting `socket.domain` to `localhost:3000` is what I was looking for, it's right there in the documentation, apologies for that.

**Comment by shakyShane** [comment]
no problem @mikew, glad you found it :)
