### ISSUE TITLE
Page scrolls up on full page reload

### ISSUE THREAD

**Issue by faergeek** [BrowserSync/browser-sync#80]
When css is changed everything's ok, but when I change js or html it needs full page reload and when it's done the page is scrolled up.
It's reproducible on Chrome, Opera (with Blink), Safari, but not on Firefox. Old Opera (Presto) and IE untested.
It happens even if page reload not initiated by browser-sync. So I think the problem somewhere where you inject scripts or trying to sync scroll to soon may be (but it happens event with ghostMode set to false).
With livereload (using gulp-connect) it doesn't happen.

**Comment by steckerhalter** [comment]
I'm using BrowserSync with https://github.com/hexojs/hexo (plugin: https://github.com/hexojs/hexo-browsersync/) and noticed that upon **[BS] Reloading Browsers...** the page doesn't keep the scrolling position in Iceweasel (Firefox on Debian) 31.6.0.

With Chromium 41.0.2272.118 it works as expected

**Comment by steckerhalter** [comment]
same issue on latest Firefox 37.0.2

**Comment by octoxan** [comment]
Still having this issue in Chrome Version 50.0.2661.102. After page reload the page scrolls up a little, down a little, up a little, and fights me when I try to scroll. Does this for about 30 seconds before giving me the ability to scroll.

**Comment by ArmorDarks** [comment]
Having this issue too, but in my case page jump are pretty big (but always to same, but wrong position).

**Comment by DailyBombs** [comment]
I got the same issue. Chrome Version 56.0.2924.87 (64-bit)

**Comment by ArmorDarks** [comment]
Also worth to mention that in my case after initial load of Browser Sync everything works fine, without accident jump, but after a while it start to jump to same position, like there is an issue with position memorization.

**Comment by Zdend** [comment]
The issue is still there in Chrome Version 56.0.2924.87 (64-bit). In my case it jumps somewhere in the middle of the page.

**Comment by numbfall** [comment]
I have the same issue on every css injection. Firefox 52.0.2 (64-bit). The scroll position goes to somewhere in the middle of the page.

**Comment by aristidesfl** [comment]
Same Chrome Version 61.0.3128.0

**Comment by Kurren123** [comment]
I'm getting this too on the latest version of chrome

**Comment by testgit-1** [comment]
+1

**Comment by testgit-1** [comment]
Firefox 54.0
The scroll position goes to somewhere in the middle of the page.

**Comment by mbxtr** [comment]
Came across this issue while encountering the same problem. I noticed that browser-sync was trying to reload browsers a lot, so I set the `--reload-debounce` (CLI) option to 200. Now, browser-sync only attempts to reload once after making changes and I no longer have scroll position issues.

**Comment by claudiney** [comment]
Same on Firefox 57, page moves to top.

**Comment by muiqo** [comment]
+1 Firefox 57 on Windows

**Comment by onetrev** [comment]
Same issue here. However, in Chrome 67, everything works perfectly, a BrowserSync induced reload and scroll position is maintained. But in Firefox 61 and Edge 17, a BrowserSync reload causes the page to jump to the top. A regular (F5 style) refresh and scroll position is maintained as expected.

**Comment by panoply** [comment]
Chrome version 73 and this issue persists.

**Comment by stgreenman** [comment]
To stop my browser scroll from resetting when saving a SCSS file, I appended `.on('change', browserSync.reload)` to my Gulp Sass watch line.
 
(Note - Gulp v4)
```
gulp.watch('scss/**/*.scss', sassCompile).on('change', browserSync.reload) 
````

**gulpfile.js example:**

```
var gulp = require('gulp');
const { series } = require('gulp');
var sass = require('gulp-sass');
var browserSync = require('browser-sync').create();

function serve(){
  browserSync.init({
    server: {
        baseDir: "./"
    },
  });
  gulp.watch('scss/**/*.scss', sassCompile).on('change', browserSync.reload);
  gulp.watch('./css/*.css').on('change', browserSync.reload);
  gulp.watch("./*.html").on('change', browserSync.reload);
}
exports.serve = serve;

function sassCompile(cb) {
  return gulp
      .src('./scss/*.scss')
      .pipe(sass()) // Converts Sass to CSS with gulp-sass
      .pipe(gulp.dest('css'))
      .pipe(browserSync.stream());
  cb();
}
exports.sass = sassCompile;

exports.default = series(serve);
```

**Comment by TamirCode** [comment]
when saving SCSS file my chrome skips to the bottom of the page.

**Comment by snuup** [comment]
I have a very trivial page. Whenever I scroll in one browser the other browser scrolls to the top. This is extremely disturbing, since i want to compare the pages - which is now impossible.
