### ISSUE TITLE
Is browser-sync meant for deployment?

### ISSUE THREAD

**Issue by zwhitchcox** [BrowserSync/browser-sync#800]
Probably a stupid question, which is why I can't find an answer...but is browser sync mean for deployment or just your development environment? I mean, I don't think it would really make sense for deployment, and you would probably be creating a websocket server for no reason at all, but I guess it would just prevent me from having to create a development and a server environment, and with tools like source maps, it seems like you don't really need to anymore.

It's been burning on my mind throughout the entire documentation.

Sorry.

**Comment by shakyShane** [comment]
Development only :)
