### ISSUE TITLE
Inject css very slow

### ISSUE THREAD

**Issue by lmnnn** [BrowserSync/browser-sync#801]
I need some help...
![image](https://cloud.githubusercontent.com/assets/10400425/9623596/896e2738-5175-11e5-99a4-01cad4a1bf97.png)
Inject css very slow when I save my css on webstorm.
I must to wait these request end. Times are too long. around 2-3 seconds.

os: win10
node: v0.12.7

gulpfile:

var gulp = require('gulp');
var browserSync = require('browser-sync').create();
var watch = require('gulp-watch');
var reload = browserSync.reload;

var path = {
    html: '**/*.html',
    css: '**/*.css'
};

gulp.task('server', function () {
    browserSync.init({
        server: {
            baseDir: './',
            directory: true
        }
    });
    gulp.watch([path.html]).on('change',reload);
    gulp.watch([path.css],['css']);
});

gulp.task('css',function () {
   gulp.src(path.css)
       .pipe(watch(path.css))
       .pipe(browserSync.stream());
});

gulp.task('default', ['server']);

Thanks.

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem

---------

Return the `gulp.src` stream inside the task. https://github.com/gulpjs/gulp/blob/87e8364f2c445c717ed5287b1b28c6ba02a1801f/docs/API.md#return-a-stream

**Comment by lmnnn** [comment]
Thank you.
