### ISSUE TITLE
Should have ability to disable reload/injections via UI

### ISSUE THREAD

**Issue by codeofsumit** [BrowserSync/browser-sync#802]
We searched for a way to stop automatic refresh (auto-reload / live-reload) of the page when changing a file.

Turns out, it is possible when clicked on "disable all" on the following screen:

![image](https://cloud.githubusercontent.com/assets/2399810/9653650/371298ba-5225-11e5-9af7-608d731ba1b5.png)

Even when re-enabling all options on this page, the page won't be automatically reloaded. When "enable all" is clicked again, live-reload works again.

We searched for exactly this option but the current UI doesn't show if live-reload is active or not or that it even can be changed there.

**Comment by shakyShane** [comment]
also `codeSync: false` in the Browsersync config will disable all reloads

**Comment by shakyShane** [comment]
fixed via https://github.com/BrowserSync/UI/commit/eb9d5b3ddb47a02ba92f40fdcb1ffcb450808027

**Comment by sgarbesi** [comment]
@shakyShane Is this a way to simply disable browser sync on a given page? Maybe just a small snippet in console? For example I have to run through a number of steps on Page A, meanwhile I'm plugging away at Page B trying to fix an issue, but I don't want Page A to reload, just Page B. Both pages sharing the same project.

**Comment by johannesjo** [comment]
@sgarbesi That command somehow does not work any more.
