### ISSUE TITLE
Changing the default browser?

### ISSUE THREAD

**Issue by andysaini** [BrowserSync/browser-sync#803]
Hi! How do I change the default browser launched by browser-sync command?

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem
http://www.browsersync.io/docs/command-line/#command-line-options

**Comment by andysaini** [comment]
Can I set the value in some config file such that I don't have to specify it every time I run browsersync?

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/blob/f8c6a0ae33a1150a3cc7c4844a9dc1f8a6ba7407/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by shakyShane** [comment]
http://browsersync.io/docs/options/#option-browser
