### ISSUE TITLE
SCSS + Sourcemaps, not reloading, not injecting

### ISSUE THREAD

**Issue by robertbaker** [BrowserSync/browser-sync#806]
Using gulp and gulp-sass (not the ruby one)

```js

gulp.task('compile:scss', function(done) {
    return gulp.src([path.join(config.path.srcApp, config.glob.scss)])
        .pipe(initSourceMaps())
        .pipe(plugins.cached('scss'))
        .pipe(plugins.sass({outputStyle: doMinify() ? 'compressed' : 'expanded'}))
        .pipe(plugins.remember('scss'))
        .pipe(plugins.concat('app.css', {newLine: ''}))
        .pipe(writeSourceMaps())
        .pipe(gulp.dest(config.path.buildApp))
        .pipe(browserSync.stream({match:'**/*.css'}));
});


```
My sourcemaps are external *.map files.

If I remove the sourcemaps and just have stream() it injects the css fine. However, I can't get the css to inject with sourcemaps.

In the above example, it's not reloading or injecting. If I take out the match, but leave in sourcemaps, it reloads.

Help?

I tried match: '*.css', 'app.css' '!**/*.map', '!*.map'

**Comment by shakyShane** [comment]
This sounds like it's probably an actual bug in Browsersync, but rather an implementation/integration problem. 

Even so, we're still happy to help. Please provide the results of placing `https://www.npmjs.com/package/gulp-debug` just before `browserSync.stream()`

Also provide either a full gulp file, or ideally a small sample showing your issue (just like https://github.com/BrowserSync/recipes/tree/master/recipes/gulp.sass)

**Comment by mdreizin** [comment]
@shakyShane I also have that issue.

I have got large stream and `browser-sync` fails to reload it.

doesn't work:

```
.pipe(gulp.dest(...))
.pipe(bs.stream())
```

works

```
.pipe(bs.stream())
.pipe(gulp.dest(...))
```
