### ISSUE TITLE
Error: listen EADDRINUSE : instance not killed with gulp, but after refresh website

### ISSUE THREAD

**Issue by raDiesle** [BrowserSync/browser-sync#807]
by using different versions, e.g. 2.9.1
and windows or linux

I run within gulp with the following two properties

```js
browserSync.init(filesToWatch, {
            server: {
                baseDir: "*"
            },
            startPath: "localhost"
        });
```
If I close the gulp process in console and run again the webserver than I get Error: listen EADDRINUSE. If website is refreshed, the process is released and webserver can be started again.

1. detection of new port and running instance seems to be broken
2. process is not released

**Comment by robertbaker** [comment]
I can't Ctrl-C to exit my dev task. Seems BrowserSync is hanging. I have to close the console and go to taskman and kill the node process.

**Comment by shakyShane** [comment]
@robertbaker try v2.9.3

**Comment by shakyShane** [comment]
@raDiesle try v2.9.3

**Comment by chrisjansky** [comment]
@shakyShane Perfect, seemed I had the same problem as @robertbaker and @raDiesle and updating to v2.9.3 worked for me. Thanks a ton!

**Comment by robertbaker** [comment]
Thanks!

**Comment by GodsLonelyMan** [comment]
I'm still having the same problem as @raDiesle on Windows and OSX. 

Version 2.9.1 works just fine, but al higher versions (including the mentioned 2.9.3)  have the following problems:
1. Detection of new port and running instance seems to be broken
2. The process is not released
