### ISSUE TITLE
Control+C stopped working on 2.9.2

### ISSUE THREAD

**Issue by OnkelTem** [BrowserSync/browser-sync#813]
Sorry for the terse report, but unfort. I have no time atm to figure out what does exactly go wrong after upgrading from 2.9.1 to 2.9.2 so I'm describing what I see. I use gulp to run building tasks including BS's specific task: 

```js
var gulp = require('gulp');
var browserSync = require('browser-sync');
var config = require('../config');

gulp.task('browserSync', ['build'], function() {
  browserSync(config.browserSync);
});
```
and its config object:
```js
browserSync: {
    files: [
      dest + "/**"
    ],
    proxy: "sportmar",
    ghostMode: {
      clicks: false,
      scroll: false,
      forms: {
        submit: false,
        inputs: false,
        toggles: false
      }
    },
    logLevel: 'debug',
    logConnections: true,
  },
```
Now when I press Ctrl-C I see:
```
^C[BS] Exiting...
[BS] [debug] Removing event listeners...
[BS] [debug] Setting active: false
```
which never exists, so I have to kill the gulp process.

**Comment by shakyShane** [comment]
We previously called `process.exit()` on `SIGINT` which was a mistake/bug. 

It's more likely that you have something else in your gulpfile that is keep the process alive. You can prove this by trying this [recipe](https://github.com/BrowserSync/recipes/tree/master/recipes/gulp.sass) - follow the intructions (only takes 2 mins) and you'll see that hitting control+c does indeed exit the process.

If you still believe this to be a 'bug' with Browsersync, please create a minimal sample repo that demonstrates your problem - then we'll reopen the issue

**Comment by OnkelTem** [comment]
Thanks for the quick reply @shakyShane 

I guess there is no need to create a sample repo as the described behavior is reproducible with that gulp.sass receipt.

For some magical reason this does work:
```
$ npm start
```
while this doesn't:
```
$ gulp
```
Thoughts?

**Comment by OnkelTem** [comment]
I confirm that it works now. Thanks!

**Comment by shakyShane** [comment]
![tumblr_m0osrrhqmk1qzcv7no4_250](https://cloud.githubusercontent.com/assets/1643522/9746840/17dd581c-5672-11e5-96e3-de70e52ddb1e.gif)
