### ISSUE TITLE
Won't load page

### ISSUE THREAD

**Issue by tomicicivan** [BrowserSync/browser-sync#814]
I get notice in terminal that browser-sync is started and when it does it would open new tab in browser but that tab would keep loading forever and it won't load page?

Does anybody know what might be an issue?

**Comment by foresttoney** [comment]
I upgraded browser-sync to `v2.9.2` this afternoon and was experiencing similar issues. It was also hanging my gulp process. After downgrading to `v2.9.1` I no longer saw the issues.

**Comment by shakyShane** [comment]
Try 2.9.3

**Comment by shakyShane** [comment]
Also, @tomicicivan please provide more details
https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#tips
