### ISSUE TITLE
Feature Request: query for auto-detected domain and port

### ISSUE THREAD

**Issue by bit-seq** [BrowserSync/browser-sync#816]
By omitting the port option, the auto-detection allows to run several instances of browser-sync at the same time, for a new instance the port-number will be incremented until a free port is found.
This feature makes it very pleasant to start several tasks depending on the same browser-sync task, however, I was not able to configure dependent tasks with the current port of their instance.

The documentation doesn't mention how to query the auto-detected port, neither was I able to find the current port on an instance.

Thanks in advance

**Comment by shakyShane** [comment]
This should be enough for you 

```js
var browserSync = require('browser-sync').create();

bs.init({
    server: './app'
}, function (err, bs) {
    // port
    console.log(bs.options.get('port'))
});
```
