### ISSUE TITLE
files CSS not reload after compile

### ISSUE THREAD

**Issue by LeG3nDz** [BrowserSync/browser-sync#817]
Hi,

I use browser-sync for reload my browser. If i save php or js file, the page has been reloaded. But if my app.css if edit, no reaction.

The path is correct, I checked (and display on command line : File changed: public/css/app.min.css

Do you have any idea how i can resolv my problem ?

Browser-sync version : 2.9.3

Thank you !

**Comment by shakyShane** [comment]
Check that you have a `<link>` element with a href pointing to `app.min.css`.

If this is not the cause of your problem, please reproduce the bug in a small sample project :)

**Comment by LeG3nDz** [comment]
Hi @shakyShane,

I've add my config on this repo : https://github.com/LeG3nDz/www.modele-decoupe.lan

I use grunt with browerSync, but same result with browserSync command line.

Thank you !

**Comment by shakyShane** [comment]
Cool, could you also copy/paste **view source** on your homepage too? I just want to check the HTML to ensure Browsersync is not breaking anything

**Comment by LeG3nDz** [comment]
I see data-href=".../app.min.css". Maybe because Foundation framework, but nothing else.

**Comment by shakyShane** [comment]
Ahh - Browsersync does not support none-standard ways of adding stylesheets

Change it to a regular link tag and everything will work fine :)

**Comment by LeG3nDz** [comment]
Okay, thank you for this information :)

Have a nice day ;)
