### ISSUE TITLE
Does socket.io's Node v4 build issues impact browser-sync?

### ISSUE THREAD

**Issue by fkling** [BrowserSync/browser-sync#820]
[This comment](https://github.com/BrowserSync/browser-sync/issues/805#issuecomment-138905566) claims that browser-sync works fine on Node v4, however, there are build errors with the current socket.io version on npm (v1.3.6) and Node v4, which can also be found in the [CI log](https://travis-ci.org/BrowserSync/browser-sync/jobs/79350666#L1500). 

But given that the tests seem to pass fine, can I expect browser-sync to work even if there are build errors during install?

See also https://github.com/websockets/utf-8-validate/issues/13, which points out the issues with socket.io.

**Comment by shinnn** [comment]
The errors arise only on [optional deps](https://docs.npmjs.com/files/package.json#optionaldependencies) build and they don't stop browser-sync working.

**Comment by fkling** [comment]
Ah, should have looked in the package.json. Thanks for the clarification! Those errors do look scarry...
