### ISSUE TITLE
A single module that syncs the "navigation"?

### ISSUE THREAD

**Issue by serapath** [BrowserSync/browser-sync#824]
browser-sync does a lot of things. I'd like to have a standalone module that i can re-use to just sync the navigation, like having the same scrolling position during development across multiple browser windows which open the webapp under development.

If it doesn't exist yet and it's not too big of a task, maybe the functionality can be isolated and copied into a separate module? If so, I'd be happy if someone could point me where to look in the code base and some hints on how to accomplish that.

thx

**Comment by shakyShane** [comment]
You'll be able to get the bare-bones (no cli, no logging etc) with [browser-sync-core](https://github.com/BrowserSync/browser-sync-core) which I'm hoping to finish within a couple of weeks :)
