### ISSUE TITLE
browser-sync ghost-mode only?

### ISSUE THREAD

**Issue by serapath** [BrowserSync/browser-sync#830]
I'm using `browserify` and `watchify` in combination with `browserify-hmr` to hot reload my project live during development. Changes get streamed via web sockets and it even works when i open my project through a "double-clicked" `index.html`

I imagine it should/might be possible to use browser-sync to synchronize navigation across devices/browsers, but when adding:

```html
<script type='text/javascript' id="__bs_script__">//<![CDATA[
	document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.2.9.3.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```
to my index.html file, it doesn't work, because `location.hostname` makes no sense - and i can't do a lot about it when using with a `cordova` built mobile app running on my usb connected device or an android emulator.

I could generate the `script tag` and add automatically add my current `wifi ip` instead, but it seems the downloaded `browser-sync-client.2.9.3.js` is using `location.hostname` internally which breaks everything. Maybe it could use my `wifi ip` or whatever parameter i append to the script src instead?

**Comment by serapath** [comment]
`browserify-hmr` manages to deal with cross origin problems using https://github.com/socketio/engine.io-client/tree/master/lib/transports

**Comment by serapath** [comment]
Ok, so i created a browserify transform that starts a browser-sync server to add just the "ghostmode" feature. Sadly, it doesn't work when you open the `index.html` file via "doubleclick". Instead it needs to be served from a server (for example: [`ecstatic`](https://www.npmjs.com/package/ecstatic)), because the `browser-sync-client` script uses `location.host` and there is no `option` to overwrite this behavior.

**It would be great if the `url` to fetch the client script from could be set via `options`**
*(So I would figure out my local ip dynamically via [`my-local-ip`](https://www.npmjs.com/package/my-local-ip) and provide it as an option) - with a bit of help I'm willing to do the __Pull Request__ :-)*

**Comment by shakyShane** [comment]
sorry for the delay. This feature already exists.

```js
scriptPath: function (path, port, options) {
    return 'shane';
}
```

http://www.browsersync.io/docs/options/#option-scriptPath

**Comment by serapath** [comment]
thank you for the hint. It worked already for script fetching. That part I already solved by adding the `browser-sync-client` script tag to my custom server to my `index.html`.

The problem is (probably I'm doing/using it wrong?) - once the browser-sync-client script downloaded to the client, it tries to establish a websocket or some sort of connection to fetch `"ghostmode updates"` and here it appends `"/browser-sync/browser-sync-client.js"` to whatever `location.hostname` is, which is **empty string** if you open the `index.html` by double-clicking.

 The `scriptPath` option changes the generated `script tag` to include the browser-sync client script, but maybe there is some pieces missing regarding the connection to fetch "ghostmode updates"?

**Comment by shakyShane** [comment]
```js
socket: {
    domain: ''http://someurl.dev'
}
```

will result in requests being made to `http://someurl.dev/browser-sync`

**Comment by serapath** [comment]
great - thx, that did the job regarding my browser-sync-server address, but now I get `GET http://192.168.2.179/browser-sync/socket.io/?EIO=3&transport=polling&t=1442956966956-47 net::ERR_CONNECTION_REFUSED` those...

I'm not sure, but it feels it's because the `browser-sync-client` script is trying to connect to the browser-sync server via xhr? I wasn't really able to figure out where in the `browser-sync` codebase that gets decided and whether I can influence it.

The `browserify-hmr` module somehow get's arround cross-site-origin problems. Could you hint me at something?
