### ISSUE TITLE
Problem with Polymer paper-dialog and Firefox

### ISSUE THREAD

**Issue by pensierinmusica** [BrowserSync/browser-sync#832]
Would it be possible to fix this in Browsersync, wothout having to write this custom option for just a weird execption in one browser?

https://github.com/PolymerElements/polymer-starter-kit/pull/127

Thanks!

**Comment by shakyShane** [comment]
> fix this in Browsersync

How exactly do you mean?

**Comment by pensierinmusica** [comment]
@shakyShane...mmm, I don't know... to be honest I don't even know what exactly is causing the problem in the first place (if I understand correctly it's related to some HTML tags in a sub-component of `paper-dialog`).

It seems weird though that the problem only happens in Firefox, so being a browser-specific issue I wonder if Browsersync could find a way to automatically handle this type of cases with Firefox.

Would this make sense? Cheers  :)

**Comment by shakyShane** [comment]
This issue was to do with the automatic insertion of the snippet - we cannot even attempt to solve every use-case & browser quirk out there, which is why we allow you to completely override how it works (as seen in the issue you linked)
