### ISSUE TITLE
Browser sync is starting too fast

### ISSUE THREAD

**Issue by jrock2004** [BrowserSync/browser-sync#834]
I am trying to set this up where I start my dnx server, then start browser sync. The problem is that BS is starting before my server starts. Any ideas on what I can do to resolve this problem?

```js
gulp.task('browser-sync', 'web', function () {
	browserSync.init(null, {
		proxy: "http://localhost:56619",
		port: 56620
	});
});

var options = {
	restore: false,
	build: false,
	run: true,
	cwd: './'
};

gulp.task('server', dnx('kestrel', options));

gulp.task('web', function () {
	return gulp.start('server');
});
```

**Comment by shakyShane** [comment]
Depends if `dnx` has some way of informing you it's 'ready' (such as a callback) - if it does, just move the Browsersync init code into that callback. 

Alternatively, just wrap the Browsersync in a setTimeout.
