### ISSUE TITLE
Memory leak if lost connection and browser console is open

### ISSUE THREAD

**Issue by aarongray** [BrowserSync/browser-sync#835]
If your server is shut down, but you still have a window open with the browser console or network request tab open, it will continue to make requests every 5 seconds for infinity. Eventually, this begins to take up a ton of memory. I've seen it take 8 GB of memory after I accidentally left a window up for a couple days. I'm using OS X.

In Chrome:
![image](https://cloud.githubusercontent.com/assets/660463/9998947/a0ffa5ac-6048-11e5-85ae-3f88df037a78.png)

![image](https://cloud.githubusercontent.com/assets/660463/9998954/afbd8618-6048-11e5-80b2-0307d9e9ad87.png)

In Firefox:
![image](https://cloud.githubusercontent.com/assets/660463/9999026/04414d78-6049-11e5-8f38-8393496255a9.png)

Would it be reasonable to stop making requests after they've been failing consistently for some period of time, and log a message to the console or make an alert message. It could say: "Browsersync has stopped making requests because the server seems to be down. Please refresh the page to try again."

**Comment by shakyShane** [comment]
v2.9.5

You can also provide your own limit to reconnects through 

```js
socketIoClientConfig: {
      reconnectionAttempts: 50
},
```

**Comment by aarongray** [comment]
:metal: Rock on!
