### ISSUE TITLE
Subdomain wildcards

### ISSUE THREAD

**Issue by ProLoser** [BrowserSync/browser-sync#836]
I'm building a multi-site which requires switching subdomains periodically. Is it possible to monitor a subdomain wildcard `*.mysite.com` or at the very least specify more than one domain?

**Comment by shakyShane** [comment]
The proxy requires a target, so a wildcard is not likely to work. We are adding a dynamic proxy however, that will allow you to change the target on the fly. Please see https://github.com/BrowserSync/ui

**Comment by indolering** [comment]
Is this still not working?

**Comment by SirAiedail** [comment]
[This](https://github.com/BrowserSync/browser-sync/issues/784#issuecomment-261589472) might be what you're looking for.
