### ISSUE TITLE
FS Event error and hiccup

### ISSUE THREAD

**Issue by smlombardi** [BrowserSync/browser-sync#837]
I've got Gulp watch running and browsersync. Every now and then the browser will not respond when clicking navigation. I look at the Terminal and see

`2015-09-21 10:35 gulp[49951] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'`

Gulp keeps running and eventually responds.

Specs:
CLI version 3.8.11
Local version 3.9.0
Node v0.12.7
OS 10.11 GM (15A282b)
MBP Retina 15, Thunderbolt display

**Comment by shakyShane** [comment]
Hi - thanks for this report.

It's unlikely this is a problem with Browsersync it's self - more likely a configuration/system problem. For this reason I will close this issue, but if you could provide a minimal sample project highlighting this problem, then I will happily investigate it :)
