### ISSUE TITLE
Breakpoint Tester

### ISSUE THREAD

**Issue by oleersoy** [BrowserSync/browser-sync#838]
Hi,

We're looking for a solution that can help us test media query breakpoints (Specifically for the SUITCSS tests).   We were wondering if browsersync could perform something like this:
http://breakpointtester.com/

Perhaps detect the media query breakpoints and open three different chrome windows with the viewport set to sizes that match the breakpoints.

I hope this is the right channel to ask this question in.  If there is a better one, please let me know.

Thanks,
- Ole

**Comment by shakyShane** [comment]
For feature requests, please post here https://github.com/BrowserSync/ui :)
