### ISSUE TITLE
How to determine if a named instance is running?

### ISSUE THREAD

**Issue by glen-84** [BrowserSync/browser-sync#839]
I create my named instance in a separate file. How do I tell if it's running without it throwing an error?

`browserSync.get("my-server")` throws an error if the instance is not running.

Maybe it would make more sense if this method returned `null`?

I want my build task to only call `stream()` if the instance is running.

**Comment by shakyShane** [comment]
first file
```js
var browserSync = require('browser-sync');
browserSync.create('Shane');

// Now load another file
require('./app.js');
```

`app.js`

```js
var browserSync = require('browser-sync');

browserSync
    .get('Shane')
    .init({
        server: 'test/fixtures'
    })
```

Works as expected. Try to copy this, if you still believe there's a bug, please provide more detailed info about your use-case

**Comment by glen-84** [comment]
@shakyShane,

The problem is that `create()` is called within a gulp task, like this:

```js
gulp.task("serve", ["build"], () => {
    browserSync.create("bs-server").init({
        server: {
            baseDir: "dist"
        },
        startPath: "/app",
        open: false
    });
});
```

Which means that it may not have been created if this task was not called first.

Should I rather move the `create()` call outside of the task, like this?

```js
let bs = browserSync.create("bs-server");

gulp.task("serve", ["build"], () => {
    bs.init({
        server: {
            baseDir: "dist"
        },
        startPath: "/app",
        open: false
    });
});
```

It seems to work, I'm just not sure if there is any overhead in calling `create()` when the server may not be used.

Thanks.

**Comment by shakyShane** [comment]
There's virtually no overhead until you call `init` - that's when servers are started, file watchers start running etc

**Comment by glen-84** [comment]
Great, thanks Shane. :smiley:

**Comment by shakyShane** [comment]
Any time :)

**Comment by glen-84** [comment]
@shakyShane `instances` is exported but not documented, is it okay to use this property?

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6982.

**Comment by shakyShane** [comment]
@glen-84 sorry for the delay!

Please only provide type definitions for the *documented* public api. This is stable and guaranteed. Any other exports are usually to facilitate testing.

**Comment by glen-84** [comment]
No worries. =)

Would you consider adding a `has(name)` or `hasInstance(name)` method?

**Comment by shakyShane** [comment]
has(name) sounds fine to me
