### ISSUE TITLE
Open same tab when running browserSync

### ISSUE THREAD

**Issue by htmled** [BrowserSync/browser-sync#84]
Although this issue has to do with using Gulp.js, I believe this request should be logged under "browser-sync".

Whenever I stop gulp to update my config, then I restart gulp, a new browser tab opens, instead of the tab that was already open.

It would be great if you could make it so the same tab will reload whenever "gulp-browser-sync" runs.

**Comment by raptor235** [comment]
Was this added to core at all? I'm drowning in windows too... every time gulp dies because of a sass issue I have to restart gulp and so new windows are being created every time...

**Comment by shakyShane** [comment]
@raptor235 it wasn't I'm afraid - Either use `open: false`

or address your bigger issue here, which is that you should be handling your `sass` errors better (ie, not exiting the process).

**Comment by timthez** [comment]
For anyone out there who has had this issue, Ive made a bit of a different version of what @shakyShane made for a plugin. 
https://gist.github.com/d1b29ea02cce7a2a59ff.git
Instead of reloading the tab if it exists, the plugin will close the page when it loses connection to the server. I prefer this as I like having my context switch to the browser when I restart the server but I don't want lots of old tabs from previous sessions.

**Comment by Nirazul** [comment]
@timthez Your gist is not available, at least for me.

**Comment by timthez** [comment]
Thanks @Nirazul , the .git extension was breaking the link, I think it should work now.

**Comment by Nirazul** [comment]
Thank you for the snippet, @timthez. It'll be surely of use to me :)

**Comment by andrewsuzuki** [comment]
For anyone out there using OS X and only developing on their browser, try downloading BetterTouchTool. I registered Cmd+Ctrl+R to execute the following commands only when inside my terminal (iTerm2):
1. Open chrome
2. Exec Cmd+R
3. Open terminal

Now when I hit Cmd+Ctrl+R it refreshed my disconnected window in an instant, without leaving the terminal.

**Comment by adambuczynski** [comment]
+1 for what it's worth. I think this would be a welcome feature for the core of BS.

My use case is that sometimes the tab just gets "overloaded" for lack of a better word, and that I have to restart the build/watch process manually. I do this via terminal, but that will open a new BS tab each time.

Ideally, I do think BS should know to "recycle" an existing TAB, if that one had been opened by a previous BS process. But I will look into the proposed plugins here.

**Comment by danimalweb** [comment]
+1 for using the same tab.

**Comment by daslicht** [comment]
I have the same issue with the current version of BrowserSync , either I get no Refresh (open:false) or I get a new tab on each refresh when not using the system default browser (browser: "google chrome")

**Comment by elgubenis** [comment]
the discussion here inspired me to make a tiny little module for use with browser-sync https://www.npmjs.com/package/browser-sync-close-hook, check it out

**Comment by adambuczynski** [comment]
@elgubenis unfortunately, it doesn't seem to work for me with my implementation:

```js
browserSync.use({
  plugin() {},
  hooks: {
    'client:js': autoClose
  }
});
```

I am not using gulp, but start BrowserSync directly:

```js
/**
 * Initialize browser sync
 */
browserSync.init({
  port: PORT,
  server: {
    baseDir: BASE_DIR,
    middleware: [
      logMiddleware,
      staticMiddleware,
      spaMiddleware
    ]
  }
});

/**
 * Create a stream of file-change events
 */
Rx.Observable.create(observer => {
  let watcher = chokidar
    .watch([`${BASE_DIR}/**/*`], {ignoreInitial: true})
    .on('all', (event, file) => {
      observer.onNext({event, file});
    });
  return function() {
    watcher.close();
  };
})
  .debounce(1000)
  .filter(x => (x.event === 'add' || x.event === 'change'))
  .subscribe(x => {
    if (x.file.match(/\.css$/)) {
      browserSync.reload(x.file);
    }
    else {
      browserSync.reload();
    }
  });
```

Any thoughts?

**Comment by elgubenis** [comment]
could you check your browsers console output after you disconnected from bs?

**Comment by adambuczynski** [comment]
Yup, I get a `Scripts may close only the windows that were opened by it.`

**Comment by elgubenis** [comment]
I'd then recommend to set open to false in the browserSync options, and (on mac os x) cmd + leftclick on that colored link in your terminal: https://www.dropbox.com/s/k7chtx1a53tx3va/Screenshot%202016-03-28%2020.36.35.png?dl=0

**Comment by adambuczynski** [comment]
That doesn't help, still results in the same message in the console.

**Comment by elgubenis** [comment]
yeah about that .. its just so you don't need to close manually many times, with open: false you have to open manually (cmd + double leftclick on link in terminal) and like that no new windows open and its easy to open one almost-programatically

**Comment by adambuczynski** [comment]
Right, that's what you meant, ok. But still... What's the point of your
plugin then if it doesn't work? How did you get it to work? Are you using a
different browser?

**Comment by elgubenis** [comment]
there seems to be some weird circumstance under which it still works, yes, but later on i wasn't able to reproduce it anymore so I came up with the manual solution above

**Comment by zakdances** [comment]
The problem with closing the tab instead of re-using/reloading it (like how BS works on Safari) is that Developer Tools closes too. This is a problem if you need data from the Tools but also need BS paused.

**Comment by DrakeXiang** [comment]
I found that gulp-connect can reload server page without opening a new one, maybe browsersync could take a peek how they achieved this

**Comment by marcvangend** [comment]
Almost 5 years later, this would still be nice to have.

**Comment by adrian-wozniak** [comment]
@shakyShane Thanks for your gist!

I had a bit more tricky scenario: reload tab if exists (or tabs if more)  otherwise open new one.

Plugin below worked for me:
```
    {
        plugin: (server, client) => {
            setTimeout(() => {
                const registeredConnections = client.io.sockets.sockets;
                if (registeredConnections.length === 0) {
                    grunt.log.writeln('No browser connected, opening new browser page...');
                    client.setOption('open', 'local');
                    client.utils.openBrowser(client.options.getIn(['urls', 'local']), client.options, client);
                }
            }, 1000);
        },
        hooks: {
            'client:js': '' +
                '((window, bs) => {' +
                '    let canReload = false;' +
                '    bs.socket.on("connection", () => {' +
                '        if (canReload) {' +
                '            canReload = false;' +
                '            window.location.reload();' +
                '        }' +
                '    });' +
                '    bs.socket.on("disconnect", () => canReload = true);' +
                '})(window, ___browserSync___);'
        }
    }
```

**Comment by blachawk** [comment]
Any progress on this?

**Comment by bastinald** [comment]
sept 2021 and still want this feature friends!
