### ISSUE TITLE
Changing sync options on the fly

### ISSUE THREAD

**Issue by davej** [BrowserSync/browser-sync#840]
The UI allows me to enable/disable clicks, scrolls and form entry. This seems to be done on the fly without a server restart.

Is is possible to do this programmatically on-the-fly without using Browsersync UI?

**Comment by shakyShane** [comment]
```js
browserSync.init({
	server: './app'
}, function (err, bs) {
	bs.setOptionIn(['ghostMode', 'clicks'], false);
})
```
