### ISSUE TITLE
BrowserSync not reloading with Grunt tasks

### ISSUE THREAD

**Issue by jleplomet** [BrowserSync/browser-sync#841]
Hello, I am having a problem with BrowserSync not reloading after my Grunt tasks complete. I am using ```grunt-browser-sync``` as well.

BrowserSync config:
```
module.exports = {
  dev: {
    files: {
      src : [
        "<%= config.tmp %>/**/*",
        "!<%= config.tmp %>files/css/main.css.map"
      ]
    },
    options: {
      watchTask: true,
      server: "<%= config.tmp %>"
    }
  }
};
```

Running ```grunt``` with ```-v``` logs that BrowserSync is finding all files but it seems like its ```watchTask``` is not working.

CSS files do not inject, JS files do not reload. The browser reports that BrowserSync connects but no reload. [#115](https://github.com/BrowserSync/grunt-browser-sync/issues/115#issuecomment-136004785) mentions to downgrade BrowserSync but this might not be the best option to manually downgrade on every project install of BrowserSync.

Computer details
```
Mac OS X 10.10
node v0.12.7
npm 2.11.3
package.json
"devDependencies": {
    "babelify": "^6.3.0",
    "glob": "^5.0.14",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^3.0.3",
    "grunt-browser-sync": "^2.1.3",
    "grunt-browserify": "^4.0.1",
    "grunt-concurrent": "^2.0.3",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-imagemin": "^0.9.4",
    "grunt-contrib-sass": "^0.9.2",
    "grunt-contrib-uglify": "^0.9.2",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-env": "^0.4.4",
    "grunt-newer": "^1.1.1",
    "grunt-sync": "^0.4.1",
    "jit-grunt": "^0.9.1",
    "load-grunt-tasks": "^3.3.0",
    "time-grunt": "^1.2.1"
}
```

**Comment by shakyShane** [comment]
what's the value of `config.tmp`

**Comment by jleplomet** [comment]
```config.tmp``` is where i compile all files, its value is a folder ```.tmp```. Inside its just my index.html, js, css, etc.. files.

**Comment by shakyShane** [comment]
Try this

```js
module.exports = {
  dev: {
    files: {
      src : [
        "<%= config.tmp %>/**/*",
        "!<%= config.tmp %>files/css/main.css.map"
      ]
    },
    options: {
      watchTask: true,
      watchOptions: {
          ignored: ''
      },
      server: "<%= config.tmp %>"
    }
  }
};
```

**Comment by jleplomet** [comment]
That works!

Thank you.
