### ISSUE TITLE
Feature Request: After reload hook

### ISSUE THREAD

**Issue by Nirazul** [BrowserSync/browser-sync#844]
I'm using browser-sync together with gulp. A common pattern in my tasks is following:

```
return gulp.src(...)
    .pipe(..do stuff..)
    .pipe(browserSync.stream({ once: true }));
```

I'd like to add a notification to the browser-window after the tab has been reloaded. Unfortunately I haven't got a possibility apart from a randomly set timeout. 
Is it technically even possible to add a callback when browser-sync has triggered the reload?

**Comment by shakyShane** [comment]
I'm assuming you want a callback to fire when each and every device & browser is reconnected? That would be a great plugin for v3 perhaps, but I'm afraid it's out of scope for Browsersync core.

Please let me know if my assumption is incorrect
