### ISSUE TITLE
BrowserSync only launches default browser (v2.9.7)

### ISSUE THREAD

**Issue by r-park** [BrowserSync/browser-sync#849]
After updating to `v2.9.7`, BrowserSync is only launching the system default browser (in this case, FireFox Dev Edition). Downgrading to `v2.9.6` resolves this issue. Running OSX 10.10.

The following config launches Firefox Dev Edition, not Chrome:
```
config = { browser: 'google chrome' } 
```
The following launches 3 instances of Firefox Dev Edition, no Chrome, no Safari:
```
config = { browser: ['google chrome', 'firefoxdeveloperedition', 'safari'] } 
```

**Comment by alexblunck** [comment]
I can confirm this. Running `v2.9.7` and `OS X 10.10.5` as well as `OS X 10.11`

**Comment by jeffbski** [comment]
+1 

tested on OS X 10.10.3 with browser-sync@2.9.7 ignores browser option

**Comment by shakyShane** [comment]
fixed in browser-sync@2.9.8

**Comment by jeffbski** [comment]
Thanks for quick fix!

**Comment by shakyShane** [comment]
:+1:

**Comment by r-park** [comment]
:+1:

**Comment by shaddyz** [comment]
I'm experiencing this exact issue using lite-server depending on browser-sync 2.12.8
