### ISSUE TITLE
Browser sync injects old browser-sync-client version after update

### ISSUE THREAD

**Issue by kvcrawford** [BrowserSync/browser-sync#851]
Browser sync 2.9.8 is installed:

```bash
$ npm ls browser-sync
docdata@0.0.1 /Users/kvcrawford/git/DocData/DocDataWebApp
└── browser-sync@2.9.8
```

My very basic Browser Sync gulp task:

```coffee
gulp        = require 'gulp'
browserSync = require 'browser-sync'

gulp.task 'sync', ->
  browserSync
    server: true
    startPath: '/dev.html'
    files: [
      './*.html'
      './dist/js/**/*.js'
      './dist/**/*.css'
    ]
```

Yet the script injected at the top of the page is the wrong version:

```html
<script type='text/javascript' id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.2.8.2.js'><\/script>".replace("HOST", location.hostname));
//]]></script>
```

This path returns a 404.

Following @sc0ttwad3's instructions in https://github.com/BrowserSync/browser-sync/issues/791#issuecomment-138741818 resolves the issue.

**Comment by shakyShane** [comment]
Have you cleared your browser cache?

**Comment by simonh1000** [comment]
I'm seeing this too and have cleared my cache. And normally I get 4 URLs in this message not 2.

```
[BS] Access URLs:
 -------------------------------------
          UI: http://localhost:3001
 -------------------------------------
 UI External: http://192.168.0.10:3001
 -------------------------------------
```

**Comment by shakyShane** [comment]
@simonh1000 - You are missing the server or proxy option

**Comment by simonh1000** [comment]
@shakyShane - whoops I had indeed overwritten it. Apologies

**Comment by smajl** [comment]
Damn.. lost half an hour wondering what is wrong. :) **Clearing cache / disabling cache in Chrome devtools** helped!

**Comment by jeffbski** [comment]
+1
