### ISSUE TITLE
`#__bs_notify__` added even with `{notify: false}`

### ISSUE THREAD

**Issue by Mitranim** [BrowserSync/browser-sync#858]
When my server settings are set to `{notify: false}`, browser-sync still adds the `<div id="__bs_notify__">`. It's no big deal, but may produce visible artefacts depending on site CSS.

**Comment by shakyShane** [comment]
Agreed, it shouldn't be added at all `{notify: false}`

**Comment by shakyShane** [comment]
fixed in browser-sync@2.9.11
