### ISSUE TITLE
Ability to redirect for page 404 when not found a page

### ISSUE THREAD

**Issue by brunowego** [BrowserSync/browser-sync#862]
Having the ability to redirect to page 404 when not found one page would be a great feature. Of course this is probably not the tool's purpose, but it would be a nice feature.

**Comment by shakyShane** [comment]
I created this example as response to your issue :)

https://github.com/BrowserSync/browser-sync/blob/master/examples/404.js

**Comment by brunowego** [comment]
Thanks @shakyShane :+1:

**Comment by brunowego** [comment]
Last question, it is possible to do this with grunt? I'm reading the documentation but can not find anything about. Thanks!

**Comment by brunowego** [comment]
@shakyShane

**Comment by trusktr** [comment]
> I created this example as response to your issue :)
> 
> https://github.com/BrowserSync/browser-sync/blob/master/examples/404.js

this doesn't work when using the CLI right? We need an option to make it use a particular file for 404s.
