### ISSUE TITLE
Feature request: Multiple clients with different query params

### ISSUE THREAD

**Issue by sergru** [BrowserSync/browser-sync#863]
Hi guys,
I found your plugin is very useful for some of my dev work. Thanks for your work!

But one thing I cannot do or cannot figure it out how. I need to start several browsers but with different query params. For example, I need at the same time to run: IE for PC, IE for Mobile, Chrome for PC and Chrome for Mobile. So it is 4 client instances. The difference I need is in start multuple browsers, which you already support, and adding extra query params to them some or all of them. Therefore, each browser can start like this: http://localhost?useDesktop[&....],  http://localhost?useMobile[&....]. Or it could be “useDebug” and “”. Is there a way I can do this?

If not, is it too complicated to add this feature? I see the ways by adding object to the browser prop or making the browser prop as array of strings or objects with browser name and query params. Technically they are both not easy to use. Maybe you can come with better solution for this. It will be really useful.

Thanks,
Serg

PS:
As a developer I can help you with descussion and of course implementations of this feature. Please let me know.

**Comment by shakyShane** [comment]
For functionality such as this, it's easy enough to use the callback and launch the browsers yourself.

we use the [opn](https://github.com/sindresorhus/opn), so you could do something like 

```js
var bs = require('browser-sync').create();

bs.init({
    server: './app'
}, function (err, bs) {
	var urls = bs.options.get('urls').toJS();
    require('opn')(urls.local, {app: 'google chrome'})
})
```
