### ISSUE TITLE
When installed version mismatched with project's `package.json` dependencies version, Browser Sync write the version in `package.json` which will cause a 404 error.

### ISSUE THREAD

**Issue by xieranmaya** [BrowserSync/browser-sync#864]
installed version: 
`./node_modules/browser-sync/package.json:`
```json
{
    "version": "2.9.11"
}
```

Project's package.json
```json
{
  "dependencies":{
    "browser-sync": "^2.8.2"
  }
}
```

Browser Sync write something like `http://localhost:3000/browser-sync/browser-sync-client.2.8.2.js` to page which will cause a 404 error.
Should write installed version path to page, not dependencies' version.

**Comment by shakyShane** [comment]
Browsersync uses the currently installed version, it never looks at your `package.json` file. What you're seeing is a simple browser cache issue. So clear it and it will work :)

**Comment by xieranmaya** [comment]
I've disabled cache and hit Ctrl + F5 to refresh but it still load the old version untill I change the project's package.json's dependencies to the installed version.
I've changed back the version but the problem never showed up, probably my fault, thank you very much!
