### ISSUE TITLE
Allow custom arguments when starting the server

### ISSUE THREAD

**Issue by rhumaric** [BrowserSync/browser-sync#867]
I wanted to pass additional flags to the `browser-sync start` command in order to tweak the configuration returned by my bs-config.js file (to provide shortcuts for proxying to a list of well known servers). Unfortunately, browser-sync checks the flags it is given against a whitelist, so I had to resort to using an environment variable to provide which proxy to use (eg. `MY_PROXY=demo1 browser-sync start`).

It did the job, but the syntax is not really intuitive. It'd be great if there was a way to pass additional CLI arguments that could be interpreted by the bs-config file. If needs be, they could be namespaced so they wouldn't collide with future arguments. For example:
`browser-sync start --args.myProxy demo1`

**Comment by shakyShane** [comment]
agreed

**Comment by shakyShane** [comment]
Closing as this is a dupe of https://github.com/BrowserSync/browser-sync/issues/796
