### ISSUE TITLE
browsersync and gulp-connect-php

### ISSUE THREAD

**Issue by mjrev** [BrowserSync/browser-sync#871]
hello. i used this code in my gulpfile on windows:
```javascript
gulp.task('connect', function() {
  connect.server({
    hostname: '0.0.0.0',
    bin: 'C:/php/php.exe',
    ini: 'C:/php/php.ini',
    base: './dist',
    keepalive: true
  }, function (){
    browserSync.init({
      proxy: "localhost:8000",
      open: false
    });
  });
});
```
it's a [gulp-connect-php](https://github.com/micahblu/gulp-connect-php) plugin, and it worked well.

after i migrated to linux, i changed code to
```javascript
gulp.task('connect', function() {
  connect.server({
    hostname: '0.0.0.0',
    bin: '/usr/bin/php',
    ini: '/etc/php5/cli/php.ini',
    base: './dist',
    keepalive: true,
  }, function (){
    browserSync.init({
      proxy: "localhost:8000",
      open: false
    });
  });
});
```
but gulp throws error:
![error](https://i.imgur.com/npKbRbw.png)

it disappears only if i set `hostname: localhost`, but in that case livereload isn't working. 
`[BS] Reloading Browsers...` in console, but actually nothing happens.

can you help me, please?

**Comment by shakyShane** [comment]
what happens if you try to run browsersync from another terminal window instead of through that callback?

**Comment by mjrev** [comment]
`hostname: '0.0.0.0'` is running fine, but browsersync still doesn't reload page

**Comment by shakyShane** [comment]
Do you see 'Browsersync connected' message in the browser?

**Comment by mjrev** [comment]
can't remember, because i had to move back to windows recently.
i will close issue, until someone will face similar problem

**Comment by mjrev** [comment]
i came to solution by dividing tasks and running them in two terminal windows:
```javascript
gulp.task('connect', function() {
  connect.server({
    hostname: 'localhost',
    bin: '/usr/bin/php',
    ini: '/etc/php5/cli/php.ini',
    base: './dist',
    keepalive: true
  });
});

gulp.task('bs', ['watch'], function() {
  browserSync.init({
    proxy: "localhost:8000",
    open: false
  });
});
```
everything works fine
