### ISSUE TITLE
browserSync does not work offline

### ISSUE THREAD

**Issue by joseluisq** [BrowserSync/browser-sync#876]
Recently I work with browserSync and grunt task but browserSync is slow and does not work offline. Needs BrowserSync internet connection? Exists some way to fix this?

**Comment by shakyShane** [comment]
no, Browsersync does not require an internet connection. Some features do, but the core does run without it.

if you're experiencing slow start-ups when offline, it's usually because a dns lookup never completes - try setting `online: false` - that should help

**Comment by joseluisq** [comment]
@shakyShane great!

**Comment by sahtlil** [comment]
where I can find that option bro ,
