### ISSUE TITLE
rewriteRules are not used

### ISSUE THREAD

**Issue by ahfarmer** [BrowserSync/browser-sync#878]
However I try things, I can't get the rewriteRules to take effect. Maybe I'm not using them correctly, but it seems like a 🐛.

Here's my `index.js`.
```
var bs = require("browser-sync").create();

bs.init({
  server: "./app",
  rewriteRules: [
    {
      match: /Hello/ig,
      fn: function(match) {
        console.log('MATCH!!!!');
        return 'Cello';
      },
    },
    {
      match: 'Hello',
      replace: 'Shmello',
    },
  ],
});
```

`app/index.html` is just a plain text file with 'Hello World' as the contents.

Here's my gist:
https://gist.github.com/ahfarmer/0b58726838e4c169c9a9

When I run this it opens up my web page, but 'MATCH!!!!' is not printed in the terminal, and my output has the original  'Hello World', instead of 'Cello World' or 'Shmello World' as I would expect.

Thanks!

BTW, possibly related issue: https://github.com/BrowserSync/browser-sync/issues/715

**Comment by shakyShane** [comment]
I ran your example and it worked perfectly for me?

**Comment by ahfarmer** [comment]
What did you get as output? Cello World or Shmello World? I still get 'Hello World'.

Maybe it has to do with node version?

```
$ node --version
v4.1.0
```

**Comment by shakyShane** [comment]
`Cello World`

**Comment by ahfarmer** [comment]
Okay I put my example into a git repository, would you mind trying again?
https://github.com/ahfarmer/browsersync-rewrite-rules

To ensure consistency, I added a vagrant file. If your local test doesn't reproduce the issue, would you mind running the Vagrant test? I'm still seeing 'Hello World' as the output on mac & Ubuntu with both Node 0.12.7 and Node 4.2.

**Comment by shakyShane** [comment]
sorry for the delay, turns out this is a simple fix. your example does not include any HTML so the rewrite rules are skipped.

swap it for 

```html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    Hello World
</body>
</html>

```

... then clear/disable the browser cache and you'll see it working :)
