### ISSUE TITLE
Usage information (browser-sync --help) is incorrectly formatted

### ISSUE THREAD

**Issue by d-g-h** [BrowserSync/browser-sync#880]
The below image is of the current build of browser-sync (2.9.11)

<img width="709" alt="screenshot 2015-10-29 20 34 28" src="https://cloud.githubusercontent.com/assets/1667967/10836128/6de67622-7e80-11e5-96a0-579fd42af3d3.png">

I think the image below is more readable though.

<img width="765" alt="screenshot 2015-10-29 20 49 50" src="https://cloud.githubusercontent.com/assets/1667967/10836129/6de80320-7e80-11e5-8df4-5f6045d815b5.png">

**Comment by shakyShane** [comment]
fixed via https://github.com/BrowserSync/browser-sync/pull/881
