### ISSUE TITLE
the problems when use server.baseDir and server.directory?

### ISSUE THREAD

**Issue by jpuncle** [BrowserSync/browser-sync#882]
I have the code

```javascript
browserSync.init({
    server: {
        baseDir: ['.tmp', 'src'],
        directory: true
    }
})
```

I use the sass, and use gulp to build sass to `./.tmp/css`, but my .html is in the `./src/`.

when I set `directoty` to `true`, I can't find the html files in the browser

**Comment by shakyShane** [comment]
`directory: true` will only work on the first item in the `baseDir` property :)
