### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by gonsfx** [BrowserSync/browser-sync#883]
When using `https: true`, how can i redirect all http requests to their http counterpart? i tried using middleware, but i didn't get too far.

**Comment by shakyShane** [comment]
You couldn't I'm afraid. If the Browsersync server is running at `https://localhost:3000` - any request to `http://localhost:3000` won't make to the server & hence your middleware will not be run.

Unless you're talking about the `proxy` option, in that case you should handle the redirects with your backend ideally and not with Browsersync. Hope that makes sense :)
