### ISSUE TITLE
Reload does not work for new/deleted files

### ISSUE THREAD

**Issue by miraage** [BrowserSync/browser-sync#884]
It's not fun. Can you reload on all events?...
https://github.com/BrowserSync/browser-sync/blob/v2.9.11/lib/file-utils.js#L19-L23

// EDIT

You could provide an options for developers to choose on which events BS should reload.

**Comment by faergeek** [comment]
Are you sure that you need this? What's your use case?

**Comment by miraage** [comment]
I'm using gulp + gulp-rev.
Once files are changed - new fingerprinted file has been created and old files is removed.
Yes, this is not an ideal development flow (imo fingerprint should only apply in production mode), but sometimes we're forced to some technologies.

Also I think this feature is not hard to implement. Just add some options to `watchOptions`.

**Comment by shakyShane** [comment]
create your own watcher, call `bs.reload()` whenever you want?

**Comment by shakyShane** [comment]
```js
var bs = require('browser-sync').create();

bs.init({server: true});
bs.watch('app/**').on('all', bs.reload);
```
