### ISSUE TITLE
Problem with fontawesome icons, probably content type.

### ISSUE THREAD

**Issue by mnemanja** [BrowserSync/browser-sync#885]
It was okay with older browser-sync version - 1.5.8, the font-icons were being shown correctly.
I just updated to 2.7.6, and tried the latest 2.9.11 and the font-icons are being shown as squares.

A reason for this is I believe `Content-Type:text/html; charset=UTF-8` but previously it used to be `Content-Type:application/octet-stream`.

Using this boilerplate:
https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate

**Comment by shakyShane** [comment]
Could you create a red
