### ISSUE TITLE
Browser-Sync with credentials

### ISSUE THREAD

**Issue by J0hnRoger** [BrowserSync/browser-sync#888]
Hello, 

I try to use Browser-sync in proxy mode, for proxied a .net website. It works but I must deal with authentification prompt. When I pass my credentials, the page is reloading, then the prompt is displayed yet. 

My gulp task : 

```javascript
gulp.task('browser-sync', function() {
    var files = [
        './deploy/JobOffers/app/**/*.js',
    ]
    browserSync.init(files, {
        proxy : 'http://vm-r7-pcm/',
        
    });
});
```

**Comment by J0hnRoger** [comment]
The login form come from my enterprise Active Directory. Peraps that's the problem.

**Comment by shakyShane** [comment]
in some cases, Browsersync cannot always 'fake' it's way past all the login systems out there. This is a limitation of this tool unfortunately. 

basically, unless you can get it working directly with something such as https://github.com/nodejitsu/node-http-proxy, then it probably won't work with Browsersync. :(

If you can find another Node proxy that can handle the auth of your app, please message back here and I'll re-open this issue :)
