### ISSUE TITLE
Put styles into seperate stylesheet

### ISSUE THREAD

**Issue by leo** [BrowserSync/browser-sync#891]
Like you do it with the `/browser-sync/browser-sync-client.2.9.12.js` file, it should also be done with the styling of the notification on the top right. This will allow developers to change the styling of the notification without needing to use `!important`.

**Comment by shakyShane** [comment]
Styles can be changed with 

```js
{
    notify: {
        styles: [
        /* styles */
        ]
    }
}
```

see https://github.com/BrowserSync/browser-sync-client/blob/master/lib/notify.js#L6
