### ISSUE TITLE
EventListeners fire on all open tabs that are of the same page?!

### ISSUE THREAD

**Issue by schoening** [BrowserSync/browser-sync#892]
I am working on a multiplayer game using socket.io.
Browsersync is part of my workflow in Gulp:
```js
gulp.task("browsersync", function () {

	browsersync.init({
		proxy: {
			target: "http://localhost:3000",
			ws: true
		},
    port: 3001,
    reloadDelay: 2000
	});

});
```
I have a simple eventListener that acts really crazy...
```js
document.getElementById("button").addEventListener("click", function () {
	console.log("button");
});
```
I have multiple tabs open to test the multiplayer game. When I press the button. BOTH of my windows display the "button" message. 
That makes absolutely no sense o_o'.
This does not happen on the "non-proxied?" - page. Only on the browsersync one.

I'm not entirely sure how to show you. Perhaps a zip file with my project?

Has anyone an idea tho?
I am also using browserify. And the eventListener exists inside a module.

**Comment by shakyShane** [comment]
Yeah, please provide a test app for me to look at. Also worth checking you don't have any inactive tabs running as this can cause havoc with the socket streams - something which we'll be addressing in v3
