### ISSUE TITLE
Cannot reach external IP from other device

### ISSUE THREAD

**Issue by Louistiti** [BrowserSync/browser-sync#893]
Hello,

For several days now, I can't reach the external address Browsersync gives. When I try to reach from the browser of another device, nothing happens. I'm currently using Windows 10 on the local machine.

I tried with another machine using Windows 7 and it's working well, then it's not a issue from router-level. When I launch Browsersync with the machine using Windows 7, I can reach the external address by using any device I want.

Someone has any suggestion ?

In pleasure to read you.

**Comment by shakyShane** [comment]
Browsersync does nothing 'special' with any IP addresses. We bind to localhost and then ask your OS for any IP addresses it believes can accept external connections. This is not fool-proof as you've noticed. you can check http://www.browsersync.io/docs/#external-url

other than that I will close this issue as it's not directly related to the Browsersync program :)
