### ISSUE TITLE
Feature Request: Ignoring files

### ISSUE THREAD

**Issue by webdif** [BrowserSync/browser-sync#897]
I think it would be very convenient to add a way to ignore files. Just like the `files` option, but for ignoring instead of watching.

Browser-sync uses [chokidar](https://github.com/paulmillr/chokidar) for watching files, and chokidar have already a `ignored` option.

It could be a solution to [the symlink problem](#651). Currently, it's not possible to watch files where a symlink is involved. But watching the parent directory instead of a glob pattern makes browser-sync work. (as it makes chokidar work). A `ignored` option, and you will be able to ignore the files that do not interest you.

**Comment by shakyShane** [comment]
anything you pass in `watchOptions` will be passed directly to chokidar :)

http://www.browsersync.io/docs/options/#option-watchOptions

**Comment by webdif** [comment]
Sorry I missed that.
Thanks a lot!
