### ISSUE TITLE
Feature Request: add 'reconnect to proxy' option in reload function

### ISSUE THREAD

**Issue by eltimn** [BrowserSync/browser-sync#899]
I have a Scala (JVM based) app where I use [SBT](http://www.scala-sbt.org/) to build the app and Gulp to build the JavaScript and CSS. To get BrowserSync to work I just update a file every time the app reloads. BrowserSync watches that file and reloads the browsers.

I am now trying a new approach to building the app. Instead of reloading the app in place (Jetty is used to do the reload), I am now just killing the forked VM and restarting.

The problem I'm seeing is that BrowserSync takes ~ 10 seconds to reload using this technique.  What I suspect is happening is that the connection to the proxy is being severed since the port is being closed, and BrowserSync takes a while to reconnect.

So, I was thinking if the reload function had an option to automatically reconnect to the proxy, it wouldn't take as long. Of course I'm not familiar with the code base, so I'm not sure if this is feasible.

Any thoughts?

**Comment by shakyShane** [comment]
if it's taking 10 seconds to perform a reload, it's likely the Browsersync is requesting your page whilst your app is not actually back online?

**Comment by eltimn** [comment]
Now that I think about it more, when I was testing this the other day, if I hit stop then reload in the browser it would load right away. So, I know my app is back online and the browser sync proxy is working. The problem must be between bs and the browser. Anyway, I'll try to narrow it down some more.
