### ISSUE TITLE
BrowserSync refreshes page but content doesn't update, PHP files

### ISSUE THREAD

**Issue by peterph-am** [BrowserSync/browser-sync#900]
This is my current watch task using `gulp-watch`:

```
watch('html/**/*.php', function() {
	browserSync.reload();
});
```

I'm simply trying to reload the browser when .php files are edited. The browser is reloading but the content doesn't change with the edits made in the file. I've been at it for a while and sometimes it refreshes and sometimes it doesn't. 

I tried to up the `readDelay` but that didn't work either. Any ideas?

**Comment by shakyShane** [comment]
Sounds like a browser-cache issue. Check you're on the latest version of Browsersync first. IF you already are, try the following middleware, or do something similar with your backend

```
var browserSync = require("browser-sync").create();

browserSync.init({
    proxy: {
        target: "http://www.bbc.co.uk",
        proxyRes: [
            function (res) {
                res.headers["Expires"] = "0";
                res.headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
                res.headers["Pragma"] = "no-cache";
            }
        ]
    }
});
```

**Comment by peterph-am** [comment]
Thanks @shakyShane, that worked a treat!
