### ISSUE TITLE
A wrong encoding question，help me 

### ISSUE THREAD

**Issue by guohuihot** [BrowserSync/browser-sync#901]
![1](https://cloud.githubusercontent.com/assets/3119995/11204007/01975fd6-8d35-11e5-9804-52e6052631ba.jpg)
![2](https://cloud.githubusercontent.com/assets/3119995/11204008/02130c3a-8d35-11e5-9612-9210ec3a9f41.jpg)
![3](https://cloud.githubusercontent.com/assets/3119995/11204009/028d62a0-8d35-11e5-928d-cab444e699a5.jpg)

**Comment by shakyShane** [comment]
Sorry, currently Browsersync only supports UTF8 encoding.
