### ISSUE TITLE
Unable to use local IP

### ISSUE THREAD

**Issue by binarykitchen** [BrowserSync/browser-sync#903]
Wrote code to use the local IP instead of `localhost` so that I can share my work across work colleagues on the same local network.

Tried using these options but no luck:

```
    open: 'external',
    host: <my local ip>,
    browser: 'google chrome'
```

Browsersync still opens chrome with `localhost`. Why?

**Comment by shakyShane** [comment]
Can you give me a full example? 

This works for me

```
var bs = require('./').create();

bs.init({
    host: "192.167.1.1",
    open: "external",
    proxy: "http://magento.dev",
    browser: ['google chrome']
});
```

Chrome is opened at the address given in 'host' property with the port appended

**Comment by binarykitchen** [comment]
Ah, this worked. It wasn't obvious in the documentation. Thanks.

**Comment by shakyShane** [comment]
yeah, looking to simplify some bits like this in v3 :)
