### ISSUE TITLE
Proxy request timeout when content-length not present (Transfer-Encoding: chunked)

### ISSUE THREAD

**Issue by axefrog** [BrowserSync/browser-sync#905]
Just upgraded to ASP.Net 5 RC1 and the Kestrel web server does not appear to return a Content-Length header in my case, opting instead for a chunked response. As a result, BrowserSync just sits there and ticks over forever, never resolving the request. I tried pointing it at a different local proxy and it worked fine, with difference being that the other web server was returning a Content-Length header. Chrome, Firefox, curl, etc., do not have any problem resolving and completing requests directly to the proxy address, they only sit there spinning their tyres when going via BrowserSync.

**Comment by axefrog** [comment]
Further investigation; I'm getting the following response in my `proxyRes` function, which simply calls `console.log(res.headers)`:

```
{ date: 'Fri, 20 Nov 2015 02:52:23 GMT',
  'content-type': 'text/html; charset=utf-8',
  server: 'Kestrel',
  connection: 'close' }
```

**Comment by axefrog** [comment]
I've switched from Kestrel to WebListener for now and it's working again. I'll close the issue as I suspect it'll go away with the next release.

**Comment by everystone** [comment]
This is still an issue, I had to switch to WebListener myself, which forces me to develop on Windows.( if I am going to use browser-sync ).

**Comment by amcdnl** [comment]
I'm also getting this issue.

**Comment by amcdnl** [comment]
Logged issue on Krestel Project ^^

**Comment by cesarbs** [comment]
@everystone @amcdnl Are you on RC1, or are you using the latest dev packages?

**Comment by brantw** [comment]
@cesarbs We are on RC1.

**Comment by everystone** [comment]
@casarbs 1.0.0-rc1-update1 coreclr

**Comment by peterblazejewicz** [comment]
Hi,
I know that is not BS problem. I'me getting this problem on OS X with RC2. Can someone point me the best way to debug a problem? (I could log issues to Kestrel team to fix the problem).
Thanks!
