### ISSUE TITLE
"Open" ignores index when starting server

### ISSUE THREAD

**Issue by electerious** [BrowserSync/browser-sync#909]
Hi,

I'm starting a server with the following options:

```js
let bs = require('browser-sync').create()

const server = {
	baseDir : 'src',
	index   : 'test.html'
}

bs.init({
	server : server
})
```

The documentation says that the index-option can be used to "Serve files from the app directory, with a specific index filename". I expected BS to open `http://localhost:300/test.html`, but it opens `http://localhost:3000` instead.

Is there a way to change the default URL? What's the impact of the index-option?

Node.js Version: v5.1.0
BrowserSync Version: v2.10.0

**Comment by shakyShane** [comment]
re: the functionality of the index option, please see https://github.com/expressjs/serve-static#index

you want `startPath: 'test.html` 
http://www.browsersync.io/docs/options/#option-startPath
