### ISSUE TITLE
[QUESTION] Is it possible to use nginx with browser sync without proxy ?

### ISSUE THREAD

**Issue by a93ushakov** [BrowserSync/browser-sync#911]
Some html is served by nginx.
How using `browser sync` cli reload web page manually?

In other words, nginx will be used as main server,  `browser-sync` - as server for manual reload ability.

**Comment by shakyShane** [comment]
sure, just run Browsersync with neither `server` nor `proxy` options and you'll be given a snippet to paste into your website :)

**Comment by a93ushakov** [comment]
thanks 4 reply;

but, how to make `browser-sync` refresh web-pages only in manual way - by command browser-sync reload?
