### ISSUE TITLE
browserSync nevere reloads for .js file

### ISSUE THREAD

**Issue by msatala** [BrowserSync/browser-sync#915]
Hello,
I'm using browser-sync 2.10.0 in proxy mode and I can't get it to reload the browser for .js file.
It doesn't matter whether I run browser-sync with gulp or standalone. 

It also doesn't matter if the change is triggered by `files: ["server/public/templates.js"]` option or `gulp.watch("server/public/templates.js").on("change", browserSync.reload);`. 

BS even correctly logs `[BS] File changed: server/public/templates.min.js` or `[BS] Reloading Browsers...`. However no reload ever happens.

It works for all other file types.

For completeness: I'm running Linux Mint 17.2 which is based on Ubuntu 14.04. BS is used as a proxy for a play application and here's the gulp file:
```javascript
var gulp = require('gulp');
var watch = require('gulp-watch');
var templateCache = require('gulp-templatecache');
var browserSync = require('browser-sync').create();
var batch = require('gulp-batch');

var templatesPath = 'client/src/**/*.html';


gulp.task("default", ["watch-templates", "browser-sync"]);

gulp.task('watch-templates', function () {
    watch(templatesPath, {ignoreInitial: false}, batch(function (events, done) {
        gulp.start('build-templates', done);
    }));
});


gulp.task('build-templates', function () {
    var options = {
        output: "templates.js",
        moduleName: 'newgold',
        strip: "main/scala/com/cloudfarms/newgold/client/"
    };

    return gulp.src(templatesPath)
        .pipe(templateCache(options))
        .pipe(gulp.dest('server/public'))
});


gulp.task('browser-sync', function () {
    browserSync.init({
        proxy: 'localhost:9000',
        port: 3000,
        files: [
            "client/src/**/*.scala",
            "shared/src/**/*.scala",
            "server/app/**/*.scala.html",
            "server/public/**/*.html",
            "server/public/**/*.css",
            "server/public/templates.js"
        ],
        open: false,
        ui: false,
        ghostMode: false
    });

    // doesn't work either
    //gulp.watch("server/public/templates.js").on("change", browserSync.reload);
    //gulp.watch("client/src/**/*.scala").on("change", browserSync.reload);
});
```

**Comment by marvinhagemeister** [comment]
Besides the browser-sync issue there are multiple other ones with your gulpfile and how you execute task dependencies. `gulp.start` has always been a bit flakely and not the proper way to start tasks after another one has been finished. It will be removed in the upcoming Gulp 4 as per [Issue #426](https://github.com/gulpjs/gulp/issues/426).

I'm not sure if that alone fixes your problems with browser-sync not reloading and I can't test it at the moment since I'm not near a pc. Have a try with this one:

```js
var gulp = require('gulp');
var templateCache = require('gulp-templatecache');
var browserSync = require('browser-sync').create();

var templatesPath = 'client/src/**/*.html';

// Default task
gulp.task("default", ["build-templates", "browser-sync"]);

// Build templates
gulp.task('build-templates', function () {
    var options = {
        output: "templates.js",
        moduleName: 'newgold',
        strip: "main/scala/com/cloudfarms/newgold/client/"
    };

    return gulp.src(templatesPath)
        .pipe(templateCache(options))
        .pipe(gulp.dest('server/public'));
});

// browser-sync
gulp.task('browser-sync', function () {
    browserSync.init({
        proxy: 'localhost:9000',
        port: 3000,
        open: false,
        ui: false,
        ghostMode: false
    });

    gulp.watch(templatesPath, ['build-templates'])
        .on("change", browserSync.reload);
    gulp.watch("client/src/**/*.scala")
        .on("change", browserSync.reload);
});
```

**Comment by msatala** [comment]
Thank you for your reply. It was in fact a problem in my build. Another instance of browser-sync was started with different settings, The instance I was looking at started on port 3001 instead. It took me a long time to notice.
I think BS should fail to start if the port is already bound instead of silently starting on different port.
Anyway sorry for false bug report.
