### ISSUE TITLE
Browsersync stuck loading behind proxy

### ISSUE THREAD

**Issue by janpieterz** [BrowserSync/browser-sync#916]
Browsersync seems stuck loading the website when run in proxy mode. When using the same config but another website it does work, so it must be something in my local setup but I have been unable to figure out what.

I'm running it on Windows, proxying a ASP.NET 5 application which runs on localhost:5000. Directly navigating towards this location works fine. Trying to hook into the pipeline on ASP.NET's side signals the html is exported over the pipeline but the browser never receives a response and stays pending.

The logging output indicates no difference besides a different session and the obvious proxy url if I run it on another website, where also other sites on localhost seems to work (on IIS). 

Configuration used (gulp):
```js
gulp.task('browsersync', function () {
    browserSync({
        proxy: 'localhost:5000',
        notify: true,
        open: true,
        logLevel: 'debug'
    });
});
```

**Comment by janpieterz** [comment]
Seems more fit for StackOverflow after reading through it again ;)

**Comment by AlexWebYourmind** [comment]
Did you manage to fix the issue @janpieterz ? I am having a similar one (works with one vhosts not with another)

**Comment by dedisuryadi** [comment]
I have similar issue using PHP built in server:
`php -S localhost:8088 -t .`

Using this browser-sync command:
`browser-sync start --proxy="localhost:8088" --files="*.php, view/dashboard/*.html, css/*.css, js/*.js"`
