### ISSUE TITLE
TypeError: o is null

### ISSUE THREAD

**Issue by slarti-b** [BrowserSync/browser-sync#918]
Using browsersync together with Grunt, mainly to auto-reload CSS once the SASS build has run.  I inject the javascript snippet to run the sync (so I can avoid running against odd ports for the actual website).  Getting the following error in my Firebug console: "TypeError: o is null"
![typeerror](https://cloud.githubusercontent.com/assets/12972794/11538093/f105499e-9928-11e5-8139-c24d7090231a.png)

Injecting the following javascript (as per what it says to use when I run grunt):
```
<script type='text/javascript' id='__bs_script__'>//<![CDATA[\n	document.write("<script async src='https://HOST:$port/browser-sync/browser-sync-client.2.10.0.js'><\/script>".replace('HOST', location.hostname));\n //]]></script>
```

Grunt packages in use:
```
    "grunt": "^0.4.5",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-sass": "^0.18.0",
    "grunt-sass-globbing": "~1.4.0",
    "grunt-browser-sync": "~2.2.0"
```

Browser is Firefox 42.0 on Win 8.1  Grunt and browsersync running on a virtualbox centos.

**Comment by shakyShane** [comment]
This is likely caused by a conflict with some other script in your app. Try removing them all (so that Browsersync is the only one) and then add them back in 1-by-1 until you find the cause. If this turns out to be reproducible, please send a sample and I will take a look :)

**Comment by slarti-b** [comment]
Hmm.. seems to have been fixed by moving the js to add browser-sync to really last in my page body (it does say to add it there - but everything wants to be last!)
