### ISSUE TITLE
BrowserSync not detecting changes

### ISSUE THREAD

**Issue by prashcr** [BrowserSync/browser-sync#919]
I wrote a Makefile to minify my HTML/CSS/JS, shown here

I ran `make server` in one terminal tab, then opened another terminal tab, made some changes to the source files and ran `make rebuild`. BrowserSync doesn't detect the changes or reload the page. When I directly edit the HTML in `build`, BrowserSync updates as expected though.
```
# HTML
HTML_SRC       := $(wildcard src/*.jade)
HTML_BUILD     := $(patsubst src/%.jade,build/%.html,$(HTML_SRC))
HTML_FLAGS     := --conservative-collapse \
	--collapse-whitespace \
	--remove-comments
JADE_PATH      := $(CURDIR)/src/includes

# CSS
CSS_SRC        := src/assets/sass/my.scss
CSS_BUILD      := build/assets/css/main.css

# JS
# These need to be in this order
JS_SRC         := src/assets/js/jquery.min.js \
	src/assets/js/jquery.dropotron.min.js \
	src/assets/js/jquery.scrolly.min.js \
	src/assets/js/jquery.scrollgress.min.js \
	src/assets/js/skel.min.js \
	src/assets/js/util.js \
	src/assets/js/main.js
JS_BUILD       := build/assets/js/bundle.js

all: $(HTML_BUILD) $(CSS_BUILD) $(JS_BUILD)

rebuild: clean all

server: 
	browser-sync start --files "build/*.html, $(CSS_BUILD), $(JS_BUILD)" --server "build"
	
build/%.html: src/%.jade 
	jade -p $(JADE_PATH) < $< | \
	html-minifier -o $@ $(HTML_FLAGS)

$(CSS_BUILD): $(CSS_SRC)
	node-sass $< > $@
	cleancss -o $@ $@

$(JS_BUILD): $(JS_SRC)
	uglifyjs $(JS_SRC) -c -m -o $@

clean:
	rm $(CSS_BUILD)
	rm $(HTML_BUILD)
	rm $(JS_BUILD)

```

**Comment by prashcr** [comment]
#62
> Just want to point this out. I have discovered something might worth to share with others. Not sure if this is stated somewhere though. My issue actually was that if you run browser-sync it will detect file changes for existing files prior to running browser-sync. And when you create additional file and modify it, browser-sync won't notice this change since the file is created after browser-sync started running.  
  
Hmm, this seems like the case. How should I work around this?

**Comment by shakyShane** [comment]
try watching just the `/build` directory, see if that helps.

```shell
browser-sync start --files "build" --server "build"
```

**Comment by prashcr** [comment]
Yeah, I think my problem was that I was `rm *`-ing all my built files every time I rebuilt, and browser-sync couldn't detect changes after that. The folder syntax is cool, thanks!
