### ISSUE TITLE
API to inject custom html

### ISSUE THREAD

**Issue by marvinhagemeister** [BrowserSync/browser-sync#920]
I just played around with [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) and I was wondering if something the error handling part would fit into the scope of browsersync. Good use cases would be gulp compilation or runtime errors (sass-errors, js-errors,...) so that there is no need to switch back to the terminal all the time. I'm aware of `gulp-notify` but I think it'd be even nicer to display a giant error message in the browser itself.

**Comment by shakyShane** [comment]
absolutely, check out the source code for this plugin https://github.com/shakyShane/bs-fullscreen-message - it does exactly what you want (display messages in browsers) - you should be able to tweak to your needs

**Comment by marvinhagemeister** [comment]
That's amazing! Thanks for the heads up :+1:
