### ISSUE TITLE
BrowserSync client crashes

### ISSUE THREAD

**Issue by PedroD** [BrowserSync/browser-sync#922]
More info here: https://stackoverflow.com/questions/34109937/browsersync-client-is-crashing-for-some-reason

**Comment by shakyShane** [comment]
There's something in your app code that's causing this. Remove all of your scripts (so that Browsersync is the the only one) then begin adding them back in one-by-one until you find the cause :)

**Comment by PedroD** [comment]
Hi! 

Yes my app is totally broken. But my point is, if I am coding with automated reloading, it is normal that sometimes my app will not run and crash that way. 

This means that whenever I am coding and my code has issues, I will have to reload the browser manually because browser sync will stop working? Isn't there a way to isolate browser sync from my webapp's errors? 

On December 7, 2015 7:13:58 AM WET, Shane Osbourne <notifications@github.com> wrote:
>There's something in your app code that's causing this. Remove all of
>your scripts (so that Browsersync is the the only one) then begin
>adding them back in one-by-one until you find the cause :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/BrowserSync/browser-sync/issues/922#issuecomment-162434779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
