### ISSUE TITLE
Not able to open virtual host name instead of localhost:3000

### ISSUE THREAD

**Issue by paramsinghvc** [BrowserSync/browser-sync#923]
I really wanna use browser-sync in my workflow but the only problem is I'm using Nginx virtual host domains on my local for serving my angular website which in turns uses the backend rest apis made in laravel which sets the cors thing and I have made whitelist entry of my site (http://mj.dev) in the backend for it. Now, using browser Sync with gulp only opens the site with localhost:3000 which is unacceptable for my situation. I tried using 

gulp.task('browser-sync', function() {
    browserSync.init({        
        proxy: 'mj.dev'        
    })
})

but didn't work out. Can someone help me with this.

**Comment by edinchez** [comment]
I have the exact same problem. Help please?

**Comment by shakyShane** [comment]
Provide no options and you will be given a snippet to paste into your website

**Comment by edinchez** [comment]
@shakyShane This worked perfectly! Thank you so much.

**Comment by paramsinghvc** [comment]
@shakyShane Please a little more explanation or a code sample.

**Comment by shakyShane** [comment]
@paramsinghvc 

```js
gulp.task('browser-sync', function() {
    browserSync.init();
});
```

^ this will give you a snippet in the terminal that you can paste into your website
