### ISSUE TITLE
auto port assignment bug in 2.10.0?

### ISSUE THREAD

**Issue by sgraham785** [BrowserSync/browser-sync#927]
In 2.9.11 if I am running more that one project the ports are auto assigned on availability e.g. 3000 & 3001 for project 1, then 3002 & 3003 for project 2, but in 2.10.0 it always uses port 3000 & 3001

is think intentional or a bug?

-CentOS 6.6, nodejs 0.12.7, apache 2.2.15
-Proxying
-it's a bit complex to show my entire gulpfile.js, but here are the browsersync configs:

```js
browserSync: {
      //ui: false, // turn-off ui
      proxy: {
        target: proxyDomain
      }, // set existing vhost
      browser: "google chrome", // Open the site in Chrome
      open: false, // Open the external URL - must be online.
      reloadOnRestart: true, // auto-reload all browsers following a Browsersync restart
      minify: true,
    },
```

**Comment by shakyShane** [comment]
can you provide a bit more detail re: your setup please :)

https://github.com/BrowserSync/browser-sync/blob/master/CONTRIBUTING.md#-tips-for-a-creating-a-great-issue-report
