### ISSUE TITLE
Page won't stop loading when using SuperAgent (Pending websocket)

### ISSUE THREAD

**Issue by wsmd** [BrowserSync/browser-sync#928]
First of all, I'm not sure if this is the right place to post this. However, I started using [SuperAgent@1.5.0](https://github.com/visionmedia/superagent) and noticed the page won't stop loading when i'm running the site through a browser-sync server.

I digged a little deeper I noticed that a there's a `browser-sync/socket.io` websocket that is pending.

`ws://localhost:3000/browser-sync/socket.io/?EIO=3&transport=websocket&sid=XIvrtnlp2agslXGDAAA6`
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: KN6Ef7ItaBAVymUZR1J+wqahxFA=
Sec-WebSocket-Extensions: permessage-deflate
```

![screen shot 2015-12-11 at 2 50 27 pm](https://cloud.githubusercontent.com/assets/2100222/11754123/3ff6e07c-a017-11e5-835b-ae2d718ea8e6.png)

This is all I have on my page

```javascript
import request from 'superagent';

request
  .get('README.md')
  .end(function handleResponse(err, res) {
    if (res.ok) {
      document.write(res.text);
    } else {
      document.write(`File not found`);
    }
  });
```

Again, this only happens when I'm using SuperAgent (notice the GET request is ended).

**Comment by shakyShane** [comment]
This is the correct state for a websocket. I'm not sure how or why this would cause you a problem, but if you look at any websocket implementation you will see the same activity in the browser. The websocket is always 'pending' as it's open connection. Hope that helps in some way, but I'll close this issue as this is not outside of the norm for websocket behaviour
