### ISSUE TITLE
Can Browser-Sync be configured to watch for incoming files?

### ISSUE THREAD

**Issue by tevko** [BrowserSync/browser-sync#93]
Let's say I have browser-sync watching my css directory, which only contains foo.css. If I add bar.css, it seems as if browser-sync doesn't see the file until it is restarted. If it were able to watch for incoming files, it would be a lot easier to use with build tools like grunt and gulp, being that when a default task is run that contains a clean function and a browser-sync function, certain files are removed and added back before browser-sync has the chance to notice that they exist in the directory it is being configured to watch. Currently I have removed gulp-clean from my gulpfile because of this issue, being that when the clean task and the browser-sync task run at the same time, gulp-clean will remove my css file in my build directory before browser-sync notices it, at which the css file is added back when a change is made to the file in my dev directory. This means that browser-sync will not see any css files in dev/css/ because it cannot tell that they were added to the folder

**Comment by Avcajaraville** [comment]
Yeah, this issue is old, but Im running into the same issues... browsersync does not recognize new/remove/rename files ...

Would appreciate much a quick snippet or similar where we can see how to do it.

Thanks a lot !

**Comment by LRPalacios** [comment]
I am on the same train here, an example ins this discussion would be great!

**Comment by evanre** [comment]
+1

**Comment by mcqj** [comment]
+1
