### ISSUE TITLE
No instant file changes across browsers

### ISSUE THREAD

**Issue by ihabovich** [BrowserSync/browser-sync#932]
Using virtual host name on LAMP, I started Browsersync as:
`browser-sync start --proxy "project.dev" --files "templates/css/*.css"`

Except I don`t get file sync in browser automatically! . Any suggestions?

**Comment by shakyShane** [comment]
Please see https://www.browsersync.io/docs/#requirements

If you actually see the 'Browsersync connected' message in the browser, then it maybe be a bug, so if you could provide more information + a sample html page of your website we look at this further
