### ISSUE TITLE
Serving index.html from static does not get snippet injected

### ISSUE THREAD

**Issue by techniq** [BrowserSync/browser-sync#933]
I currently have the following setup within a gulp task (truncated for brevity):

```js
browserSync.init({
  port: 8000,
  proxy: 'localhost:8080',
  serveStatic: ['public']
});
```

If `index.html` is served from the `public` directory, it does not get injected with the browser-sync-client snippet (and thus automatic reload on file changes doesn't occur).  If `index.html` is served from the proxy (localhost:8080/index.html) then it does get injected with the browser-sync-client snippet.  I also tried serving my public directory as an explicit middleware (which I assume `serveStatic` is doing behind the scenes):

```js
browserSync.init({
  port: 8000,
  proxy: 'localhost:8080',
  middleware: [
    require('serve-static')('public')
  ]
});
```

**Comment by techniq** [comment]
rewriteRules and other features also do not apply to the these static resources.  I figure I need to manually add the middleware that performs these features (inject the snippet, rewrite the body responses, etc), but I'm lost as to which middleware does each of these items.  Also not sure if it would be possible to add the static middleware earlier in the stack to have all this work.

**Comment by shakyShane** [comment]
@techniq thanks for the detailed report.

You have actually unearthed a major design flaw with Browsersync 1.x + 2.x and the way it treats proxies separately from server or snippet modes. 

This is fixed and works as expected in v3, but until that's ready for release, you could make your example work with the following.

```js
var bs        = require('./').create();
var httpProxy = require('http-proxy');

var proxy     = httpProxy.createProxyServer({
    // you may/may not need these
    changeOrigin: true,
    autoRewrite: true,
    secure: false
});

var proxyAddress = 'http://www.bbc.co.uk';

bs.init({
    server: ["public"]
}, function (err, bs) {
    bs.addMiddleware('*',
        function proxyMiddleware (req, res) {
            proxy.web(req, res, {target: proxyAddress});
        }
    );
});
```

Or, if you also need the link-rewriting feature of Browsersync, you'd have to steal from the foxy lib

```js
var bs           = require('./').create();
var httpProxy    = require('http-proxy');
var url          = require('url');
var rewriteLinks = require('foxy/lib/utils').rewriteLinks;

var proxy        = httpProxy.createProxyServer({
    changeOrigin: true,
    autoRewrite: true,
    secure: false
});

var proxyAddress = 'http://www.bbc.co.uk';

bs.init({
    server: ["public"],
    open: false,
    online: false,
    rewriteRules: [
                                              // browsersync's url
        rewriteLinks(url.parse(proxyAddress), 'localhost:3000')
    ]
}, function (err, bs) {
    bs.addMiddleware('*',
        function proxyMiddleware (req, res) {
            proxy.web(req, res, {target: proxyAddress});
        }
    );
});
```


Hope that helps, and just to re-iterate, in v3 you'll be able to do just

```js
var bs = require('./');
bs.create({
    serveStatic: ['public'],
    proxy: {
        target: 'http://www.bbc.co.uk'
    },
});
```

**Comment by techniq** [comment]
Exactly what I was looking for. Thanks
