### ISSUE TITLE
Sending event from browser to server

### ISSUE THREAD

**Issue by stoffeastrom** [BrowserSync/browser-sync#935]
Tried using the `window.___browserSync___.socket.emit("foo");` but I don't get notified on the server using

`instance.io.sockets.on("foo", () => { console.log("foo"); } );`

I'm using browser sync to run mocha tests in the browser and would like to tell the server when it's finished.

Any pointers?

**Comment by stoffeastrom** [comment]
@shakyShane Is it possible to listen for client emitted events?

**Comment by shakyShane** [comment]
yep, you just need to wait until Browsersync is ready before you listen for connections

```js
var browserSync = require('./').create();

browserSync
    .init({
        minify: false,
        server: 'test/fixtures'
    }, listen);

function listen() {
    browserSync.sockets.on('connection', function (client) {
        client.on('foo', function () {
            console.log('ere');
        });
    });
}
```

then on the client you can 

```js
window.___browserSync___.socket.emit("foo");
```

**Comment by stoffeastrom** [comment]
:+1: Works like a charm! Thanks for the great library!!
