### ISSUE TITLE
Question: support for hot-reloading JS?

### ISSUE THREAD

**Issue by rstacruz** [BrowserSync/browser-sync#944]
When changing CSS files, they're changed without reloading the page. Would it be possible to do the same for JavaScript files (and leave it to the user to figure out how to implement it in their code)?

**Comment by tsm91** [comment]
would be an awesome feature

**Comment by marvinhagemeister** [comment]
I got this working with webpacks hot module replacement plugin. Just pass it as a middleware to browsersyncs server instance and that's it.

**Comment by shakyShane** [comment]
Hot-loading JS requires a module bundler. It's not the same concept at reloading CSS. Please see our various examples here with webpack https://browsersync.io/docs/recipes/

**Comment by tsm91** [comment]
ahh okay, so this is a `browserify` related feature then
