### ISSUE TITLE
How to disable auto refresh?

### ISSUE THREAD

**Issue by a93ushakov** [BrowserSync/browser-sync#947]
?

**Comment by a93ushakov** [comment]
I wont to use only manual reload ability.

**Comment by igidas** [comment]
RTFM: https://www.browsersync.io/docs/options

**Comment by equiman** [comment]
You can use Yargs as parameter and disable watch task:

https://stackoverflow.com/a/44731009/812915

**Comment by ebuildy** [comment]
Options:

```codeSync: false```
