### ISSUE TITLE
Gulp 4 style injection

### ISSUE THREAD

**Issue by JamesJosephFinn** [BrowserSync/browser-sync#951]
I'm attempting to use browser-sync with Gulp 4 and the new bs `.stream()` syntax, but bs is not preserving state and does a full refresh. Have you folks created a recipe / best practice for gulp v4 yet, so I can compare notes. Thanks for this awesome tool.

**Comment by JamesJosephFinn** [comment]
I guess some code would help.

My default task:
```js
gulp.task('default',
    gulp.series('clean:dev',
        gulp.parallel('copy:dev', 'styles:dev'), 'browserSync', 'watch')
);
```

The `styles:dev` task:
```js
gulp.task('styles:dev', function() {
    return gulp.src(config.src)
        .pipe(sourcemaps.init())
        .pipe(postcss(config.postcss.dev))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(config.dest.dev))
        .pipe(browserSync.stream());
});
```

The `browserSync` task:
```js
gulp.task('browserSync', function(cb) {
    browserSync.init(config, cb);
});
```

Finally, the `watch` task:
```js
gulp.task('watch:styles', function() {
    return gulp.watch(config.paths.css,
        gulp.series('styles:dev'));
});

gulp.task('watch', gulp.parallel('watch:styles'));
```

Thanks in advance.

**Comment by JamesJosephFinn** [comment]
Fixed. Here's the issue:

The browser-sync constructor takes an options object, which can include a `files` array. Most of the tutorials I've read, including the gulpfile for Google's very own Web Starter Kit, do not include this. As it turns out, this is required for style injection to preserve state.

Furthermore, do not pass `.stream()` or `.reload()` as the final pipe in your styles task. It is not needed, and will short circuit style injection, forcing a full refresh.

Hope this helps anybody facing this issue.

**Comment by iliakan** [comment]
@JamesJosephFinn would you show the resulting gulpfile?

**Comment by JamesJosephFinn** [comment]
@iliakan sure:
```js
var gulp = require('gulp');
var browserSync = require('browser-sync');

var config = {
    server: {
        baseDir: './dev/'
    },
    files: [
        './dev/*.css',
        './dev/*.js',
        './dev/**/*.svg'
    ],
    browser: 'google chrome canary',
    notify: false
};

gulp.task('browserSync', function() {
    browserSync.init(config);
});
```

and then a separate file for css task setup:

```js
var gulp = require('gulp');

var config = {
    src: './src/css/styles.css',
    dest: {
        dev: './dev/'
    }
};

gulp.task('css:dev', function() {
    return gulp
        .src(config.src)
        .pipe(foo()) // whatever you're into
        .pipe(gulp.dest(config.dest.dev));
});
```

watching is a joy in gulp4:

```js
var gulp = require('gulp');

var config = {
    paths: {
        css: './src/css/**/*'
    }
};

gulp.task('watch:css', function() {
    return gulp.watch(config.paths.css,
        gulp.series('css:dev'));
});

gulp.task('watch', gulp.parallel('watch:css'));
```

and then default task... I've only shown css related stuff above, to keep this a simple illustration of live style injection using browser-sync and gulp4:

```js
gulp.task('default',
    gulp.series(
        'clean:dev',
        gulp.parallel(
            'copy:dev', 'html:dev', 'css:dev',
            'js:dev', 'svgSymbol:dev', 'svg:dev'
        ),
        gulp.parallel('watch', 'browserSync')
    )
);
```

**Comment by JamesJosephFinn** [comment]
NB, also, the important difference in the default task: `watch` and `browserSync` execute in parallel.

**Comment by cdbattags** [comment]
@JamesJosephFinn, do you mind explaining how your splitting out your tasks into multiple files? Using gulp-hub?

**Comment by JamesJosephFinn** [comment]
I use an [npm module called require-dir](https://www.npmjs.com/package/require-dir) which creates an object out of the contents of the directory you pass in. Each file in the directory will be assigned a key, and the value will be the file contents. In your `gulpfile.js`:

```javascript
// Node module to require an entire directory
var requireDir = require('require-dir');
// Pull in all task files from the /gulp directory
requireDir('./gulp');
```
The keys will be created by file name in alphabetical order. This can create issues, as I'm sure you can imagine. Gulp v. 4 to the rescue again with a new feature they've dubbed *forward references*. I've never used the API, nor do I know how, but it is certainly useful.

**Comment by savokiss** [comment]
Helped me! Thanks!

**Comment by JamesJosephFinn** [comment]
👍

**Comment by rtxrulez** [comment]
@JamesJosephFinn Can I download scripts without reloading the page?

**Comment by cdbattags** [comment]
@rtxrulez, unsure what you mean by this. Care to explain a bit more about your use case?

**Comment by smth** [comment]
With the above configuration, should the page be automatically refreshing when changes are detected? For me it got `watch` and `browserSync` running in parallel, but no automatic refresh when code is edited. There doesn't seem to be anywhere in the config where we are telling browserSync when to refresh, so perhaps this was not the intention (others here seem to be expecting it too).
