### ISSUE TITLE
Installation dependency errors windows

### ISSUE THREAD

**Issue by hainzee** [BrowserSync/browser-sync#954]
My shell output is a little different to #886 but are these just optional dependency errors?
Running Visual Studio 2015 at present.

$ npm update

npm WARN optional dep failed, continuing fsevents@1.0.6

> utf-8-validate@1.2.1 install C:\projects\examples\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-va
lidate
> node-gyp rebuild

/
C:\projects\examples\node_modules\browser-sync\node_modules\socket.io\node_module
s\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_confi
g_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bi
node  rebuild ) dules\node-gyp\bin\node-gyp.js" rebuild )  else -(
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\vali
dation.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\examples\node_modules\browser-sync\node_modules\so
cket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\buil
d\validation.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\projects\examples\node_modules\browser-sync\node_mo
dules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\projects\examples\node_modules\browser-sync\node_modules\socket.io\node_module
s\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_no
de_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferut
il.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\examples\node_modules\browser-sync\node_modules\so
cket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bu
fferutil.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> utf-8-validate@1.2.1 install C:\projects\examples\node_modules\browser-sync\nod
e_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\
node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\projects\examples\node_modules\browser-sync\node_modules\socket.io\node_module
s\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\ut
f-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\no
dejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\n
ode_modules\utf-8-validate\build\validation.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\examples\node_modules\browser-sync\node_modules\so
cket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_module
s\ws\node_modules\utf-8-validate\build\validation.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\no
de_modules\utf-8-validate
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> bufferutil@1.2.1 install C:\projects\examples\node_modules\browser-sync\node_mo
dules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node
_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\projects\examples\node_modules\browser-sync\node_modules\socket.io\node_module
s\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bu
fferutil>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\n
ode_modules\bufferutil\build\bufferutil.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\projects\examples\node_modules\browser-sync\node_modules\so
cket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_module
s\ws\node_modules\bufferutil\build\bufferutil.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\projects\examples\node_modules\browser-sync\node_modules\socket.i
o\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\no
de_modules\bufferutil
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

**Comment by hainzee** [comment]
I have decided to use `npm install browser-sync --no-optional` which eliminates the errors but use wisely.

**Comment by shakyShane** [comment]
`optional dep` - this is due to a platform specific lib, it can be ignored :)
