### ISSUE TITLE
SSL certificate with a chain of trust

### ISSUE THREAD

**Issue by atalis** [BrowserSync/browser-sync#956]
I'm trying to set up a gulp HTTPS server.  My server's certificate is signed by my company's CA.  In order for it to be validated by a browser, the CA's certificate itself also needs to be specified, so that the client browser can validate the chain of trust.  

Node's HTTPS object has an option "ca" for listing trusted certificates to establish the chain of trust.  Is there a way to specify ca certs in browser-sync?  Optimally, I'd be looking for something like the snippet below, but I'd take a workaround, if there are any.

``` js
 browserSync.instance = browserSync.init({
      server: {
        baseDir: "app"
      },
      https: {
        cert: './certs/serverCert.pem',
        key: './certs/serverKey.pem',
        ca: ['./certs/mycompany-ca.cer', './certs/mycompany-root-ca.cer']
      },
      ...
    });
```

**Comment by ibmkendrick** [comment]
+1

**Comment by kendrickw** [comment]
+1

**Comment by shakyShane** [comment]
So, looks like we just need to support an array of strings as the docs state:

> ca: A string, Buffer or array of strings or Buffers of trusted certificates in PEM format. If this is omitted several well known "root" CAs will be used, like VeriSign. These are used to authorize connections.

currently we're just reading a single one here https://github.com/BrowserSync/browser-sync/blob/78c519ef28e0377f1bd3d835f30ed4010b4ada5a/lib/server/utils.js#L30-L30

**Comment by shakyShane** [comment]
@atalis this has been fixed by instead allowing ANY additional https options instead. https://github.com/BrowserSync/browser-sync/pull/1252

https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
