### ISSUE TITLE
Old injection script used in 2.11.0 

### ISSUE THREAD

**Issue by thebuilder** [BrowserSync/browser-sync#957]
After updating to 2.11.0 browser-sync still injects the script tag for the last version, failing since it doesn't exist.

```
document.write("<script async src='/browser-sync/browser-sync-client.2.10.1.js'>
```

**Comment by patrickfatrick** [comment]
I ran into this as well. Downgraded to 2.10.1 for now.

**Comment by shakyShane** [comment]
More likely your browser is caching something. The snippet is dynamically generated from the version, so this cannot be the case. Please clear all browser caches and try again.

**Comment by patrickfatrick** [comment]
That did it for me, thanks!
