### ISSUE TITLE
Getting BrowserSync and Vagrant to work together 

### ISSUE THREAD

**Issue by Quirksmode** [BrowserSync/browser-sync#958]
When I use Vagrant it sets up my project on a specific domain which I then Proxy with BrowserSync. The problem is that BrowserSync creates it's own domain `localhost:3000` which causes problems with security/CORs as it is no longer the correct domain. How can we proxy a domain and keep that domain name?

**Comment by gil--** [comment]
```
    browsersync.init({
        proxy: "https://mydomain.dev",
        https: true
    });
```

**Comment by Quirksmode** [comment]
That will not fix it unfortunately, it will still try to create the localhost domain

**Comment by shakyShane** [comment]
@Quirksmode can you not alter `cors` headers through either

https://github.com/BrowserSync/browser-sync/blob/master/examples/proxy.proxyRes.js

or 

https://github.com/BrowserSync/browser-sync/blob/master/examples/proxy.middleware.js

**Comment by shakyShane** [comment]
fixed via new option

`cors: true`

https://github.com/BrowserSync/browser-sync/commit/62d83b895d032624957474b6a23da157913caabd

**Comment by AurelienPillevesse** [comment]
Hi, i would like to know something.
Do you execute the gulp inside the vagrant or not?
Thanks

**Comment by thecodenametyler** [comment]
apparently you should execute gulp outside vagrant
