### ISSUE TITLE
how can i use command line to start different browser at the same time ?

### ISSUE THREAD

**Issue by qileilove** [BrowserSync/browser-sync#960]
hi, when i test the our project code for different URL ,i need to input the URL for different browser, so can i just use the command line to excute the command to change the url ? such as "browser-sync start --open http://localhost:3001/test.html"

**Comment by shakyShane** [comment]
the `startPath` option is what you want.

if you're using `bs-config.js` just add 

```js
startPath: 'test.html'
```

or if you're cli only

```shell
browser-sync start --server --startPath test.html
```

**Comment by qileilove** [comment]
hi shane
what i want to say is that the start options has '--browser'  options, it
can choose which browser should be auto-opened, But it can only enter one
parameter，it didn't support  multiple ，for example if i want start firefox
and chrome at the same time, it didn't support ["chrome", "firefox"].

**Comment by shakyShane** [comment]
put multiple `--browser` and it will work
