### ISSUE TITLE
Creating a new instance results in a circular dependency

### ISSUE THREAD

**Issue by olanb7** [BrowserSync/browser-sync#961]
I'm attempting to use `browser-sync` with https://github.com/webpack/grunt-webpack and https://github.com/Va1/browser-sync-webpack-plugin, however I get the following error when configured correctly, `Warning: Circular reference detected (.webpack.plugins[1].browserSync.instance.publicInstance)` which causes the build to abort. I think this is due to the fact that `grunt.config(arr)` throws an error when dealing with an object with a cyclic dep.

The circular dependency can be validated with the following piece of code:
```js
var browserSync = require('browser-sync');
var bs = browserSync.create('test');
console.log(JSON.stringify(bs));
```

```shell
$ node index.js
bs/index.js:3
console.log(JSON.stringify(bs));
                 ^
TypeError: Converting circular structure to JSON
```

This appears to be due to the following piece of code in `index.js`.
```js
    var instance = {
        name:      name,
        instance:  browserSync,
        ...
    };

    browserSync.publicInstance = instance;
```

Not sure what's the best approach to resolving this. For my purposes,`instance:  _.clone(browserSync),` resolves the issue, but I'm guessing this will cause issues where ``instance` is used for context elsewhere...

**Comment by shakyShane** [comment]
yes there are circular dependencies within Browsersync - that's a totally valid technique for what I need. I can't imagine any scenario where you'd want to JSON encode the object returned - so I'm going to close this, but feel free to explain why you believe this is an issue
