### ISSUE TITLE
BrowserSync + gulp + wamp not syncing .php files

### ISSUE THREAD

**Issue by eyal670** [BrowserSync/browser-sync#964]
HI
my gulp file:

```javascript
var gulp        = require('gulp');
var browserSync = require('browser-sync').create();

//server
gulp.task('run', function() {
    browserSync.init({
        proxy: "http://localhost/test-site/"
    });
    gulp.watch("./*.php").on('change', browserSync.reload);
});
```
when running ```gulp run``` from terminal it's fire the browser and shows the page as expected but without the "connected to browserSync" msg and when saving some changes the gulp watch fires and the terminal shows ```[BS] Reloading Browsers...``` but the browser not refreshing the page

now on the other hand when i'm changing the file extension to "html" and gulp watch to ```gulp.watch("./*.html").on('change', browserSync.reload);```
it all work as expected: when running the task it's fire the browser, this time with the "connected to browserSync" msg and when saving some changes it refresh the page.
early today i did manage to refresh the page on php file change but i lost it and can't find the reason why it's not working any more, i couldn't find any post about it on google
any ideas ?

**Comment by shakyShane** [comment]
first, check the site being served by your php files meets the requirements https://www.browsersync.io/docs/#requirements

After that (make sure you have a `<body>` tag etc), you can remove the gulp watcher and instead use the files option in browsersync

```js
//server
gulp.task('run', function() {
    browserSync.init({
        proxy: "http://localhost/test-site/",
        files: ["**/*.php"]
    });
});
```
