### ISSUE TITLE
cant reload even just watch the css style!

### ISSUE THREAD

**Issue by ivanberry** [BrowserSync/browser-sync#966]
```js
         //I just want an easy task,once the css change,reload the browser.
        var gulp = require('gulp');
        var browserSync = require('browser-sync');
         gulp.task('watch',['browserSync'], function() {
         gulp.watch('src/css/*.css', browserSycn.reload);
         gulp.watch('src/*.html', browserSync.reload);
     });

       gulp.task('browserSync', function() {
                 browserSync({
                      server: {
                         baseDir: 'src'
                        }
               })
        });
```

but once I click the browser, it works , I have google this a lot , I think this is the last place who can handle this issuse, So what's next?

**Comment by JodiWarren** [comment]
You've got a typo in there:

gulp.watch('src/css/*.css', browserS*yc*n.reload);

Does it work properly when you fix that?

**Comment by ivanberry** [comment]
@JodiWarren  thanks for you help , fixed and problem still, BTW, I am using the webstorm , someone on overstackflow told me it's a bug or something with it, but ,after trying simple editor like vim ,sublime, problem still there.

**Comment by ivanberry** [comment]
@JodiWarren  I do some try again, after I save the change by myself, the vim, editor,and also including the webstorm, browser reload! so, maybe this is a bug of webstorm?

**Comment by JodiWarren** [comment]
So this will reload the browser on CSS change:

```javascript
//I just want an easy task,once the css change,reload the browser.
var gulp = require('gulp');
var browserSync = require('browser-sync');
 gulp.task('watch',['browserSync'], function() {
     gulp.watch('src/css/*.css').on('change', browserSync.reload);
     gulp.watch('src/*.html').on('change', browserSync.reload);
 });

gulp.task('browserSync', function() {
   browserSync.init({
    server: {
      baseDir: 'src'
    }
 })
});
```

but you can stream the CSS changes in with this, which will update the CSS without reloading the page:

```javascript
//I just want an easy task,once the css change,reload the browser.
var gulp = require('gulp');
var browserSync = require('browser-sync');
 gulp.task('watch',['browserSync'], function() {
     gulp.watch('src/css/*.css').on('change', function(event){
     	return gulp.src(event.path).pipe(browserSync.stream());
     });
     gulp.watch('src/*.html').on('change', browserSync.reload);
 });

gulp.task('browserSync', function() {
   browserSync.init({
    server: {
      baseDir: 'src'
    }
 })
});
```

**Comment by ivanberry** [comment]
@JodiWarren  Thanks for all you have done for me! with your last post, yeah, the browser reload, but that's just happened after my save by myself,like :w with vim, So, I give it up, just let it go! thank you again!

**Comment by Keitarokido** [comment]
This is an older post but for future reference if anyone is having any issues.

The following should work if you are working on WebStorm:

Go to Settings >System Settings > Synchronization > Uncheck Use "safe write"

**Comment by radcapitalist** [comment]
@HectorManriquez @ivanberry At least for me, unchecking "safe write" did not help.  However, you can just do Ctrl+S (Save All) in WebStorm just like in other editors, and at that point, browser-sync does catch it and update the browser.
