### ISSUE TITLE
SSL Self signed certificate

### ISSUE THREAD

**Issue by vincentmorneau** [BrowserSync/browser-sync#970]
I'm having an issue with the SHA-1 certificate. This is what I'm getting (Firefox): 

![image](https://cloud.githubusercontent.com/assets/5391291/12435348/f68f4e00-beda-11e5-8503-e9a237c1d856.png)

Is is possible to switch to SHA-2 when using a proxy?

This is how I launch browsersync:
```javascript
browserSync.init({
            host: host,
            port: config.browsersync.port,
            notify: config.browsersync.notify,
            proxy: {
                target: apexHost + apexQueryString,
                middleware: function (req, res, next) {
                    res.setHeader('Access-Control-Allow-Origin', '*');
                    next();
                  }
            },
            serveStatic: [config.distFolder]
        });
```

Am I missing something?

**Comment by shakyShane** [comment]
This is just a warning, Browsersync is a **development only** tool so we don't tend to worry too much about security related issues such as these...

Having said that, we will be using a better cert thanks to the PR mentioned above
