### ISSUE TITLE
unable to change port

### ISSUE THREAD

**Issue by Mattchewone** [BrowserSync/browser-sync#972]
Hi, 

I am using gulp + browsersync + babel, everything seems to be running ok, except when I pass in a custom port number browser-sync does not seem to be using it. 

Here is a snippet

```js
import {create as bsCreate} from 'browser-sync';
const browserSync = bsCreate();

gulp.task('browser-sync', () => {
  browserSync.init({
    server: {
      baseDir: "./build",
      port: 8081
    }
  });
});
```

It just defaults to 3000, to get round this temporarily I have gone in and change the default-config.js but this is not ideal.

Matt

**Comment by shakyShane** [comment]
port is not a child property of the server option. (I know that's not intuitive, I've addressed this in V3)

change to this and you're good.

```
```js
import {create as bsCreate} from 'browser-sync';
const browserSync = bsCreate();

gulp.task('browser-sync', () => {
  browserSync.init({
    server: {
      baseDir: "./build"
    },
    port: 8081
  });
});
```
```

**Comment by chrillewoodz** [comment]
I use this and it's still defaulting to 3001.

```gulp.task('browser-sync', function() {

  browserSync.init({
    port: 3000,
    server: {
      baseDir: './app'
    }
  });
});```

**Comment by heinhoang** [comment]
I'm meeting same problem

**Comment by krisha23** [comment]
`gulp.task('browserSync', function() {
  browserSync.init({
    server: {
      baseDir: './src',
        port : 5000
    }
  })
});
`
I have this, and it still defaults to 3001

**Comment by pratikthakur222** [comment]
I too have the same issue,
Changed port to 9000 but it was showing 9001,
but then when i tried changing my default port in my server file to 9001 , browserSync got it right to 9000
And when my port is set to 9000 in browserSync and then I run my server file it gives Error: listen EADDRINUSE ::: 9000
Which means browserSync is using that address.

I guess browserSync does not allows to use the same port which we are using in our server/app.js file
