### ISSUE TITLE
Can we sync mouse pointer?

### ISSUE THREAD

**Issue by jainaman23** [BrowserSync/browser-sync#973]
It would be great if we sync mouse pointer with browser-sync.

**Comment by shakyShane** [comment]
It would be great! But whilst you can listen to mouse pointer events, you cannot *set* the position of it.

**Comment by dsamarin** [comment]
@shakyShane How about a mouse visual? Would be awesome to see where my clients are pointing to on a per element basis. The mouse position can be identified by the mouse target element and the pointers offset relative to this element. Then the virtual mouse cursor can be smoothly interpolated across the element's offset.
