### ISSUE TITLE
Can't override default browser 

### ISSUE THREAD

**Issue by alkaithil** [BrowserSync/browser-sync#974]
I'm using browser-sync on a gulp task. I've checked [the docs](https://www.browsersync.io/docs/options/) and there's an option for setting the browser in which to open the project. But despite I pass "safari" as a value, it keeps opening on chrome (my system default browser).

    browserSync({
        server: {
            baseDir: "./",
            index: "myindex.html",
            browser: "safari"
        }
    });

**Comment by shakyShane** [comment]
Should be: 


```js
    browserSync({
        server: {
            baseDir: "./",
            index: "myindex.html",
        },
        browser: ["safari"]
    });
```

:)
