### ISSUE TITLE
Ability to set the socket.io Port when calling manually.

### ISSUE THREAD

**Issue by clubdesign** [BrowserSync/browser-sync#979]
Hey Guys,

might be just a Use-Case, but it would make handling browser-sync with Vagrant easier.

When i attach the Client Script manually in the code, and tell the script to call domain:8080 f.e., and browser-sync listens on Port 8080, then the script is called correctly but the socket.io connection is made to the default port. It would be nice if the socket.io port could be overwritten when manually added.

It would make it possible to run browser-sync on a Vagrant Machine, on any Port, but call the site with the normal domain (without adding the port). This would make everything easier for us..;)

Is this possible? I see that you get the socket base infos from window.location on every call, maybe this could be made overwritable by a global?

Greets Marcus

**Comment by shakyShane** [comment]
check the `socket.domain` property - if you set that it will be used in place of `window.location.hostname`

https://www.browsersync.io/docs/options/#option-socket
