### ISSUE TITLE
Documentation Issue with browser sync on Windows

### ISSUE THREAD

**Issue by StfBauer** [BrowserSync/browser-sync#983]
I did recently some testing on what the minimum requirements will be to get browser-sync running on Windows. I turned out that Visual Studio don't needs to be installed it works will event without that.

The only thing that was missing in my tests was a Visual C++ Runtime. I installed the 64bit Version I downloaded from [Microsoft](https://support.microsoft.com/en-us/kb/2977003).

After that i haven't got any python or other error during and after the installation of browser-sync.

I think this is a more lightweight solution rather than install the whole VS Community Edition.

**Comment by MWrathDev** [comment]
This is correct, only the runtime is necessary. But it is also a misnomer, most likely browser-sync isnt what's causing the problem but the node-gyp dependency.

**Comment by StfBauer** [comment]
I tried it out and the problem comes from bufferutil that try to compile optional dependancies.
When browser sync will be install with the ```--no-optional```everything works fine and without an error during installation.

**Comment by CodyPredy** [comment]
Same issue here as @StfBauer. Had it installed in devDependencies and was crashing during npm install on Jenkins build on a Windows environment. 
Fixed by adding a **call npm install browser-sync --no-optional ** before calling **npm install**. It's a workaround more then a fix unfortunately.
