### ISSUE TITLE
Rewrite broken for protocol-relative URLs

### ISSUE THREAD

**Issue by xpd** [BrowserSync/browser-sync#991]
Rewrites doesn't seem to work on protocol-relative URLs. The proxy rewrites works on everything except those. I can't even target the url inside src with custom rewrites.

```html
<!-- Working -->
<script type='text/javascript' src='http://test.dev/file.js'>

<!-- Broken -->
<script type='text/javascript' src='//test.dev/file.js'>
```

**Comment by RobertoSnap** [comment]
Same issue here.

**Comment by fvsch** [comment]
Though this might warrant a fix in browser-sync, note that you can use `https://...` URLs always instead of protocol-relative ones.

Protocol-relative URLs [are now considered an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/).

**Comment by xpd** [comment]
Https urls works just fine. The problem is that WooCommerce with a huge number of active users forces it to output protocol-relative urls, without really providing any ways of changing that behaviour.

We tried writing some custom find/replace. The replace works fine everywhere except inside those urls. Seems like it totally skips over them. Even for small substrings.

**Comment by cryptelli** [comment]
Experiencing the same issue which is affecting page loads as it tries to find WooCommerce assets which aren't being rewritten.

Any fix?

**Comment by shakyShane** [comment]
Please update to v2.14.2 for this fix.
