### ISSUE TITLE
browser-sync cannot proxy https-websites

### ISSUE THREAD

**Issue by wheleph** [BrowserSync/browser-sync#992]
I use browser-sync 2.11.1 with OS X Chrome 48.0.2564.97 (64-bit)

When I use it as a proxy for http-website:
```
browser-sync start --proxy http://folding.extremeoverclocking.com/
```
it works great and I can point multiple browsers to localhost:3000 so that actions done in one of them are replicated in others.

However when I use it for https-website:
```
browser-sync start --proxy https://twitter.com
```
it doesn't work. When I point browsers to localhost:3000 they do not show up in "Current Connections" of browser-sync UI and also the actions are not replicated between them.

Maybe it has something to do with my browser complaining about https: ![SSL error in browser](http://i.stack.imgur.com/vbMhJ.png)

**Comment by shakyShane** [comment]
any large site like twitter has multiple techniques in place to prevent proxing like this - and rightly so. 

Browsersync is a development tool to be used on local addresses that you're working on - in those cases it will work fine with HTTPS - you'll just have to click accept on the warning about self-signed certs :)

**Comment by atalis** [comment]
I'm in a similar situation, except I'm proxying to an HTTPS Node server on localhost.  The server is using a cert.  I'd like to be able to:
a) Run BrowserSync in HTTP, not HTTPS mode, and
b) Configure the proxy to use the same cert in order for BrowserSync to be able to connect to the server. 

Is it possible?  So far whatever I do, BrowserSync launches with https, even if I exlicitly set the https option to false.
