### ISSUE TITLE
Browser Sync in iframe using local content?

### ISSUE THREAD

**Issue by Jakobud** [BrowserSync/browser-sync#994]
I am using Browser Sync on a page I'm working on for development. The page includes an iframe, to local content like this:

```
<iframe src="section/page.html"></iframe>
```

I've got Gulp setup with BrowserSync and almost everything works great. My app will reload CSS, HTML, etc just fine. But I can't get the content in the iframe to change. When I update CSS that is specific to the iframe, the change doesn't get injected in there. And when I change the HTML for the iframe, the iframe doesn't refresh automatically.

Is it possible to set up BrowserSync so that changes get injected also into my iframe?

**Comment by shakyShane** [comment]
only if the page within the iframe has a body tag (which would cause the snippet to be injected into it).

**Comment by Jakobud** [comment]
Ah that was my problem. That worked thank you
