### ISSUE TITLE
Browsersync does not work in offline

### ISSUE THREAD

**Issue by Avik-B** [BrowserSync/browser-sync#996]
i am trying to use browser sync offline, but have no success, maybe i am doing something wrong or could be bugs.

I am using grunt to do the automated tasks. I also added `online:false` in the options, still no difference.
It works perfectly fine when i am online but when offline the browser stays at loading. :disappointed: 

[full Image link](https://i.imgur.com/OlY5RK8.jpg)
!['page is loading forever'](https://i.imgur.com/OlY5RK8l.jpg)

**Comment by shakyShane** [comment]
Browsersync does not require an internet connection. Please try following example to see what I mean 
https://github.com/Browsersync/recipes/tree/master/recipes/server

More than likely you have a font or something else blocking the rendering of the page.

If i'm incorrect please provide a sample project (like the one linked above) that shows your bug and I will be happy to help  :)
