### ISSUE TITLE
Can website auto refresh when we use proxy mode?

### ISSUE THREAD

**Issue by wzl610** [BrowserSync/browser-sync#997]
I have a website and I can access the `index.html` by "www.test.com". When I use proxy mode 

```shell
browser-sync start --proxy www.test.com css/*.css
```

and I can access it by `http://localhost:3000`, but when I change the css of the index.html It can`t refresh automatically. How can I make it auto refresh when I modify the   index.html of the "www.test.com"?

**Comment by marvinhagemeister** [comment]
It is as easy as watching both your `*.css` and `*.html` files.

**Comment by shakyShane** [comment]
@wzl610 you need to provide patterns that match the location your html + css files under the `--files` option. 

Eg: 

```shell
browser-sync start --proxy www.test.com --files="*.html, css/*.css"
```

**Comment by wzl610** [comment]
@shakyShane  I write as you told me and it also doesn`t work，it can`t refresh automatically when I modify the html and css.

**Comment by shakyShane** [comment]
check https://browsersync.io/docs/#requirements
