### ISSUE TITLE
Having issues with Emitters

### ISSUE THREAD

**Issue by carlosacabrera** [BrowserSync/browser-sync#999]
Given the code below, the emitter **service:running** gets triggered after executing the function `run()` and **service:exit** when executing the function `stop()`, but if I execute `run()` again after `stop()` the **service:running** never gets triggered again.

```javascript
const bs = require('browser-sync').create();
​
function run(url) {
	bs.init({
		proxy: url,
	});
}
​
function stop() {
	bs.exit();
}
​
​
bs.emitter.on('service:running', function(attrs) {
	console.log('running', attrs);
       // functionality to update status messages to "running" goes here...
});
​
bs.emitter.on('service:exit', function(attrs) {
	console.log('stopped', attrs);
       // functionality to update status messages to "not running" goes here...
});
```

**Steps:**
1. `run('htttp://www.google.com'); // creates BS Proxy for Google and triggers service:running`
2. `stop(); // stops the proxy and triggers service:running`
3. `run('http://www.yahoo.com'); // creates BS Proxy for Yahoo but doesn't trigger service:running `

**Comment by shakyShane** [comment]
emitters are not shared, so when you call `bs.exit` the reference is lost.

You should rework how you're doing this to instead use the callback, this would work

```js
function run(url) {
    const bs = require('browser-sync').create();
    bs.cleanup();
    bs.init({
        proxy: url,
        open: false
    }, function (err, bs) {
        console.log('RUNNING', bs.options.get('urls'));
        bs.events.on('service:exit', function () {
        	console.log('EXIT');
        });
    });
    return bs;
}

var bs = run('http://www.example.com');

setTimeout(x => {
    bs.exit();
    bs = run('http://bbc.co.uk');
    setTimeout(x => {
        bs.exit();
    }, 1000);
}, 1000);
```

**Comment by carlosacabrera** [comment]
Thanks for the feedback @shakyShane. Works like a charm.
